/** Specialist pack matrix data (late domains). */
import type { ReLaneSpecialistDomainPackV1 } from "./specialist-pack-matrix-types.ts";

export const RE_LANE_SPECIALIST_COMMAND_PACK_MATRIX_LATE: ReLaneSpecialistDomainPackV1[] = [
	{
		domainId: "pcap-dfir",
		routeMatchers: ["DFIR / PCAP / stego", "tcp.stream", "flow conversation", "carved object"],
		laneSeeds: ["flow", "stream", "extract", "timeline"],
		commandPackMarkers: ["pcap-flow", "pcap-stream", "pcap-extract", "pcap-secret"],
		analyzerAnchors: [
			"PCAP/DFIR traffic flow anchors",
			"PCAP stream ranking anchors",
			"PCAP extracted artifact anchors",
			"PCAP secret timeline anchors",
		],
		selfHealCommands: ["re_lane plan extract <target>", "re_knowledge_graph build", "re_verifier matrix"],
		proofExitBridge: ["flow conversation", "follow-stream", "carved object", "timeline evidence"],
	},
	{
		domainId: "memory-forensics",
		routeMatchers: ["Memory forensics", "volatility", "vmem", "process/network"],
		laneSeeds: ["image", "process-network", "credential", "timeline"],
		commandPackMarkers: [
			"memory-image-profile-scaffold",
			"memory-process-network-scaffold",
			"memory-credential-artifact-scaffold",
			"memory-timeline-carve-scaffold",
		],
		analyzerAnchors: [
			"memory forensics image anchors",
			"memory forensics process/network anchors",
			"memory forensics credential/artifact anchors",
			"memory forensics timeline/carve anchors",
		],
		selfHealCommands: ["re_lane plan process-network <target>", "re_replayer run", "re_verifier matrix"],
		proofExitBridge: ["image profile", "process/network map", "credential/artifact proof", "timeline/carve evidence"],
	},
	{
		domainId: "firmware-iot",
		routeMatchers: ["Firmware / IoT", "rootfs", "squashfs", "emulation"],
		laneSeeds: ["extract", "service", "config", "emulate"],
		commandPackMarkers: [
			"firmware-image-fingerprint",
			"firmware-extraction-rootfs",
			"firmware-service-surface",
			"firmware-config-secret",
		],
		analyzerAnchors: [
			"Firmware image metadata anchors",
			"Firmware extraction/rootfs anchors",
			"Firmware config/secret anchors",
			"Firmware emulation/runtime anchors",
		],
		selfHealCommands: ["re_lane plan extract <target>", "re_campaign plan <target>", "re_operation plan <target>"],
		proofExitBridge: ["filesystem extraction", "service map", "credential/config proof", "emulation notes"],
	},
	{
		domainId: "crypto",
		routeMatchers: ["Crypto / stego", "oracle", "lattice", "transform chain"],
		laneSeeds: ["params", "solver", "kat", "transform"],
		commandPackMarkers: [
			"crypto-param-oracle-scaffold",
			"crypto-solver-scaffold",
			"known-answer test",
			"crypto-stego-extraction-scaffold",
		],
		analyzerAnchors: [
			"Crypto transform chain anchors",
			"crypto parameter derivation anchors",
			"solver script anchors",
			"known-answer test anchors",
		],
		selfHealCommands: ["re_lane plan solver <target>", "re_replayer run", "re_proof_loop run <target>"],
		proofExitBridge: ["parameter derivation", "solver script", "known-answer test", "transform replay"],
	},
	{
		domainId: "cloud-identity",
		routeMatchers: ["Cloud / container", "Identity / Windows / AD", "K8s", "AD graph"],
		laneSeeds: ["config", "metadata", "privilege", "graph"],
		commandPackMarkers: [
			"cloud-identity-config-map",
			"cloud-metadata-probe-scaffold",
			"cloud-privilege-edge-scaffold",
			"identity-ad-graph-scaffold",
		],
		analyzerAnchors: [
			"Cloud identity anchors",
			"Cloud metadata probe anchors",
			"Cloud privilege edge anchors",
			"Identity/AD graph edge anchors",
		],
		selfHealCommands: ["re_lane plan privilege <target>", "re_campaign plan <target>", "re_supervisor review"],
		proofExitBridge: ["token source", "credential usability", "privilege edge", "graph/path evidence"],
	},
	{
		domainId: "agent-security",
		routeMatchers: ["Agent / LLM boundary", "agent-security", "prompt injection", "tool boundary"],
		laneSeeds: ["surface", "boundary", "poison", "injection"],
		commandPackMarkers: [
			"agent-prompt-surface-map",
			"agent-tool-boundary-scaffold",
			"agent-memory-poisoning-scaffold",
			"agent-injection-replay-harness",
		],
		analyzerAnchors: [
			"Agent prompt surface anchors",
			"Agent tool boundary anchors",
			"Agent memory poisoning anchors",
			"Agent injection replay anchors",
		],
		selfHealCommands: ["re_lane plan injection", "re_replayer run", "re_verifier matrix"],
		proofExitBridge: [
			"prompt surface map",
			"tool boundary proof",
			"memory poisoning proof",
			"injection replay proof",
		],
	},
	{
		domainId: "malware-analysis",
		routeMatchers: ["Malware analysis", "malware-analysis", "IOC", "behavior trace"],
		laneSeeds: ["static", "rules", "ioc", "behavior"],
		commandPackMarkers: [
			"malware-static-triage-scaffold",
			"malware-yara-capa-floss-scaffold",
			"malware-ioc-config-scaffold",
			"malware-behavior-trace-scaffold",
		],
		analyzerAnchors: [
			"Malware static triage anchors",
			"Malware rule/capability anchors",
			"Malware IOC/config anchors",
			"Malware behavior trace anchors",
		],
		selfHealCommands: ["re_lane plan behavior", "re_knowledge_graph build", "re_verifier matrix"],
		proofExitBridge: ["static triage proof", "rule/capability signal", "IOC/config proof", "behavior trace"],
	},
	{
		domainId: "exploit-reliability",
		routeMatchers: ["Exploit reliability", "PoC", "replay matrix", "flake triage"],
		laneSeeds: ["inventory", "matrix", "pin", "bundle"],
		commandPackMarkers: [
			"exploit-poc-inventory",
			"poc-replay-matrix",
			"exploit-environment-pin",
			"exploit-artifact-bundle",
		],
		analyzerAnchors: [
			"Exploit PoC inventory anchors",
			"PoC replay matrix anchors",
			"Exploit environment pin anchors",
			"Exploit artifact bundle anchors",
		],
		selfHealCommands: ["re_exploit_lab run <target> 5", "re_autofix plan", "re_complete audit"],
		proofExitBridge: ["multi-run success rate", "stdout/stderr hash", "environment pin", "bundle manifest"],
	},
];
