/** Toolchain domain matrix: reverse/native/pwn/mobile/malware. */
import type { ToolchainDomainSpec } from "./toolchain-domain-types.ts";

export const TOOLCHAIN_DOMAIN_MATRIX_REVERSE: readonly ToolchainDomainSpec[] = [
	{
		id: "rev-native",
		label: "Native reverse: headers/imports/strings/control-flow/runtime trace",
		requiredAny: ["file", "strings", "readelf", "objdump"],
		preferred: ["r2", "rabin2", "radare2", "ghidra", "angr", "strace", "ltrace"],
		fallbacks: ["file", "strings", "readelf", "objdump", "python3"],
		playbookMarkers: ["entrypoint", "imports", "strings", "control-flow", "patch"],
		commandScaffolds: ["re_native_runtime", "re_lane", "re_knowledge_graph", "re_verifier"],
		proofExit: ["symbol/import map", "comparison sink", "runtime trace", "patch/replay proof"],
	},
	{
		id: "pwn",
		label: "Pwn primitive: mitigations, crash, leak, ROP/libc, heap/tcache, fmtstr, SROP/ret2dlresolve, one_gadget, seccomp verifier",
		requiredAny: ["file", "readelf", "gdb", "python3"],
		preferred: ["checksec", "pwn", "ROPgadget", "ropper", "one_gadget", "seccomp-tools", "patchelf"],
		fallbacks: ["readelf", "objdump", "gdb", "python3", "strace"],
		playbookMarkers: [
			"mitigations",
			"cyclic",
			"leak",
			"primitive",
			"ROP/libc",
			"heap/tcache",
			"format-string",
			"SROP/ret2dlresolve",
			"one_gadget constraint",
			"seccomp/sandbox",
		],
		commandScaffolds: ["re_native_runtime", "re_exploit_lab", "re_replayer", "re_proof_loop"],
		proofExit: [
			"offset",
			"leak source",
			"controllable bytes",
			"local verifier",
			"heap/tcache bin state",
			"format-string leak/write",
			"SROP syscall surface",
			"ret2dlresolve payload scaffold",
			"one_gadget constraint review",
			"seccomp/sandbox syscall filter",
		],
	},
	{
		id: "mobile",
		label: "Android/APK: manifest, jadx/apktool, ADB/Frida hooks",
		requiredAny: ["unzip", "strings"],
		preferred: ["jadx", "apktool", "adb", "frida", "frida-ps", "objection", "aapt", "r2"],
		fallbacks: ["unzip", "strings", "readelf", "python3"],
		playbookMarkers: ["APK", "manifest", "smali", "Frida", "Java crypto", "native compare"],
		commandScaffolds: ["re_mobile_runtime", "re_lane", "re_verifier", "re_knowledge_graph"],
		proofExit: ["manifest/package map", "Java/native hook", "anti-debug evidence", "runtime anchors"],
	},
	{
		id: "mobile-ios",
		label: "iOS/IPA: Info.plist, entitlements, Mach-O/classes, Frida/objection hooks",
		requiredAny: ["unzip", "strings", "file"],
		preferred: ["plutil", "otool", "nm", "codesign", "class-dump", "frida", "frida-ps", "objection"],
		fallbacks: ["unzip", "strings", "python3", "file"],
		playbookMarkers: ["iOS IPA", "Info.plist", "Mach-O/class", "iOS Frida", "keychain"],
		commandScaffolds: ["re_mobile_runtime", "re_lane", "re_replayer", "re_verifier"],
		proofExit: ["IPA inventory", "Mach-O/class map", "Frida/objection hook", "network/keychain replay"],
	},
	{
		id: "firmware-iot",
		label: "Firmware/IoT: image fingerprint, rootfs, configs, service surface, emulation",
		requiredAny: ["file", "strings"],
		preferred: ["binwalk", "unblob", "unsquashfs", "7z", "qemu-system-x86_64", "qemu-arm", "qemu-mips"],
		fallbacks: ["file", "strings", "binwalk", "python3"],
		playbookMarkers: ["rootfs", "squashfs", "config secret", "service surface", "emulation"],
		commandScaffolds: ["re_lane", "re_campaign", "re_operation", "re_knowledge_graph"],
		proofExit: ["filesystem extraction", "service map", "credential/config proof", "emulation notes"],
	},
	{
		id: "malware-analysis",
		label: "Malware analysis: static triage, rule/capability, IOC/config, behavior trace",
		requiredAny: ["file", "strings", "python3"],
		preferred: ["yara", "capa", "floss", "rabin2", "strace", "upx", "clamscan"],
		fallbacks: ["file", "strings", "python3", "readelf"],
		playbookMarkers: [
			"Malware static triage anchors",
			"Malware rule/capability anchors",
			"Malware IOC/config anchors",
			"Malware behavior trace anchors",
		],
		commandScaffolds: ["re_lane", "re_knowledge_graph", "re_verifier", "re_replayer"],
		proofExit: ["static triage proof", "rule/capability signal", "IOC/config proof", "behavior trace"],
	},
	{
		id: "exploit-reliability",
		label: "Exploit/PoC reliability: replay matrix, env pin, flake triage, bundle",
		requiredAny: ["python3", "bash", "node"],
		preferred: ["docker", "gdb", "jq", "curl", "patchelf"],
		fallbacks: ["python3", "bash", "node", "sh"],
		playbookMarkers: ["PoC inventory", "replay matrix", "environment pin", "flake triage", "artifact bundle"],
		commandScaffolds: ["re_exploit_lab", "re_replayer", "re_autofix", "re_complete"],
		proofExit: ["multi-run success rate", "stdout/stderr hash", "environment pin", "bundle manifest"],
	},
];
