/** pwntools local verifier adapter command template. */
export function buildPwntoolsLocalVerifierCommandTemplate(): string {
	return [
		"adapter-pwntools-local-verifier-runner: python3 - <<'PY'",
		"import hashlib, os, re, shutil, signal, stat, subprocess, sys",
		"target = os.environ.get('REPI_ADAPTER_TARGET', '')",
		"runs = max(1, min(int(os.environ.get('REPI_EXPLOIT_VERIFY_RUNS', '3') or '3'), 12))",
		"def sha(data): return hashlib.sha256(data or b'').hexdigest()[:24]",
		"def run(cmd, **kwargs):",
		"    try:",
		"        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=kwargs.pop('timeout', 4), **kwargs)",
		"        print('[tool-run] cmd=' + ' '.join(cmd[:3]) + ' exit=' + str(result.returncode) + ' stdout_sha256=' + sha(result.stdout) + ' stderr_sha256=' + sha(result.stderr))",
		"        out = (result.stdout + result.stderr).decode('latin1', 'replace')[:1600].replace('\\n', ' ')",
		"        if out: print('[tool-output-head] ' + out)",
		"        return result",
		"    except Exception as error:",
		"        print('[tool-error] cmd=' + ' '.join(cmd[:3]) + ' error=' + str(error))",
		"        return None",
		"print('[pwn-target] target=' + target + ' exists=' + str(os.path.exists(target)))",
		"if not target or not os.path.exists(target):",
		"    sys.exit(2)",
		"run(['file', target]) if shutil.which('file') else None",
		"run(['readelf', '-h', target]) if shutil.which('readelf') else None",
		"def readelf_text(args):",
		"    if not shutil.which('readelf'): return ''",
		"    try:",
		"        result = subprocess.run(['readelf'] + args + [target], stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=4)",
		"        return (result.stdout + result.stderr).decode('latin1', 'replace')",
		"    except Exception: return ''",
		"def emit_mitigation_map():",
		"    header = readelf_text(['-h'])",
		"    if 'ELF' not in header and 'Type:' not in header: return",
		"    program = readelf_text(['-W', '-l'])",
		"    dynamic = readelf_text(['-W', '-d'])",
		"    symbols = readelf_text(['-Ws'])",
		"    m = re.search(r'Type:\\s+(\\S+)', header)",
		"    elf_type = m.group(1) if m else 'unknown'",
		"    pie = 'yes' if elf_type == 'DYN' else 'no'",
		"    relro = 'full' if 'BIND_NOW' in dynamic else ('partial' if 'GNU_RELRO' in program else 'none')",
		"    stack = next((line for line in program.splitlines() if 'GNU_STACK' in line), '')",
		"    nx = 'unknown' if not stack else ('disabled' if 'RWE' in stack else 'enabled')",
		"    canary = 'yes' if '__stack_chk_fail' in symbols else 'no'",
		"    fortify = 'yes' if re.search(r'(__.*_chk|_chk@)', symbols) else 'no'",
		"    print('[pwn-mitigation] pie=%s nx=%s relro=%s canary=%s fortify=%s type=%s' % (pie, nx, relro, canary, fortify, elf_type))",
		"emit_mitigation_map()",
		"if shutil.which('strings'):",
		"    result = run(['strings', '-a', target], timeout=5)",
		"    text = ((result.stdout if result else b'') or b'').decode('latin1', 'replace')",
		"    interesting = sorted(set(x for x in ['system','execve','puts','printf','gets','strcpy','scanf','read','write','/bin/sh','flag','password','token'] if x in text))",
		"    if interesting: print('[pwn-primitive-candidate] symbols=' + ','.join(interesting))",
		"mode = os.stat(target).st_mode",
		"if not (mode & stat.S_IXUSR):",
		"    print('[pwn-exec-skip] reason=not_executable')",
		"    sys.exit(0)",
		"crashes = 0",
		"for index in range(runs):",
		"    try:",
		"        payload = (b'A' * 512) + b'\\n'",
		"        result = subprocess.run([target], input=payload, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=float(os.environ.get('REPI_EXPLOIT_RUN_TIMEOUT_SEC', '2')))",
		"        sig = -result.returncode if result.returncode < 0 else 0",
		"        if sig: crashes += 1",
		"        sig_name = signal.Signals(sig).name if sig else 'NONE'",
		"        print('[pwn-exec-run] run=' + str(index + 1) + ' exit=' + str(result.returncode) + ' signal=' + sig_name + ' stdout_sha256=' + sha(result.stdout) + ' stderr_sha256=' + sha(result.stderr) + ' stdout_bytes=' + str(len(result.stdout)) + ' stderr_bytes=' + str(len(result.stderr)))",
		"        if sig: print('[pwn-crash-observed] signal=' + sig_name + ' offset=needs_cyclic_repro')",
		"    except subprocess.TimeoutExpired as error:",
		"        print('[pwn-exec-timeout] run=' + str(index + 1) + ' timeout=' + str(error.timeout))",
		"print('[pwn-multirun-summary] runs=' + str(runs) + ' crash_runs=' + str(crashes))",
		"PY",
	].join("\n");
}
