/** Web CDP adapter node script main capture body. */
export const WEB_CDP_SCRIPT_MAIN_LINES: string[] = [
	"(async () => {",
	"  if (!target) { console.log('[adapter-error] missing target'); process.exitCode = 2; return; }",
	"  if (fs.existsSync(target) && fs.statSync(target).isFile()) { emitHar(target); return; }",
	"  if (cdp) {",
	"    const cdpHttp = cdp.replace(/^ws/i, 'http').replace(/\\/devtools\\/.*$/i, '');",
	"    try {",
	"      const cdpResponse = await fetch(cdpHttp.replace(/\\/$/, '') + '/json/version');",
	"      console.log('[cdp-endpoint] status=' + cdpResponse.status + ' url=' + cdpHttp);",
	"      const cdpVersion = await cdpResponse.text();",
	"      console.log('[web-cdp-version] status=' + cdpResponse.status + ' sha256=' + sha(cdpVersion) + ' body=' + head(cdpVersion, 700));",
	"      const targetResponse = await fetch(cdpHttp.replace(/\\/$/, '') + '/json/list');",
	"      const targetText = await targetResponse.text();",
	"      console.log('[cdp-target-list] status=' + targetResponse.status + ' sha256=' + sha(targetText) + ' body=' + head(targetText, 900));",
	"    } catch (error) {",
	"      console.log('[cdp-endpoint-error] ' + head(error && error.message ? error.message : error, 400));",
	"    }",
	"  }",
	"  const response = await fetch(target, { redirect: 'manual', headers: { 'User-Agent': 'REPI-runtime-adapter' } });",
	"  const body = await response.text();",
	"  console.log('[http-response] status=' + response.status + ' url=' + response.url + ' content_type=' + (response.headers.get('content-type') || '<none>') + ' bytes=' + body.length + ' sha256=' + sha(body));",
	"  emitRouteMap('fetch', 1, 'GET', response.status, response.url, 'content_type=' + (response.headers.get('content-type') || '<none>'));",
	"  for (const [key, value] of response.headers) { emitHeaderSignal('fetch', 'response', key, value); if (/^set-cookie$/i.test(key)) emitSetCookieHeader('fetch', 'response', value); }",
	"  console.log('[served-asset-head] ' + head(body));",
	"  const routeMatches = [...body.matchAll(/(?:fetch|XMLHttpRequest|WebSocket|graphql|\\/api\\/|wss?:\\/\\/)[^\\\"'<>\\s)]{0,240}/gi)].map((match: any) => match[0]);",
	"  const seenRoutes = new Set();",
	"  let routeIndex = 0;",
	"  for (const route of routeMatches) {",
	"    const compactRoute = head(route, 500);",
	"    if (seenRoutes.has(compactRoute)) continue;",
	"    seenRoutes.add(compactRoute);",
	"    routeIndex += 1;",
	"    console.log('[route-candidate] ' + compactRoute);",
	"    console.log('[request-order] index=' + routeIndex + ' route=' + compactRoute);",
	"    emitRouteMap('served-asset', routeIndex, '<unknown>', '<none>', compactRoute);",
	"    if (routeIndex >= 40) break;",
	"  }",
	"  emitSignedFields('served-asset', body);",
	"})().catch((error: any) => { console.log('[adapter-error] ' + head(error && error.stack ? error.stack : error)); process.exitCode = 1; });",
	"NODE",
];
