/** Web CDP adapter node script helpers. */
export const WEB_CDP_SCRIPT_HELPER_LINES: string[] = [
	"adapter-web-cdp-network-runner: node - <<'NODE'",
	"const crypto = require('node:crypto');",
	"const fs = require('node:fs');",
	"const target = process.env.REPI_ADAPTER_TARGET || '';",
	"const cdp = process.env.REPI_BROWSER_CDP_URL || '';",
	"function head(value, max = 8000) { return String(value ?? '').replace(/\\s+/g, ' ').slice(0, max); }",
	"function sha(value) { return crypto.createHash('sha256').update(String(value ?? '')).digest('hex').slice(0, 24); }",
	"function headerRows(headers) { return Array.isArray(headers) ? headers.map(h => [h.name || h.key || '', h.value || '']) : Object.entries(headers || {}); }",
	"function cookieRows(cookies) { return Array.isArray(cookies) ? cookies.map(c => [c.name || c.key || '', c.value || '']) : []; }",
	"function emitRouteMap(source, index, method, status, url, extra = '') {",
	"  console.log('[web-route-map] source=' + source + ' index=' + index + ' method=' + (method || '<method>') + ' status=' + String(status ?? '<none>') + ' url_sha256=' + sha(url) + ' url=' + head(url, 700) + (extra ? ' ' + extra : ''));",
	"}",
	"function emitHeaderSignal(source, direction, key, value) {",
	"  if (!key) return;",
	"  const row = key + ': ' + String(value ?? '');",
	"  if (/set-cookie|cookie|authorization|csrf|nonce|signature|timestamp|etag|location|x-[a-z0-9-]*sign/i.test(row)) {",
	"    console.log('[http-header-signal] ' + key + ': ' + head(value, 500));",
	"    console.log('[web-header-signal] source=' + source + ' direction=' + direction + ' key=' + String(key).toLowerCase() + ' value_sha256=' + sha(value) + ' value=' + head(value, 400));",
	"  }",
	"}",
	"function emitCookieSignal(source, direction, name, value) {",
	"  if (!name && !value) return;",
	"  console.log('[web-cookie-signal] source=' + source + ' direction=' + direction + ' name=' + head(name || '<cookie>', 120) + ' value_sha256=' + sha(value));",
	"}",
	"function emitSignedFields(source, surface) {",
	"  const seen = new Set();",
	"  for (const match of String(surface ?? '').matchAll(/(?:signature|\\bsign\\b|nonce|timestamp|x-[a-z0-9-]*sign[a-z0-9-]*|authorization|csrf)[^\\\"'<>\\s)]{0,180}/gi)) {",
	"    const item = head(match[0], 400);",
	"    if (seen.has(item)) continue;",
	"    seen.add(item);",
	"    console.log('[crypto-request-field] ' + item);",
	"    console.log('[web-signed-field] source=' + source + ' field_sha256=' + sha(item) + ' field=' + item);",
	"    if (seen.size >= 60) break;",
	"  }",
	"}",
	"function emitSetCookieHeader(source, direction, value) {",
	"  for (const part of String(value ?? '').split(/,(?=\\s*[^;,=]+=[^;,]+)/).slice(0, 20)) {",
	"    const match = part.match(/\\s*([^=;\\s]+)=([^;]*)/);",
	"    if (match) emitCookieSignal(source, direction, match[1], match[2]);",
	"  }",
	"}",
	"function emitHar(targetPath) {",
	"  const har = JSON.parse(fs.readFileSync(targetPath, 'utf8'));",
	"  const entries = Array.isArray(har.log?.entries) ? har.log.entries : [];",
	"  console.log('[har-file] path=' + targetPath + ' entries=' + entries.length);",
	"  let routeIndex = 0;",
	"  for (const entry of entries.slice(0, 120)) {",
	"    const request = entry.request || {};",
	"    const response = entry.response || {};",
	"    const url = request.url || entry.url || '<unknown>';",
	"    const method = request.method || '<method>';",
	"    const bodyText = response.content?.text || request.postData?.text || '';",
	"    const requestBody = request.postData?.text || '';",
	"    const status = response.status || 0;",
	"    routeIndex += 1;",
	"    console.log('[http-response] status=' + status + ' method=' + method + ' url=' + url + ' content_type=' + (response.content?.mimeType || '<none>') + ' bytes=' + String(bodyText).length + ' sha256=' + sha(bodyText));",
	"    console.log('[request-order] index=' + routeIndex + ' route=' + head(url, 700));",
	"    emitRouteMap('har', routeIndex, method, status, url, 'content_type=' + (response.content?.mimeType || '<none>'));",
	"    if (requestBody) console.log('[web-request-body] source=har index=' + routeIndex + ' method=' + method + ' bytes=' + String(requestBody).length + ' sha256=' + sha(requestBody) + ' body=' + head(requestBody, 500));",
	"    if (/\\/api\\/|graphql|websocket|wss?:\\/\\//i.test(url)) console.log('[route-candidate] ' + head(url, 700));",
	"    for (const [key, value] of headerRows(request.headers)) { emitHeaderSignal('har', 'request', key, value); if (/^cookie$/i.test(key)) for (const pair of String(value || '').split(';').slice(0, 30)) { const match = pair.match(/\\s*([^=;\\s]+)=([^;]*)/); if (match) emitCookieSignal('har', 'request', match[1], match[2]); } }",
	"    for (const [key, value] of headerRows(response.headers)) { emitHeaderSignal('har', 'response', key, value); if (/^set-cookie$/i.test(key)) emitSetCookieHeader('har', 'response', value); }",
	"    for (const [name, value] of cookieRows(request.cookies)) emitCookieSignal('har', 'request', name, value);",
	"    for (const [name, value] of cookieRows(response.cookies)) emitCookieSignal('har', 'response', name, value);",
	"    const signedSurface = [url, request.queryString, request.postData?.text, JSON.stringify(request.cookies || []), JSON.stringify(request.headers || [])].join(' ');",
	"    emitSignedFields('har', signedSurface);",
	"  }",
	"}",
];
