/** Context-pack memory engine sections (orchestrator → experience). */
import type { ContextPackFormatView } from "./types.ts";

export function formatContextPackMemoryEngineSections(pack: ContextPackFormatView): Array<string | undefined> {
	return [
		"memory_orchestrator:",
		`- MemoryOrchestratorV6=${pack.memoryOrchestrator?.MemoryOrchestratorV6 ?? false}`,
		`- mandatory_memory_control_loop=${pack.memoryOrchestrator?.mandatory_memory_control_loop ?? false}`,
		`- phase=${pack.memoryOrchestrator?.phase ?? "none"}`,
		`- report=${pack.memoryOrchestrator?.reportPath ?? "none"}`,
		`- retrieval_hits=${pack.memoryOrchestrator?.retrievalHitIds.length ?? 0}`,
		`- injection_events=${pack.memoryOrchestrator?.injectionEventIds.length ?? 0}`,
		`- compact_resume_status=${pack.memoryOrchestrator?.compactResumeStatus ?? "unknown"}`,
		"memory_quality_ledger_v11:",
		`- MemoryQualityLedgerV11=${pack.memoryQuality?.MemoryQualityLedgerV11 ?? false}`,
		`- active_memory_policy=${pack.memoryQuality?.active_memory_policy ?? false}`,
		`- quality_score_feedback_loop=${pack.memoryQuality?.quality_score_feedback_loop ?? false}`,
		`- status=${pack.memoryQuality?.status ?? "unknown"}`,
		`- rows=${pack.memoryQuality?.rowCount ?? 0}`,
		`- average_quality_score=${pack.memoryQuality?.averageQualityScore ?? 0}`,
		`- required_feedback=${pack.memoryQuality?.requiredFeedbackEventIds.length ?? 0}`,
		`- report=${pack.memoryQuality?.reportPath ?? "none"}`,
		`- ledger=${pack.memoryQuality?.ledgerPath ?? "none"}`,
		"memory_replay_evaluator_v12:",
		`- MemoryReplayEvaluatorV12=${pack.memoryReplay?.MemoryReplayEvaluatorV12 ?? false}`,
		`- memory_ab_replay=${pack.memoryReplay?.memory_ab_replay ?? false}`,
		`- causal_attribution_signal=${pack.memoryReplay?.causal_attribution_signal ?? false}`,
		`- status=${pack.memoryReplay?.status ?? "unknown"}`,
		`- scenarios=${pack.memoryReplay?.scenarioCount ?? 0}`,
		`- average_causal_score=${pack.memoryReplay?.averageCausalScore ?? 0}`,
		`- saved_steps=${pack.memoryReplay?.totalSavedStepEstimate ?? 0}`,
		`- attribution_events=${pack.memoryReplay?.attributionEventIds.length ?? 0}`,
		`- regression_events=${pack.memoryReplay?.regressionEventIds.length ?? 0}`,
		`- report=${pack.memoryReplay?.reportPath ?? "none"}`,
		`- ledger=${pack.memoryReplay?.ledgerPath ?? "none"}`,
		"memory_strategy_capsule_v13:",
		`- MemoryStrategyCapsuleV13=${pack.memoryStrategy?.MemoryStrategyCapsuleV13 ?? false}`,
		`- executable_strategy_capsule=${pack.memoryStrategy?.executable_strategy_capsule ?? false}`,
		`- replay_backed_strategy_promotion=${pack.memoryStrategy?.replay_backed_strategy_promotion ?? false}`,
		`- strategy_quality_check=${pack.memoryStrategy?.strategy_quality_check ?? false}`,
		`- status=${pack.memoryStrategy?.status ?? "unknown"}`,
		`- capsules=${pack.memoryStrategy?.capsuleCount ?? 0}`,
		`- promoted=${pack.memoryStrategy?.promotedCapsuleIds.length ?? 0}`,
		`- report=${pack.memoryStrategy?.reportPath ?? "none"}`,
		`- ledger=${pack.memoryStrategy?.capsuleLedgerPath ?? "none"}`,
		`- book=${pack.memoryStrategy?.strategyBookPath ?? "none"}`,
		"memory_active_kernel_v14:",
		`- MemoryActiveKernelV14=${pack.memoryActiveKernel?.MemoryActiveKernelV14 ?? false}`,
		`- unified_memory_decision_engine=${pack.memoryActiveKernel?.unified_memory_decision_engine ?? false}`,
		`- active_recall_scheduler=${pack.memoryActiveKernel?.active_recall_scheduler ?? false}`,
		`- scope_safe_strategy_injection=${pack.memoryActiveKernel?.scope_safe_strategy_injection ?? false}`,
		`- status=${pack.memoryActiveKernel?.status ?? "unknown"}`,
		`- decisions=${pack.memoryActiveKernel?.decisionCount ?? 0}`,
		`- inject=${pack.memoryActiveKernel?.injectDecisionIds.length ?? 0}`,
		`- reuse=${pack.memoryActiveKernel?.reuseDecisionIds.length ?? 0}`,
		`- report=${pack.memoryActiveKernel?.reportPath ?? "none"}`,
		`- active_injection_pack=${pack.memoryActiveKernel?.injectionPackPath ?? "none"}`,
		`- board=${pack.memoryActiveKernel?.strategyBoardPath ?? "none"}`,
		"memory_maturation_runtime_v15:",
		`- MemoryMaturationRuntimeV15=${pack.memoryMaturation?.MemoryMaturationRuntimeV15 ?? false}`,
		`- automatic_memory_maturation_pipeline=${pack.memoryMaturation?.automatic_memory_maturation_pipeline ?? false}`,
		`- tool_result_to_strategy_loop=${pack.memoryMaturation?.tool_result_to_strategy_loop ?? false}`,
		`- closed_loop_writeback=${pack.memoryMaturation?.closed_loop_writeback ?? false}`,
		`- status=${pack.memoryMaturation?.status ?? "unknown"}`,
		`- rows=${pack.memoryMaturation?.rowCount ?? 0}`,
		`- promoted=${pack.memoryMaturation?.promotedEventIds.length ?? 0}`,
		`- pending_feedback=${pack.memoryMaturation?.pendingFeedbackEventIds.length ?? 0}`,
		`- report=${pack.memoryMaturation?.reportPath ?? "none"}`,
		`- ledger=${pack.memoryMaturation?.ledgerPath ?? "none"}`,
		`- board=${pack.memoryMaturation?.actionBoardPath ?? "none"}`,
		"memory_deposition_engine_v7:",
		`- MemoryDepositionEngineV7=${pack.memoryDeposition?.MemoryDepositionEngineV7 ?? false}`,
		`- runtime_step_event_bus=${pack.memoryDeposition?.runtime_step_event_bus ?? false}`,
		`- post_tool_writeback_autocapture=${pack.memoryDeposition?.post_tool_writeback_autocapture ?? false}`,
		`- status=${pack.memoryDeposition?.status ?? "unknown"}`,
		`- runtime_events=${pack.memoryDeposition?.runtimeEventCount ?? 0}`,
		`- memory_writebacks=${pack.memoryDeposition?.memoryWritebackCount ?? 0}`,
		`- report=${pack.memoryDeposition?.depositionReportPath ?? "none"}`,
		`- event_bus=${pack.memoryDeposition?.depositionEventBusPath ?? "none"}`,
		"memory_experience_engine_v8:",
		`- MemoryExperienceEngineV8=${pack.memoryExperience?.MemoryExperienceEngineV8 ?? false}`,
		`- episode_model_v8=${pack.memoryExperience?.episode_model_v8 ?? false}`,
		`- structured_claim_extraction=${pack.memoryExperience?.structured_claim_extraction ?? false}`,
		`- lesson_promotion_check=${pack.memoryExperience?.lesson_promotion_check ?? false}`,
		`- status=${pack.memoryExperience?.status ?? "unknown"}`,
		`- episodes=${pack.memoryExperience?.episodeCount ?? 0}`,
		`- claims=${pack.memoryExperience?.claimCount ?? 0}`,
		`- lessons=${pack.memoryExperience?.lessonCount ?? 0}`,
		`- report=${pack.memoryExperience?.reportPath ?? "none"}`,
		`- lesson_book=${pack.memoryExperience?.lessonBookPath ?? "none"}`,
	];
}
