import type { ProfessionalRuntimeBridgeSpec } from "./professional-runtime-bridges-types.ts";

/** Professional runtime bridge matrix data + type re-exports. */
export type {
	ProfessionalRuntimeBridgeRowV1,
	ProfessionalRuntimeBridgeSpec,
	ProfessionalRuntimeBridgeStatus,
	ProfessionalRuntimeBridgesCheckV1,
} from "./professional-runtime-bridges-types.ts";

export const PROFESSIONAL_RUNTIME_BRIDGE_MATRIX: ProfessionalRuntimeBridgeSpec[] = [
	{
		id: "tool-bridge-runtime",
		title: "真实工具链桥接总控",
		domains: ["rev-native", "pwn", "web-cdp", "mobile-frida", "pcap-dfir", "firmware-iot"],
		preferredTools: [
			"ghidra",
			"r2",
			"rabin2",
			"angr",
			"gdb",
			"gef",
			"pwndbg",
			"checksec",
			"ROPgadget",
			"one_gadget",
			"seccomp-tools",
			"tshark",
			"volatility3",
			"binwalk",
			"qemu-arm",
			"frida",
			"adb",
			"jadx",
		],
		fallbackTools: ["file", "strings", "readelf", "objdump", "python3", "node", "curl", "unzip"],
		commandTemplates: [
			"bridge-rev-ghidra-r2-angr: re_runtime_bridge show tool-bridge-runtime && re_native_runtime run <target>",
			"bridge-pwn-pwntools-checksec-rop: re_toolchain_domain show pwn && re_exploit_lab run <target> 5",
			"bridge-web-cdp-http-replay: re_runtime_bridge show web-cdp-replay && re_live_browser run <url>",
			"bridge-mobile-frida-adb-jadx: re_runtime_bridge show mobile-frida && re_mobile_runtime run <apk-or-package>",
			"bridge-dfir-tshark-volatility: re_lane plan pcap-dfir <artifact> && re_verifier matrix",
			"bridge-firmware-binwalk-qemu: re_lane plan firmware-iot <image> && re_proof_loop run <image>",
		],
		artifactPlan: [
			".repi/evidence/toolchain/<timestamp>-professional-runtime-bridges.md",
			".repi/evidence/runs/<mission>/tool-output-hashes.json",
			".repi/recon/memory/tool-bridge-ledger.jsonl",
		],
		envRefs: [
			"REPI_TOOLBRIDGE_TIMEOUT_MS",
			"REPI_TOOLBRIDGE_WORKDIR",
			"REPI_ANDROID_SERIAL",
			"REPI_FRIDA_DEVICE",
			"REPI_BROWSER_CDP_URL",
		],
		proofExit: [
			"tool presence discovery",
			"fallback command generation",
			"artifact path plan",
			"proof-exit mapping",
			"no narrative-only bridge",
		],
	},
	{
		id: "exploit-verifier-runtime",
		title: "自动利用验证闭环",
		domains: ["pwn", "web-api", "frontend-js", "mobile-frida"],
		preferredTools: ["gdb", "pwntools", "checksec", "ROPgadget", "one_gadget", "curl", "playwright", "frida"],
		fallbackTools: ["python3", "node", "bash", "sh", "curl"],
		commandTemplates: [
			"verifier-pwn-crash-offset-primitive-exploit: re_exploit_lab run <target> 5 && re_verifier matrix",
			"verifier-web-replay-diff: re_replayer run <captured-request> 3 && re_domain_proof_exit write web-api",
			"verifier-js-signing-replay: re_js_signing run <url-or-bundle> && re_live_browser run <url> && re_replayer run <signed-request> 3",
			"verifier-mobile-hook-output: re_mobile_runtime run <package> && re_verifier check",
			"verifier-regression-bundle: re_proof_loop run <target> 4 2 && re_complete audit",
		],
		artifactPlan: [
			".repi/evidence/runs/<mission>/exploit-verifier-matrix.json",
			".repi/evidence/runs/<mission>/stdout-stderr-hashes.json",
			".repi/evidence/reports/<mission>-replay-verifier.md",
		],
		envRefs: [
			"REPI_EXPLOIT_VERIFY_RUNS",
			"REPI_EXPLOIT_VERIFY_TIMEOUT_MS",
			"REPI_REPLAY_BASE_URL",
			"REPI_FRIDA_DEVICE",
		],
		proofExit: [
			"crash-to-offset proof",
			"primitive control evidence",
			"multi-run verifier",
			"stdout/stderr hash",
			"state rollback proof",
		],
	},
	{
		id: "web-cdp-replay",
		title: "Web/CDP replay harness",
		domains: ["web-api", "frontend-js", "web-scan"],
		preferredTools: ["playwright", "mitmproxy", "httpx", "ffuf", "nuclei", "jq"],
		fallbackTools: ["curl", "node", "python3", "rg"],
		commandTemplates: [
			"cdp-network-capture: re_runtime_bridge show web-cdp-replay && re_live_browser run <url>",
			"cdp-xhr-ws-route-extraction: re_lane plan frontend-js <url> && re_knowledge_graph build",
			"cdp-cookie-session-isolation: re_web_authz_state run <url> 45000",
			"cdp-signed-request-replay: re_replayer run <request-artifact> 3",
			"cdp-authz-request-order-proof: re_domain_proof_exit write web-api",
			"cdp-blocked-mutation-operator-command: re_live_browser run <target> | re_domain_proof_exit show",
		],
		artifactPlan: [
			".repi/evidence/browser/<mission>/cdp-network.har",
			".repi/evidence/browser/<mission>/xhr-ws-routes.json",
			".repi/evidence/browser/<mission>/signed-replay-diff.json",
			".repi/evidence/browser/<mission>/request-order-proof.md",
		],
		envRefs: ["REPI_BROWSER_CDP_URL", "REPI_BROWSER_PROFILE_DIR", "REPI_REPLAY_BASE_URL", "REPI_SESSION_COOKIE_REF"],
		proofExit: [
			"CDP network capture",
			"XHR/WS route extraction",
			"cookie/session isolation",
			"signed request replay",
			"authz replay matrix",
			"request order proof",
		],
	},
	{
		id: "mobile-frida",
		title: "Frida/Mobile 动态分析桥接",
		domains: ["mobile", "mobile-ios", "rev-native"],
		preferredTools: [
			"frida",
			"frida-ps",
			"objection",
			"adb",
			"jadx",
			"apktool",
			"aapt",
			"class-dump",
			"otool",
			"codesign",
			"ios-deploy",
		],
		fallbackTools: ["unzip", "strings", "file", "python3", "node"],
		commandTemplates: [
			"mobile-apk-ipa-static-triage: re_runtime_bridge show mobile-frida && re_mobile_runtime plan <apk-or-ipa>",
			"mobile-frida-java-hook-template: frida -U -f <package> -l hooks/java-crypto.js --no-pause",
			"mobile-frida-objc-swift-hook-template: frida -U -f <bundle> -l hooks/objc-keychain.js --no-pause",
			"mobile-keystore-keychain-certpin-anchors: re_verifier check <mobile-artifact>",
			"mobile-runtime-attach-env-check: REPI_FRIDA_DEVICE=<device> re_mobile_runtime run <package>",
			"mobile-hook-output-artifact-contract: re_domain_proof_exit write mobile",
		],
		artifactPlan: [
			".repi/evidence/mobile/<mission>/static-triage.json",
			".repi/evidence/mobile/<mission>/frida-hook-output.jsonl",
			".repi/evidence/mobile/<mission>/cert-pinning-anchors.md",
			".repi/evidence/mobile/<mission>/runtime-attach-manifest.json",
		],
		envRefs: ["REPI_FRIDA_DEVICE", "REPI_ANDROID_SERIAL", "REPI_IOS_BUNDLE_ID", "REPI_MOBILE_RUNTIME_TIMEOUT_MS"],
		proofExit: [
			"APK/IPA static triage",
			"Java/ObjC/Swift method anchors",
			"keystore/keychain/cert pinning anchors",
			"runtime attach env checkpoint",
			"hook output artifact contract",
		],
	},
];
