export type SwarmWorkerFormatView = {
	id: string;
	status: string;
	worker: string;
	objective: string;
	dependencies: string[];
	mergeKeys: string[];
	evidenceContract: string[];
	spawnPrompt: string[];
	commands: string[];
};

export type SwarmExecutionFormatView = {
	workerId: string;
	status: string;
	worker: string;
	command: string;
	output: string;
};

export type SwarmFormatView = {
	timestamp: string;
	mode: string;
	missionId?: string;
	route?: string;
	target?: string;
	delegationArtifact?: string;
	workers: SwarmWorkerFormatView[];
	executions: SwarmExecutionFormatView[];
	workerResults: string[];
	blocked: string[];
	mergeDigest: string[];
	executionAudit: string[];
	coverageMatrix: string[];
	retryQueue: string[];
	parallelGroups: string[];
	mergeProtocol: string[];
	collisionMatrix: string[];
	evidenceContract: string[];
	commanderNextActions: string[];
	handoffDigest: string[];
	parallelPlan?: {
		planId?: string;
		source?: string;
		merge?: unknown;
		workers?: unknown[];
	};
	planCoverage: string[];
	releaseCheckMetadata?: string[];
	sourceArtifacts: string[];
	claimLedger?: string[];
	claimLedgerPath?: string;
	claimLedgerEventCount?: number;
	claimLedgerTipHash?: string;
	runtimeClaimLedgerCaptured?: boolean;
	subagentRuntimeManifests?: any[];
	subagentRuntimeManifestPath?: string;
	subagentRuntimeManifestCount?: number;
	subagentRuntimeManifestsCaptured?: boolean;
	subagentRuntimeManifestStatus?: string;
	subagentRuntimeManifestErrors?: string[];
	structuredClaimMerge?: any;
	structuredClaimMergePath?: string;
	structuredClaimMergeStatus?: string;
	structuredClaimMergeErrors?: string[];
	workerRuntimePoolBridge?: any;
	workerRuntimePoolBridgeErrors?: string[];
	workerChildSessionRuntime?: any;
	workerChildSessionRuntimePath?: string;
	workerChildSessionRuntimeStatus?: string;
	workerRuntimePoolBridgeStatus?: string;
	workerRuntimePoolBridgePath?: string;
	workerChildSessionRuntimeErrors?: string[];
	workerLeaseScheduler?: any;
	workerLeaseSchedulerErrors?: string[];
	workerRetryHandoffClosure?: any;
	workerRetryHandoffClosurePath?: string;
	workerRetryHandoffClosureStatus?: string;
	workerRetryHandoffClosureErrors?: string[];
	workerRetryHandoffMergeSummary?: any;
	workerRetryHandoffMergeSummaryPath?: string;
	workerRetryHandoffMergeSummaryStatus?: string;
	workerRetryHandoffMergeSummaryErrors?: string[];
	memoryWritebackStatus?: string;
	memoryWritebackCount?: number;
	memoryWritebackEvents?: any[];
	memoryWritebackErrors?: string[];
	[key: string]: unknown;
};
