/** Profile-check critical/reverse marker lists. */
export const PROFILE_CHECK_CRITICAL_MARKERS: string[] = [
	// reverse product gates
	"partial_runtime_capture",
	"bind_ready",
	"re_native_runtime",
	"re_web_authz_state",
	"re_mobile_runtime",
	"re_exploit_lab",
	"re_proof_loop",
	"re_autopilot",
	"re_knowledge_graph",
	"re_toolchain_domain",
	"re_runtime_bridge",
	"re_runtime_adapter",
	"ToolchainDomainCapabilityV1",
	"ProfessionalRuntimeBridgesCheckV1",
	"RuntimeAdapterExecutionCheckV1",
	"domain_toolchain_matrix",
	"runtime_execution_bridge_matrix",
	"adapter_runner_parser_ingest_contract",
	"compact_resume_case_memory",
	"compact_resume_repair_from_case_memory",
	"compact_resume_success_skip_low_value_lane",
	"operator_command_floor",
	"proof_exit_criteria",
	"specialist_runtime_planner",
	"re_profile_check",
	"profile_check_artifact",
	"install_readiness",
	"reverse_capability_guards",
	"regression_guards",
];

export const PROFILE_CHECK_REVERSE_CAPABILITY_MARKERS: string[] = [
	"partial_runtime_capture",
	"runtime_capture_strong",
	"bind_ready",
	"re_domain_proof_exit",
	"re_runtime_adapter",
	"appendReverseRuntimeEvidence",
	"reverseDomainCaptureNextCommands",
	"reverse_domain_next",
	"reverse_proof_exit_missing",
	"blocked_until_runtime_capture_and_bind_ready",
	"Native deep symbol/import/string anchors",
	"browser/XHR/WS",
	"web scanner manual replay",
	"web authz matrix anchors",
	"JS signing replay harness anchors",
	"pwn ROP/libc chain anchors",
	"Exploit PoC inventory anchors",
	"PCAP stream ranking anchors",
	"memory forensics credential",
	"Firmware image metadata anchors",
	"iOS Frida/objection hook anchors",
	"Agent prompt surface anchors",
	"Malware IOC/config anchors",
	"Cloud identity anchors",
	"Identity/AD graph edge anchors",
	"Frida/GDB trace",
	"Web/CDP replay",
	"Frida/Mobile",
	"bridge-rev-ghidra-r2-angr",
	"verifier-pwn-crash-offset-primitive-exploit",
	"cdp-network-capture",
	"mobile-frida-java-hook-template",
	"adapter-r2-native-xref-runner",
	"adapter-frida-mobile-hook-runner",
	"adapter-web-cdp-network-runner",
	"adapter-pwntools-local-verifier-runner",
	"domain:web-api",
	"domain:rev-native",
	"domain:pwn",
	"domain:frontend-js",
	"domain:web-scan",
	"domain:mobile",
	"domain:mobile-ios",
	"domain:pcap-dfir",
	"domain:memory-forensics",
	"domain:firmware-iot",
	"domain:crypto",
	"domain:cloud-identity",
	"domain:exploit-reliability",
	"fallback_available",
];
