/** Specialist pack handlers: cloud/identity/agent. */
import type { SpecialistPackContext } from "./types.ts";

export function applyWantsCloudRuntime(ctx: SpecialistPackContext): void {
	ctx.specialists.push("Cloud/K8s identity");
	ctx.add(
		"cloud-runtime-repi-bridge",
		ctx.target
			? `printf '%s\n' "re_runtime_adapter run ${ctx.targetArg}" "re_domain_proof_exit show" "re_complete audit"`
			: "printf '[cloud-runtime-repi-bridge] target_missing\n'",
		"bridge cloud/k8s config analysis to runtime capture gates when reverse-relevant",
	);
	ctx.add(
		"cloud-identity-config-map",
		`python3 - <<'PY'\nimport hashlib, json, os, pathlib\nkeys=['AWS_ACCESS_KEY_ID','AWS_PROFILE','AWS_REGION','AWS_ROLE_ARN','AZURE_CLIENT_ID','AZURE_TENANT_ID','GOOGLE_APPLICATION_CREDENTIALS','KUBECONFIG','KUBERNETES_SERVICE_HOST','KUBERNETES_SERVICE_PORT']\nfor key in keys:\n    value=os.getenv(key)\n    if value:\n        print('[cloud-identity]', 'env='+key, 'len='+str(len(value)), 'sha256='+hashlib.sha256(value.encode()).hexdigest()[:16])\npaths=[pathlib.Path('~/.aws/credentials').expanduser(), pathlib.Path('~/.aws/config').expanduser(), pathlib.Path('~/.azure').expanduser(), pathlib.Path('~/.config/gcloud').expanduser(), pathlib.Path(os.getenv('KUBECONFIG','~/.kube/config')).expanduser(), pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount/token'), pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount/namespace'), pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount/ca.crt')]\nfor path in paths:\n    if path.exists():\n        try: data=path.read_bytes()[:4096]\n        except Exception: data=b''\n        print('[cloud-identity]', 'path='+str(path), 'type=' + ('dir' if path.is_dir() else 'file'), 'bytes='+str(path.stat().st_size if path.is_file() else 0), 'sha256='+hashlib.sha256(data).hexdigest()[:16])\nsa=pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount/token')\nif sa.exists(): print('[k8s-serviceaccount]', 'token_path='+str(sa), 'namespace='+(pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount/namespace').read_text(errors='ignore').strip() if pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount/namespace').exists() else '<unknown>'))\nPY`,
		"cloud/K8s identity material map without dumping secret values",
	);
	ctx.add(
		"cloud-runtime-config-scaffold",
		`cat > /tmp/repi-cloud-runtime.sh <<'SH'\nset +e\nprintf '[cloud-runtime-config] pwd=%s\\n' "$PWD"\nfind . -maxdepth 5 -type f \\( -name 'Dockerfile*' -o -name 'docker-compose*.yml' -o -name '*.tf' -o -name '*.tfvars' -o -name 'Chart.yaml' -o -name 'values*.yaml' -o -name '*deployment*.yml' -o -name '*service*.yml' -o -name '*rbac*.yml' -o -name '*secret*.yml' -o -name '*configmap*.yml' \\) -print 2>/dev/null | head -240 | sed 's/^/[cloud-runtime-config] manifest=/'\ncommand -v docker >/dev/null 2>&1 && { docker ps --format '[cloud-runtime-config] docker_container={{.Names}} image={{.Image}} status={{.Status}}' 2>/dev/null | head -80; docker compose ps 2>/dev/null | sed 's/^/[cloud-runtime-config] docker_compose=/' | head -80; }\ncommand -v kubectl >/dev/null 2>&1 && { kubectl config current-ctx.context 2>/dev/null | sed 's/^/[k8s-ctx.context] /'; kubectl auth can-i --list 2>/dev/null | head -80 | sed 's/^/[k8s-rbac] /'; kubectl get pods,svc,sa,secrets,roles,rolebindings -A -o wide 2>/dev/null | head -160 | sed 's/^/[k8s-resource] /'; }\ncommand -v aws >/dev/null 2>&1 && aws sts get-caller-identity 2>/dev/null | tr '\\n' ' ' | sed 's/^/[cloud-identity] aws_sts=/'\ncommand -v az >/dev/null 2>&1 && az account show 2>/dev/null | tr '\\n' ' ' | sed 's/^/[cloud-identity] azure_account=/'\ncommand -v gcloud >/dev/null 2>&1 && gcloud auth list --format=json 2>/dev/null | tr '\\n' ' ' | sed 's/^/[cloud-identity] gcloud_auth=/'\nSH\nchmod +x /tmp/repi-cloud-runtime.sh\n/tmp/repi-cloud-runtime.sh`,
		"container/K8s/IaC/cloud CLI runtime configuration and RBAC surface",
	);
	ctx.add(
		"cloud-metadata-probe-scaffold",
		`cat > /tmp/repi-cloud-metadata-probe.py <<'PY'\n#!/usr/bin/env python3\nimport hashlib, urllib.error, urllib.request\nENDPOINTS=[('aws-imds-root','http://169.254.169.254/latest/meta-data/'),('aws-imds-iam','http://169.254.169.254/latest/meta-data/iam/security-credentials/'),('gcp-metadata','http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/'),('azure-imds','http://169.254.169.254/metadata/instance?api-version=2021-02-01')]\ndef req(name,url,headers=None,method='GET',data=None):\n    try:\n        r=urllib.request.Request(url, headers=headers or {}, method=method, data=data)\n        with urllib.request.urlopen(r, timeout=2) as resp:\n            body=resp.read(2048)\n            print('[cloud-metadata]', 'provider='+name, 'status='+str(resp.status), 'bytes='+str(len(body)), 'sha256='+hashlib.sha256(body).hexdigest()[:16], 'sample='+body[:120].decode('utf-8','replace').replace('\\n',' '))\n    except Exception as exc:\n        print('[cloud-metadata]', 'provider='+name, 'error='+type(exc).__name__+':'+str(exc)[:120])\ntry:\n    token_req=urllib.request.Request('http://169.254.169.254/latest/api/token', method='PUT', headers={'X-aws-ec2-metadata-token-ttl-seconds':'60'})\n    with urllib.request.urlopen(token_req, timeout=2) as resp:\n        token=resp.read(256).decode()\n        print('[cloud-metadata]', 'provider=aws-imds-token', 'status='+str(resp.status), 'token_len='+str(len(token)))\n        req('aws-imds-v2-iam','http://169.254.169.254/latest/meta-data/iam/security-credentials/', {'X-aws-ec2-metadata-token': token})\nexcept Exception as exc:\n    print('[cloud-metadata]', 'provider=aws-imds-token', 'error='+type(exc).__name__+':'+str(exc)[:120])\nfor name,url in ENDPOINTS:\n    headers={}\n    if name.startswith('gcp'): headers['Metadata-Flavor']='Google'\n    if name.startswith('azure'): headers['Metadata']='true'\n    req(name,url,headers)\nPY\nchmod +x /tmp/repi-cloud-metadata-probe.py\npython3 /tmp/repi-cloud-metadata-probe.py`,
		"bounded AWS/GCP/Azure metadata identity probe with short timeouts and hashed samples",
	);
	ctx.add(
		"cloud-privilege-edge-scaffold",
		`python3 - <<'PY'\nimport os, pathlib, re\nprint('[cloud-privilege-edge]', 'inputs=env,kubeconfig,serviceaccount,manifests')\npatterns=[('aws',r'arn:aws:[^\\s"\\']+'),('gcp',r'[^\\s"\\']+@[^\\s"\\']+\\.iam\\.gserviceaccount\\.com'),('k8s-rbac',r'ClusterRoleBinding|RoleBinding|serviceAccountName|automountServiceAccountToken'),('secret-ref',r'secretKeyRef|envFrom|imagePullSecrets|Secret')]\nfiles=[]\nfor root in ['.', str(pathlib.Path('~/.kube').expanduser())]:\n    p=pathlib.Path(root)\n    if p.exists(): files += [f for f in p.rglob('*') if f.is_file() and f.stat().st_size < 2_000_000]\nfor f in files[:400]:\n    text=f.read_text(errors='ignore')[:200000]\n    for label,pat in patterns:\n        if re.search(pat,text,re.I): print('[cloud-privilege-edge]', 'file='+str(f), 'kind='+label)\nfor key in ['AWS_ROLE_ARN','AWS_WEB_IDENTITY_TOKEN_FILE','KUBERNETES_SERVICE_HOST','GOOGLE_APPLICATION_CREDENTIALS','AZURE_CLIENT_ID']:\n    if os.getenv(key): print('[cloud-privilege-edge]', 'env='+key, 'present=true')\nPY`,
		"privilege edge hints from IAM/K8s manifests, env, and local config",
	);
}
