/** Host aapt/aapt2 CAP with structured package/permission surface + pure fallback. */
export const MOBILE_AAPT_HOST_LINES: string[] = [
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then',
	"  if command -v aapt >/dev/null 2>&1 || command -v aapt2 >/dev/null 2>&1; then",
	"    AAPT_BIN=$(command -v aapt || command -v aapt2)",
	'    printf "[mobile-aapt] host=1 bin=%s\\n" "$AAPT_BIN"',
	'    BADGING=$("$AAPT_BIN" dump badging "$TARGET" 2>/tmp/repi-aapt-err.txt)',
	'    if [ -n "$BADGING" ]; then',
	'      printf "%s\\n" "$BADGING" | head -60 | sed "s/^/[mobile-aapt] /"',
	'      PKG=$(printf "%s\\n" "$BADGING" | sed -n "s/.*package: name=\'\\([^\']*\\)\'.*/\\1/p" | head -1)',
	'      VER=$(printf "%s\\n" "$BADGING" | sed -n "s/.*versionName=\'\\([^\']*\\)\'.*/\\1/p" | head -1)',
	'      SDK=$(printf "%s\\n" "$BADGING" | sed -n "s/.*sdkVersion:\'\\([^\']*\\)\'.*/\\1/p" | head -1)',
	'      [ -n "$PKG" ] && printf "[mobile-aapt-pkg] package=%s version=%s sdk=%s\\n" "$PKG" "${VER:-?}" "${SDK:-?}"',
	'      printf "%s\\n" "$BADGING" | grep -E "uses-permission:|launchable-activity:|application-label:" | head -40 | sed "s/^/[mobile-aapt-meta] /"',
	'      printf "%s\\n" "$BADGING" | sed -n "s/.*uses-permission: name=\'\\([^\']*\\)\'.*/[mobile-aapt-perm] name=\\1/p" | head -40',
	'      PERM_N=$(printf "%s\\n" "$BADGING" | grep -c "uses-permission:" || true)',
	'      printf "[mobile-aapt] permissions=%s ok=1\\n" "${PERM_N:-0}"',
	"      CAP_AAPT=1",
	"    else",
	'      ERR=$(head -3 /tmp/repi-aapt-err.txt 2>/dev/null | tr "\\n" " ")',
	'      printf "[mobile-aapt] dump_failed=1 err=%s\\n" "${ERR:-unknown}"',
	"    fi",
	"  else",
	'    printf "[mobile-aapt] host=0 note=aapt_missing\\n"',
	"  fi",
	"  if command -v python3 >/dev/null 2>&1; then",
	"python3 - \"$TARGET\" <<'PY'",
	"import pathlib, re, sys, zipfile",
	"p = pathlib.Path(sys.argv[1])",
	"print('[mobile-aapt-fallback] path=%s' % p)",
	"if not zipfile.is_zipfile(p):",
	"  print('[mobile-aapt-fallback] zip=0'); raise SystemExit(0)",
	"with zipfile.ZipFile(p) as z:",
	"  names = z.namelist()",
	"  print('[mobile-aapt-fallback] entries=%d' % len(names))",
	"  pkgs=[]; perms=[]",
	"  for name in names:",
	"    try: raw = z.read(name)[:2_000_000]",
	"    except Exception: continue",
	"    text = raw.decode('latin1','ignore')",
	"    for m in re.finditer(r'([a-zA-Z][\\w]*\\.){2,}[a-zA-Z][\\w]*', text):",
	"      s=m.group(0)",
	"      if re.search(r'android\\.|java\\.|javax\\.|okhttp|kotlin|apache', s, re.I): continue",
	'      if s.count(".")>=2 and len(s)<80: pkgs.append(s)',
	"    for m in re.finditer(r'android\\.permission\\.[A-Z0-9_]+', text):",
	"      perms.append(m.group(0))",
	"    for m in re.finditer(r'(?i)\\b(INTERNET|CAMERA|READ_SMS|WRITE_EXTERNAL_STORAGE|ACCESS_FINE_LOCATION|RECORD_AUDIO)\\b', text):",
	"      perms.append(m.group(0) if m.group(0).startswith('android') else 'android.permission.'+m.group(0).upper() if m.group(0).isupper() else m.group(0))",
	"  # path-based package from dex class descriptors later filled by host aapt; keep zip-derived",
	"  pkgs=list(dict.fromkeys(pkgs))[:12]",
	"  perms=list(dict.fromkeys(perms))[:20]",
	"  for s in pkgs: print('[mobile-aapt-pkg] package=%s source=zip-strings' % s)",
	"  for s in perms: print('[mobile-aapt-perm] name=%s' % s)",
	"  print('[mobile-aapt-fallback] ok=1 packages=%d permissions=%d' % (len(pkgs), len(perms)))",
	"PY",
	"    CAP_AAPT=1",
	"  fi",
	"fi",
];
