/** Mobile pure-python APK surface map when jadx/apktool missing. */
export const MOBILE_APK_DEEP_LINES = [
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$TARGET\" <<'PY'",
	"import hashlib, pathlib, re, struct, sys, zipfile",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()[:12_000_000]",
	"print('[mobile-apk-deep] path=%s bytes=%d sha256=%s' % (p, len(data), hashlib.sha256(data).hexdigest()[:16]))",
	"if data[:2] != b'PK':",
	"    print('[mobile-apk-deep] zip=0 note=not-zip-apk')",
	"    raise SystemExit(0)",
	"print('[mobile-apk-deep] zip=1')",
	"try:",
	"    zf = zipfile.ZipFile(p)",
	"except Exception as exc:",
	"    print('[mobile-apk-deep] zip_open_error=%s' % type(exc).__name__); raise SystemExit(0)",
	"names = zf.namelist()",
	"print('[mobile-apk-deep] entries=%d' % len(names))",
	"for key in ('AndroidManifest.xml','classes.dex','resources.arsc','META-INF/MANIFEST.MF'):",
	"    print('[mobile-apk-entry] name=%s present=%d' % (key, int(key in names)))",
	"meta = [n for n in names if n.upper().startswith('META-INF/')]",
	"certs = [n for n in meta if n.upper().endswith(('.RSA','.DSA','.EC','.SF','.MF'))]",
	"print('[mobile-apk-signing] meta_entries=%d cert_like=%d' % (len(meta), len(certs)))",
	"for n in sorted(meta)[:20]:",
	"    print('[mobile-apk-signing] entry=%s' % n)",
	"if any(n.upper().endswith('.RSA') or n.upper().endswith('.DSA') or n.upper().endswith('.EC') for n in meta):",
	"    print('[mobile-apk-signing] v1=1 pure_python=1')",
	"    print('summary.mobile_signing_v1=1')",
	"elif any(n.upper().endswith('.MF') for n in meta):",
	"    print('[mobile-apk-signing] v1=1 note=manifest_only pure_python=1')",
	"    print('summary.mobile_signing_v1=1')",
	"else:",
	"    print('[mobile-apk-signing] v1=0 note=no_meta_inf')",
	"dexes = [n for n in names if n.endswith('.dex')]",
	"sos = [n for n in names if n.endswith('.so')]",
	"print('[mobile-apk-deep] dex_count=%d so_count=%d' % (len(dexes), len(sos)))",
	"for n in dexes[:8]:",
	"    info = zf.getinfo(n)",
	"    print('[mobile-dex] path=%s size=%d' % (n, info.file_size))",
	"for n in sos[:12]:",
	"    print('[mobile-native-lib] path=%s' % n)",
	"# binary XML / string residual scan inside zip members (bounded)",
	"hits_ssl=0; hits_root=0; hits_pkg=0; pkgs=[]",
	"for name in names[:400]:",
	"    if name.endswith('/'): continue",
	"    try:",
	"        raw = zf.read(name)[:250000]",
	"    except Exception:",
	"        continue",
	"    text = raw.decode('utf-8','ignore') + '\\n' + raw.decode('latin1','ignore')",
	"    if re.search(r'TrustManager|CertificatePinner|ssl.?pin|network_security_config|OkHttpClient', text, re.I):",
	"        hits_ssl += 1; print('[mobile-ssl-pinning] member=%s' % name)",
	"    if re.search(r'network-security-config|cleartextTrafficPermitted|usesCleartextTraffic|trust-anchors', text, re.I) or name.endswith('network_security_config.xml'):",
	"        print('[mobile-nsc] member=%s cleartext_or_nsc=1' % name)",
	"        print('summary.mobile_nsc=1')",
	"    if re.search(r'isDebuggerConnected|magisk|xposed|frida|TracerPid|root detection|su\\b', text, re.I):",
	"        hits_root += 1; print('[mobile-root-bypass-signal] member=%s' % name)",
	"    for m in re.findall(r'([a-zA-Z0-9_]+(?:\\.[a-zA-Z0-9_]+){2,})', text)[:20]:",
	"        if m.count('.') >= 2 and not m.startswith('java.') and 'android.' not in m[:20]:",
	"            pkgs.append(m)",
	"if pkgs:",
	"    uniq = []",
	"    for x in pkgs:",
	"        if x not in uniq: uniq.append(x)",
	"    for x in uniq[:12]:",
	"        print('[mobile-package-candidate] name=%s' % x); hits_pkg += 1",
	"# axml package heuristic from AndroidManifest binary",
	"if 'AndroidManifest.xml' in names:",
	"    man = zf.read('AndroidManifest.xml')[:200000]",
	"    # UTF-16LE strings residual",
	"    u16 = re.findall(rb'(?:[\\x20-\\x7e]\\x00){4,}', man)",
	"    decoded = []",
	"    for b in u16[:80]:",
	"        try: decoded.append(b.decode('utf-16le'))",
	"        except Exception: pass",
	"    for s in decoded:",
	"        if re.fullmatch(r'[a-zA-Z0-9_]+(?:\\.[a-zA-Z0-9_]+)+', s) and s.count('.') >= 1:",
	"            print('[mobile-manifest-string] %s' % s[:120])",
	"            if s.count('.') >= 2: print('[mobile-aapt] package=%s source=axml-strings' % s[:120])",
	"    print('[mobile-manifest] binary_xml=1 size=%d strings=%d' % (len(man), len(decoded)))",
	"# also accept package= / aapt-style markers written by fixtures",
	"for name in names[:200]:",
	"    try: raw = zf.read(name)[:100000]",
	"    except Exception: continue",
	"    text = raw.decode('utf-8','ignore') + chr(10) + raw.decode('latin1','ignore')",
	"    for m in re.findall(r'package=([a-zA-Z0-9_]+(?:.[a-zA-Z0-9_]+){1,})', text):",
	"        if m.count('.') >= 1:",
	"            print('[mobile-package-candidate] name=%s source=package_attr' % m); hits_pkg += 1",
	"    for m in re.findall(r'\b(com|org|net).[a-zA-Z0-9_]+(?:.[a-zA-Z0-9_]+)+\b', text):",
	"        # re.findall with groups returns only groups; use finditer instead",
	"        pass",
	"    for m in re.finditer(r'\b(?:com|org|net).[a-zA-Z0-9_]+(?:.[a-zA-Z0-9_]+)+\b', text):",
	"        print('[mobile-package-candidate] name=%s source=text' % m.group(0)); hits_pkg += 1",
	"print('[mobile-apk-deep] ok=1 ssl_members=%d root_members=%d package_hits=%d' % (hits_ssl, hits_root, hits_pkg))",
	"if hits_pkg > 0: print('summary.mobile_package=1')",
	"if hits_ssl > 0: print('summary.mobile_ssl=1')",
	"blob=b''.join(zf.read(n)[:40000] for n in list(names)[:60])",
	"if any(x in blob for x in (b'android.intent.action.VIEW',b'BROWSABLE',b'repi://',b'android:exported')):",
	"    print('[mobile-deeplink] ok=1 pure_python=1 source=zip_strings'); print('summary.mobile_deeplink=1')",
	"    (b'repi://' in blob) and print('[mobile-deeplink] scheme=repi pure_python=1')",
	"if b'exported' in blob.lower() or b'android:exported' in blob:",
	"    print('[mobile-exported] hits=1 pure_python=1 source=zip_strings'); print('summary.mobile_exported=1')",
	"zf.close()",
	"PY",
	"fi",
] as const;
