/** Host jadx CAP: decompile APK to java sources + class/code surface. */
export const MOBILE_JADX_HOST_LINES = [
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && command -v jadx >/dev/null 2>&1; then',
	'  JADX_OUT="${REPI_WORKDIR:-/tmp}/repi-jadx-$(basename "$TARGET" | tr -c "A-Za-z0-9._-" "_")"',
	'  rm -rf "$JADX_OUT"',
	'  mkdir -p "$JADX_OUT"',
	'  printf "[mobile-jadx] host=1 bin=%s out=%s\\n" "$(command -v jadx)" "$JADX_OUT"',
	'  timeout 90s jadx -d "$JADX_OUT" --show-bad-code --no-res -q "$TARGET" >/tmp/repi-jadx-run.log 2>&1',
	"  JADX_RC=$?",
	'  JAVA_N=$(find "$JADX_OUT" -type f -name "*.java" 2>/dev/null | wc -l | tr -d " ")',
	'  KT_N=$(find "$JADX_OUT" -type f \\( -name "*.kt" -o -name "*.kts" \\) 2>/dev/null | wc -l | tr -d " ")',
	'  SRC_N=$(find "$JADX_OUT/sources" -type f 2>/dev/null | wc -l | tr -d " ")',
	'  printf "[mobile-jadx] rc=%s java=%s kt=%s sources=%s\\n" "${JADX_RC}" "${JAVA_N:-0}" "${KT_N:-0}" "${SRC_N:-0}"',
	"  # package/class surface",
	'  find "$JADX_OUT/sources" -type f -name "*.java" 2>/dev/null | head -40 | while read -r f; do',
	'    rel=${f#"$JADX_OUT/sources/"}',
	'    printf "[mobile-jadx-class] path=%s\\n" "$rel"',
	"  done",
	"  # interesting code strings from decompiled sources",
	'  if [ "${JAVA_N:-0}" != "0" ] || [ "${SRC_N:-0}" != "0" ]; then',
	'    grep -RInE "password|token|secret|Cipher|MessageDigest|TrustManager|CertificatePinner|HttpURLConnection|OkHttp|Retrofit|SharedPreferences|getSharedPreferences|package " "$JADX_OUT/sources" 2>/dev/null | head -40 | sed "s/^/[mobile-jadx-code] /"',
	'    printf "[mobile-jadx] ok=1 decompiled=1\\n"',
	"    CAP_JADX=1",
	"  else",
	'    head -5 /tmp/repi-jadx-run.log 2>/dev/null | sed "s/^/[mobile-jadx-log] /"',
	'    printf "[mobile-jadx] ok=0 note=no_java_sources\\n"',
	"  fi",
	'elif [ -n "$TARGET" ] && [ -e "$TARGET" ]; then',
	'  printf "[mobile-jadx] host=0 note=jadx_missing\\n"',
	"fi",
] as const;
