/** Host-local frida attach CAP (no USB device; proves dynamic instrumentation). */
// Landmark: CAP_LOCAL_ATTACH mobile-frida-local-attach interceptor clock_nanosleep
import { MOBILE_FRIDA_LOCAL_ATTACH_SCRIPT_LINES } from "./mobile-shell-frida-local-script.ts";

export const MOBILE_FRIDA_LOCAL_ATTACH_LINES: string[] = [
	"# Local-host frida attach CAP (no USB device; proves dynamic instrumentation + interceptor)",
	"if command -v frida >/dev/null 2>&1; then",
	'  if [ "${REPI_MOBILE_ATTACH:-0}" = "1" ] || [ "${REPI_FRIDA_LOCAL_ATTACH:-1}" = "1" ]; then',
	"    cat > /tmp/repi-frida-local-target.py <<'PY'",
	"import time, sys",
	'print("repi-frida-local-target-ready", flush=True)',
	"sys.stdout.flush()",
	"# busy-wait sleeps so libc clock_nanosleep/nanosleep is exercised under attach",
	"for _ in range(30):",
	"    time.sleep(0.2)",
	'print("repi-frida-local-target-done", flush=True)',
	"PY",
	"    python3 /tmp/repi-frida-local-target.py >/tmp/repi-frida-local-target.log 2>&1 &",
	"    LOCAL_PID=$!",
	"    sleep 0.4",
	'    if kill -0 "$LOCAL_PID" 2>/dev/null; then',
	'      printf "[mobile-frida-local] pid=%s target=python-sleep\\n" "$LOCAL_PID"',
	"      cat > /tmp/repi-frida-local-attach.js <<'JS'",
	...MOBILE_FRIDA_LOCAL_ATTACH_SCRIPT_LINES,
	"JS",
	'      ATT_OUT=$(timeout 18s frida -p "$LOCAL_PID" -l /tmp/repi-frida-local-attach.js 2>&1 || true)',
	'      printf "%s\\n" "$ATT_OUT" | grep -E "mobile-frida-local-attach|mobile-frida-local-hook|Attached|Failed|Error|Unable|TypeError" | head -60 | sed "s/^/[mobile-frida-local] /"',
	"      HOOKED=0; HITS=0",
	'      if printf "%s" "$ATT_OUT" | grep -q "mobile-frida-local-hook] hooked=1"; then HOOKED=1; fi',
	'      if printf "%s" "$ATT_OUT" | grep -q "mobile-frida-local-hook] hit "; then HITS=1; fi',
	'      if printf "%s" "$ATT_OUT" | grep -q "hits_total=[1-9]"; then HITS=1; fi',
	'      if printf "%s" "$ATT_OUT" | grep -q "mobile-frida-local-attach] ok=1"; then',
	'        printf "[mobile-frida-local] ok=1 attach=1 mode=host-process interceptor=%s hits=%s\\n" "$HOOKED" "$HITS"',
	"        CAP_ATTACH=1",
	"        CAP_LOCAL_ATTACH=1",
	"        CAP_FRIDA=1",
	'        if [ "$HOOKED" = "1" ]; then CAP_HOOKS=1; fi',
	"      else",
	'        ATT2=$(timeout 12s frida -p "$LOCAL_PID" -q -e \'console.log("[mobile-frida-local-attach] ok=1");\' 2>&1 || true)',
	'        printf "%s\\n" "$ATT2" | head -30 | sed "s/^/[mobile-frida-local] /"',
	'        if printf "%s" "$ATT2" | grep -q "ok=1"; then',
	'          printf "[mobile-frida-local] ok=1 attach=1 mode=host-process-q\\n"',
	"          CAP_ATTACH=1",
	"          CAP_LOCAL_ATTACH=1",
	"          CAP_FRIDA=1",
	"        else",
	'          printf "[mobile-frida-local] ok=0 note=attach_failed\\n"',
	'          head -5 /tmp/repi-frida-local-target.log 2>/dev/null | sed "s/^/[mobile-frida-local] target_log=/"',
	"        fi",
	"      fi",
	'      kill "$LOCAL_PID" 2>/dev/null || true',
	'      wait "$LOCAL_PID" 2>/dev/null || true',
	"    else",
	'      printf "[mobile-frida-local] ok=0 note=target_spawn_failed\\n"',
	'      head -5 /tmp/repi-frida-local-target.log 2>/dev/null | sed "s/^/[mobile-frida-local] target_log=/"',
	'      ls -la /tmp/repi-frida-local-target.py 2>/dev/null | sed "s/^/[mobile-frida-local] /"',
	"    fi",
	"  else",
	'    printf "[mobile-frida-local] skipped=1 set_REPI_FRIDA_LOCAL_ATTACH=1_or_REPI_MOBILE_ATTACH=1\\n"',
	"  fi",
	"fi",
];
