/** Mobile proof-capture rollup lines. */
export const MOBILE_PROOF_CAPTURE_LINES = [
	"# mobile proof-capture rollup (host-tool CAP path; attach remains opt-in)",
	"CAP_APK=0; CAP_AAPT=0; CAP_JADX=0; CAP_SSL=0; CAP_ROOT=0; CAP_FRIDA=0; CAP_DEVICE=0; CAP_ATTACH=${CAP_ATTACH:-0}; CAP_LOCAL_ATTACH=${CAP_LOCAL_ATTACH:-0}; CAP_HOOKS=0; CAP_DEEP=0; CAP_DEX=0",
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then CAP_APK=1; fi',
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && { command -v aapt >/dev/null 2>&1 || command -v aapt2 >/dev/null 2>&1; }; then CAP_AAPT=1; fi',
	'if command -v jadx >/dev/null 2>&1 && find /tmp -maxdepth 2 -type d -name "repi-jadx-*" 2>/dev/null | while read -r d; do find "$d" -type f -name "*.java" 2>/dev/null; done | head -1 | grep -q .; then CAP_JADX=1; fi',
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then strings -a "$TARGET" 2>/dev/null | grep -qiE "TrustManager|CertificatePinner|ssl.?pin|pinning|OkHttp" && CAP_SSL=1; fi',
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then strings -a "$TARGET" 2>/dev/null | grep -qiE "isDebuggerConnected|magisk|xposed|TracerPid|ptrace|frida|su\\b" && CAP_ROOT=1; fi',
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && command -v unzip >/dev/null 2>&1; then unzip -p "$TARGET" assets/markers.txt 2>/dev/null | grep -qiE "CertificatePinner|TrustManager|ssl" && CAP_SSL=1; unzip -p "$TARGET" assets/markers.txt 2>/dev/null | grep -qiE "isDebuggerConnected|magisk|xposed|frida|TracerPid" && CAP_ROOT=1; fi',
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then unzip -l "$TARGET" 2>/dev/null | grep -qiE "CertificatePinner|ssl|TrustManager|OkHttp" && CAP_SSL=1; fi',
	'if [ "${CAP_JADX:-0}" = "1" ]; then grep -RIqE "CertificatePinner|TrustManager|ssl-pinning|OkHttp" /tmp/repi-jadx-* 2>/dev/null && CAP_SSL=1; grep -RIqE "isDebuggerConnected|magisk|xposed|frida|TracerPid" /tmp/repi-jadx-* 2>/dev/null && CAP_ROOT=1; fi',
	"if command -v frida >/dev/null 2>&1; then CAP_FRIDA=1; fi",
	'if command -v adb >/dev/null 2>&1 && adb devices 2>/dev/null | grep -qE "device$|emulator"; then CAP_DEVICE=1; fi',
	"if [ -f /tmp/repi-mobile-frida-hooks.js ]; then CAP_HOOKS=1; fi",
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then CAP_DEEP=1; file -b "$TARGET" 2>/dev/null | grep -qiE "Zip|Android" && CAP_DEX=1; fi',
	'if [ "${REPI_MOBILE_ATTACH:-0}" = "1" ] && [ -n "$PKG" ] && command -v frida >/dev/null 2>&1; then CAP_ATTACH=1; fi',
	'printf "[mobile-proof-capture] apk=%s aapt=%s jadx=%s ssl_pin=%s root=%s frida=%s device=%s hooks=%s attach=%s local_attach=%s deep=%s dex=%s\\n" "$CAP_APK" "$CAP_AAPT" "$CAP_JADX" "$CAP_SSL" "$CAP_ROOT" "$CAP_FRIDA" "$CAP_DEVICE" "$CAP_HOOKS" "$CAP_ATTACH" "${CAP_LOCAL_ATTACH:-0}" "$CAP_DEEP" "$CAP_DEX"',
	'if [ "$CAP_APK" = "1" ] && { [ "$CAP_SSL" = "1" ] || [ "$CAP_ROOT" = "1" ] || [ "$CAP_DEEP" = "1" ] || [ "$CAP_JADX" = "1" ]; } && { [ "$CAP_FRIDA" = "1" ] || [ "$CAP_HOOKS" = "1" ]; }; then PROOF_EXIT=runtime_capture_strong; BIND=true; elif [ "$CAP_APK" = "1" ]; then PROOF_EXIT=partial_runtime_capture; BIND=true; else PROOF_EXIT=pending_runtime_capture; BIND=false; fi',
	'printf "[mobile-proof-capture] proof.exit=%s bind_ready=%s\\n" "$PROOF_EXIT" "$BIND"',
	'printf "summary.proof_exit=%s\\n" "$PROOF_EXIT"',
	'printf "summary.bind_ready=%s\\n" "$BIND"',
	'if [ "${CAP_LOCAL_ATTACH:-0}" = "1" ] || [ "${CAP_ATTACH:-0}" = "1" ]; then printf "summary.local_attach=1\\n"; fi',
	'echo "[runtime-technique] mobile-apk-triage-frida-bridge | mobile-ssl-pinning-bypass | mobile-root-bypass"',
	'grep -nE "Java.perform|Cipher.doFinal|MessageDigest|Mac.doFinal|String.equals|Module.findExportByName|Interceptor.attach" /tmp/repi-mobile-frida-hooks.js | head -80 | sed "s/^/[mobile-hook-line] /"',
] as const;
