/** Host-local frida attach JS payload lines (embedded into shell heredoc). */
// Landmark: CAP_LOCAL_ATTACH mobile-frida-local-attach-script
export const MOBILE_FRIDA_LOCAL_ATTACH_SCRIPT_LINES: string[] = [
	'console.log("[mobile-frida-local-attach] script-loaded");',
	'console.log("[mobile-frida-local-attach] pid=" + Process.id + " arch=" + Process.arch + " platform=" + Process.platform);',
	"try {",
	"  const mods = Process.enumerateModules().slice(0, 8);",
	'  console.log("[mobile-frida-local-attach] modules=" + mods.length + " first=" + (mods[0] ? mods[0].name : "none"));',
	'  const ranges = Process.enumerateRanges("r-x").slice(0, 3);',
	'  console.log("[mobile-frida-local-attach] rx_ranges=" + ranges.length);',
	"  let libc = null;",
	'  try { libc = Process.findModuleByName("libc.so.6") || Process.findModuleByName("libc.so") || Process.findModuleByName("libSystem.B.dylib"); } catch (e0) {}',
	'  console.log("[mobile-frida-local-attach] libc=" + (libc ? libc.name + "@" + libc.base : "none"));',
	"  if (libc && libc.enumerateExports) {",
	'    const ex = libc.enumerateExports().filter(function (e) { return e.type === "function" && /sleep|open|read|write|mmap/.test(e.name); }).slice(0, 8);',
	'    console.log("[mobile-frida-local-attach] libc_exports=" + ex.length);',
	'    for (var i = 0; i < ex.length; i++) console.log("[mobile-frida-local-export] " + ex[i].name);',
	"  }",
	"  try {",
	"    const thr = Process.enumerateThreads().slice(0, 4);",
	'    console.log("[mobile-frida-local-attach] threads=" + thr.length);',
	'  } catch (e1) { console.log("[mobile-frida-local-attach] threads-err=" + e1); }',
	"} catch (e) {",
	'  console.log("[mobile-frida-local-attach] enum-err=" + e);',
	"}",
	"let hits = 0;",
	"function resolveExport(name) {",
	"  try { if (Module.getGlobalExportByName) return Module.getGlobalExportByName(name); } catch (e) {}",
	"  try { if (Module.findExportByName) return Module.findExportByName(null, name); } catch (e) {}",
	"  return null;",
	"}",
	"function attachName(name) {",
	"  const addr = resolveExport(name);",
	"  if (!addr) return false;",
	"  try {",
	"    Interceptor.attach(addr, {",
	"      onEnter() {",
	"        hits++;",
	'        if (hits <= 6) console.log("[mobile-frida-local-hook] hit fn=" + name + " n=" + hits);',
	"      }",
	"    });",
	'    console.log("[mobile-frida-local-hook] interceptor=" + name);',
	"    return true;",
	"  } catch (e) {",
	'    console.log("[mobile-frida-local-hook] attach-err=" + name + " " + e);',
	"    return false;",
	"  }",
	"}",
	'const hooked = attachName("clock_nanosleep") || attachName("nanosleep") || attachName("sleep") || attachName("usleep");',
	'console.log("[mobile-frida-local-hook] hooked=" + (hooked ? 1 : 0));',
	"// self-trigger one native sleep so interceptor can fire even if target is between sleeps",
	"try {",
	'  const ns = resolveExport("nanosleep") || resolveExport("clock_nanosleep");',
	"  if (ns && Memory && Memory.alloc) {",
	"    const ts = Memory.alloc(16);",
	"    ts.writeU64(0); // tv_sec",
	"    // tv_nsec at +8",
	"    ts.add(8).writeU64(50000000);",
	'    const fn = new NativeFunction(ns, "int", ["pointer", "pointer"]);',
	"    try { fn(ts, ptr(0)); } catch (e2) {}",
	"  }",
	"} catch (e) {",
	'  console.log("[mobile-frida-local-hook] self-trigger-err=" + e);',
	"}",
	'console.log("[mobile-frida-local-attach] ok=1");',
	"setTimeout(function () {",
	'  console.log("[mobile-frida-local-hook] hits_total=" + hits);',
	'  console.log("[mobile-frida-local-hook] ok=" + (hooked ? 1 : 0));',
	"}, 1800);",
];
