/** Host frida deepen: frida-ps inventory + frida-compile (no device attach). */
export const MOBILE_FRIDA_HOST_DEEPEN_LINES: string[] = [
	"# Host frida deepen: compile hooks + local process inventory (no device attach unless REPI_MOBILE_ATTACH=1)",
	"if command -v frida >/dev/null 2>&1; then",
	"  FRIDA_BIN=$(command -v frida)",
	"  FRIDA_VER=$($FRIDA_BIN --version 2>/dev/null | head -1)",
	'  printf "[mobile-frida-host] version=%s host=1 bin=%s\\n" "${FRIDA_VER:-unknown}" "$FRIDA_BIN"',
	"  CAP_FRIDA=1",
	"  # local process inventory (host frida-server/self; not USB attach)",
	"  if command -v frida-ps >/dev/null 2>&1; then",
	"    PS_OUT=$(frida-ps 2>/dev/null | head -40)",
	'    if [ -n "$PS_OUT" ]; then',
	'      printf "%s\\n" "$PS_OUT" | sed "s/^/[mobile-frida-ps] /"',
	'      PS_N=$(printf "%s\\n" "$PS_OUT" | tail -n +3 | grep -cE "^[[:space:]]*[0-9]+" || true)',
	'      printf "[mobile-frida-ps] ok=1 rows=%s mode=local\\n" "${PS_N:-0}"',
	"    else",
	'      printf "[mobile-frida-ps] ok=0 note=empty_or_no_local_session\\n"',
	"    fi",
	"  else",
	'    printf "[mobile-frida-ps] ok=0 note=frida_ps_missing\\n"',
	"  fi",
	"  # compile hook template with frida-compile when available (proves toolchain runnable)",
	"  if [ -f /tmp/repi-mobile-frida-hooks.js ] && command -v frida-compile >/dev/null 2>&1; then",
	'    COMPILE_ROOT="${REPI_WORKDIR:-/tmp}/repi-frida-compile"',
	'    mkdir -p "$COMPILE_ROOT"',
	'    cp -f /tmp/repi-mobile-frida-hooks.js "$COMPILE_ROOT/hooks.js"',
	'    if (cd "$COMPILE_ROOT" && frida-compile -S -c -o hooks.compiled.js hooks.js) >/tmp/repi-frida-compile.log 2>&1; then',
	'      CBYTES=$(wc -c < "$COMPILE_ROOT/hooks.compiled.js" 2>/dev/null | tr -d " ")',
	'      printf "[mobile-frida-compile] ok=1 out=%s bytes=%s\\n" "$COMPILE_ROOT/hooks.compiled.js" "${CBYTES:-0}"',
	"      CAP_HOOKS=1",
	"    else",
	'      head -5 /tmp/repi-frida-compile.log 2>/dev/null | sed "s/^/[mobile-frida-compile] /"',
	"      # fallback: compile from repo workdir if present",
	"      if [ -f .repi-tmp/repi-mobile-frida-hooks.js ]; then",
	"        if frida-compile -S -c -o .repi-tmp/repi-mobile-frida-hooks.compiled.js .repi-tmp/repi-mobile-frida-hooks.js >/tmp/repi-frida-compile.log 2>&1; then",
	'          CBYTES=$(wc -c < .repi-tmp/repi-mobile-frida-hooks.compiled.js 2>/dev/null | tr -d " ")',
	'          printf "[mobile-frida-compile] ok=1 out=.repi-tmp/repi-mobile-frida-hooks.compiled.js bytes=%s\\n" "${CBYTES:-0}"',
	"          CAP_HOOKS=1",
	"        else",
	'          printf "[mobile-frida-compile] ok=0 note=compile_failed\\n"',
	"        fi",
	"      else",
	'        printf "[mobile-frida-compile] ok=0 note=compile_failed\\n"',
	"      fi",
	"    fi",
	"  elif [ -f /tmp/repi-mobile-frida-hooks.js ]; then",
	'    printf "[mobile-frida-compile] ok=0 note=frida_compile_missing\\n"',
	"  fi",
	'  printf "[mobile-frida-host] deepen=1 attach_default=0 note=set_REPI_MOBILE_ATTACH=1_for_device\\n"',
	"else",
	'  printf "[mobile-runtime-blocked] reason=frida_missing\\n"',
	"fi",
];
