/** Pure-python DEX/SO surface map when jadx is missing (no device attach). */

export const MOBILE_DEX_EXTRA_LINES: string[] = [
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$TARGET\" <<'PY'",
	"import pathlib, re, sys, zipfile",
	"p = pathlib.Path(sys.argv[1])",
	"print('[mobile-dex-extra] path=%s bytes=%d' % (p, p.stat().st_size if p.exists() else 0))",
	"if not zipfile.is_zipfile(p):",
	"  print('[mobile-dex-extra] zip=0'); raise SystemExit(0)",
	"with zipfile.ZipFile(p) as z:",
	"  names = z.namelist()",
	"  dexes = [n for n in names if n.endswith('.dex')]",
	"  sos = [n for n in names if n.endswith('.so')]",
	"  print('[mobile-dex-extra] dex_files=%d so_files=%d' % (len(dexes), len(sos)))",
	"  strings_found = []",
	"  class_hits = []",
	"  method_hits = []",
	"  for name in dexes[:8]:",
	"    try: raw = z.read(name)[:4_000_000]",
	"    except Exception as e:",
	"      print('[mobile-dex-extra] read_fail=%s err=%s' % (name, type(e).__name__)); continue",
	"    magic = raw[:8]",
	"    print('[mobile-dex-header] file=%s magic=%s size=%d' % (name, magic[:4].decode('latin1','ignore'), len(raw)))",
	"    if raw[:3] == b'dex' or raw[:4] == b'dex\\n':",
	"      print('[mobile-dex-header] format=dex')",
	"    for m in re.finditer(rb'[\\x20-\\x7e]{4,}', raw[:2_000_000]):",
	"      s = m.group(0).decode('ascii', 'ignore')",
	"      if re.search(r'L[a-zA-Z0-9_/$]+;|[a-zA-Z0-9_<>$]+\\(|https?://|CertificatePinner|TrustManager|isDebuggerConnected|Cipher|MessageDigest|OkHttp|Retrofit|SharedPreferences|getPackageInfo|AES|RSA|Mac\\.|javax\\.crypto', s):",
	"        strings_found.append(s[:120])",
	"      if s.startswith('L') and s.endswith(';') and '/' in s:",
	"        class_hits.append(s[:120])",
	"      # method descriptors: name(...), smali lifecycle, or explicit method: markers",
	"      if ('(' in s and ')' in s and re.match(r'^[a-zA-Z_<][\\w<>$]{1,}\\(.*\\)', s)) or re.fullmatch(r'(onCreate|onResume|onPause|onDestroy|onStart|onStop|encryptPayload|decryptPayload|doFinal|init|update)', s) or s.startswith('method:'):",
	"        method_hits.append(s[:120])",
	"  for name in sos[:12]:",
	"    try: raw = z.read(name)[:512_000]",
	"    except Exception: continue",
	"    is_elf = raw[:4] == bytes([0x7f,0x45,0x4c,0x46])",
	"    exports = []",
	"    for m in re.finditer(rb'[\\x20-\\x7e]{4,}', raw[:200_000]):",
	"      s = m.group(0).decode('ascii','ignore')",
	"      if re.search(r'strcmp|strncmp|memcmp|JNI_OnLoad|Java_|pthread|ssl|crypto', s, re.I):",
	"        exports.append(s[:80])",
	"    print('[mobile-so] path=%s elf=%d interesting=%d' % (name, int(is_elf), len(exports)))",
	"    for e in exports[:8]:",
	"      print('[mobile-so-symbol] name=%s sample=%s' % (name, e))",
	"  uniq_str = list(dict.fromkeys(strings_found))[:40]",
	"  uniq_cls = list(dict.fromkeys(class_hits))[:30]",
	"  uniq_mth = list(dict.fromkeys(method_hits))[:30]",
	"  for s in uniq_str[:16]:",
	"    print('[mobile-dex-string] sample=%s' % s.replace(chr(10),' ')[:120])",
	"  for s in uniq_cls[:12]:",
	"    print('[mobile-dex-class] name=%s' % s)",
	"  for s in uniq_mth[:12]:",
	"    print('[mobile-dex-method] sig=%s' % s)",
	"  ssl = sum(1 for s in uniq_str if re.search(r'CertificatePinner|TrustManager|ssl.?pin|OkHttp', s, re.I))",
	"  crypto = sum(1 for s in uniq_str if re.search(r'Cipher|MessageDigest|Mac|javax\\.crypto|AES|RSA', s, re.I))",
	"  root = sum(1 for s in uniq_str if re.search(r'isDebuggerConnected|magisk|xposed|frida|TracerPid|su\\b', s, re.I))",
	"  print('[mobile-dex-extra] ok=1 strings=%d classes=%d methods=%d ssl=%d crypto=%d root=%d' % (len(uniq_str), len(uniq_cls), len(uniq_mth), ssl, crypto, root))",
	"  if len(uniq_mth) > 0: print('summary.mobile_dex_methods=1')",
	"  if crypto > 0: print('summary.mobile_crypto=1')",
	"  if len(sos) > 0: print('summary.mobile_so=1')",
	"PY",
	"  CAP_DEX=1; CAP_DEEP=1",
	"fi",
];
