/** Mobile frida lean host path: inventory + hook surface without device attach. */
import { MOBILE_FRIDA_HOST_DEEPEN_LINES } from "./mobile-shell-frida-host.ts";
import { MOBILE_FRIDA_LOCAL_ATTACH_LINES } from "./mobile-shell-frida-local.ts";

export const MOBILE_FRIDA_LEAN_LINES: string[] = [
	...MOBILE_FRIDA_HOST_DEEPEN_LINES,
	...MOBILE_FRIDA_LOCAL_ATTACH_LINES,
	"if [ -f /tmp/repi-mobile-frida-hooks.js ]; then",
	"  HOOK_JS=/tmp/repi-mobile-frida-hooks.js",
	"  CAP_HOOKS=1",
	"  python3 - \"$HOOK_JS\" <<'PY'",
	"import pathlib, re, sys",
	"p = pathlib.Path(sys.argv[1])",
	'text = p.read_text(errors="ignore")',
	"sites = [",
	'  ("java_perform", r"Java\\.perform"),',
	'  ("cipher", r"Cipher\\.doFinal"),',
	'  ("digest", r"MessageDigest"),',
	'  ("mac", r"Mac\\.doFinal"),',
	'  ("string_eq", r"String\\.equals|StringCls\\.equals"),',
	'  ("debug", r"isDebuggerConnected"),',
	'  ("interceptor", r"Interceptor\\.attach"),',
	'  ("export", r"Module\\.findExportByName"),',
	"]",
	"hits = []",
	"for name, pat in sites:",
	"  n = len(re.findall(pat, text))",
	"  if n:",
	'    hits.append("%s=%d" % (name, n))',
	'    print("[mobile-frida-surface] hook=%s count=%d" % (name, n))',
	'print("[mobile-frida-surface] total_hook_kinds=%d bytes=%d" % (len(hits), len(text.encode())))',
	'print("[mobile-frida-surface] inventory=%s" % (",".join(hits) or "none"))',
	'if "Interceptor.attach" in text and "Java.perform" in text:',
	'  print("[mobile-frida-surface] dual_surface=java+native")',
	"PY",
	"fi",
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$TARGET\" <<'PY'",
	"import pathlib, re, sys, zipfile",
	"p = pathlib.Path(sys.argv[1])",
	'text = ""',
	"try:",
	"  if zipfile.is_zipfile(p):",
	"    with zipfile.ZipFile(p) as z:",
	"      for name in z.namelist()[:120]:",
	"        low = name.lower()",
	'        if low.endswith((".dex", ".so", "androidmanifest.xml", ".txt")) or "asset" in low:',
	'          try: text += "\\n" + z.read(name)[:200_000].decode("latin1", "ignore")',
	"          except Exception: pass",
	"  else:",
	'    text = p.read_bytes()[:2_000_000].decode("latin1", "ignore")',
	"except Exception as e:",
	'  print("[mobile-frida-map] zip_read_skipped=%s" % type(e).__name__)',
	"needles = {",
	'  "ssl_pin": r"CertificatePinner|TrustManager|network_security_config|OkHttp",',
	'  "crypto": r"Cipher|MessageDigest|Mac|AES|RSA|javax\\.crypto",',
	'  "root": r"isDebuggerConnected|magisk|xposed|frida|TracerPid|su\\b",',
	'  "native_cmp": r"strcmp|strncmp|memcmp|strstr",',
	"}",
	"for k, pat in needles.items():",
	"  m = re.findall(pat, text, re.I)",
	"  if m:",
	'    print("[mobile-frida-map] surface=%s hits=%d sample=%s" % (k, len(m), str(m[0])[:60]))',
	'print("[mobile-frida-map] ok=1")',
	"PY",
	"fi",
];
