/** Native qiling lightweight CAP via optional /opt/repi-tools/qiling-venv. */
export const NATIVE_SYMBOLIC_QILING_LINES: string[] = [
	"# Host qiling lightweight CAP (optional venv at /opt/repi-tools/qiling-venv)",
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then',
	'  QL_PY=""',
	"  if [ -x /opt/repi-tools/qiling-venv/bin/python ]; then QL_PY=/opt/repi-tools/qiling-venv/bin/python; fi",
	'  if [ -z "$QL_PY" ] && command -v python3 >/dev/null 2>&1; then',
	'    if python3 -c "import qiling" >/dev/null 2>&1; then QL_PY=python3; fi',
	"  fi",
	'  if [ -n "$QL_PY" ]; then',
	'    printf "[native-symbolic-qiling] host=1 python=%s\\n" "$QL_PY"',
	'    QL_OUT=$(timeout 20s "$QL_PY" - "$TARGET" <<\'PY\'',
	"import pathlib, sys",
	"path = pathlib.Path(sys.argv[1])",
	'print("[native-symbolic-qiling] path=%s bytes=%d" % (path, path.stat().st_size if path.is_file() else 0))',
	"try:",
	"  from qiling import Qiling",
	"  from qiling.const import QL_VERBOSE",
	"  import qiling as qlmod",
	'  print("[native-symbolic-qiling] version=%s" % getattr(qlmod, "__version__", "?"))',
	"  # lean load: system rootfs, no full OS bootstrap beyond loader",
	'  ql = Qiling([str(path)], rootfs="/", verbose=QL_VERBOSE.OFF)',
	'  print("[native-symbolic-qiling] arch=%s os=%s entry=0x%x" % (ql.arch.type, ql.os.type, ql.loader.elf_entry if hasattr(ql.loader, "elf_entry") else ql.arch.regs.arch_pc))',
	"  # bounded instruction window only",
	'  start = getattr(ql.loader, "elf_entry", None) or ql.arch.regs.arch_pc',
	"  ql.emu_start(start, 0, count=8)",
	"  pc = ql.arch.regs.arch_pc",
	'  print("[native-symbolic-qiling] emu=1 start=0x%x stop_pc=0x%x count=8" % (start, pc))',
	"  # map inventory (first few)",
	"  maps = 0",
	"  try:",
	"    for m in list(ql.mem.get_mapinfo())[:12]:",
	"      maps += 1",
	'      print("[native-symbolic-qiling-map] %s" % (m if isinstance(m, str) else str(m)[:120]))',
	"  except Exception:",
	"    pass",
	'  print("[native-symbolic-qiling] maps=%d" % maps)',
	'  print("[native-symbolic-qiling] ok=1")',
	"except Exception as e:",
	'  print("[native-symbolic-qiling] ok=0 note=%s" % type(e).__name__)',
	"  import traceback",
	"  for line in traceback.format_exc().splitlines()[-5:]:",
	'    print("[native-symbolic-qiling-err] %s" % line)',
	"PY",
	")",
	'    printf "%s\\n" "$QL_OUT"',
	'    if printf "%s" "$QL_OUT" | grep -q "\\[native-symbolic-qiling\\] ok=1"; then',
	"      CAP_SYMBOLIC=1; CAP_QILING=1",
	"    fi",
	"  else",
	'    printf "[native-symbolic-qiling] host=0 note=qiling_missing install=/opt/repi-tools/qiling-venv\\n"',
	"  fi",
	"else",
	'  printf "[native-symbolic-qiling] host=0 note=target_missing\\n"',
	"fi",
] as const;
