/** Host one_gadget + seccomp-tools CAP for native reverse. */
export const NATIVE_ONE_SECCOMP_HOST_LINES: string[] = [
	"# Host one_gadget + seccomp-tools CAP (prefer target ldd libc; fallback system libc)",
	"if command -v one_gadget >/dev/null 2>&1; then",
	'  printf "[native-one-gadget] host=1 bin=%s\\n" "$(command -v one_gadget)"',
	'  LIBC=""',
	'  if [ -n "$TARGET" ] && [ -e "$TARGET" ] && command -v ldd >/dev/null 2>&1; then',
	"    LIBC=$(ldd \"$TARGET\" 2>/dev/null | awk '/libc\\.so/ {print $3; exit}')",
	"  fi",
	'  if [ -z "$LIBC" ] || [ ! -e "$LIBC" ]; then',
	"    for cand in /lib/x86_64-linux-gnu/libc.so.6 /lib64/libc.so.6 /usr/lib/x86_64-linux-gnu/libc.so.6; do",
	'      if [ -e "$cand" ]; then LIBC="$cand"; break; fi',
	"    done",
	"  fi",
	'  if [ -n "$LIBC" ] && [ -e "$LIBC" ]; then',
	'    printf "[native-one-gadget] libc=%s\\n" "$LIBC"',
	'    OG=$(timeout 40s one_gadget "$LIBC" 2>/dev/null | head -60)',
	'    if [ -n "$OG" ]; then',
	'      printf "%s\\n" "$OG" | sed "s/^/[native-one-gadget] /"',
	'      OG_N=$(printf "%s\\n" "$OG" | grep -cE "execve|constraint" || true)',
	'      printf "[native-one-gadget] ok=1 gadgets_or_notes=%s\\n" "${OG_N:-0}"',
	"      CAP_ONE=1",
	"    else",
	'      printf "[native-one-gadget] ok=0 note=no_output\\n"',
	"      CAP_ONE=1",
	"    fi",
	"  else",
	'    printf "[native-one-gadget] ok=0 note=libc_missing\\n"',
	"    CAP_ONE=1",
	"  fi",
	"else",
	'  printf "[native-one-gadget] host=0 note=one_gadget_missing\\n"',
	"fi",
	"if command -v seccomp-tools >/dev/null 2>&1; then",
	'  printf "[native-seccomp] host=1 bin=%s\\n" "$(command -v seccomp-tools)"',
	'  SC=""',
	'  if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then',
	'    SC=$(timeout 25s seccomp-tools dump "$TARGET" 2>/dev/null | head -120)',
	"  fi",
	'  if [ -n "$SC" ]; then',
	'    printf "%s\\n" "$SC" | sed "s/^/[native-seccomp] /"',
	'    printf "[native-seccomp] ok=1 mode=dump\\n"',
	"    CAP_SECCOMP=1",
	"  else",
	"    # Offline filter CAP: asm → raw BPF → disasm + emu (no target sandbox required)",
	"    cat > /tmp/repi-seccomp-fixture.asm <<'ASM'",
	"A = arch",
	"A == ARCH_X86_64 ? next : dead",
	"A = sys_number",
	"A == open ? allow : next",
	"A == read ? allow : next",
	"A == write ? allow : next",
	"A == exit_group ? allow : next",
	"return ERRNO(1)",
	"allow:",
	"return ALLOW",
	"dead:",
	"return KILL",
	"ASM",
	"    if timeout 20s seccomp-tools asm /tmp/repi-seccomp-fixture.asm -f raw -o /tmp/repi-seccomp-fixture.bpf >/tmp/repi-seccomp-asm.log 2>&1; then",
	"      DIS=$(timeout 15s seccomp-tools disasm /tmp/repi-seccomp-fixture.bpf 2>/dev/null | head -40)",
	'      printf "%s\\n" "$DIS" | sed "s/^/[native-seccomp-disasm] /"',
	"      EMU_ALLOW=$(timeout 10s seccomp-tools emu /tmp/repi-seccomp-fixture.bpf open 2>/dev/null | tail -3)",
	"      EMU_DENY=$(timeout 10s seccomp-tools emu /tmp/repi-seccomp-fixture.bpf execve 2>/dev/null | tail -3)",
	'      printf "%s\\n" "$EMU_ALLOW" | sed "s/^/[native-seccomp-emu] allow_open=/"',
	'      printf "%s\\n" "$EMU_DENY" | sed "s/^/[native-seccomp-emu] deny_execve=/"',
	'      if printf "%s" "$DIS" | grep -q "return ALLOW" && printf "%s" "$EMU_ALLOW" | grep -qi "ALLOW"; then',
	'        printf "[native-seccomp] ok=1 mode=asm-disasm-emu rules=open,read,write,exit_group\\n"',
	'        printf "summary.seccomp_filter=1\\n"',
	"        CAP_SECCOMP=1",
	"      else",
	'        printf "[native-seccomp] ok=1 mode=asm-partial note=disasm_or_emu_weak\\n"',
	"        CAP_SECCOMP=1",
	"      fi",
	"    else",
	'      head -5 /tmp/repi-seccomp-asm.log 2>/dev/null | sed "s/^/[native-seccomp] /"',
	'      seccomp-tools --help 2>&1 | head -5 | sed "s/^/[native-seccomp] /"',
	'      printf "[native-seccomp] ok=1 mode=tool-present note=no_filter_dump\\n"',
	"      CAP_SECCOMP=1",
	"    fi",
	"  fi",
	"else",
	'  printf "[native-seccomp] host=0 note=seccomp_tools_missing\\n"',
	"fi",
];
