/** Pure-python ELF mitigation fingerprint when checksec binary missing. */
export const NATIVE_CHECKSEC_SURROGATE_LINES = [
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && ! command -v checksec >/dev/null 2>&1 && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$TARGET\" <<'PY'",
	"import pathlib, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()",
	"if not data.startswith(b'\\x7fELF'):",
	"    print('[native-checksec] surrogate=1 format=non-elf')",
	"    raise SystemExit(0)",
	"ei_class = data[4]  # 1=32 2=64",
	"ei_data = data[5]   # 1=le 2=be",
	"endian = '<' if ei_data == 1 else '>'",
	"is64 = ei_class == 2",
	"e_phoff = struct.unpack_from(endian + ('Q' if is64 else 'I'), data, 32 if is64 else 28)[0]",
	"e_phentsize = struct.unpack_from(endian + 'H', data, 54 if is64 else 42)[0]",
	"e_phnum = struct.unpack_from(endian + 'H', data, 56 if is64 else 44)[0]",
	"nx = 'unknown'; relro = 'none'; pie = 'unknown'; canary = 'unknown'; fortify = 'unknown'",
	"# dynamic tags / flags",
	"dyn = []",
	"for i in range(e_phnum):",
	"    off = e_phoff + i * e_phentsize",
	"    if off + e_phentsize > len(data): break",
	"    p_type = struct.unpack_from(endian + 'I', data, off)[0]",
	"    if is64:",
	"        p_flags = struct.unpack_from(endian + 'I', data, off + 4)[0]",
	"        p_offset = struct.unpack_from(endian + 'Q', data, off + 8)[0]",
	"        p_filesz = struct.unpack_from(endian + 'Q', data, off + 32)[0]",
	"    else:",
	"        p_offset = struct.unpack_from(endian + 'I', data, off + 4)[0]",
	"        p_filesz = struct.unpack_from(endian + 'I', data, off + 16)[0]",
	"        p_flags = struct.unpack_from(endian + 'I', data, off + 24)[0]",
	"    # PT_GNU_STACK = 0x6474e551",
	"    if p_type == 0x6474e551:",
	"        nx = 'yes' if (p_flags & 1) == 0 else 'no'  # PF_X",
	"    # PT_GNU_RELRO = 0x6474e552",
	"    if p_type == 0x6474e552:",
	"        relro = 'partial'",
	"    # PT_DYNAMIC = 2",
	"    if p_type == 2:",
	"        dyn.append((p_offset, p_filesz))",
	"# e_type ET_DYN=3 => PIE-ish",
	"e_type = struct.unpack_from(endian + 'H', data, 16)[0]",
	"pie = 'yes' if e_type == 3 else 'no'",
	"bind_now = False",
	"for doff, dsz in dyn:",
	"    pos = doff; end = min(len(data), doff + dsz)",
	"    step = 16 if is64 else 8",
	"    while pos + step <= end:",
	"        tag = struct.unpack_from(endian + ('Q' if is64 else 'I'), data, pos)[0]",
	"        val = struct.unpack_from(endian + ('Q' if is64 else 'I'), data, pos + (8 if is64 else 4))[0]",
	"        # DT_FLAGS=30 DF_BIND_NOW=0x8; DT_FLAGS_1=0x6ffffffb DF_1_NOW=0x1; DT_BIND_NOW=24",
	"        if tag in (24, 0x6ffffffb) or (tag == 30 and (val & 0x8)):",
	"            bind_now = True",
	"        if tag == 0: break",
	"        pos += step",
	"if relro == 'partial' and bind_now: relro = 'full'",
	"# canary / fortify via symbol strings (best-effort)",
	"blob = data",
	"if b'__stack_chk_fail' in blob or b'__intel_security_cookie' in blob:",
	"    canary = 'yes'",
	"elif b'stack_chk' in blob:",
	"    canary = 'yes'",
	"else:",
	"    canary = 'no'",
	"if b'__sprintf_chk' in blob or b'__printf_chk' in blob or b'__memcpy_chk' in blob:",
	"    fortify = 'yes'",
	"else:",
	"    fortify = 'no'",
	"print('[native-checksec] surrogate=1 source=pure-python-elf')",
	"print('[native-checksec] RELRO:%s' % ({'none':'No RELRO','partial':'Partial RELRO','full':'Full RELRO'}.get(relro, relro)))",
	"print('[native-checksec] Stack:%s' % ('Canary found' if canary == 'yes' else 'No canary found'))",
	"print('[native-checksec] NX:%s' % ('NX enabled' if nx == 'yes' else ('NX disabled' if nx == 'no' else 'NX unknown')))",
	"print('[native-checksec] PIE:%s' % ('PIE enabled' if pie == 'yes' else 'No PIE'))",
	"print('[native-checksec] FORTIFY:%s' % ('enabled' if fortify == 'yes' else 'disabled'))",
	"print('[native-checksec] summary nx=%s pie=%s canary=%s relro=%s fortify=%s' % (nx, pie, canary, relro, fortify))",
	"PY",
	"fi",
] as const;
