/** Native r2 function/cc surface + z3 micro sat (angr-free symbolic CAP). */
export const NATIVE_SYMBOLIC_R2_LINES: string[] = [
	"# Host r2 symbolic-ish surface: functions/cc/edges without angr",
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && command -v r2 >/dev/null 2>&1; then',
	'  printf "[native-symbolic-r2] host=1 bin=%s\\n" "$(command -v r2)"',
	'  R2_OUT=$(timeout 45s r2 -e scr.color=0 -e bin.cache=true -q -c "aaa; aflc; afll" "$TARGET" 2>/dev/null | head -80)',
	'  if [ -n "$R2_OUT" ]; then',
	'    printf "%s\\n" "$R2_OUT" | sed "s/^/[native-symbolic-r2] /"',
	'    STATS=$(printf "%s\\n" "$R2_OUT" | awk \'BEGIN{funcs=0;bbs=0;edges=0;maxcc=0} $1 ~ /^0x/ {funcs++; bbs+=$4+0; edges+=$5+0; if(($6+0)>maxcc) maxcc=$6+0} END{printf "funcs=%d bbs=%d edges=%d max_cc=%d", funcs,bbs,edges,maxcc}\')',
	'    printf "[native-symbolic-r2] %s\\n" "$STATS"',
	'    timeout 20s r2 -e scr.color=0 -q -c "aaa; ii~imp.; is~vuln; is~main" "$TARGET" 2>/dev/null | head -40 | sed "s/^/[native-symbolic-r2-sym] /" || true',
	"    for fn in main sym.vuln vuln entry0; do",
	'      PD=$(timeout 15s r2 -e scr.color=0 -q -c "aaa; s $fn; pdf" "$TARGET" 2>/dev/null | head -50)',
	'      if [ -n "$PD" ]; then',
	'        printf "%s\\n" "$PD" | sed "s/^/[native-symbolic-r2-pdf] /"',
	'        BRN=$(printf "%s\\n" "$PD" | grep -cE "call | je | jne | jl | jg | jle | jge | ja | jb | jmp " || true)',
	'        printf "[native-symbolic-r2] pdf_fn=%s branchish_or_call_lines=%s\\n" "$fn" "${BRN:-0}"',
	"        break",
	"      fi",
	"    done",
	'    printf "[native-symbolic-r2] ok=1\\n"',
	"    CAP_SYMBOLIC=1; CAP_R2=1",
	"  else",
	'    printf "[native-symbolic-r2] ok=0 note=empty_analysis\\n"',
	"  fi",
	"else",
	'  printf "[native-symbolic-r2] host=0 note=r2_or_target_missing\\n"',
	"fi",
	"# Optional z3 micro constraint (toy sat) as symbolic host signal without angr",
	"if command -v python3 >/dev/null 2>&1; then",
	"  Z3_OUT=$(python3 - <<'PY'",
	"try:",
	"  import z3",
	'  x = z3.BitVec("x", 32)',
	"  s = z3.Solver()",
	"  s.add(x * 3 + 7 == 0x1337)",
	"  r = s.check()",
	'  if str(r) == "sat":',
	"    m = s.model()",
	'    print("[native-symbolic-z3] ok=1 sat=1 x=%s" % m[x])',
	"  else:",
	'    print("[native-symbolic-z3] ok=1 sat=0")',
	"except Exception as e:",
	'  print("[native-symbolic-z3] ok=0 note=%s" % type(e).__name__)',
	"PY",
	")",
	'  printf "%s\\n" "$Z3_OUT"',
	'  if printf "%s" "$Z3_OUT" | grep -q "ok=1 sat=1"; then CAP_SYMBOLIC=1; CAP_Z3=1; fi',
	"fi",
] as const;
