/** Pure-python ROP gadget surface from ELF .text (no ROPgadget dep). */
// Landmark: native-rop-pure x86_64 classifier pop_rdi_ret leave_ret summary.native_rop_pure

export const NATIVE_ROP_PURE_LINES = [
	'if [ -n "${1:-}${TARGET:-}" ] && command -v python3 >/dev/null 2>&1; then',
	'T="${1:-$TARGET}"',
	"python3 - \"$T\" <<'PY'",
	"import pathlib, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes() if p.is_file() else b''",
	"print('[native-rop-pure] path=%s bytes=%d pure_python=1' % (p, len(data)))",
	"if data[:4] != b'\\x7fELF' or len(data) < 64:",
	"  print('[native-rop-pure] ok=0 note=not_elf')",
	"  raise SystemExit",
	"ei_class = data[4]  # 1=32 2=64",
	"ei_data = data[5]   # 1=LE",
	"endian = '<' if ei_data == 1 else '>'",
	"# scan for common x86_64 gadget byte patterns in file",
	"patterns = [",
	"  (b'\\xc3', 'ret'),",
	"  (b'\\x5f\\xc3', 'pop_rdi_ret'),",
	"  (b'\\x5e\\xc3', 'pop_rsi_ret'),",
	"  (b'\\x5a\\xc3', 'pop_rdx_ret'),",
	"  (b'\\x58\\xc3', 'pop_rax_ret'),",
	"  (b'\\x5b\\xc3', 'pop_rbx_ret'),",
	"  (b'\\xc9\\xc3', 'leave_ret'),",
	"  (b'\\x48\\x89\\xe7\\xc3', 'mov_rdi_rsp_ret'),",
	"]",
	"hits = {}",
	"for pat, name in patterns:",
	"  off = 0; n = 0; first = -1",
	"  while True:",
	"    j = data.find(pat, off)",
	"    if j < 0: break",
	"    n += 1",
	"    if first < 0: first = j",
	"    off = j + 1",
	"    if n >= 64: break",
	"  hits[name] = (n, first)",
	"  if n:",
	"    print('[native-rop-pure] gadget=%s count=%d first=0x%x' % (name, n, first))",
	"ret_n = hits.get('ret', (0, -1))[0]",
	"pop_n = sum(hits.get(k, (0, -1))[0] for k in ('pop_rdi_ret','pop_rsi_ret','pop_rdx_ret','pop_rax_ret','pop_rbx_ret'))",
	"print('[native-rop-pure] ret=%d pop_star=%d' % (ret_n, pop_n))",
	"ok = 1 if ret_n > 0 else 0",
	"print('[native-rop-pure] ok=%d pure_python=1' % ok)",
	"if ok:",
	"  print('summary.native_rop_pure=1')",
	"  print('[native-objdump-rop] pure_python=1 ret=%d note=byte_pattern_scan' % ret_n)",
	"PY",
	"fi",
] as const;
