/** Native unicorn emu + CAP rollup tail for symbolic host. */
export const NATIVE_SYMBOLIC_EMU_LINES: string[] = [
	"if unicorn_ok and entry is not None and loads:",
	"  try:",
	"    mu = Uc(UC_ARCH_X86, UC_MODE_64)",
	"    mapped_pages = 0",
	"    for off, va, fsz, msz, fl in loads:",
	"      page = va & ~0xFFF",
	"      end = (va + max(msz, fsz) + 0xFFF) & ~0xFFF",
	"      size = max(0x1000, end - page)",
	"      try:",
	"        mu.mem_map(page, size, UC_PROT_ALL)",
	"        mapped_pages += size // 0x1000",
	"      except Exception:",
	"        pass",
	"      if fsz > 0:",
	"        chunk = data[off:off + min(fsz, msz, len(data) - off)]",
	"        if chunk:",
	"          try:",
	"            mu.mem_write(va, chunk)",
	"          except Exception:",
	"            pass",
	"    stack = 0x7FFFFFFDE000",
	"    mu.mem_map(stack, 0x4000, UC_PROT_ALL)",
	"    mu.reg_write(UC_X86_REG_RSP, stack + 0x2000)",
	"    mu.emu_start(entry, 0, count=8, timeout=1000000)",
	"    rip = mu.reg_read(UC_X86_REG_RIP)",
	'    print("[native-symbolic] unicorn_emu=1 entry=0x%x stop_rip=0x%x mapped_pages=%d" % (entry, rip, mapped_pages))',
	'    print("[native-symbolic] ok=1 mode=unicorn+surface")',
	"  except Exception as exc:",
	"    try:",
	"      mu = Uc(UC_ARCH_X86, UC_MODE_64)",
	"      base = 0x1000000",
	"      mu.mem_map(base, 0x2000, UC_PROT_ALL)",
	"      mu.mem_write(base, bytes([0xc3]))",
	"      mu.reg_write(UC_X86_REG_RSP, base + 0x1000)",
	"      mu.mem_write(base + 0x1000, bytes(8))",
	"      mu.emu_start(base, 0, count=1, timeout=500000)",
	'      print("[native-symbolic] unicorn_emu=1 mode=ret_stub note=%s" % type(exc).__name__)',
	"      if branch_ops or cmp_ops or call_ops:",
	'        print("[native-symbolic] ok=1 mode=unicorn_stub+surface")',
	"      else:",
	'        print("[native-symbolic] ok=1 mode=unicorn_stub")',
	"    except Exception as exc2:",
	'      print("[native-symbolic] unicorn_emu=0 err=%s fallback=%s" % (type(exc).__name__, type(exc2).__name__))',
	"      if branch_ops or cmp_ops or call_ops:",
	'        print("[native-symbolic] ok=1 mode=surface_only note=emu_failed")',
	"      else:",
	'        print("[native-symbolic] ok=0 note=emu_failed")',
	"elif branch_ops or cmp_ops or call_ops:",
	'  print("[native-symbolic] ok=1 mode=pure-python-surface")',
	"else:",
	'  print("[native-symbolic] ok=0 note=no_surface")',
	"PY",
	")",
	'  printf "%s\\n" "$SYM_OUT"',
	'  if printf "%s" "$SYM_OUT" | grep -q "\\[native-symbolic\\] ok=1"; then CAP_SYMBOLIC=1; fi',
	'  if printf "%s" "$SYM_OUT" | grep -q "unicorn=1"; then CAP_UNICORN=1; fi',
	'  if printf "%s" "$SYM_OUT" | grep -q "unicorn_emu=1"; then CAP_UNICORN_EMU=1; fi',
	"else",
	'  printf "[native-symbolic] ok=0 note=python_or_target_missing\\n"',
	"fi",
];
