/** Native symbolic pure-python branch surface + unicorn import probe. */
export const NATIVE_SYMBOLIC_SURFACE_LINES: string[] = [
	"# Symbolic / unicorn lightweight CAP (host unicorn or pure-python branch surface)",
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && command -v python3 >/dev/null 2>&1; then',
	"  SYM_OUT=$(python3 - \"$TARGET\" <<'PY'",
	"import pathlib, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	'data = p.read_bytes() if p.is_file() else b""',
	'print("[native-symbolic] path=%s bytes=%d" % (p, len(data)))',
	"unicorn_ok = 0",
	"try:",
	"  from unicorn import Uc, UC_ARCH_X86, UC_MODE_64, UC_PROT_ALL",
	"  from unicorn.x86_const import UC_X86_REG_RIP, UC_X86_REG_RSP",
	"  unicorn_ok = 1",
	'  print("[native-symbolic] unicorn=1")',
	"except Exception as exc:",
	'  print("[native-symbolic] unicorn=0 note=%s" % type(exc).__name__)',
	"entry = None",
	"loads = []",
	"if data[:4] == bytes([0x7f,0x45,0x4c,0x46]) and len(data) > 0x40 and data[4] == 2:",
	'  entry = struct.unpack_from("<Q", data, 0x18)[0]',
	'  e_phoff = struct.unpack_from("<Q", data, 0x20)[0]',
	'  e_phentsize = struct.unpack_from("<H", data, 0x36)[0]',
	'  e_phnum = struct.unpack_from("<H", data, 0x38)[0]',
	"  for i in range(min(e_phnum, 64)):",
	"    o = e_phoff + i * e_phentsize",
	"    if o + 56 > len(data):",
	"      break",
	'    p_type, p_flags = struct.unpack_from("<II", data, o)',
	'    p_offset, p_vaddr = struct.unpack_from("<QQ", data, o + 8)',
	'    p_filesz, p_memsz = struct.unpack_from("<QQ", data, o + 32)',
	"    if p_type == 1 and p_memsz > 0:",
	"      loads.append((p_offset, p_vaddr, p_filesz, p_memsz, p_flags))",
	"  text = next(((off, va, fsz, msz) for off, va, fsz, msz, fl in loads if fl & 1 and fsz > 0), None)",
	"  if text:",
	"    text_off, text_va, text_sz = text[0], text[1], min(text[2], 0x10000)",
	"  else:",
	"    text_off = text_va = text_sz = None",
	'  print("[native-symbolic] elf64=1 entry=0x%x loads=%d text_va=%s text_off=%s text_sz=%s" % (entry, len(loads), hex(text_va) if text_va is not None else None, hex(text_off) if text_off is not None else None, text_sz))',
	"else:",
	"  text_off = text_va = text_sz = None",
	'  print("[native-symbolic] elf64=0")',
	"branch_ops = cmp_ops = call_ops = 0",
	"if text_off is not None and text_sz:",
	"  blob = data[text_off:text_off + text_sz]",
	"  i = 0",
	"  while i < len(blob) - 1:",
	"    b = blob[i]",
	"    if b == 0xE8:",
	"      call_ops += 1; i += 5; continue",
	"    if b in (0x74, 0x75, 0x7C, 0x7D, 0x7E, 0x7F, 0x72, 0x73, 0x76, 0x77):",
	"      branch_ops += 1; i += 2; continue",
	"    if b == 0x0F and blob[i + 1] in (0x84, 0x85, 0x8C, 0x8D, 0x8E, 0x8F):",
	"      branch_ops += 1; i += 6; continue",
	"    if b in (0x39, 0x3B, 0x83, 0x80, 0x81):",
	"      cmp_ops += 1",
	"    i += 1",
	'  print("[native-symbolic] surface branches=%d cmp_ish=%d calls=%d" % (branch_ops, cmp_ops, call_ops))',
	'  print("[native-symbolic] pure_python_surface=1")',
];
