/** Native rizin suite deepen CAP: rz-find/rz-asm/rz-hash. */
export const NATIVE_RIZIN_SUITE_LINES: string[] = [
	"# Host rizin suite deepen: rz-find / rz-asm / rz-hash (prefer /opt/repi-tools/rizin)",
	'RZ_ROOT=""',
	"for d in /opt/repi-tools/rizin /opt/repi-tools/rizin/bin; do",
	'  if [ -x "$d/rz-bin" ] || [ -x "$d/rz-find" ]; then RZ_ROOT="$d"; break; fi',
	"done",
	'if [ -z "$RZ_ROOT" ] && command -v rz-bin >/dev/null 2>&1; then RZ_ROOT=$(dirname "$(command -v rz-bin)"); fi',
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && [ -n "$RZ_ROOT" ]; then',
	'  PATH="$RZ_ROOT:$PATH"',
	"  CAP_RIZIN_FIND=0; CAP_RIZIN_ASM=0; CAP_RIZIN_HASH=0",
	"  if command -v rz-find >/dev/null 2>&1; then",
	'    printf "[native-rizin-find] host=1 bin=%s\\n" "$(command -v rz-find)"',
	"    for sym in main _start system execve strcpy gets; do",
	'      HIT=$(timeout 8s rz-find -S "$sym" "$TARGET" 2>/dev/null | head -3)',
	'      if [ -n "$HIT" ]; then printf "%s\\n" "$HIT" | sed "s/^/[native-rizin-find] symbol=$sym /"; CAP_RIZIN_FIND=1; fi',
	"    done",
	"    for imp in system execve strcpy gets read write; do",
	'      HIT=$(timeout 8s rz-find -I "$imp" "$TARGET" 2>/dev/null | head -3)',
	'      if [ -n "$HIT" ]; then printf "%s\\n" "$HIT" | sed "s/^/[native-rizin-find] import=$imp /"; CAP_RIZIN_FIND=1; fi',
	"    done",
	'    STR=$(timeout 8s rz-find -z "$TARGET" 2>/dev/null | head -80)',
	'    printf "%s\\n" "$STR" | grep -Ei "system|execve|/bin/sh|strcpy|gets|setvbuf|libc" | head -20 | sed "s/^/[native-rizin-find] string /" || true',
	'    if printf "%s" "$STR" | grep -qiE "system|execve|strcpy|setvbuf|libc"; then CAP_RIZIN_FIND=1; fi',
	'    printf "[native-rizin-find] ok=%s pure_python=0\\n" "$CAP_RIZIN_FIND"',
	"  else",
	'    printf "[native-rizin-find] host=0 note=rz-find_missing\\n"',
	"  fi",
	"  if command -v rz-asm >/dev/null 2>&1; then",
	'    printf "[native-rizin-asm] host=1 bin=%s\\n" "$(command -v rz-asm)"',
	'    ASM=$(rz-asm -a x86 -b 64 "nop; ret" 2>/dev/null | head -3)',
	'    if [ -n "$ASM" ]; then',
	'      printf "[native-rizin-asm] assemble=%s\\n" "$ASM"',
	'      DIS=$(rz-asm -a x86 -b 64 -d "$ASM" 2>/dev/null | head -4 | tr "\\n" ";")',
	'      printf "[native-rizin-asm] disasm=%s\\n" "${DIS:-n/a}"',
	"      CAP_RIZIN_ASM=1",
	"    fi",
	'    printf "[native-rizin-asm] ok=%s pure_python=0\\n" "$CAP_RIZIN_ASM"',
	"  else",
	'    printf "[native-rizin-asm] host=0 note=rz-asm_missing\\n"',
	"  fi",
	"  if command -v rz-hash >/dev/null 2>&1; then",
	'    printf "[native-rizin-hash] host=1 bin=%s\\n" "$(command -v rz-hash)"',
	'    H=$(timeout 8s rz-hash -a md5,sha1,sha256 "$TARGET" 2>/dev/null | head -12)',
	'    printf "%s\\n" "$H" | sed "s/^/[native-rizin-hash] /"',
	'    if [ -n "$H" ]; then CAP_RIZIN_HASH=1; fi',
	'    printf "[native-rizin-hash] ok=%s pure_python=0\\n" "$CAP_RIZIN_HASH"',
	"  else",
	'    printf "[native-rizin-hash] host=0 note=rz-hash_missing\\n"',
	"  fi",
	'  if [ "$CAP_RIZIN_FIND" = "1" ] || [ "$CAP_RIZIN_ASM" = "1" ] || [ "$CAP_RIZIN_HASH" = "1" ]; then',
	"    CAP_R2=1; CAP_SYM=1; CAP_RIZIN_SUITE=1",
	'    printf "[native-rizin-suite] ok=1 find=%s asm=%s hash=%s pure_python=0\\n" "$CAP_RIZIN_FIND" "$CAP_RIZIN_ASM" "$CAP_RIZIN_HASH"',
	"  fi",
	"else",
	'  printf "[native-rizin-suite] host=0 note=rz_root_or_target_missing\\n"',
	"fi",
] as const;
