/** Native rizin/rz-bin host CAP (info/imports/sections/mitigations). */
export const NATIVE_RIZIN_HOST_LINES: string[] = [
	"# Host rizin/rz-bin CAP (prefer /opt/repi-tools/rizin, then PATH)",
	'RZ_BIN=""',
	'for c in /opt/repi-tools/rizin/rz-bin /opt/repi-tools/rizin/bin/rz-bin; do [ -x "$c" ] && RZ_BIN="$c" && break; done',
	'if [ -z "$RZ_BIN" ] && command -v rz-bin >/dev/null 2>&1; then RZ_BIN=$(command -v rz-bin); fi',
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ] && [ -n "$RZ_BIN" ]; then',
	'  printf "[native-rizin] host=1 bin=%s\\n" "$RZ_BIN"',
	'  "$RZ_BIN" -v 2>/dev/null | head -2 | sed "s/^/[native-rizin] /"',
	'  "$RZ_BIN" -I "$TARGET" 2>/dev/null | head -40 | sed "s/^/[native-rizin-info] /"',
	'  "$RZ_BIN" -e "$TARGET" 2>/dev/null | head -20 | sed "s/^/[native-rizin-exports] /" || true',
	'  "$RZ_BIN" -i "$TARGET" 2>/dev/null | head -30 | sed "s/^/[native-rizin-imports] /" || true',
	'  "$RZ_BIN" -z "$TARGET" 2>/dev/null | head -20 | sed "s/^/[native-rizin-strings] /" || true',
	'  "$RZ_BIN" -S "$TARGET" 2>/dev/null | head -30 | sed "s/^/[native-rizin-sections] /" || true',
	'  "$RZ_BIN" -l "$TARGET" 2>/dev/null | head -20 | sed "s/^/[native-rizin-libs] /" || true',
	"  # mitigation-ish from info",
	'  INFO=$("$RZ_BIN" -I "$TARGET" 2>/dev/null || true)',
	'  printf "%s\\n" "$INFO" | awk -F\'[[:space:]]+\' \'/^relro/{print "[native-rizin-mitigation] relro="$2} /^canary/{print "[native-rizin-mitigation] canary="$2} /^nx/{print "[native-rizin-mitigation] nx="$2} /^pic/{print "[native-rizin-mitigation] pie="$2} /^static/{print "[native-rizin-mitigation] static="$2}\'',
	'  printf "[native-rizin] ok=1\\n"',
	"  CAP_R2=1; CAP_SYM=1; CAP_CHECKSEC=1",
	"else",
	'  printf "[native-rizin] host=0 note=rz-bin_or_target_missing\\n"',
	"fi",
] as const;
