/** Native angr symbolic CAP via optional /opt/repi-tools/angr-venv. */
/** Default path is light (project+entry); set REPI_NATIVE_SYMBOLIC=1 for CFGFast + multi-step. */
export const NATIVE_SYMBOLIC_ANGR_LINES: string[] = [
	"# Host angr symbolic CAP (optional venv at /opt/repi-tools/angr-venv)",
	'if [ -n "$TARGET" ] && [ -e "$TARGET" ]; then',
	'  ANGR_PY=""',
	"  if [ -x /opt/repi-tools/angr-venv/bin/python ]; then ANGR_PY=/opt/repi-tools/angr-venv/bin/python; fi",
	'  if [ -z "$ANGR_PY" ] && command -v python3 >/dev/null 2>&1; then',
	'    if python3 -c "import angr" >/dev/null 2>&1; then ANGR_PY=python3; fi',
	"  fi",
	'  if [ -n "$ANGR_PY" ]; then',
	'    printf "[native-symbolic-angr] host=1 python=%s deep=%s\\n" "$ANGR_PY" "${REPI_NATIVE_SYMBOLIC:-0}"',
	'    ANGR_OUT=$(timeout 25s "$ANGR_PY" - "$TARGET" <<\'PY\'',
	"import os, sys, pathlib, logging, warnings",
	"path = pathlib.Path(sys.argv[1])",
	'print("[native-symbolic-angr] path=%s bytes=%d" % (path, path.stat().st_size if path.is_file() else 0))',
	'warnings.filterwarnings("ignore")',
	'for name in ("angr", "angr.state_plugins.unicorn_engine", "cle", "claripy"):',
	"  logging.getLogger(name).setLevel(logging.ERROR)",
	"deep = os.environ.get('REPI_NATIVE_SYMBOLIC', '').strip() in ('1', 'true', 'on', 'full')",
	"try:",
	"  import angr",
	'  print("[native-symbolic-angr] version=%s" % getattr(angr, "__version__", "?"))',
	"  try:",
	"    import unicorn as _uc",
	'    print("[native-symbolic-angr] unicorn_plugin=1 version=%s" % getattr(_uc, "__version__", "?"))',
	"  except Exception as ue:",
	"    try:",
	"      import sys as _sys",
	'      _sys.path.insert(0, "/usr/local/lib/python3.12/dist-packages")',
	"      import unicorn as _uc",
	'      print("[native-symbolic-angr] unicorn_plugin=1 version=%s source=system" % getattr(_uc, "__version__", "?"))',
	"    except Exception as ue2:",
	'      print("[native-symbolic-angr] unicorn_plugin=0 note=%s/%s pure_host_unicorn_separate=1" % (type(ue).__name__, type(ue2).__name__))',
	"  p = angr.Project(str(path), auto_load_libs=False)",
	'  print("[native-symbolic-angr] entry=0x%x arch=%s" % (p.entry, p.arch))',
	"  if deep:",
	"    cfg = p.analyses.CFGFast()",
	"    funcs = list(cfg.functions.values())",
	'    print("[native-symbolic-angr] cfg_funcs=%d" % len(funcs))',
	"    shown = 0",
	"    for f in sorted(funcs, key=lambda x: x.addr):",
	'      name = f.name or ("sub_%x" % f.addr)',
	'      if any(k in name for k in ("main", "vuln", "entry", "init", "read", "system", "exec")) or shown < 8:',
	'        print("[native-symbolic-angr-func] name=%s addr=0x%x size=%s" % (name, f.addr, getattr(f, "size", "?")))',
	"        shown += 1",
	"      if shown >= 16: break",
	"    state = p.factory.entry_state()",
	"    simgr = p.factory.simulation_manager(state)",
	"    for i in range(4):",
	"      if not simgr.active: break",
	"      simgr.step()",
	'    print("[native-symbolic-angr] step_active=%d deadended=%d errored=%d" % (len(simgr.active), len(simgr.deadended), len(getattr(simgr, "errored", []))))',
	"  else:",
	"    # Light CAP: load project + entry only (fast interactive path).",
	'    print("[native-symbolic-angr] cfg_funcs=light mode=project_entry set_REPI_NATIVE_SYMBOLIC=1_for_cfg")',
	"    try:",
	"      state = p.factory.entry_state()",
	'      print("[native-symbolic-angr] step_active=1 deadended=0 errored=0 light_entry=1")',
	"    except Exception as se:",
	'      print("[native-symbolic-angr] light_entry_note=%s" % type(se).__name__)',
	"  try:",
	"    import claripy",
	'    x = claripy.BVS("x", 32)',
	"    s = claripy.Solver()",
	"    s.add(x * 3 + 7 == 0x1337)",
	"    if s.satisfiable():",
	'      print("[native-symbolic-angr] claripy_sat=1 sample=%s" % s.eval(x, 1)[0])',
	"    else:",
	'      print("[native-symbolic-angr] claripy_sat=0")',
	"  except Exception as ce:",
	'    print("[native-symbolic-angr] claripy_note=%s" % type(ce).__name__)',
	'  print("[native-symbolic-angr] ok=1")',
	"except Exception as e:",
	'  print("[native-symbolic-angr] ok=0 note=%s" % type(e).__name__)',
	"  import traceback",
	"  for line in traceback.format_exc().splitlines()[-6:]:",
	'    print("[native-symbolic-angr-err] %s" % line)',
	"PY",
	")",
	'    printf "%s\\n" "$ANGR_OUT"',
	'    if printf "%s" "$ANGR_OUT" | grep -q "\\[native-symbolic-angr\\] ok=1"; then',
	"      CAP_SYMBOLIC=1; CAP_ANGR=1",
	"    fi",
	"  else",
	'    printf "[native-symbolic-angr] host=0 note=angr_missing install=/opt/repi-tools/angr-venv\\n"',
	"  fi",
	"else",
	'  printf "[native-symbolic-angr] host=0 note=target_missing\\n"',
	"fi",
] as const;
