/** Context artifact kind -> evidence directory specs. */
import {
	evidenceAutofixDir,
	evidenceBrowserDir,
	evidenceCampaignsDir,
	evidenceChainsDir,
	evidenceCompilersDir,
	evidenceDecisionsDir,
	evidenceDelegationsDir,
	evidenceExploitLabDir,
	evidenceGraphsDir,
	evidenceKnowledgeDir,
	evidenceMapsDir,
	evidenceMobileRuntimeDir,
	evidenceNativeRuntimeDir,
	evidenceOperationsDir,
	evidenceOperatorsDir,
	evidenceProfileCheckDir,
	evidenceProofLoopsDir,
	evidenceReflectionsDir,
	evidenceReplayersDir,
	evidenceRunsDir,
	evidenceSupervisorsDir,
	evidenceSwarmsDir,
	evidenceVerifiersDir,
	evidenceWebAuthzDir,
} from "../storage.ts";

export function contextArtifactDirSpecs(): Array<[string, string]> {
	return [
		["map", evidenceMapsDir()],
		["browser", evidenceBrowserDir()],
		["web_authz", evidenceWebAuthzDir()],
		["exploit_lab", evidenceExploitLabDir()],
		["mobile_runtime", evidenceMobileRuntimeDir()],
		["native_runtime", evidenceNativeRuntimeDir()],
		["run", evidenceRunsDir()],
		["attack_graph", evidenceGraphsDir()],
		["exploit_chain", evidenceChainsDir()],
		["decision_core", evidenceDecisionsDir()],
		["campaign", evidenceCampaignsDir()],
		["operation", evidenceOperationsDir()],
		["delegation", evidenceDelegationsDir()],
		["swarm", evidenceSwarmsDir()],
		["supervisor", evidenceSupervisorsDir()],
		["reflection", evidenceReflectionsDir()],
		["operator", evidenceOperatorsDir()],
		["verifier", evidenceVerifiersDir()],
		["compiler", evidenceCompilersDir()],
		["replayer", evidenceReplayersDir()],
		["autofix", evidenceAutofixDir()],
		["proof_loop", evidenceProofLoopsDir()],
		["knowledge", evidenceKnowledgeDir()],
		["harness", evidenceProfileCheckDir()],
	];
}
