/** Build assembleContextPackArtifact input bag from state. */
// Landmark: buildAssembleContextPackArtifactInput

import { compactionResumeTelemetryPath } from "../storage.ts";
import { slug, truncateMiddle } from "../text.ts";
import { assembleContextPackMemoryBuilders } from "./build-core-assemble-memory.ts";
import type { ContextPackBuildState } from "./build-core-state.ts";
import {
	appendCompactResumeTransition,
	buildCompactResumeLedgerV2Report,
	buildContextEvidenceTail,
	buildContextMemoryTail,
	buildToolDigest,
	contextCompactionLedger,
	formatCompletionAudit,
	formatMission,
} from "./deps.ts";
import { contextArtifactHashes, contextPackSha256, memoryPath } from "./index.ts";

export function buildAssembleContextPackArtifactInput(state: ContextPackBuildState, nextCommands: string[]): any {
	const {
		timestamp,
		mission,
		active,
		supervisorPath,
		reflectionPath,
		supervisor,
		reflection,
		target,
		autonomousBudget,
		swarmRetry,
		checkSummary,
		pendingGates,
		repairQueue,
		commanderMergeBudget,
		workerScoreboard,
		swarmRetryQueue,
		memorySettings,
		includeMemoryRuntimeReports,
		caseMemoryPlan,
		caseMemoryNextCommands,
		reflectionReuseRules,
		route,
		mode,
		memoryOrchestrator,
		contextPath,
		scope,
		options,
	} = state;
	return {
		mission,
		active,
		pendingGates,
		reflectionPath,
		supervisorPath,
		reflection,
		supervisor,
		repairQueue,
		swarmRetryQueue,
		autonomousBudget,
		commanderMergeBudget,
		caseMemoryPlan,
		nextCommands,
		scope,
		contextPath,
		timestamp,
		route,
		target,
		mode,
		options,
		includeMemoryRuntimeReports,
		memorySettings,
		swarmRetry,
		workerScoreboard,
		caseMemoryNextCommands,
		reflectionReuseRules,
		checkSummary,
		memoryOrchestrator,
		appendCompactResumeTransition,
		buildCompactResumeLedgerV2Report,
		...assembleContextPackMemoryBuilders(),
		buildContextEvidenceTail,
		buildContextMemoryTail,
		contextArtifactHashes,
		slug,
		memoryPath,
		contextCompactionLedger,
		truncateMiddle,
		buildToolDigest,
		formatCompletionAudit,
		formatMission,
		compactionResumeTelemetryPath,
		contextPackSha256,
	};
}
