/** Optional memory artifact path pairs (product-lean opt-in). */
import { existsSync } from "node:fs";
import {
	caseMemoryPath,
	compactResumeLedgerV2ReportPath,
	compactResumeTransitionLedgerPath,
	memoryActiveInjectionPackPath,
	memoryActiveKernelReportPath,
	memoryActiveStrategyBoardPath,
	memoryArtifactScopeFilterReportPath,
	memoryContradictionLedgerPath,
	memoryDepositionEventBusPath,
	memoryDepositionReportPath,
	memoryDistillationReportPath,
	memoryDistillPromotionBookPath,
	memoryDistillPromotionCandidateLedgerPath,
	memoryDistillPromotionReportPath,
	memoryEventsPath,
	memoryExperienceClaimsPath,
	memoryExperienceEpisodesPath,
	memoryExperienceLessonBookPath,
	memoryExperiencePromotionLedgerPath,
	memoryExperienceReportPath,
	memoryFeedbackClosureReportPath,
	memoryInjectionPacketPath,
	memoryLifecycleBoardPath,
	memoryMaturationActionBoardPath,
	memoryMaturationRuntimeLedgerPath,
	memoryMaturationRuntimeReportPath,
	memoryOrchestratorReportPath,
	memoryQualityBoardPath,
	memoryQualityLedgerPath,
	memoryQualityReportPath,
	memoryQuarantinePath,
	memoryReplayEvaluatorBoardPath,
	memoryReplayEvaluatorLedgerPath,
	memoryReplayEvaluatorReportPath,
	memoryRetrievalReportPath,
	memoryScopeIsolationReportPath,
	memorySedimentationReportPath,
	memorySemanticIndexPath,
	memorySkillCapsuleBookPath,
	memorySkillCapsuleLedgerPath,
	memorySkillCapsuleReportPath,
	memoryStoreReportPath,
	memoryStoreSnapshotPath,
	memoryStrategyCapsuleBookPath,
	memoryStrategyCapsuleLedgerPath,
	memoryStrategyCapsuleReportPath,
	memorySupervisorReportPath,
	memoryUsefulnessEvalReportPath,
	memoryVectorIndexPath,
	memoryVectorSearchReportPath,
} from "../storage.ts";

const existingPath = (path: string): string | undefined => (existsSync(path) ? path : undefined);

export function fullContextMemoryPairs(): Array<[string, string | undefined]> {
	return [
		["artifact_scope_filter", existingPath(memoryArtifactScopeFilterReportPath())],
		["memory_events", existingPath(memoryEventsPath())],
		["memory_case_memory", existingPath(caseMemoryPath())],
		["memory_retrieval_report", existingPath(memoryRetrievalReportPath())],
		["memory_store_report", existingPath(memoryStoreReportPath())],
		["memory_store_snapshot", existingPath(memoryStoreSnapshotPath())],
		["memory_usefulness_eval", existingPath(memoryUsefulnessEvalReportPath())],
		["memory_feedback_closure", existingPath(memoryFeedbackClosureReportPath())],
		["memory_scope_isolation", existingPath(memoryScopeIsolationReportPath())],
		["memory_orchestrator", existingPath(memoryOrchestratorReportPath())],
		["memory_deposition_report", existingPath(memoryDepositionReportPath())],
		["memory_deposition_events", existingPath(memoryDepositionEventBusPath())],
		["memory_experience_report", existingPath(memoryExperienceReportPath())],
		["memory_experience_episodes", existingPath(memoryExperienceEpisodesPath())],
		["memory_experience_claims", existingPath(memoryExperienceClaimsPath())],
		["memory_experience_lesson_book", existingPath(memoryExperienceLessonBookPath())],
		["memory_experience_promotions", existingPath(memoryExperiencePromotionLedgerPath())],
		["memory_skill_capsule_report", existingPath(memorySkillCapsuleReportPath())],
		["memory_skill_capsules", existingPath(memorySkillCapsuleLedgerPath())],
		["memory_skill_capsule_book", existingPath(memorySkillCapsuleBookPath())],
		["memory_distill_promotion_report", existingPath(memoryDistillPromotionReportPath())],
		["memory_distill_promotion_candidates", existingPath(memoryDistillPromotionCandidateLedgerPath())],
		["memory_distill_promotion_book", existingPath(memoryDistillPromotionBookPath())],
		["memory_quality_report", existingPath(memoryQualityReportPath())],
		["memory_quality_ledger", existingPath(memoryQualityLedgerPath())],
		["memory_quality_board", existingPath(memoryQualityBoardPath())],
		["memory_replay_report", existingPath(memoryReplayEvaluatorReportPath())],
		["memory_replay_ledger", existingPath(memoryReplayEvaluatorLedgerPath())],
		["memory_replay_board", existingPath(memoryReplayEvaluatorBoardPath())],
		["memory_strategy_capsule_report", existingPath(memoryStrategyCapsuleReportPath())],
		["memory_strategy_capsules", existingPath(memoryStrategyCapsuleLedgerPath())],
		["memory_strategy_capsule_book", existingPath(memoryStrategyCapsuleBookPath())],
		["memory_active_kernel_report", existingPath(memoryActiveKernelReportPath())],
		["memory_active_injection_pack", existingPath(memoryActiveInjectionPackPath())],
		["memory_active_strategy_board", existingPath(memoryActiveStrategyBoardPath())],
		["memory_maturation_runtime_report", existingPath(memoryMaturationRuntimeReportPath())],
		["memory_maturation_runtime_ledger", existingPath(memoryMaturationRuntimeLedgerPath())],
		["memory_maturation_action_board", existingPath(memoryMaturationActionBoardPath())],
		["compact_resume_transition_ledger", existingPath(compactResumeTransitionLedgerPath())],
		["compact_resume_ledger_v2_report", existingPath(compactResumeLedgerV2ReportPath())],
		["memory_vector_index", existingPath(memoryVectorIndexPath())],
		["memory_vector_search", existingPath(memoryVectorSearchReportPath())],
		["memory_distillation_report", existingPath(memoryDistillationReportPath())],
		["memory_quarantine", existingPath(memoryQuarantinePath())],
		["memory_semantic_index", existingPath(memorySemanticIndexPath())],
		["memory_contradiction_ledger", existingPath(memoryContradictionLedgerPath())],
		["memory_injection_packet", existingPath(memoryInjectionPacketPath())],
		["memory_sedimentation_report", existingPath(memorySedimentationReportPath())],
		["memory_supervisor_report", existingPath(memorySupervisorReportPath())],
		["memory_lifecycle_board", existingPath(memoryLifecycleBoardPath())],
	];
}
