/** Context-pack artifact type. */

import type { ArtifactScopeFilterReportV1 } from "../artifact-scope-types.ts";
import type { AutonomousExecutionBudget } from "../operator-format-types.ts";
import type { CaseMemoryLanePlan } from "../proof-loop-runtime/types.ts";
import type { ContextArtifactIndexEntry, ContextResumeVerification } from "./types-index.ts";

export type ContextPackArtifact = {
	contractId?: string;
	schemaVersion?: 2;
	timestamp: string;
	createdAt?: string;
	missionId?: string;
	sessionId?: string;
	cwd?: string;
	workspaceRoot?: string;
	route?: string;
	target?: string;
	mode: "pack" | "resume";
	contextPath?: string;
	contextSha256?: string;
	resumedFromContextPath?: string;
	scope?: {
		missionId?: string;
		sessionId: string;
		cwd: string;
		workspaceRoot: string;
		target?: string;
		branchId: string;
	};
	artifactHashes?: Array<{ artifactId: string; path: string; sha256: string | null; required: boolean }>;
	resumeQueueStatus?: "queued" | "running" | "done" | "blocked" | "exhausted";
	idempotencyKey?: string;
	ledgerPath?: string;
	closure?: {
		status: "open" | "closed" | "blocked" | "exhausted";
		closedAt: string | null;
		reason: string;
		verifiedBy: string;
	};
	resumeContract?: {
		contractId: string;
		schemaVersion: 2;
		compactionEntryId: string;
		contextPath: string;
		contextSha256: string;
		cwd: string;
		missionId: string;
		sessionId: string;
		target: string;
		artifactHashes: Array<{ artifactId: string; path: string; sha256: string; required: boolean }>;
		resumeQueueStatus: "queued" | "running" | "done" | "blocked" | "exhausted";
		idempotencyKey: string;
		ledgerPath: string;
		budget: { maxResumeTurns: number; maxOperatorDispatch: number; maxProofLoops: number };
		closure: {
			status: "open" | "closed" | "blocked" | "exhausted";
			closedAt: string | null;
			reason: string;
			verifiedBy: string;
		};
	};
	compactionLedger?: { path: string; appendOnly: true; prevHash: string; entryHash: string };
	exactResumeVerification?: ContextResumeVerification;
	activeLane?: string;
	checkSummary: string[];
	missionSnapshot: string;
	evidenceTail: string;
	memoryTail: string;
	toolDigest: string;
	completionAudit: string;
	artifactIndex: ContextArtifactIndexEntry[];
	artifactScopeFilter?: ArtifactScopeFilterReportV1;
	memoryOrchestrator?: any;
	memoryDeposition?: any;
	memoryExperience?: any;
	memorySkillCapsules?: any;
	memoryDistillPromotion?: any;
	memoryQuality?: any;
	memoryReplay?: any;
	memoryStrategy?: any;
	memoryActiveKernel?: any;
	memoryMaturation?: any;
	compactResumeLedgerV2?: any;
	repairQueue: string[];
	commanderMergeBudget: string[];
	workerScoreboard: string[];
	swarmRetryQueue: string[];
	autonomousBudget: AutonomousExecutionBudget;
	dispatcherScoreDecay: string[];
	repeatedFailureDemotions: string[];
	highScorePromotions: string[];
	caseMemoryLanePlan?: CaseMemoryLanePlan;
	caseMemoryNextCommands: string[];
	reflectionReuseRules: string[];
	resumeBrief: string[];
	nextCommands: string[];
	sourceArtifacts: string[];
};
