/** Domain-specific active tool sets (softband split). */
export const DOMAIN_ACTIVE_TOOLS: Record<string, readonly string[]> = {
	// Keep values on the lean product surface (no re_subagent/re_reflect/re_compiler). re_operator is lean-global.
	"Native reverse": [
		"re_native_runtime",
		"re_exploit_lab",
		"re_domain_proof_exit",
		"re_operator",
		"re_proof_loop",
		"re_verifier",
		"re_replayer",
	],
	"Pwn / exploit": [
		"re_native_runtime",
		"re_exploit_lab",
		"re_domain_proof_exit",
		"re_operator",
		"re_proof_loop",
		"re_verifier",
		"re_replayer",
	],
	"Exploit reliability": [
		"re_exploit_lab",
		"re_native_runtime",
		"re_domain_proof_exit",
		"re_proof_loop",
		"re_replayer",
		"re_verifier",
	],
	"Web / API pentest": [
		"re_live_browser",
		"re_web_authz_state",
		"re_js_signing",
		"re_domain_proof_exit",
		"re_operator",
		"re_verifier",
		"re_replayer",
		"re_graph",
	],
	"Web pentest scanning": [
		"re_live_browser",
		"re_web_authz_state",
		"re_domain_proof_exit",
		"re_operator",
		"re_verifier",
		"re_replayer",
		"re_graph",
	],
	"Frontend JS reverse": [
		"re_js_signing",
		"re_live_browser",
		"re_domain_proof_exit",
		"re_operator",
		"re_verifier",
		"re_replayer",
	],
	"Mobile / Android": ["re_mobile_runtime", "re_domain_proof_exit", "re_verifier", "re_proof_loop", "re_replayer"],
	"Mobile / iOS": ["re_mobile_runtime", "re_domain_proof_exit", "re_verifier", "re_proof_loop", "re_replayer"],
	"Firmware / IoT": [
		"re_runtime_adapter",
		"re_native_runtime",
		"re_domain_proof_exit",
		"re_verifier",
		"re_proof_loop",
		"re_graph",
	],
	"DFIR / PCAP / stego": ["re_runtime_adapter", "re_domain_proof_exit", "re_verifier", "re_graph", "re_proof_loop"],
	"Memory forensics": ["re_runtime_adapter", "re_domain_proof_exit", "re_verifier", "re_graph", "re_proof_loop"],
	"Malware analysis": [
		"re_runtime_adapter",
		"re_native_runtime",
		"re_domain_proof_exit",
		"re_verifier",
		"re_proof_loop",
	],
	"Cloud / container": ["re_map", "re_graph", "re_verifier", "re_domain_proof_exit", "re_evidence"],
	"Identity / Windows / AD": ["re_map", "re_graph", "re_verifier", "re_domain_proof_exit", "re_evidence"],
	"Agent / LLM boundary": ["re_map", "re_graph", "re_verifier", "re_domain_proof_exit", "re_complete"],
	"Crypto / stego": ["re_runtime_adapter", "re_domain_proof_exit", "re_verifier", "re_proof_loop", "re_graph"],
	"CTF / sandbox": [
		"re_native_runtime",
		"re_exploit_lab",
		"re_live_browser",
		"re_js_signing",
		"re_domain_proof_exit",
		"re_proof_loop",
	],
};
