/** Cloud IAM/policy surface pure-python CAP without aws/kubectl binaries. */
export const CLOUD_IDENTITY_IAM_LINES = [
	"python3 - <<'PY'",
	"import os, pathlib, re",
	"print('[cloud-iam] start=1')",
	"hits = []",
	"home = pathlib.Path.home()",
	"for path in (home/'.aws/credentials', home/'.aws/config', home/'.azure', home/'.config/gcloud', home/'.kube/config'):",
	"  p = pathlib.Path(path)",
	"  if p.exists():",
	"    kind = 'dir' if p.is_dir() else 'file'",
	"    size = p.stat().st_size if p.is_file() else sum(1 for _ in p.rglob('*'))",
	"    print('[cloud-iam-local] path=%s present=1 kind=%s size_or_entries=%s' % (path, kind, size))",
	"    hits.append(str(path))",
	"  else:",
	"    print('[cloud-iam-local] path=%s present=0' % path)",
	"root = pathlib.Path('.')",
	"policy_keys = re.compile(r'(?i)\\b(Action|Resource|Effect|Principal|Statement|Role|PolicyDocument|AssumeRole)\\b\\s*:' )",
	"policy_files = 0",
	"for p in list(root.rglob('*.json'))[:80] + list(root.rglob('*.yml'))[:40] + list(root.rglob('*.yaml'))[:40]:",
	"  try:",
	"    if p.stat().st_size > 250_000: continue",
	"    text = p.read_text(errors='ignore')",
	"  except Exception: continue",
	"  if policy_keys.search(text) and re.search(r'(?i)\\b(Allow|Deny)\\b|arn:aws:|serviceAccount|roles/', text):",
	"    policy_files += 1",
	"    print('[cloud-iam-policy] path=%s hits=%d' % (str(p)[:160], len(policy_keys.findall(text))))",
	"    if policy_files >= 12: break",
	"print('[cloud-iam-policy] files=%d' % policy_files)",
	"sa = pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount')",
	"if sa.is_dir():",
	"  for name in ('token','namespace','ca.crt'):",
	"    fp = sa/name",
	"    print('[cloud-iam-k8s] file=%s present=%d' % (name, int(fp.exists())))",
	"  hits.append('k8s-sa')",
	"else:",
	"  print('[cloud-iam-k8s] present=0')",
	"for k,v in os.environ.items():",
	"  if re.search(r'(?i)^(AWS_|AZURE_|GOOGLE_|KUBE|KUBERNETES).*|ROLE_ARN|AWS_PROFILE|KUBECONFIG|SERVICE_ACCOUNT', k):",
	"    print('[cloud-iam-env] key=%s set=%d' % (k, int(bool(v))))",
	"    hits.append(k)",
	"print('[cloud-iam] ok=1 hits=%d' % len(hits))",
	"PY",
] as const;
