/** Cloud identity inventory + metadata probe (python body lines). */
// Landmark: CLOUD_IDENTITY_INVENTORY_LINES cloud-metadata imds_base
export const CLOUD_IDENTITY_INVENTORY_LINES: string[] = [
	"import hashlib, os, pathlib, re, sys, urllib.error, urllib.request",
	"root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.')",
	"if not root.exists():",
	"    root = pathlib.Path('.')",
	"keys = ['AWS_ACCESS_KEY_ID','AWS_PROFILE','AWS_REGION','AWS_ROLE_ARN','AZURE_CLIENT_ID','AZURE_TENANT_ID','GOOGLE_APPLICATION_CREDENTIALS','KUBECONFIG','KUBERNETES_SERVICE_HOST','KUBERNETES_SERVICE_PORT']",
	"for key in keys:",
	"    value = os.getenv(key)",
	"    if value:",
	"        print('[cloud-identity] env=%s len=%d sha256=%s' % (key, len(value), hashlib.sha256(value.encode()).hexdigest()[:16]))",
	"paths = [",
	"    pathlib.Path('~/.aws/credentials').expanduser(),",
	"    pathlib.Path('~/.aws/config').expanduser(),",
	"    pathlib.Path(os.getenv('KUBECONFIG','~/.kube/config')).expanduser(),",
	"    pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount/token'),",
	"]",
	"for path in paths:",
	"    if path.exists():",
	"        try:",
	"            data = path.read_bytes()[:4096]",
	"            print('[cloud-identity] path=%s bytes=%d sha256=%s' % (path, path.stat().st_size, hashlib.sha256(data).hexdigest()[:16]))",
	"        except Exception as exc:",
	"            print('[cloud-identity] path=%s error=%s' % (path, type(exc).__name__))",
	"print('[cloud-identity] inventory_ok=1')",
	"manifests = 0",
	"search_roots = [root if root.is_dir() else pathlib.Path('.')]",
	"for base in search_roots:",
	"    for path in list(base.rglob('*'))[:800]:",
	"        if not path.is_file() or path.stat().st_size > 2_000_000: continue",
	"        name = path.name.lower()",
	"        if any(k in name for k in ('dockerfile','docker-compose','.tf','chart.yaml','values','deployment','rbac','secret','configmap','serviceaccount')):",
	"            print('[cloud-runtime-config] manifest=%s' % path)",
	"            manifests += 1",
	"            if manifests >= 40: break",
	"print('[cloud-runtime-config] manifests=%d' % manifests)",
	"edge = 0",
	"patterns = [",
	"    ('aws_arn', re.compile(r'arn:aws:[^\\s\"\\']+', re.I)),",
	"    ('gcp_sa', re.compile(r'[^\\s\"\\']+@[^\\s\"\\']+\\.iam\\.gserviceaccount\\.com', re.I)),",
	"    ('k8s_rbac', re.compile(r'ClusterRoleBinding|RoleBinding|serviceAccountName|automountServiceAccountToken', re.I)),",
	"    ('secret_ref', re.compile(r'secretKeyRef|envFrom|imagePullSecrets|\\bSecret\\b', re.I)),",
	"    ('ad_edge', re.compile(r'AdminTo|MemberOf|GenericAll|GenericWrite|AllowedToDelegate|BloodHound|kerberoast|ASREP', re.I)),",
	"]",
	"for base in search_roots:",
	"    for path in list(base.rglob('*'))[:600]:",
	"        if not path.is_file() or path.stat().st_size > 1_500_000: continue",
	"        if any(part in {'.git','node_modules','dist','build'} for part in path.parts): continue",
	"        try: text = path.read_text('utf-8','ignore')[:200000]",
	"        except Exception: continue",
	"        hits = [label for label, rx in patterns if rx.search(text)]",
	"        if hits:",
	"            print('[cloud-privilege-edge] file=%s hits=%s' % (path, ','.join(hits)))",
	"            if 'ad_edge' in hits: print('[ad-graph-edge] file=%s' % path)",
	"            edge += 1",
	"            if edge >= 40: break",
	"print('[cloud-privilege-edge] edges=%d' % edge)",
	"imds_base = (os.getenv('REPI_IMDS_BASE_URL') or '').rstrip('/')",
	"ENDPOINTS = [",
	"    ('aws-imds-root', (imds_base + '/latest/meta-data/') if imds_base else 'http://169.254.169.254/latest/meta-data/', {}),",
	"    ('gcp-metadata', (imds_base + '/computeMetadata/v1/') if imds_base else 'http://metadata.google.internal/computeMetadata/v1/', {'Metadata-Flavor':'Google'}),",
	"    ('azure-imds', (imds_base + '/metadata/instance?api-version=2021-02-01') if imds_base else 'http://169.254.169.254/metadata/instance?api-version=2021-02-01', {'Metadata':'true'}),",
	"]",
	"meta_ok = 0",
	"for name, url, headers in ENDPOINTS:",
	"    try:",
	"        req = urllib.request.Request(url, headers=headers, method='GET')",
	"        with urllib.request.urlopen(req, timeout=1.2) as resp:",
	"            body = resp.read(256)",
	"            print('[cloud-metadata] provider=%s status=%s body_sha=%s mock=%s' % (name, getattr(resp,'status',200), hashlib.sha256(body).hexdigest()[:12], 1 if imds_base else 0))",
	"            meta_ok += 1",
	"    except Exception as exc:",
	"        print('[cloud-metadata] provider=%s blocked=%s' % (name, type(exc).__name__))",
	"print('[cloud-metadata] reachable=%d mock_base=%s' % (meta_ok, imds_base or '<none>'))",
	"print('[ad-principal] note=host-scaffold domain=%s' % (os.getenv('DOMAIN') or '<unset>'))",
];
