/** Deep cloud/identity pure-python probes without aws/kubectl CLIs. */
export const CLOUD_IDENTITY_DEEP_LINES = [
	"python3 - \"$root\" <<'PY'",
	"import hashlib, os, pathlib, re, sys",
	"root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.')",
	"if not root.exists(): root = pathlib.Path('.')",
	"sa_candidates = []",
	"env_sa = os.getenv('REPI_K8S_SA_DIR')",
	"if env_sa: sa_candidates.append(pathlib.Path(env_sa))",
	"sa_candidates.extend([pathlib.Path('/tmp/repi-k8s-sa'), pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount'), pathlib.Path('/run/secrets/kubernetes.io/serviceaccount')])",
	"sa_dir = next((p for p in sa_candidates if p.is_dir()), pathlib.Path('/var/run/secrets/kubernetes.io/serviceaccount'))",
	"print('[cloud-k8s-sa] probe_root=%s exists=%d' % (sa_dir, int(sa_dir.is_dir())))",
	"for name in ('token','namespace','ca.crt'):",
	"    p = sa_dir / name",
	"    if p.exists():",
	"        try:",
	"            data = p.read_bytes()[:2048]",
	"            print('[cloud-k8s-sa] file=%s bytes=%d sha256=%s' % (p, len(data), hashlib.sha256(data).hexdigest()[:16]))",
	"            if name == 'namespace':",
	"                print('[cloud-k8s-sa] namespace=%s' % data.decode('utf-8','ignore').strip()[:80])",
	"            if name == 'token' and data:",
	"                print('[cloud-k8s-sa] token_present=1 jwt_dots=%d' % data.count(b'.'))",
	"                # decode JWT header/payload claims only (no signature verify; fixture-safe)",
	"                try:",
	"                    import base64, json",
	"                    parts=data.decode('utf-8','ignore').strip().split('.')",
	"                    if len(parts)>=2:",
	"                        def b64url(s):",
	"                            s+= '=' * (-len(s) % 4)",
	"                            return base64.urlsafe_b64decode(s.encode())",
	"                        hdr=json.loads(b64url(parts[0]))",
	"                        pl=json.loads(b64url(parts[1]))",
	"                        print('[cloud-k8s-jwt] alg=%s typ=%s' % (hdr.get('alg'), hdr.get('typ')))",
	"                        for k in ('iss','sub','aud','exp','iat','nbf','kubernetes.io'):",
	"                            if k in pl: print('[cloud-k8s-jwt] claim=%s value=%s' % (k, str(pl.get(k))[:120]))",
	"                        # nested k8s claims",
	"                        k8s=pl.get('kubernetes.io') if isinstance(pl.get('kubernetes.io'), dict) else {}",
	"                        if k8s:",
	"                            print('[cloud-k8s-jwt] ns=%s sa=%s' % (k8s.get('namespace'), (k8s.get('serviceaccount') or {}).get('name') if isinstance(k8s.get('serviceaccount'), dict) else k8s.get('serviceaccount')))",
	"                        print('[cloud-k8s-jwt] ok=1 pure_python=1')",
	"                        print('summary.cloud_k8s_jwt=1')",
	"                except Exception as je:",
	"                    print('[cloud-k8s-jwt] err=%s' % type(je).__name__)",
	"        except Exception as exc:",
	"            print('[cloud-k8s-sa] file=%s error=%s' % (p, type(exc).__name__))",
	"    else:",
	"        print('[cloud-k8s-sa] file=%s present=0' % p)",
	"print('[cloud-k8s-sa] probe=1')",
	"for sock in (pathlib.Path('/var/run/docker.sock'), pathlib.Path('/run/containerd/containerd.sock')):",
	"    print('[cloud-runtime] socket=%s exists=%s' % (sock, int(sock.exists())))",
	"if pathlib.Path('/.dockerenv').exists():",
	"    print('[cloud-runtime] in_docker=1')",
	"cgroup = pathlib.Path('/proc/1/cgroup')",
	"if cgroup.exists():",
	"    cg = cgroup.read_text('utf-8','ignore')[:500]",
	"    if re.search(r'docker|kubepods|containerd|libpod', cg, re.I):",
	"        print('[cloud-runtime] cgroup_container_signal=1 sample=%s' % cg.replace(chr(10),' ')[:120])",
	"aws_cred = pathlib.Path('~/.aws/credentials').expanduser()",
	"aws_cfg = pathlib.Path('~/.aws/config').expanduser()",
	"for path, kind in ((aws_cred,'credentials'), (aws_cfg,'config')):",
	"    if not path.exists():",
	"        print('[cloud-aws-file] kind=%s present=0' % kind); continue",
	"    text = path.read_text('utf-8','ignore')[:20000]",
	"    profiles = re.findall(r'^\\[([^\\]]+)\\]', text, re.M)",
	"    has_key = bool(re.search(r'aws_access_key_id\\s*=', text, re.I))",
	"    has_role = bool(re.search(r'role_arn\\s*=|credential_process\\s*=', text, re.I))",
	"    print('[cloud-aws-file] kind=%s present=1 profiles=%d access_key_field=%d role_or_process=%d sha256=%s' % (kind, len(profiles), int(has_key), int(has_role), hashlib.sha256(text.encode()).hexdigest()[:16]))",
	"    for prof in profiles[:12]:",
	"        print('[cloud-identity] aws_profile=%s' % prof)",
	"kube = pathlib.Path(os.getenv('KUBECONFIG','~/.kube/config')).expanduser()",
	"if kube.exists():",
	"    kt = kube.read_text('utf-8','ignore')[:100000]",
	"    contexts = re.findall(r'name:\\s*([^\\n]+)', kt)",
	"    print('[cloud-kubeconfig] present=1 contexts=%d sha256=%s' % (len(set(contexts)), hashlib.sha256(kt.encode()).hexdigest()[:16]))",
	"    if re.search(r'exec:|client-certificate-data|token:', kt):",
	"        print('[cloud-kubeconfig] auth_surface=1')",
	"else:",
	"    print('[cloud-kubeconfig] present=0')",
	"pol = 0",
	"base = root if root.is_dir() else pathlib.Path('.')",
	"for path in list(base.rglob('*'))[:900]:",
	"    if not path.is_file() or path.stat().st_size > 1_500_000: continue",
	"    if any(part in {'.git','node_modules','dist','build'} for part in path.parts): continue",
	"    try: text = path.read_text('utf-8','ignore')[:120000]",
	"    except Exception: continue",
	'    if re.search(r\'"Effect"\\s*:\\s*"Allow"|Action\\s*:\\s*\\[|"Principal"|sts:AssumeRole|iam:PassRole\', text):',
	"        print('[cloud-iam-policy] file=%s' % path); pol += 1",
	"    if pol >= 20: break",
	"print('[cloud-iam-policy] docs=%d' % pol)",
	"imds_base = os.getenv('REPI_IMDS_BASE_URL')",
	"if imds_base:",
	"  print('[cloud-imds-chain] mock_base=%s' % imds_base)",
	"  print('[cloud-imds-chain] next=curl %s/latest/meta-data/' % imds_base.rstrip('/'))",
	"else:",
	"  print('[cloud-imds-chain] scaffold=1 next=curl -H Metadata:true http://169.254.169.254/metadata/instance?api-version=2021-02-01')",
	"  print('[cloud-imds-chain] scaffold=1 next=curl -H Metadata-Flavor:Google http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token')",
	"  print('[cloud-imds-chain] scaffold=1 next=curl http://169.254.169.254/latest/meta-data/iam/security-credentials/')",
	"print('[cloud-identity-deep] ok=1')",
	"PY",
] as const;
