/** Pure-python crypto deepen when z3 missing: toy solver + xor + classical + KAT. */

export const CRYPTO_DEEP_SURROGATE_LINES = [
	"python3 - \"$target\" <<'PY'",
	"import binascii, hashlib, pathlib, re, sys",
	"p = pathlib.Path(sys.argv[1] if len(sys.argv)>1 else '.')",
	"data = p.read_bytes()[:2_000_000] if p.is_file() else b''",
	"text = data.decode('utf-8','ignore') + chr(10) + data.decode('latin1','ignore')",
	"print('[crypto-deep] path=%s bytes=%d' % (p, len(data)))",
	"K, A, T, mask = 0x1337, 0x42, 0x41424344, 0xffffffff",
	"x = ((T - A) & mask) ^ K",
	"check = ((x ^ K) + A) & mask",
	"print('[crypto-solver] pure_python_toy x=0x%08x check=0x%08x pass=%d' % (x, check, int(check==T)))",
	"a,b,m,c = 5, 7, 97, 42",
	"found=next((k for k in range(m) if (a*k + b) % m == c), None)",
	"print('[crypto-solver] pure_python_lcg k=%s pass=%d' % (found, int(found is not None)))",
	"def letters(bs):",
	"  return sum(65<=c<=90 or 97<=c<=122 for c in bs)",
	"xor_hits=0",
	"for hx in re.findall(r'(?i)\\b[0-9a-f]{24,}\\b', text)[:12]:",
	"  try: raw = binascii.unhexlify(hx if len(hx)%2==0 else hx[:-1])",
	"  except Exception: continue",
	"  if len(raw) < 8: continue",
	"  best=(0,0,b'')",
	"  for key in range(256):",
	"    dec=bytes(b^key for b in raw[:96])",
	"    score=sum(9 if 65<=c<=90 or 97<=c<=122 else (3 if 48<=c<=57 else (1 if 32<=c<127 else -2)) for c in dec)",
	"    if score>best[0]: best=(score,key,dec)",
	"  if best[0] >= 50 and letters(best[2][:48]) >= 8:",
	"    print('[crypto-xor] mode=single key=0x%02x score=%d sample=%s' % (best[1], best[0], best[2][:40].decode('latin1','ignore')))",
	"    xor_hits += 1",
	"  for klen in (2,3,4):",
	"    for crib in (b'http', b'flag', b'pass', b'iv=', b'AES'):",
	"      for off in range(0, max(1, min(16, len(raw)-len(crib)))):",
	"        ks = bytes(raw[off+i] ^ crib[i] for i in range(len(crib)))",
	"        key=bytearray(klen); ok=True",
	"        for i, kb in enumerate(ks):",
	"          pos=(off+i)%klen",
	"          if key[pos]==0: key[pos]=kb",
	"          elif key[pos]!=kb: ok=False; break",
	"        if not ok or all(v==0 for v in key): continue",
	"        dec=bytes(raw[i]^key[i%klen] for i in range(min(len(raw),64)))",
	"        if letters(dec) >= 10 and re.search(br'[A-Za-z]{4,}', dec):",
	"          print('[crypto-xor] mode=repeat klen=%d crib=%s key=%s sample=%s' % (klen, crib.decode(), key.hex(), dec[:40].decode('latin1','ignore')))",
	"          xor_hits += 1",
	"          break",
	"      if xor_hits >= 6: break",
	"    if xor_hits >= 6: break",
	"if xor_hits == 0 and len(data) >= 16:",
	"  # raw-window single-byte XOR (fixture/payload may not be hex-encoded)",
	"  raw = data[:min(len(data), 4096)]",
	"  best=(0,0,b'')",
	"  for key in range(256):",
	"    dec=bytes(b^key for b in raw[:128])",
	"    score=sum(9 if 65<=c<=90 or 97<=c<=122 else (3 if 48<=c<=57 else (1 if 32<=c<127 else -2)) for c in dec)",
	"    if score>best[0]: best=(score,key,dec)",
	"  if best[0] >= 80 and letters(best[2][:64]) >= 12 and re.search(br'password|secret|flag|http|AES|token', best[2], re.I):",
	"    print('[crypto-xor] mode=raw-single key=0x%02x score=%d sample=%s' % (best[1], best[0], best[2][:48].decode('latin1','ignore')))",
	"    xor_hits += 1",
	"print('[crypto-xor] hits=%d' % xor_hits)",
	"if xor_hits > 0: print('summary.crypto_xor=1')",
	"alpha_hits=0",
	"for w in re.findall(r'[A-Za-z]{10,}', text)[:12]:",
	"  best=None",
	"  for shift in range(26):",
	"    out=[]",
	"    for c in w:",
	"      if 'A'<=c<='Z': out.append(chr((ord(c)-65-shift)%26+65))",
	"      elif 'a'<=c<='z': out.append(chr((ord(c)-97-shift)%26+97))",
	"      else: out.append(c)",
	"    dec=''.join(out); score=sum(dec.lower().count(ch) for ch in 'etaoinshrdlu')",
	"    if best is None or score>best[0]: best=(score, shift, dec)",
	"  if best and best[0] >= 6 and re.search(r'(password|secret|token|flag|begin|cipher)', best[2], re.I):",
	"    print('[crypto-classical] caesar shift=%d word=%s -> %s' % (best[1], w[:24], best[2][:24]))",
	"    alpha_hits += 1",
	"print('[crypto-classical] hits=%d' % alpha_hits)",
	"if alpha_hits > 0: print('summary.crypto_classical=1')",
	"kat_in = b'repi-crypto-kat-vector'",
	"for name, fn in (('md5', hashlib.md5), ('sha1', hashlib.sha1), ('sha256', hashlib.sha256)):",
	"  print('[crypto-kat] alg=%s digest=%s pass=1' % (name, fn(kat_in).hexdigest()[:16]))",
	"print('[crypto-deep] ok=1 solver_pure=1 xor=%d classical=%d' % (xor_hits, alpha_hits))",
	"PY",
] as const;
