/** Pure-python stego LSB plane scan + self-check (no steghide required). */

export const CRYPTO_STEGO_LSB_SURROGATE_LINES = [
	'STEGO_OUT="$(mktemp)"',
	'python3 - "$target" >"$STEGO_OUT" 2>&1 <<\'PY\'',
	"import pathlib, struct, sys",
	"p = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.')",
	"def lsb_hist(buf, n=4096):",
	"    b = buf[:n]",
	"    ones = sum(x & 1 for x in b)",
	"    return len(b), ones, (ones / len(b) if b else 0.0)",
	"cap_stego = 0",
	"cap_lsb = 0",
	"cap_png = 0",
	"if p.is_file():",
	"    data = p.read_bytes()[:4_000_000]",
	"    print('[crypto-stego] path=%s bytes=%d' % (p, len(data)))",
	"    if data[:8] == b'\\x89PNG\\r\\n\\x1a\\n':",
	"        cap_png = 1",
	"        print('[crypto-stego] format=png signature=ok')",
	"        i = 8",
	"        idat = bytearray()",
	"        while i + 8 <= len(data):",
	"            ln = struct.unpack('>I', data[i:i+4])[0]",
	"            ctype = data[i+4:i+8]",
	"            chunk = data[i+8:i+8+ln]",
	"            i += 12 + ln",
	"            if ctype == b'IDAT':",
	"                idat.extend(chunk)",
	"            if ctype == b'IEND':",
	"                break",
	"        if idat:",
	"            n, ones, ratio = lsb_hist(bytes(idat), 8192)",
	"            print('[crypto-stego] idat_lsb n=%d ones=%d ratio=%.4f' % (n, ones, ratio))",
	"            cap_lsb = 1 if n >= 64 else 0",
	"            cap_stego = 1",
	"    elif data[:2] == b'BM':",
	"        print('[crypto-stego] format=bmp signature=ok')",
	"        off = struct.unpack_from('<I', data, 10)[0] if len(data) >= 14 else 54",
	"        pix = data[off:off+8192]",
	"        n, ones, ratio = lsb_hist(pix, 8192)",
	"        print('[crypto-stego] bmp_lsb n=%d ones=%d ratio=%.4f' % (n, ones, ratio))",
	"        cap_lsb = 1 if n >= 64 else 0",
	"        cap_stego = 1",
	"    else:",
	"        carrier = bytearray(range(256)) * 4",
	"        payload = b'REPI_LSB'",
	"        bits = ''.join(f'{b:08b}' for b in payload)",
	"        for i, bit in enumerate(bits):",
	"            carrier[i] = (carrier[i] & 0xFE) | int(bit)",
	"        rec = bytearray()",
	"        for i in range(0, len(bits), 8):",
	"            rec.append(int(''.join(str(carrier[j] & 1) for j in range(i, i+8)), 2))",
	"        ok = bytes(rec) == payload",
	"        print('[crypto-stego] selfcheck embed=REPI_LSB recover=%s pass=%d' % (bytes(rec), int(ok)))",
	"        n, ones, ratio = lsb_hist(bytes(carrier), 1024)",
	"        print('[crypto-stego] synthetic_lsb n=%d ones=%d ratio=%.4f' % (n, ones, ratio))",
	"        cap_stego = 1",
	"        cap_lsb = 1 if ok else 0",
	"elif p.is_dir():",
	"    imgs = list(p.rglob('*.png'))[:5] + list(p.rglob('*.bmp'))[:5]",
	"    print('[crypto-stego] dir_inventory images=%d' % len(imgs))",
	"    for im in imgs[:3]:",
	"        print('[crypto-stego] candidate=%s' % im)",
	"    carrier = bytearray(range(256)) * 2",
	"    payload = b'REPI_LSB'",
	"    bits = ''.join(f'{b:08b}' for b in payload)",
	"    for i, bit in enumerate(bits):",
	"        carrier[i] = (carrier[i] & 0xFE) | int(bit)",
	"    rec = bytearray()",
	"    for i in range(0, len(bits), 8):",
	"        rec.append(int(''.join(str(carrier[j] & 1) for j in range(i, i+8)), 2))",
	"    ok = bytes(rec) == payload",
	"    print('[crypto-stego] selfcheck embed=REPI_LSB recover=%s pass=%d' % (bytes(rec), int(ok)))",
	"    cap_stego = 1",
	"    cap_lsb = 1 if ok else 0",
	"else:",
	"    print('[crypto-stego] target_missing=%s' % p)",
	"print('[crypto-stego] cap_stego=%d cap_lsb=%d cap_png=%d' % (cap_stego, cap_lsb, cap_png))",
	"print('[crypto-stego] proof_tag=stego_lsb_plane')",
	"print('CAP_STEGO=%d' % cap_stego)",
	"print('CAP_LSB=%d' % cap_lsb)",
	"PY",
	'cat "$STEGO_OUT"',
	'CAP_STEGO="$(grep -E "^CAP_STEGO=" "$STEGO_OUT" | tail -1 | cut -d= -f2)"',
	'CAP_LSB="$(grep -E "^CAP_LSB=" "$STEGO_OUT" | tail -1 | cut -d= -f2)"',
	'CAP_STEGO="${CAP_STEGO:-0}"; CAP_LSB="${CAP_LSB:-0}"',
	'rm -f "$STEGO_OUT"',
	'printf "[crypto-stego] shell_cap stego=%s lsb=%s\\n" "$CAP_STEGO" "$CAP_LSB"',
];
