/** Pure-python ChaCha20 quarter-round / IETF test vector CAP. */
// Landmark: crypto-chacha quarter_round summary.crypto_chacha pure_python

export const CRYPTO_CHACHA_SURROGATE_LINES = [
	"if command -v python3 >/dev/null 2>&1; then",
	"  python3 - <<'PY'",
	"import struct",
	"def rotl(v, n):",
	"  return ((v << n) & 0xffffffff) | (v >> (32 - n))",
	"def qr(s, a, b, c, d):",
	"  s[a] = (s[a] + s[b]) & 0xffffffff; s[d] ^= s[a]; s[d] = rotl(s[d], 16)",
	"  s[c] = (s[c] + s[d]) & 0xffffffff; s[b] ^= s[c]; s[b] = rotl(s[b], 12)",
	"  s[a] = (s[a] + s[b]) & 0xffffffff; s[d] ^= s[a]; s[d] = rotl(s[d], 8)",
	"  s[c] = (s[c] + s[d]) & 0xffffffff; s[b] ^= s[c]; s[b] = rotl(s[b], 7)",
	"# RFC 7539 Appendix A.1 quarter round test",
	"s = [0x11111111,0x01020304,0x9b8d6f43,0x01234567]",
	"qr(s, 0, 1, 2, 3)",
	"expect = [0xea2a92f4,0xcb1cf8ce,0x4581472e,0x5881c4bb]",
	"print('[crypto-chacha] qr_pass=%d pure_python=1' % int(s == expect))",
	"# block function smoke with zero key/nonce",
	"def chacha_block(key, counter, nonce):",
	"  const = b'expand 32-byte k'",
	"  st = list(struct.unpack('<4I', const)) + list(struct.unpack('<8I', key)) + [counter] + list(struct.unpack('<3I', nonce))",
	"  w = st[:]",
	"  for _ in range(10):",
	"    qr(w,0,4,8,12); qr(w,1,5,9,13); qr(w,2,6,10,14); qr(w,3,7,11,15)",
	"    qr(w,0,5,10,15); qr(w,1,6,11,12); qr(w,2,7,12,13); qr(w,3,4,13,14)",
	"  return b''.join(struct.pack('<I', (w[i]+st[i]) & 0xffffffff) for i in range(16))",
	"out = chacha_block(b'\\x00'*32, 0, b'\\x00'*12)",
	"print('[crypto-chacha] block_len=%d head=%s' % (len(out), out[:8].hex()))",
	"print('[crypto-chacha] ok=1')",
	"print('summary.crypto_chacha=1')",
	"PY",
	"  CAP_CHACHA=1",
	"else",
	"  CAP_CHACHA=0",
	"fi",
] as const;
