/** Host python3-z3 multi-constraint solver CAP for crypto reverse. */
export const CRYPTO_Z3_HOST_LINES: string[] = [
	"# Host z3 deepen: multi-constraint model + linear congruence (python3-z3)",
	"if command -v python3 >/dev/null 2>&1 && python3 -c 'import z3' >/dev/null 2>&1; then",
	"  Z3_OUT=$(python3 <<'PY'",
	"import z3",
	'print("[crypto-z3-host] version=%s" % z3.get_version_string())',
	'x = z3.BitVec("x", 32)',
	"s = z3.Solver()",
	"s.add(((x ^ 0x1337) + 0x42) & 0xffffffff == 0x41424344)",
	"r = s.check()",
	'print("[crypto-z3-host] toy_check=%s" % r)',
	"if r == z3.sat:",
	"  m = s.model()",
	"  xv = m[x].as_long() & 0xffffffff",
	'  print("[crypto-z3-host] toy_model x=0x%08x" % xv)',
	"  check = ((xv ^ 0x1337) + 0x42) & 0xffffffff",
	'  print("[crypto-z3-host] toy_verify pass=%d" % int(check == 0x41424344))',
	"a, b, mmod, c = 5, 7, 97, 42",
	'k = z3.Int("k")',
	't = z3.Int("t")',
	"s2 = z3.Solver()",
	"s2.add(a * k + b == c + mmod * t)",
	"s2.add(k >= 0, k < mmod)",
	"r2 = s2.check()",
	'print("[crypto-z3-host] lcg_check=%s" % r2)',
	"if r2 == z3.sat:",
	"  km = s2.model()[k].as_long()",
	'  print("[crypto-z3-host] lcg_model k=%d pass=%d" % (km, int((a * km + b) % mmod == c)))',
	'u, v = z3.Ints("u v")',
	"s3 = z3.Solver()",
	"s3.add(u + 2 * v == 100)",
	"s3.add(u - v == 10)",
	"r3 = s3.check()",
	'print("[crypto-z3-host] multi_check=%s" % r3)',
	"if r3 == z3.sat:",
	"  md = s3.model()",
	"  uu, vv = md[u].as_long(), md[v].as_long()",
	'  print("[crypto-z3-host] multi_model u=%d v=%d pass=%d" % (uu, vv, int(uu + 2 * vv == 100 and uu - vv == 10)))',
	'print("[crypto-z3-host] ok=1")',
	"PY",
	")",
	'  printf "%s\\n" "$Z3_OUT"',
	'  if printf "%s" "$Z3_OUT" | grep -q "\\[crypto-z3-host\\] ok=1"; then CAP_SOLVER=1; CAP_Z3=1; fi',
	"else",
	'  printf "[crypto-z3-host] ok=0 note=z3_missing\\n"',
	"fi",
];
