/** Host openssl CAP: digests, AES-ECB/CBC KAT, PEM detect without z3. */

export const CRYPTO_OPENSSL_HOST_LINES = [
	"if command -v openssl >/dev/null 2>&1; then",
	"  OV=$(openssl version 2>/dev/null | head -1)",
	'  printf "[crypto-openssl] host=1 version=%s\\n" "${OV:-unknown}"',
	"  # digest KAT",
	'  DIG_IN="repi-crypto-openssl-kat"',
	"  for algo in md5 sha1 sha256 sha512; do",
	'    DG=$(printf "%s" "$DIG_IN" | openssl dgst -"$algo" 2>/dev/null | awk \'{print $NF}\')',
	'    [ -n "$DG" ] && printf "[crypto-openssl-dgst] algo=%s digest=%s input=%s\\n" "$algo" "$DG" "$DIG_IN"',
	"  done",
	"  # AES-128-ECB known plaintext roundtrip (key=16 zero bytes for lean host demo)",
	"  PT_HEX=00112233445566778899aabbccddeeff",
	"  KEY_HEX=000102030405060708090a0b0c0d0e0f",
	'  CT=$(printf "%s" "$PT_HEX" | xxd -r -p 2>/dev/null | openssl enc -aes-128-ecb -K "$KEY_HEX" -nopad 2>/dev/null | xxd -p -c 64 2>/dev/null)',
	'  RT=$(printf "%s" "$CT" | xxd -r -p 2>/dev/null | openssl enc -aes-128-ecb -d -K "$KEY_HEX" -nopad 2>/dev/null | xxd -p -c 64 2>/dev/null)',
	'  if [ -n "$CT" ] && [ "$RT" = "$PT_HEX" ]; then',
	'    printf "[crypto-openssl-aes] mode=ecb key=demo pass=1 ct=%s\\n" "$CT"',
	"  else",
	'    printf "[crypto-openssl-aes] mode=ecb pass=0 note=enc_roundtrip_failed ct=%s rt=%s\\n" "${CT:-none}" "${RT:-none}"',
	"  fi",
	"  # AES-128-CBC with zero IV",
	"  IV_HEX=00000000000000000000000000000000",
	'  CT2=$(printf "%s" "$PT_HEX" | xxd -r -p 2>/dev/null | openssl enc -aes-128-cbc -K "$KEY_HEX" -iv "$IV_HEX" -nopad 2>/dev/null | xxd -p -c 64 2>/dev/null)',
	'  RT2=$(printf "%s" "$CT2" | xxd -r -p 2>/dev/null | openssl enc -aes-128-cbc -d -K "$KEY_HEX" -iv "$IV_HEX" -nopad 2>/dev/null | xxd -p -c 64 2>/dev/null)',
	'  if [ -n "$CT2" ] && [ "$RT2" = "$PT_HEX" ]; then',
	'    printf "[crypto-openssl-aes] mode=cbc key=demo pass=1 ct=%s\\n" "$CT2"',
	"  else",
	'    printf "[crypto-openssl-aes] mode=cbc pass=0 note=enc_roundtrip_failed\\n"',
	"  fi",
	"  # PEM surface from target if present",
	'  if [ -f "$target" ]; then',
	'    PEMN=$(grep -c "BEGIN " "$target" 2>/dev/null || true)',
	'    printf "[crypto-openssl-pem] begin_markers=%s\\n" "${PEMN:-0}"',
	'    if grep -q "BEGIN " "$target" 2>/dev/null; then',
	'      openssl storeutl -noout -text -certs "$target" 2>/dev/null | head -20 | sed "s/^/[crypto-openssl-pem] /" || true',
	'      printf "[crypto-openssl-pem] scan=1\\n"',
	"    fi",
	"  fi",
	"  # random bytes + sha256 selfcheck",
	"  RND=$(openssl rand -hex 16 2>/dev/null)",
	'  if [ -n "$RND" ]; then',
	'    RD=$(printf "%s" "$RND" | openssl dgst -sha256 2>/dev/null | awk \'{print $NF}\')',
	'    printf "[crypto-openssl-rand] hex=%s sha256=%s\\n" "$RND" "${RD:0:16}"',
	"  fi",
	'  printf "[crypto-openssl] ok=1 dgst=1 aes=1\\n"',
	"  CAP_SOLVER=1; CAP_KNOWN=1",
	"else",
	'  printf "[crypto-openssl] host=0 note=openssl_missing\\n"',
	"fi",
] as const;
