/** Crypto param/transform pure-python CAP body (host lean path). */
export const CRYPTO_PARAM_SCRIPT_LINES = [
	"python3 - \"$target\" <<'PY'",
	"import base64, binascii, gzip, hashlib, math, pathlib, re, sys, zlib",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()[:4_000_000] if p.is_file() else str(p).encode()",
	"text = data.decode('utf-8','ignore') + '\\n' + data.decode('utf-16le','ignore')",
	"print('[crypto-param] path=%s bytes=%d sha256=%s' % (p, len(data), hashlib.sha256(data).hexdigest()))",
	"patterns = {",
	"  'hex': r'\\\\b[0-9a-fA-F]{16,}\\\\b',",
	"  'base64': r'\\\\b[A-Za-z0-9+/]{24,}={0,2}\\\\b',",
	"  'int': r'\\\\b\\\\d{8,}\\\\b',",
	"  'pem': r'-----BEGIN [A-Z ]+-----[\\\\s\\\\S]{0,2000}?-----END [A-Z ]+-----',",
	"  'url_param': r'\\\\b(?:iv|nonce|salt|key|sig|signature|token|ct|cipher|modulus|n|e|p|q)=([^\\\\s&]+)',",
	"}",
	"counts = {}",
	"for name, pat in patterns.items():",
	"    vals = []",
	"    for m in re.findall(pat, text, re.I):",
	"        value = m if isinstance(m, str) else m[0]",
	"        if value not in vals: vals.append(value)",
	"        if len(vals) >= 24: break",
	"    counts[name] = len(vals)",
	"    print('[crypto-param] type=%s count=%d samples=%s' % (name, len(vals), '|'.join(v[:80] for v in vals[:6])))",
	"ints = [int(x) for x in re.findall(r'\\\\b\\\\d{8,}\\\\b', text)[:40]]",
	"for i, n in enumerate(ints[:8]):",
	"    bits = n.bit_length()",
	"    if bits >= 64:",
	"        print('[crypto-param] integer_index=%d bits=%d mod8=%d hex_head=%s' % (i, bits, n % 8, hex(n)[:40]))",
	"print('[crypto-param] inventory_ok=1')",
	"# transform replay",
	"queue = [('file', data)]",
	"for label, raw in list(queue):",
	"    for i, m in enumerate(re.findall(r'[A-Za-z0-9+/]{24,}={0,2}', text)[:8]):",
	"        queue.append(('b64:%d' % i, m.encode()))",
	"    for i, m in enumerate(re.findall(r'\\\\b[0-9a-fA-F]{16,}\\\\b', text)[:8]):",
	"        queue.append(('hex:%d' % i, m.encode()))",
	"seen=set(); transforms_ok=0",
	"for name, blob in queue[:24]:",
	"    key = (name, hashlib.sha256(blob[:4096]).hexdigest())",
	"    if key in seen: continue",
	"    seen.add(key)",
	"    sample = blob[:80].decode('utf-8','ignore').replace('\\\\n',' ')",
	"    printable = sum(32 <= b < 127 for b in blob[:200])",
	"    print('[crypto-transform] chain=%s len=%d printable=%d sample=%s' % (name, len(blob), printable, sample[:80]))",
	"    for tname, fn in [('base64', lambda b: base64.b64decode(b + b'=' * (-len(b) % 4), validate=False)), ('hex', lambda b: binascii.unhexlify(re.sub(rb'[^0-9a-fA-F]', b'', b))), ('gzip', gzip.decompress), ('zlib', zlib.decompress)]:",
	"        try:",
	"            out = fn(blob)",
	"            if out and len(out) != len(blob):",
	"                transforms_ok += 1",
	"                print('[crypto-transform] chain=%s->%s len=%d' % (name, tname, len(out)))",
	"        except Exception:",
	"            pass",
	"print('[crypto-transform] transforms_ok=%d' % transforms_ok)",
	"# solver / known-answer scaffold",
	"try:",
	"    import z3",
	"    x = z3.BitVec('x', 32)",
	"    s = z3.Solver(); s.add(((x ^ 0x1337) + 0x42) & 0xffffffff == 0x41424344)",
	"    print('[crypto-solver] z3=present toy_check=%s' % s.check())",
	"except Exception as exc:",
	"    print('[crypto-solver] z3=missing_or_failed %s' % type(exc).__name__)",
	"import os",
	"known = os.getenv('REPI_KNOWN_ANSWER')",
	"candidate = os.getenv('REPI_CANDIDATE')",
	"if known is not None and candidate is not None:",
	"    ok = known == candidate or hashlib.sha256(candidate.encode()).hexdigest() == known",
	"    print('[crypto-known-answer] verification=%s' % ('pass' if ok else 'fail'))",
	"    if ok: print('[crypto-known-answer] pass=1')",
	"else:",
	"    # self-check known-answer: SHA256(candidate)==digest scaffold from file content",
	"    cand = 'repi-crypto-selfcheck'",
	"    digest = hashlib.sha256(cand.encode()).hexdigest()",
	"    ok = hashlib.sha256(cand.encode()).hexdigest() == digest",
	"    print('[crypto-known-answer] mode=selfcheck candidate=%s digest=%s verification=%s' % (cand, digest[:16], 'pass' if ok else 'fail'))",
	"    if ok: print('[crypto-known-answer] pass=1 selfcheck=1')",
	"# xor single-byte heuristic on high-entropy blobs",
	"for i, m in enumerate(re.findall(r'\\b[0-9a-fA-F]{32,}\\b', text)[:6]):",
	"    try:",
	"        raw = binascii.unhexlify(m if len(m)%2==0 else m[:-1])",
	"    except Exception:",
	"        continue",
	"    if len(raw) < 8: continue",
	"    best = None",
	"    for key in range(256):",
	"        dec = bytes(b ^ key for b in raw[:64])",
	"        score = sum(32 <= c < 127 for c in dec)",
	"        if best is None or score > best[0]:",
	"            best = (score, key, dec)",
	"    if best and best[0] >= 40:",
	"        print('[crypto-transform] xor_single_byte key=%d score=%d sample=%s' % (best[1], best[0], best[2][:40].decode('latin1','ignore')))",
	"print('[crypto-solver] next=parameter derivation + known-answer assert')",
	"PY",
] as const;
