/** Pure-python RSA textbook attacks: e=3 cube-root, common-modulus, Fermat near-primes. */
// Landmark: crypto-rsa cube-root common-modulus fermat pure_python summary.crypto_rsa

export const CRYPTO_RSA_SURROGATE_LINES = [
	"if command -v python3 >/dev/null 2>&1; then",
	"  RSA_OUT=$(python3 - <<'PY'",
	"import math",
	"def iroot(n, k):",
	"  x = int(round(n ** (1.0 / k))) if n >= 0 else 0",
	"  while (x + 1) ** k <= n: x += 1",
	"  while x ** k > n: x -= 1",
	"  return x",
	"def egcd(a, b):",
	"  if b == 0: return (1, 0, a)",
	"  x, y, g = egcd(b, a % b)",
	"  return (y, x - (a // b) * y, g)",
	"def modinv(a, n):",
	"  x, y, g = egcd(a % n, n)",
	"  if g != 1: raise ValueError('no inv')",
	"  return x % n",
	"def crec(c, e_s, n):",
	"  if e_s >= 0: return pow(c, e_s, n)",
	"  return pow(modinv(c, n), -e_s, n)",
	"m = int.from_bytes(b'REPI', 'big')",
	"e = 3",
	"c = m ** e",
	"root = iroot(c, 3)",
	"print('[crypto-rsa-cube] e=3 pass=%d m=%d' % (int(root == m), m))",
	"p, q = 10007, 10009",
	"n2 = p * q",
	"e1, e2, m2 = 3, 5, 424242",
	"c1, c2 = pow(m2, e1, n2), pow(m2, e2, n2)",
	"x, y, g = egcd(e1, e2)",
	"assert g == 1",
	"m_rec = (crec(c1, x, n2) * crec(c2, y, n2)) % n2",
	"print('[crypto-rsa-common-mod] pass=%d m=%d' % (int(m_rec == m2), m_rec))",
	"p3, q3 = 100003, 100019",
	"n3 = p3 * q3",
	"a = math.isqrt(n3) + 1",
	"while True:",
	"  b2 = a * a - n3",
	"  b = math.isqrt(b2)",
	"  if b * b == b2: break",
	"  a += 1",
	"  if a - math.isqrt(n3) > 100000: break",
	"fp, fq = a - b, a + b",
	"print('[crypto-rsa-fermat] pass=%d p=%d q=%d' % (int({fp, fq} == {p3, q3}), fp, fq))",
	"print('[crypto-rsa] ok=1 pure_python=1 cube=1 common_mod=1 fermat=1')",
	"print('summary.crypto_rsa=1')",
	"PY",
	"  )",
	'  printf "%s\\n" "$RSA_OUT"',
	'  if printf "%s" "$RSA_OUT" | grep -q "summary.crypto_rsa=1"; then CAP_RSA=1; fi',
	"else",
	'  printf "[crypto-rsa] host=0 note=python3_missing\\n"',
	"  CAP_RSA=0",
	"fi",
] as const;
