/** Host tshark CAP: structured conv/DNS/HTTP/TLS when tshark is installed. */
export const DFIR_TSHARK_HOST_LINES = [
	'if command -v tshark >/dev/null 2>&1 && [ -n "${1:-}" ] && [ -e "${1:-}" ]; then',
	'  printf "[dfir-tshark] host=1 bin=%s\\n" "$(command -v tshark)"',
	'  tshark -r "$1" -q -z conv,tcp 2>/dev/null | head -40 | sed "s/^/[pcap-flow] /"',
	'  tshark -r "$1" -q -z conv,udp 2>/dev/null | head -20 | sed "s/^/[pcap-flow-udp] /"',
	'  DNS_N=$(tshark -r "$1" -Y "dns.qry.name" -T fields -e dns.qry.name 2>/dev/null | head -40)',
	'  if [ -n "$DNS_N" ]; then',
	'    printf "%s\\n" "$DNS_N" | sort | uniq -c | sort -rn | head -20 | while read -r c n; do',
	'      [ -n "$n" ] && printf "[dfir-tshark-dns] name=%s hits=%s\\n" "$n" "$c"',
	"    done",
	"    CAP_DNS=1",
	"  fi",
	'  HTTP_N=$(tshark -r "$1" -Y "http.request" -T fields -e http.host -e http.request.method -e http.request.uri 2>/dev/null | head -40)',
	'  if [ -n "$HTTP_N" ]; then',
	'    printf "%s\\n" "$HTTP_N" | head -20 | while IFS="$(printf \'\\t\')" read -r host method uri; do',
	'      printf "[dfir-tshark-http] method=%s host=%s uri=%s\\n" "${method:-?}" "${host:-?}" "${uri:-?}"',
	"    done",
	"    CAP_HTTP=1",
	"  fi",
	'  SNI_N=$(tshark -r "$1" -Y "tls.handshake.extensions_server_name" -T fields -e tls.handshake.extensions_server_name 2>/dev/null | head -40)',
	'  if [ -n "$SNI_N" ]; then',
	'    printf "%s\\n" "$SNI_N" | sort | uniq -c | sort -rn | head -20 | while read -r c n; do',
	'      [ -n "$n" ] && printf "[dfir-tshark-sni] host=%s hits=%s\\n" "$n" "$c"',
	"    done",
	"    CAP_TLS=1",
	"  fi",
	"  AUTH_N=$(tshark -r \"$1\" -Y 'http.authorization || http.cookie' -T fields -e frame.number -e http.authorization -e http.cookie 2>/dev/null | head -20)",
	'  if [ -n "$AUTH_N" ]; then',
	'    printf "%s\\n" "$AUTH_N" | head -10 | sed "s/^/[dfir-tshark-auth] /"',
	"    CAP_CRED=1",
	"  fi",
	'  ARP_N=$(tshark -r "$1" -Y arp -T fields -e arp.opcode -e arp.src.proto_ipv4 -e arp.dst.proto_ipv4 2>/dev/null | head -20)',
	'  if [ -n "$ARP_N" ]; then printf "%s\\n" "$ARP_N" | head -8 | sed "s/^/[dfir-tshark-arp] /"; CAP_ARP=1; fi',
	'  ICMP_N=$(tshark -r "$1" -Y icmp -T fields -e icmp.type -e icmp.code -e ip.src -e ip.dst 2>/dev/null | head -20)',
	'  if [ -n "$ICMP_N" ]; then printf "%s\\n" "$ICMP_N" | head -8 | sed "s/^/[dfir-tshark-icmp] /"; CAP_ICMP=1; fi',
	'  DHCP_N=$(tshark -r "$1" -Y "bootp || dhcp" -T fields -e bootp.option.dhcp -e ip.src -e ip.dst 2>/dev/null | head -20)',
	'  if [ -n "$DHCP_N" ]; then printf "%s\\n" "$DHCP_N" | head -8 | sed "s/^/[dfir-tshark-dhcp] /"; CAP_DHCP=1; fi',
	'  PKT_N=$(tshark -r "$1" -T fields -e frame.number 2>/dev/null | wc -l | tr -d " ")',
	'  printf "[dfir-tshark] ok=1 packets=%s dns=%s http=%s tls=%s arp=%s icmp=%s dhcp=%s\\n" "${PKT_N:-0}" "${CAP_DNS:-0}" "${CAP_HTTP:-0}" "${CAP_TLS:-0}" "${CAP_ARP:-0}" "${CAP_ICMP:-0}" "${CAP_DHCP:-0}"',
	"  CAP_TSHARK=1; CAP_FLOW=1; CAP_PCAP=1",
	'  if [ "${PKT_N:-0}" != "0" ]; then CAP_PACKETS=${PKT_N}; fi',
	"else",
	'  printf "[dfir-tshark] host=0 note=tshark_missing_or_target_missing\\n"',
	"fi",
] as const;
