/** DFIR pure-python pcap process_frame + helpers. */
export const DFIR_PCAP_FRAME_LINES = [
	"def process_frame(frame, linktype):",
	"    global packets",
	"    packets += 1",
	"    ipoff = ip_offset(frame, linktype)",
	"    if ipoff is None or len(frame) < ipoff + 1:",
	"        return",
	"    version = frame[ipoff] >> 4",
	"    if version == 4:",
	"        if len(frame) < ipoff + 20:",
	"            return",
	"        ihl = (frame[ipoff] & 15) * 4",
	"        proto = frame[ipoff + 9]",
	"        src_ip = ip4(frame[ipoff+12:ipoff+16])",
	"        dst_ip = ip4(frame[ipoff+16:ipoff+20])",
	"        transport_off = ipoff + ihl",
	"    elif version == 6:",
	"        if len(frame) < ipoff + 40:",
	"            return",
	"        proto = frame[ipoff + 6]",
	"        src_ip = ip6(frame[ipoff+8:ipoff+24])",
	"        dst_ip = ip6(frame[ipoff+24:ipoff+40])",
	"        transport_off = ipoff + 40",
	"        print('[ipv6-flow] src=%s dst=%s next_header=%s' % (src_ip, dst_ip, proto))",
	"    else:",
	"        return",
	"    if proto == 6:",
	"        tcpoff = transport_off",
	"        if len(frame) < tcpoff + 20:",
	"            return",
	"        sport, dport = struct.unpack('!HH', frame[tcpoff:tcpoff+4])",
	"        seq = struct.unpack('!I', frame[tcpoff+4:tcpoff+8])[0]",
	"        doff = (frame[tcpoff + 12] >> 4) * 4",
	"        payload = frame[tcpoff + doff:]",
	"        src = src_ip + ':' + str(sport)",
	"        dst = dst_ip + ':' + str(dport)",
	"        conv = add_flow(src, dst, len(payload))",
	"        dkey = src + ' -> ' + dst",
	"        if payload:",
	"            stream_segments[dkey].append((seq, packets, bytes(payload)))",
	"            emit_http(packets, conv, payload)",
	"            for name in parse_tls_sni(payload):",
	"                print('[tls-sni] frame=%d flow=%s server_name=%s bytes=%d sha256=%s' % (packets, conv, clean(name), len(payload), sha(payload)))",
	"    elif proto == 17:",
	"        udpoff = transport_off",
	"        if len(frame) < udpoff + 8:",
	"            return",
	"        sport, dport, ulen, _sum = struct.unpack('!HHHH', frame[udpoff:udpoff+8])",
	"        payload = frame[udpoff+8:min(len(frame), udpoff+max(8, ulen))]",
	"        src = src_ip + ':' + str(sport)",
	"        dst = dst_ip + ':' + str(dport)",
	"        conv = add_flow(src, dst, len(payload))",
	"        if sport == 53 or dport == 53:",
	"            for section, txid, name, rtype, value in parse_dns(payload):",
	"                if section == 'query':",
	"                    print('[dns-query] frame=%d flow=%s txid=0x%04x qname=%s qtype=%s' % (packets, conv, txid, clean(name), rtype))",
	"                else:",
	"                    print('[dns-answer] frame=%d flow=%s txid=0x%04x section=%s name=%s type=%s value=%s' % (packets, conv, txid, section, clean(name), rtype, clean(value)))",
] as const;
