/** DFIR pure-python pcap base helpers (ip/sha/clean). */
export const DFIR_PCAP_BASE_LINES = [
	"adapter-tshark-pcap-flow-runner-fallback: python3 - <target> <<'PY'",
	"import collections, hashlib, re, socket, struct, sys",
	"path = sys.argv[1]",
	"data = open(path, 'rb').read()",
	"magic = data[:4]",
	"packets = 0",
	"flows = collections.defaultdict(lambda: {'packets': 0, 'bytes': 0})",
	"stream_segments = collections.defaultdict(list)",
	"def ip4(raw): return socket.inet_ntoa(raw)",
	"def ip6(raw): return socket.inet_ntop(socket.AF_INET6, raw)",
	"def sha(raw): return hashlib.sha256(raw).hexdigest()[:24]",
	"def clean(text): return re.sub(r'\\s+', ' ', str(text)).strip()[:700]",
	"def qtype_name(value):",
	"    return {1: 'A', 2: 'NS', 5: 'CNAME', 15: 'MX', 16: 'TXT', 28: 'AAAA', 33: 'SRV', 65: 'HTTPS'}.get(value, str(value))",
	"def dns_name(buf, off, depth=0):",
	"    labels = []",
	"    jumped = False",
	"    original = off",
	"    while off < len(buf) and depth < 12:",
	"        length = buf[off]",
	"        if length == 0:",
	"            off += 1",
	"            break",
	"        if length & 0xc0 == 0xc0 and off + 1 < len(buf):",
	"            ptr = ((length & 0x3f) << 8) | buf[off + 1]",
	"            label, _ = dns_name(buf, ptr, depth + 1)",
	"            if label:",
	"                labels.append(label)",
	"            off += 2",
	"            jumped = True",
	"            break",
	"        off += 1",
	"        if off + length > len(buf):",
	"            break",
	"        labels.append(buf[off:off+length].decode('latin1', 'replace'))",
	"        off += length",
	"    return '.'.join(part for part in labels if part), (original + 2 if jumped else off)",
] as const;
