/** DFIR pure-python pcap dns/tls parsers. */
export const DFIR_PCAP_DNS_TLS_LINES = [
	"def parse_dns(payload):",
	"    rows = []",
	"    if len(payload) < 12:",
	"        return rows",
	"    txid, flags, qd, an, ns, ar = struct.unpack('!HHHHHH', payload[:12])",
	"    off = 12",
	"    for _ in range(min(qd, 40)):",
	"        name, off = dns_name(payload, off)",
	"        if off + 4 > len(payload):",
	"            break",
	"        qtype, qclass = struct.unpack('!HH', payload[off:off+4])",
	"        off += 4",
	"        if name:",
	"            rows.append(('query', txid, name, qtype_name(qtype), ''))",
	"    for section, count in (('answer', an), ('authority', ns), ('additional', ar)):",
	"        for _ in range(min(count, 80)):",
	"            name, off = dns_name(payload, off)",
	"            if off + 10 > len(payload):",
	"                return rows",
	"            rtype, rclass, ttl, rdlen = struct.unpack('!HHIH', payload[off:off+10])",
	"            off += 10",
	"            rdata = payload[off:off+rdlen]",
	"            off += rdlen",
	"            value = rdata.hex()",
	"            if rtype == 1 and len(rdata) == 4:",
	"                value = ip4(rdata)",
	"            elif rtype == 28 and len(rdata) == 16:",
	"                value = socket.inet_ntop(socket.AF_INET6, rdata)",
	"            elif rtype in (2, 5, 12, 15, 33, 65):",
	"                value, _ = dns_name(payload, off - rdlen)",
	"            elif rtype == 16 and rdata:",
	"                value = clean(rdata[1:].decode('latin1', 'replace') if len(rdata) > 1 else '')",
	"            rows.append((section, txid, name or '<root>', qtype_name(rtype), value))",
	"    return rows",
	"def parse_tls_sni(payload):",
	"    names = []",
	"    if len(payload) < 9 or payload[0] != 22 or payload[1] != 3:",
	"        return names",
	"    record_len = struct.unpack('!H', payload[3:5])[0]",
	"    end = min(len(payload), 5 + record_len)",
	"    off = 5",
	"    if off + 4 > end or payload[off] != 1:",
	"        return names",
	"    hs_len = int.from_bytes(payload[off+1:off+4], 'big')",
	"    p = off + 4",
	"    hs_end = min(end, p + hs_len)",
	"    if p + 34 > hs_end:",
	"        return names",
	"    p += 2 + 32",
	"    if p >= hs_end:",
	"        return names",
	"    session_len = payload[p]",
	"    p += 1 + session_len",
	"    if p + 2 > hs_end:",
	"        return names",
	"    cipher_len = struct.unpack('!H', payload[p:p+2])[0]",
	"    p += 2 + cipher_len",
	"    if p >= hs_end:",
	"        return names",
	"    comp_len = payload[p]",
	"    p += 1 + comp_len",
	"    if p + 2 > hs_end:",
	"        return names",
	"    ext_len = struct.unpack('!H', payload[p:p+2])[0]",
	"    p += 2",
	"    ext_end = min(hs_end, p + ext_len)",
	"    while p + 4 <= ext_end:",
	"        etype, elen = struct.unpack('!HH', payload[p:p+4])",
	"        body = payload[p+4:p+4+elen]",
	"        if etype == 0 and len(body) >= 2:",
	"            q = 2",
	"            while q + 3 <= len(body):",
	"                name_type = body[q]",
	"                name_len = struct.unpack('!H', body[q+1:q+3])[0]",
	"                name = body[q+3:q+3+name_len]",
	"                if name_type == 0 and len(name) == name_len:",
	"                    try:",
	"                        names.append(name.decode('idna'))",
	"                    except Exception:",
	"                        names.append(name.decode('latin1', 'replace'))",
	"                q += 3 + name_len",
	"        p += 4 + elen",
	"    return names",
] as const;
