/** DFIR pure-python pcap iterators/parsers before process_frame. */
export const DFIR_PCAP_PARSER_LINES = [
	"def packet_iter_classic(buf):",
	"    if len(buf) < 24:",
	"        return",
	"    endian = '<' if buf[:4] in (b'\\xd4\\xc3\\xb2\\xa1', b'\\x4d\\x3c\\xb2\\xa1') else '>'",
	"    linktype = struct.unpack(endian + 'I', buf[20:24])[0]",
	"    off = 24",
	"    while off + 16 <= len(buf):",
	"        try:",
	"            _sec, _frac, incl, _orig = struct.unpack(endian + 'IIII', buf[off:off+16])",
	"        except Exception:",
	"            break",
	"        off += 16",
	"        if incl < 0 or off + incl > len(buf):",
	"            break",
	"        frame = buf[off:off+incl]",
	"        off += incl",
	"        yield frame, linktype",
	"def packet_iter_pcapng(buf):",
	"    if len(buf) < 12:",
	"        return",
	"    bom = buf[8:12]",
	"    endian = '<' if bom == b'\\x4d\\x3c\\x2b\\x1a' else '>'",
	"    off = 0",
	"    linktypes = collections.defaultdict(lambda: 1)",
	"    while off + 12 <= len(buf):",
	"        try:",
	"            block_type, block_len = struct.unpack(endian + 'II', buf[off:off+8])",
	"        except Exception:",
	"            break",
	"        if block_len < 12 or off + block_len > len(buf):",
	"            break",
	"        body = buf[off+8:off+block_len-4]",
	"        if block_type == 1 and len(body) >= 8:",
	"            iface = len(linktypes)",
	"            linktypes[iface] = struct.unpack(endian + 'H', body[:2])[0]",
	"        elif block_type == 6 and len(body) >= 20:",
	"            iface, _tsh, _tsl, cap_len, _pkt_len = struct.unpack(endian + 'IIIII', body[:20])",
	"            frame = body[20:20+cap_len]",
	"            yield frame, linktypes[iface]",
	"        elif block_type == 3 and len(body) >= 4:",
	"            pkt_len = struct.unpack(endian + 'I', body[:4])[0]",
	"            yield body[4:4+pkt_len], 1",
	"        off += block_len",
	"def ip_offset(frame, linktype):",
	"    ipv4 = b'\\x08\\x00'",
	"    ipv6 = b'\\x86\\xdd'",
	"    if linktype == 1 and len(frame) >= 14:",
	"        if frame[12:14] in (ipv4, ipv6):",
	"            return 14",
	"        if frame[12:14] == b'\\x81\\x00' and len(frame) >= 18 and frame[16:18] in (ipv4, ipv6):",
	"            return 18",
	"    if linktype == 101 and len(frame) >= 20 and frame[0] >> 4 in (4, 6):",
	"        return 0",
	"    if linktype in (113, 276) and len(frame) >= 16 and frame[14:16] in (ipv4, ipv6):",
	"        return 16",
	"    if len(frame) >= 20 and frame[0] >> 4 in (4, 6):",
	"        return 0",
	"    return None",
	"def add_flow(src, dst, payload_len):",
	"    a, b = sorted([src, dst])",
	"    key = a + ' <-> ' + b",
	"    flows[key]['packets'] += 1",
	"    flows[key]['bytes'] += payload_len",
	"    return key",
	"def emit_http(frame_no, key, payload, tag='http-object'):",
	"    text = payload.decode('latin1', 'replace')",
	"    if re.search(r'\\b(?:GET|POST|PUT|DELETE|PATCH|HTTP/)\\b|Host:', text, re.I):",
	"        first = text.splitlines()[0] if text.splitlines() else ''",
	"        host = (re.search(r'(?im)^Host:\\s*([^\\r\\n]+)', text) or [None, '<none>'])[1]",
	"        print('[%s] frame=%s flow=%s first=%s Host: %s bytes=%d sha256=%s' % (tag, frame_no, key, clean(first), clean(host), len(payload), sha(payload)))",
	"    for match in re.finditer(r'(?i)(cookie|authorization|password|passwd|token|credential|secret)[^\\r\\n;]{0,160}', text):",
	"        print('[credential-timeline] frame=%s flow=%s signal=%s' % (frame_no, key, clean(match.group(0))))",
	"def reassemble_tcp_segments(key, segments):",
	"    ordered = sorted(segments, key=lambda row: (row[0], row[1]))",
	"    out = bytearray()",
	"    expected = None",
	"    gaps = []",
	"    for seq, frame_no, payload in ordered:",
	"        if not payload:",
	"            continue",
	"        if expected is None:",
	"            out.extend(payload)",
	"            expected = seq + len(payload)",
	"            continue",
	"        if seq < expected:",
	"            overlap = expected - seq",
	"            if overlap < len(payload):",
	"                out.extend(payload[overlap:])",
	"                expected += len(payload) - overlap",
	"            continue",
	"        if seq > expected:",
	"            gaps.append(seq - expected)",
	"            print('[tcp-reassembly-gap] flow=%s expected_seq=%d next_seq=%d missing=%d' % (key, expected, seq, seq - expected))",
	"        out.extend(payload)",
	"        expected = seq + len(payload)",
	"    seq_order = ','.join(str(row[0]) for row in ordered[:40])",
	"    print('[tcp-reassembly] flow=%s segments=%d gaps=%d bytes=%d seq_order=%s sha256=%s' % (key, len(ordered), len(gaps), len(out), seq_order, sha(bytes(out))))",
	"    return bytes(out)",
] as const;
