/** Pure-python HTTP/2 preface / frame header CAP for pcap or blob. */
// Landmark: dfir-http2 PRI * HTTP/2.0 summary.dfir_http2 pure_python

export const DFIR_HTTP2_SURROGATE_LINES = [
	'if [ -n "${1:-}" ] && [ -e "${1:-}" ] && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$1\" <<'PY'",
	"import pathlib, struct, sys",
	"path = pathlib.Path(sys.argv[1])",
	"data = path.read_bytes()[:4_000_000] if path.is_file() else b''",
	"print('[dfir-http2] path=%s bytes=%d pure_python=1' % (path, len(data)))",
	"preface = b'PRI * HTTP/2.0\\r\\n\\r\\nSM\\r\\n\\r\\n'",
	"hits = 0",
	"i = 0",
	"while True:",
	"  j = data.find(preface, i)",
	"  if j < 0: break",
	"  hits += 1",
	"  print('[dfir-http2] preface_offset=0x%x' % j)",
	"  i = j + len(preface)",
	"  if hits >= 4: break",
	"# bare frame headers: length(24be)+type+flags+streamid",
	"frames = 0",
	"for off in range(0, min(len(data)-9, 200000), 1):",
	"  if data[off:off+3] == b'\\x00\\x00\\x00' and data[off+3] in (0x04,0x01,0x00,0x08):  # weak",
	"    pass",
	"# scan SETTINGS type=0x04 after preface",
	"for j in range(0, max(0, len(data)-9)):",
	"  length = int.from_bytes(data[j:j+3], 'big')",
	"  ftype = data[j+3]",
	"  if ftype in (0x00,0x01,0x04,0x08) and 0 <= length <= 16384:",
	"    # only count near HTTP/2 preface",
	"    if preface in data[max(0,j-64):j+1] or ftype == 0x04 and length in (0,18,24,36):",
	"      if ftype == 0x04:",
	"        print('[dfir-http2] frame=SETTINGS len=%d off=0x%x' % (length, j))",
	"        frames += 1",
	"        if frames >= 3: break",
	"print('[dfir-http2] preface_hits=%d settings_frames=%d' % (hits, frames))",
	"ok = 1 if hits or frames else 0",
	"print('[dfir-http2] ok=%d pure_python=1' % ok)",
	"if ok:",
	"  print('summary.dfir_http2=1')",
	"PY",
	"fi",
] as const;
