/** DFIR pure-python DNS/TLS surface deepen without tshark. */
export const DFIR_DNS_TLS_DEEP_LINES = [
	'if [ -n "${1:-}" ] && [ -e "${1:-}" ] && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$1\" <<'PY'",
	"import collections, pathlib, re, sys",
	"path = pathlib.Path(sys.argv[1])",
	"data = path.read_bytes() if path.is_file() else b''",
	"print('[dfir-dns-tls] path=%s bytes=%d' % (path, len(data)))",
	"def dns_names(blob):",
	"  names=[]",
	"  i=0",
	"  while i < len(blob)-1:",
	"    labels=[]; j=i; ok=True",
	"    while j < len(blob):",
	"      ln=blob[j]",
	"      if ln==0:",
	"        j+=1; break",
	"      if ln>=0xc0:",
	"        ok=False; break",
	"      if ln>63 or j+1+ln>len(blob):",
	"        ok=False; break",
	"      labels.append(blob[j+1:j+1+ln].decode('latin1','ignore'))",
	"      j+=1+ln",
	"    if ok and 1<=len(labels)<=8 and all(1<=len(x)<=63 for x in labels):",
	"      name='.'.join(labels)",
	"      if re.search(r'[A-Za-z]', name) and '.' in name:",
	"        names.append(name)",
	"    i+=1",
	"  return names",
	"names=collections.Counter(dns_names(data[:2_000_000]))",
	"for n,c in names.most_common(20):",
	"  print('[dfir-dns] name=%s hits=%d' % (n, c))",
	"print('[dfir-dns] unique=%d' % len(names))",
	"sni=[]",
	"for m in re.finditer(rb'([a-z0-9][a-z0-9.-]{2,60}\\.(?:com|net|org|io|dev|local|internal|example))', data[:2_000_000], re.I):",
	"  sni.append(m.group(1).decode('latin1','ignore'))",
	"sni_c=collections.Counter(sni)",
	"for h,c in sni_c.most_common(16):",
	"  print('[dfir-tls-sni] host=%s hits=%d' % (h, c))",
	"ja3=0; ja3_fp=''",
	"pos=data.find(bytes([0x16,0x03]))",
	"if pos>=0 and pos+40 < len(data):",
	"  print('[dfir-tls] handshake_offset=0x%x' % pos)",
	"  ja3=1",
	"  # Lightweight JA3-ish fingerprint from ClientHello cipher suites (offline pure-python)",
	"  try:",
	"    # TLS record: type(1)=22, ver(2), len(2), hs_type(1)=1 ClientHello",
	"    if data[pos]==0x16 and pos+5 < len(data) and data[pos+5]==0x01:",
	"      # skip record hdr(5)+hs_hdr(4)+client_ver(2)+random(32)+session",
	"      i=pos+5+4+2+32",
	"      if i < len(data):",
	"        sid_len=data[i]; i+=1+sid_len",
	"        if i+2 <= len(data):",
	"          cs_len=int.from_bytes(data[i:i+2],'big'); i+=2",
	"          ciphers=data[i:i+cs_len]",
	"          suites=[int.from_bytes(ciphers[j:j+2],'big') for j in range(0,len(ciphers)-1,2)][:32]",
	"          # JA3 fields: SSLVersion,Ciphers,Extensions,EllipticCurves,EllipticCurvePointFormats — partial",
	"          ssl_ver=int.from_bytes(data[pos+9:pos+11],'big') if pos+11<=len(data) else 0",
	"          ja3_fp='%d,%s,,, ' % (ssl_ver, '-'.join(str(x) for x in suites))",
	"          ja3_fp=ja3_fp.strip()",
	"          import hashlib",
	"          ja3_md5=hashlib.md5(ja3_fp.encode()).hexdigest()",
	"          print('[dfir-tls-ja3] suites=%d ver=0x%x fp=%s md5=%s pure_python=1' % (len(suites), ssl_ver, ja3_fp[:80], ja3_md5))",
	"          print('summary.dfir_ja3=1')",
	"  except Exception as je:",
	"    print('[dfir-tls-ja3] err=%s' % type(je).__name__)",
	"print('[dfir-tls] sni_unique=%d handshake=%d ja3=%d' % (len(sni_c), ja3, int(bool(ja3_fp))))",
	"text=data.decode('latin1','ignore')",
	"for m in re.finditer(r'(?i)(cookie|authorization|x-api-key|set-cookie)\\s*[:=]\\s*([^\\r\\n]{4,120})', text):",
	"  print('[dfir-http-auth] header=%s value=%s' % (m.group(1), m.group(2)[:80]))",
	"print('[dfir-dns-tls] ok=1 dns=%d sni=%d' % (len(names), len(sni_c)))",
	"PY",
	"fi",
] as const;
