/** Host firmware extract CAP: binwalk -eM + unsquashfs rootfs inventory. */
export const FIRMWARE_EXTRACT_HOST_LINES = [
	'if [ -f "$target" ]; then',
	'  EXTRACT_ROOT="${REPI_WORKDIR:-/tmp}/repi-fw-extract-$(basename "$target" | tr -c "A-Za-z0-9._-" "_")"',
	'  mkdir -p "$EXTRACT_ROOT"',
	'  printf "[firmware-extract-host] root=%s target=%s\\n" "$EXTRACT_ROOT" "$target"',
	"  if command -v binwalk >/dev/null 2>&1; then",
	'    printf "[firmware-extract-host] binwalk=%s\\n" "$(command -v binwalk)"',
	'    timeout 90s binwalk --run-as=root -eM -C "$EXTRACT_ROOT" "$target" 2>/tmp/repi-fw-binwalk-extract.err | head -80 | sed "s/^/[firmware-extract] /"',
	'    if [ -s /tmp/repi-fw-binwalk-extract.err ]; then head -5 /tmp/repi-fw-binwalk-extract.err | sed "s/^/[firmware-extract-err] /"; fi',
	"    CAP_BINWALK=1; CAP_EXTRACT=1; CAP_IMAGE=1",
	"  else",
	'    printf "[firmware-extract-host] binwalk=0\\n"',
	"  fi",
	'  SQ_LIST=$(find "$EXTRACT_ROOT" -maxdepth 6 -type f \\( -iname "*squash*" -o -iname "*.sqsh" -o -iname "*.squashfs" \\) 2>/dev/null | head -8)',
	'  if [ -z "$SQ_LIST" ] && command -v python3 >/dev/null 2>&1; then',
	'    OFF=$(python3 -c \'import pathlib,sys;d=pathlib.Path(sys.argv[1]).read_bytes()[:8000000];o=next((d.find(m) for m in (b"hsqs",b"sqsh") if d.find(m)>=0), -1);print(o if o>=0 else "")\' "$target" 2>/dev/null || true)',
	'    if [ -n "$OFF" ] && command -v dd >/dev/null 2>&1; then',
	'      dd if="$target" of="$EXTRACT_ROOT/carved.squashfs" bs=1 skip="$OFF" count=6000000 status=none 2>/dev/null || true',
	'      if [ -s "$EXTRACT_ROOT/carved.squashfs" ]; then SQ_LIST="$EXTRACT_ROOT/carved.squashfs"; printf "[firmware-extract-host] carved_squashfs=1 offset=%s\\n" "$OFF"; fi',
	"    fi",
	"  fi",
	"  if command -v unsquashfs >/dev/null 2>&1; then",
	"    for sq in $SQ_LIST; do",
	'      [ -f "$sq" ] || continue',
	'      OUTDIR="$EXTRACT_ROOT/unsquash-$(basename "$sq" | tr -c "A-Za-z0-9._-" "_")"',
	'      mkdir -p "$OUTDIR"',
	'      printf "[firmware-unsquash] host=1 bin=%s input=%s\\n" "$(command -v unsquashfs)" "$sq"',
	'      timeout 60s unsquashfs -d "$OUTDIR/rootfs" -f "$sq" >/tmp/repi-fw-unsquash.out 2>/tmp/repi-fw-unsquash.err || true',
	'      head -40 /tmp/repi-fw-unsquash.out 2>/dev/null | sed "s/^/[firmware-unsquash] /"',
	'      if [ -d "$OUTDIR/rootfs" ]; then',
	'        find "$OUTDIR/rootfs" -maxdepth 4 -type f \\( -name passwd -o -name shadow -o -iname "*dropbear*" -o -iname "*httpd*" -o -iname "*busybox*" \\) 2>/dev/null | head -40 | sed "s/^/[firmware-rootfs-file] /"',
	'        if [ -f "$OUTDIR/rootfs/etc/passwd" ]; then CAP_ACCOUNT=1; awk \'{print "[rootfs-account] path=/etc/passwd line=" $0}\' "$OUTDIR/rootfs/etc/passwd" | head -40; fi',
	'        if [ -d "$OUTDIR/rootfs/etc/init.d" ]; then find "$OUTDIR/rootfs/etc/init.d" -type f 2>/dev/null | head -20 | while read -r f; do printf "[rootfs-service] path=%s name=%s\\n" "${f#$OUTDIR/rootfs/}" "$(basename "$f")"; CAP_SERVICE=1; done; fi',
	"        CAP_EXTRACT=1",
	'        printf "[firmware-unsquash] ok=1 rootfs=%s\\n" "$OUTDIR/rootfs"',
	"      else",
	'        head -5 /tmp/repi-fw-unsquash.err 2>/dev/null | sed "s/^/[firmware-unsquash] /"',
	'        printf "[firmware-unsquash] ok=0\\n"',
	"      fi",
	"      break",
	"    done",
	"  else",
	'    printf "[firmware-unsquash] host=0 note=unsquashfs_missing\\n"',
	"  fi",
	'  DIRS=$(find "$EXTRACT_ROOT" -maxdepth 4 -type d 2>/dev/null | wc -l | tr -d " ")',
	'  FILES=$(find "$EXTRACT_ROOT" -maxdepth 5 -type f 2>/dev/null | wc -l | tr -d " ")',
	'  printf "[firmware-extract-host] ok=1 dirs=%s files=%s\\n" "${DIRS:-0}" "${FILES:-0}"',
	'  find "$EXTRACT_ROOT" -maxdepth 4 -type d \\( -iname "*squash*" -o -iname "*rootfs*" -o -iname "_*.extracted" \\) 2>/dev/null | head -20 | sed "s/^/[firmware-rootfs-dir] /"',
	"fi",
] as const;
