/** Host binwalk CAP: structured signature map + optional entropy when binwalk present. */
export const FIRMWARE_BINWALK_HOST_LINES = [
	'if [ -f "$target" ] && command -v binwalk >/dev/null 2>&1; then',
	'  printf "[firmware-binwalk] host=1 tool=$(command -v binwalk)\\n"',
	'  BW_OUT=$(binwalk -B "$target" 2>/dev/null | head -120)',
	'  printf "%s\\n" "$BW_OUT" | sed "s/^/[firmware-binwalk] /"',
	'  BW_HITS=$(printf "%s\\n" "$BW_OUT" | awk \'BEGIN{c=0} $1 ~ /^[0-9]+$/ {c++} END{print c+0}\')',
	'  BW_TYPES=$(printf "%s\\n" "$BW_OUT" | awk \'$1 ~ /^[0-9]+$/ {',
	'    line=$0; sub(/^[0-9]+[ \\t]+0x[0-9a-fA-F]+[ \\t]+/, "", line);',
	'    split(line, a, /[ ,]/); kind=tolower(a[1]); if(kind!="") print kind',
	"  }' | sort | uniq -c | sort -rn | head -20)",
	'  printf "%s\\n" "$BW_TYPES" | while read -r cnt kind; do',
	'    [ -n "$kind" ] || continue',
	'    printf "[firmware-binwalk-type] kind=%s count=%s\\n" "$kind" "$cnt"',
	"  done",
	'  printf "[firmware-binwalk] hits=%s\\n" "${BW_HITS:-0}"',
	'  if binwalk -E "$target" 2>/dev/null | head -8 | grep -qiE "entropy|DECIMAL|HEXADECIMAL"; then',
	'    binwalk -E "$target" 2>/dev/null | head -40 | sed "s/^/[firmware-binwalk-entropy] /"',
	'    printf "[firmware-binwalk-entropy] ok=1\\n"',
	"  else",
	'    printf "[firmware-binwalk-entropy] ok=0 note=unsupported-or-empty\\n"',
	"  fi",
	"  if command -v python3 >/dev/null 2>&1; then",
	"python3 - \"$target\" <<'PY'",
	"import pathlib, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()[:8_000_000] if p.is_file() else b''",
	"mags = [(bytes([0x7f,0x45,0x4c,0x46]),'ELF'),(b'hsqs','SQUASHFS'),(bytes([0x1f,0x8b,0x08]),'GZIP'),(bytes([0x27,0x05,0x19,0x56]),'UIMAGE'),(b'UBI#','UBI'),(b'PK'+bytes([3,4]),'ZIP')]",
	"for mag,name in mags:",
	"  pos=data.find(mag)",
	"  if pos>=0: print('[firmware-binwalk-magic] name=%s offset=0x%x' % (name, pos))",
	"print('[firmware-binwalk-magic] ok=1')",
	"PY",
	"  fi",
	'  if [ "${BW_HITS:-0}" -gt 0 ] 2>/dev/null; then CAP_BINWALK=1; CAP_EXTRACT=1; CAP_IMAGE=1; printf "[firmware-binwalk] ok=1 cap=1 hits=%s\\n" "${BW_HITS:-0}"; else CAP_BINWALK=1; printf "[firmware-binwalk] ok=1 cap=0 hits=0 note=no-signature-hits\\n"; fi',
	'elif [ -d "$target" ] && command -v binwalk >/dev/null 2>&1; then',
	"  # directory target: prefer first firmware-like image under tree (not host=0 dead-end)",
	'  IMG=$(find "$target" -maxdepth 3 -type f \\( -name "*.bin" -o -name "*.img" -o -name "*.fw" -o -name "*.squashfs" -o -name "firmware*" -o -name "*.ubi" \\) 2>/dev/null | head -1)',
	'  if [ -z "$IMG" ]; then IMG=$(find "$target" -maxdepth 2 -type f -size +1k 2>/dev/null | head -1); fi',
	'  if [ -n "$IMG" ] && [ -f "$IMG" ]; then',
	'    printf "[firmware-binwalk] host=1 tool=$(command -v binwalk) note=dir_image_probe image=%s\\n" "$IMG"',
	'    BW_OUT=$(binwalk -B "$IMG" 2>/dev/null | head -80)',
	'    printf "%s\\n" "$BW_OUT" | sed "s/^/[firmware-binwalk] /"',
	'    BW_HITS=$(printf "%s\\n" "$BW_OUT" | awk \'BEGIN{c=0} $1 ~ /^[0-9]+$/ {c++} END{print c+0}\')',
	'    printf "[firmware-binwalk] hits=%s image=%s\\n" "${BW_HITS:-0}" "$IMG"',
	'    if [ "${BW_HITS:-0}" -gt 0 ] 2>/dev/null; then CAP_BINWALK=1; CAP_IMAGE=1; CAP_EXTRACT=1; printf "[firmware-binwalk] ok=1 cap=1 dir_probe=1 hits=%s\\n" "${BW_HITS:-0}"; else CAP_BINWALK=1; printf "[firmware-binwalk] ok=1 cap=0 dir_probe=1 hits=0\\n"; fi',
	"  else",
	'    printf "[firmware-binwalk] host=1 tool=$(command -v binwalk) note=directory_no_image_probe rootfs_map_only\\n"',
	'    printf "[firmware-binwalk] ok=1 cap=0 dir_probe=0\\n"',
	"  fi",
	"else",
	'  if [ -d "$target" ]; then printf "[firmware-binwalk] host=0 note=target_is_directory_binwalk_missing\\n";',
	'  elif ! command -v binwalk >/dev/null 2>&1; then printf "[firmware-binwalk] host=0 note=binwalk_missing\\n";',
	'  else printf "[firmware-binwalk] host=0 note=target_not_file\\n"; fi',
	"fi",
] as const;
