/** Pure-python Flattened Device Tree (DTB) header/structure CAP. */
// Landmark: firmware-dtb d00dfeed totalsize off_dt_struct summary.firmware_dtb

export const FIRMWARE_DTB_SURROGATE_LINES = [
	'if [ -f "$target" ] && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$target\" <<'PY'",
	"import pathlib, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()[:12_000_000]",
	"print('[firmware-dtb] path=%s bytes=%d' % (p, len(data)))",
	"FDT_MAGIC = 0xd00dfeed",
	"hits = 0",
	"i = 0",
	"while True:",
	"  j = data.find(b'\\xd0\\x0d\\xfe\\xed', i)",
	"  if j < 0 or j + 40 > len(data): break",
	"  try:",
	"    magic, totalsize, off_dt_struct, off_dt_strings, off_mem_rsvmap, version, last_comp_version = struct.unpack_from('>IIIIIII', data, j)",
	"  except Exception:",
	"    break",
	"  if magic != FDT_MAGIC or totalsize < 40 or totalsize > len(data) - j + 8:",
	"    i = j + 4; continue",
	"  hits += 1",
	"  print('[firmware-dtb] offset=0x%x totalsize=%d version=%d off_struct=0x%x off_strings=0x%x pure_python=1' % (j, totalsize, version, off_dt_struct, off_dt_strings))",
	"  # walk a few FDT tokens for node names (FDT_BEGIN_NODE=1, END_NODE=2, PROP=3, END=9)",
	"  try:",
	"    base = j + off_dt_struct",
	"    end = j + min(totalsize, off_dt_struct + 4096)",
	"    k = base; nodes = 0; props = 0",
	"    while k + 4 <= end and nodes < 32:",
	"      tok = struct.unpack_from('>I', data, k)[0]; k += 4",
	"      if tok == 1:  # BEGIN_NODE",
	"        name = b''",
	"        while k < end and data[k] != 0:",
	"          name += bytes([data[k]]); k += 1",
	"        k += 1",
	"        while k % 4: k += 1",
	"        nodes += 1",
	"        if name: print('[firmware-dtb-node] name=%s' % name.decode('latin1','ignore')[:80])",
	"      elif tok == 3:  # PROP",
	"        if k + 8 > end: break",
	"        plen, nameoff = struct.unpack_from('>II', data, k); k += 8",
	"        props += 1",
	"        k += plen",
	"        while k % 4: k += 1",
	"      elif tok == 2:  # END_NODE",
	"        continue",
	"      elif tok == 9:  # END",
	"        break",
	"      else:",
	"        break",
	"    print('[firmware-dtb] nodes=%d props_seen=%d' % (nodes, props))",
	"  except Exception as e:",
	"    print('[firmware-dtb] walk_err=%s' % type(e).__name__)",
	"  i = j + max(4, totalsize)",
	"  if hits >= 3: break",
	"print('[firmware-dtb] count=%d' % hits)",
	"if hits:",
	"  print('[firmware-dtb] ok=1 pure_python=1')",
	"  print('summary.firmware_dtb=1')",
	"else:",
	"  print('[firmware-dtb] ok=0 note=no_fdt_magic')",
	"PY",
	"fi",
] as const;
