/** Deeper pure-python firmware CAP: multi-sig offsets, entropy bands, version strings. */

export const FIRMWARE_DEEP_SURROGATE_LINES = [
	'if [ -e "$target" ] && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$target\" <<'PY'",
	"import collections, math, pathlib, re, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = b''",
	"if p.is_file():",
	"  data = p.read_bytes()[:16_000_000]",
	"elif p.is_dir():",
	"  # directory rootfs: concat small text/binary samples for version/service map",
	"  parts=[]",
	"  for fp in sorted(p.rglob('*'))[:400]:",
	"    if not fp.is_file(): continue",
	"    try:",
	"      if fp.stat().st_size > 256_000: continue",
	"      parts.append(fp.read_bytes()[:8192])",
	"    except Exception:",
	"      pass",
	"    if sum(len(x) for x in parts) > 4_000_000: break",
	"  data = b''.join(parts)",
	"print('[firmware-deep] path=%s bytes=%d mode=%s' % (p, len(data), 'dir' if p.is_dir() else 'file'))",
	"sigs = [",
	"  (b'\\x7fELF', 'ELF'), (b'MZ', 'PE'), (b'PK\\x03\\x04', 'ZIP'), (b'\\x1f\\x8b\\x08', 'GZIP'),",
	"  (b'hsqs', 'SQUASHFS'), (b'sqsh', 'SQUASHFS-BE'), (b'UBI#', 'UBI'), (b'UBI!', 'UBI-EC'),",
	"  (b'\\x27\\x05\\x19\\x56', 'UIMAGE'), (b'\\xd0\\x0d\\xfe\\xed', 'DTB'), (b'ANDROID!', 'ANDROID-boot'),",
	"  (b'\\x88\\x16\\x88\\x58', 'JFFS2'), (b'UBIFS', 'UBIFS-text'), (b'cramfs', 'CRAMFS-text'),",
	"]",
	"hits=[]",
	"for magic, name in sigs:",
	"  start=0",
	"  while True:",
	"    pos = data.find(magic, start)",
	"    if pos < 0: break",
	"    hits.append((pos, name))",
	"    if len([h for h in hits if h[1]==name]) <= 3:",
	"      print('[firmware-deep-sig] name=%s offset=0x%x' % (name, pos))",
	"    start = pos + max(1, len(magic))",
	"    if start > len(data): break",
	"print('[firmware-deep-sig] total=%d unique=%d' % (len(hits), len({n for _,n in hits})))",
	"# entropy windows (4k) — high entropy often compressed/encrypted FS",
	"def ent(buf):",
	"  if not buf: return 0.0",
	"  c=collections.Counter(buf); n=len(buf)",
	"  return -sum((v/n)*math.log2(v/n) for v in c.values())",
	"high=0",
	"for off in range(0, min(len(data), 2_000_000), 4096):",
	"  e=ent(data[off:off+4096])",
	"  if e >= 7.2:",
	"    high += 1",
	"    if high <= 8: print('[firmware-entropy] offset=0x%x entropy=%.2f' % (off, e))",
	"print('[firmware-entropy] high_windows=%d' % high)",
	"text = data.decode('latin1','ignore')",
	"ver = re.findall(r'(?:OpenWrt|Linux version|BusyBox v|u-boot|U-Boot|dropbear[_ ]?[0-9.]+|Buildroot|DISTRIB_RELEASE)[^\\n\\x00]{0,80}', text, re.I)[:20]",
	"for v in ver[:12]:",
	"  print('[firmware-version] sample=%s' % v[:100].replace('\\n',' '))",
	"print('[firmware-version] hits=%d' % len(ver))",
	"svc = re.findall(r'(?:httpd|uhttpd|dropbear|telnetd|dnsmasq|hostapd|wpa_supplicant|nginx|lighttpd)', text, re.I)",
	"print('[firmware-service-map] hits=%d unique=%s' % (len(svc), ','.join(sorted({s.lower() for s in svc})[:12]) or 'none'))",
	"fs = any(n in {x[1] for x in hits} for n in ('SQUASHFS','SQUASHFS-BE','UBI','UBI-EC','GZIP','ZIP','UIMAGE','DTB','ANDROID-boot'))",
	"if fs:",
	"  print('[firmware-deep] fs_candidates=1')",
	"print('[firmware-deep] ok=1')",
	"raise SystemExit(0 if fs else 2)",
	"PY",
	"  if [ $? -eq 0 ]; then",
	"    CAP_IMAGE=1; CAP_EXTRACT=1",
	"    # Image-blob path: promote service/account/config CAP from deep map tags just emitted",
	'    if [ ! -d "$target" ]; then',
	"      if command -v strings >/dev/null 2>&1; then",
	'        SMAP=$(strings -a -n 4 "$target" 2>/dev/null | grep -iE "httpd|uhttpd|dropbear|telnetd|dnsmasq|hostapd" | head -5)',
	'        if [ -n "$SMAP" ]; then CAP_SERVICE=1; printf "%s\\n" "$SMAP" | sed "s/^/[firmware-service-promote] /"; fi',
	'        AMAP=$(strings -a -n 4 "$target" 2>/dev/null | grep -iE "root:|passwd|shadow|admin:" | head -5)',
	'        if [ -n "$AMAP" ]; then CAP_ACCOUNT=1; printf "%s\\n" "$AMAP" | sed "s/^/[firmware-account-promote] /"; fi',
	'        CMAP=$(strings -a -n 4 "$target" 2>/dev/null | grep -iE "DISTRIB_|OpenWrt|BusyBox v|dropbear_202" | head -5)',
	'        if [ -n "$CMAP" ]; then CAP_CONFIG=1; printf "%s\\n" "$CMAP" | sed "s/^/[firmware-config-promote] /"; fi',
	'        if command -v file >/dev/null 2>&1 && file -b "$target" 2>/dev/null | grep -qi ELF; then CAP_ELF=1; printf "[firmware-elf-promote] via=file\\n"; fi',
	'        if python3 -c "import pathlib,sys; sys.exit(0 if b\'\\\\x7fELF\' in pathlib.Path(sys.argv[1]).read_bytes() else 1)" "$target" 2>/dev/null; then CAP_ELF=1; printf "[firmware-elf-promote] via=magic\\n"; fi',
	"      fi",
	"    fi",
	'  else printf "[firmware-deep] cap=0 note=no-fs-signatures\\n"; fi',
	"fi",
] as const;
