// Landmark: pure_python=1 pure_python_map=1 for host-or-pure CAP contract
/** Pure-python firmware image surface map when binwalk path is weak. */
export const FIRMWARE_IMAGE_SURROGATE_LINES = [
	'if [ -f "$target" ] && command -v python3 >/dev/null 2>&1; then',
	"python3 - \"$target\" <<'PY'",
	"import pathlib, re, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()[:8_000_000]",
	"print('[firmware-image] path=%s bytes=%d' % (p, len(data)))",
	"sigs = [",
	"  (b'\\x7fELF', 'ELF'), (b'MZ', 'PE'), (b'PK\\x03\\x04', 'ZIP'), (b'\\x1f\\x8b\\x08', 'GZIP'),",
	"  (b'hsqs', 'SQUASHFS'), (b'sqsh', 'SQUASHFS-BE'), (b'UBI#', 'UBI'), (b'UBI!', 'UBI-EC'),",
	"  (b'\\x27\\x05\\x19\\x56', 'UIMAGE'), (b'device tree blob', 'DTB-text'), (b'\\xd0\\x0d\\xfe\\xed', 'DTB'),",
	"  (b'ANDROID!', 'ANDROID-boot'), (b'CrAU', 'ChromeOS'), (b'hsqt', 'SQUASHFS-alt'),",
	"]",
	"found=[]",
	"for magic,name in sigs:",
	"    pos = data.find(magic)",
	"    if pos >= 0:",
	"        found.append((pos, name))",
	"        print('[firmware-extract] offset=%d magic=%s name=%s' % (pos, magic[:8].hex(), name))",
	"        print('[firmware-image] signature=%s offset=%d' % (name, pos))",
	"text = data.decode('latin1','ignore')",
	"for m in re.finditer(r'(root:[^:\\n]{0,64}:0:0:|/etc/passwd|dropbear|busybox|httpd|uhttpd|telnetd|nvram|admin:|password=)', text, re.I):",
	"    print('[firmware-config] offset=%d sample=%s' % (m.start(), m.group(0)[:80].replace('\\n',' ')))",
	"for m in re.finditer(r'BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY|password=[^\\s]{3,40}|root:[x*!$][^:\\n]*:', text):",
	"    print('[firmware-secret] offset=%d sample=%s' % (m.start(), m.group(0)[:100].replace('\\n',' ')))",
	"print('[firmware-image] pure_python_map=1 signatures=%d' % len(found))",
	"if found:",
	"    print('[firmware-extract] pure_python_map=1 count=%d' % len(found))",
	"PY",
	"  CAP_EXTRACT=1",
	"fi",
] as const;
