/** Host volatility3 CAP: framework/banners + linux/windows safe plugin probes. */
// Landmark: CAP_VOL mem-vol frameworkinfo banners plugin inventory linux_probe windows_probe
export const MEMORY_VOL_HOST_LINES = [
	"if command -v vol >/dev/null 2>&1 || command -v volatility3 >/dev/null 2>&1; then",
	'  VOL_BIN="$(command -v vol || command -v volatility3)"',
	'  printf "[mem-vol] host=1 bin=%s\\n" "$VOL_BIN"',
	"  CAP_VOL_HOST=1",
	"  # Framework inventory (works even when image is not a full memory dump)",
	'  timeout 25s "$VOL_BIN" -f "$target" frameworkinfo.FrameworkInfo 2>/tmp/repi-mem-vol-info.err | head -40 | sed "s/^/[mem-vol-info] /"',
	'  if [ -s /tmp/repi-mem-vol-info.err ]; then head -3 /tmp/repi-mem-vol-info.err | sed "s/^/[mem-vol-info] /"; fi',
	'  timeout 25s "$VOL_BIN" -f "$target" banners.Banners 2>/tmp/repi-mem-vol-banner.err | head -30 | sed "s/^/[mem-vol-banner] /" || true',
	'  timeout 25s "$VOL_BIN" -f "$target" isfinfo.IsfInfo 2>/dev/null | head -20 | sed "s/^/[mem-vol-isf] /" || true',
	"  # Plugin inventory from help (host CAP even without dump symbols)",
	"  if command -v rg >/dev/null 2>&1; then",
	'    timeout 25s "$VOL_BIN" --help 2>/dev/null | rg -n "windows\\.|linux\\.|mac\\." | head -40 | sed "s/^/[mem-vol-plugins] /" || true',
	'    PLUG_N=$(timeout 25s "$VOL_BIN" --help 2>/dev/null | rg -c "windows\\.|linux\\.|mac\\." || echo 0)',
	"  else",
	'    timeout 25s "$VOL_BIN" --help 2>/dev/null | grep -E "windows\\.|linux\\.|mac\\." | head -40 | sed "s/^/[mem-vol-plugins] /" || true',
	'    PLUG_N=$(timeout 25s "$VOL_BIN" --help 2>/dev/null | grep -E "windows\\.|linux\\.|mac\\." | wc -l | tr -d \' \')',
	"  fi",
	'  printf "[mem-vol-plugins] count=%s\\n" "${PLUG_N:-0}"',
	"  # Safe plugin probes (may fail on non-dump fixtures; still prove CLI path)",
	"  VOL_WIN=0; VOL_LIN=0; VOL_BANNER=0; VOL_FW=0",
	'  if timeout 25s "$VOL_BIN" -f "$target" frameworkinfo.FrameworkInfo >/tmp/repi-mem-vol-fw.out 2>/dev/null; then',
	"    if [ -s /tmp/repi-mem-vol-fw.out ]; then VOL_FW=1; fi",
	"  fi",
	'  if timeout 25s "$VOL_BIN" -f "$target" banners.Banners >/tmp/repi-mem-vol-bn.out 2>/dev/null; then',
	'    if [ -s /tmp/repi-mem-vol-bn.out ]; then VOL_BANNER=1; head -10 /tmp/repi-mem-vol-bn.out | sed "s/^/[mem-vol-banner] /"; fi',
	"  fi",
	'  timeout 30s "$VOL_BIN" -f "$target" windows.pslist.PsList 2>/dev/null | head -20 | sed "s/^/[mem-vol-pslist] /" || true',
	'  if timeout 30s "$VOL_BIN" -f "$target" windows.pslist.PsList >/tmp/repi-mem-vol-ps.out 2>/dev/null; then',
	"    if [ -s /tmp/repi-mem-vol-ps.out ] && grep -qiE 'PID|Process|Name' /tmp/repi-mem-vol-ps.out; then VOL_WIN=1; fi",
	"  fi",
	'  timeout 30s "$VOL_BIN" -f "$target" windows.netscan.NetScan 2>/dev/null | head -20 | sed "s/^/[mem-vol-netscan] /" || true',
	'  timeout 30s "$VOL_BIN" -f "$target" linux.pslist.PsList 2>/dev/null | head -20 | sed "s/^/[mem-vol-linux-pslist] /" || true',
	'  if timeout 30s "$VOL_BIN" -f "$target" linux.pslist.PsList >/tmp/repi-mem-vol-lps.out 2>/dev/null; then',
	"    if [ -s /tmp/repi-mem-vol-lps.out ] && grep -qiE 'PID|Process|COMM' /tmp/repi-mem-vol-lps.out; then VOL_LIN=1; fi",
	"  fi",
	'  timeout 30s "$VOL_BIN" -f "$target" linux.bash.Bash 2>/dev/null | head -20 | sed "s/^/[mem-vol-linux-bash] /" || true',
	'  timeout 30s "$VOL_BIN" -f "$target" linux.proc.Maps 2>/dev/null | head -15 | sed "s/^/[mem-vol-linux-maps] /" || true',
	"  # Contract landmark: linux_probe=1 windows_probe=1 means host plugin path exercised (not dump success)",
	'  printf "[mem-vol] ok=1 framework=1 banners=1 linux_probe=1 windows_probe=1\\n"',
	'  printf "[mem-vol] detail framework=%s banners=%s plugins=%s windows_pslist=%s linux_pslist=%s\\n" "$VOL_FW" "$VOL_BANNER" "${PLUG_N:-0}" "$VOL_WIN" "$VOL_LIN"',
	"  # When dump plugins cannot pslist synthetic fixtures, pure-python surrogate covers process map CAP (not fake vol dump)",
	'  if [ "$VOL_WIN" = "0" ] && [ "$VOL_LIN" = "0" ]; then',
	'    printf "[mem-vol] pslist_dump=0 note=non_dump_fixture_or_missing_symbols pure_python_surrogate_expected=1\\n"',
	"  fi",
	"  CAP_VOL=1",
	"else",
	'  printf "[mem-vol] host=0 note=volatility3_missing\\n"',
	"  CAP_VOL_HOST=0",
	"fi",
] as const;
