import { MEMORY_DEEP_SURROGATE_LINES } from "./memory-deep-surrogates.ts";
import { MEMORY_EXTRA_SURROGATE_LINES } from "./memory-extra-surrogates.ts";
import { MEMORY_HANDLES_SURROGATE_LINES } from "./memory-handles-surrogates.ts";
import { MEMORY_MALFIND_SURROGATE_LINES } from "./memory-malfind-surrogate.ts";
import { MEMORY_VOL_HOST_LINES } from "./memory-vol-host.ts";
import { MEMORY_YARA_HOST_LINES } from "./memory-yara-host.ts";
/** Runtime adapter command templates: memory-forensics host CAP. */

export function memoryForensicsHostCommandTemplate(mode: "native" | "fallback" = "fallback"): string {
	const prefix = mode === "native" ? "adapter-memory-forensics-runner:" : "adapter-memory-forensics-runner-fallback:";
	return [
		"set +e",
		'target="${target:-$1}"',
		`printf "[adapter-memory-target] adapter=${prefix} target=%s mode=${mode}\\n" "$target"`,
		'printf "[mem-env] file=%s strings=%s sha256sum=%s volatility3=%s vol=%s python=%s\\n" "$(command -v file || true)" "$(command -v strings || true)" "$(command -v sha256sum || true)" "$(command -v volatility3 || true)" "$(command -v vol || true)" "$(command -v python3 || true)"',
		"CAP_IMAGE=0; CAP_PROCESS=0; CAP_CRED=0; CAP_TIMELINE=0; CAP_VOL=0; CAP_HEADER=0; CAP_VOL_HOST=0; CAP_YARA=0",
		'if [ -z "$target" ] || [ ! -e "$target" ]; then',
		'  printf "[mem-image] target_missing=%s\\n" "${target:-<missing>}"',
		"  find . -maxdepth 5 -type f \\( -iname '*.raw' -o -iname '*.vmem' -o -iname '*.mem' -o -iname '*.dmp' -o -iname '*.lime' \\) -print 2>/dev/null | head -40 | sed \"s/^/[mem-image-candidate] path=/\"",
		'  printf "[memory-proof-capture] domain=memory-forensics image=0 process=0 cred=0 proof.exit=pending_runtime_capture\\n"',
		"  exit 0",
		"fi",
		'printf "[mem-image] target=%s\\n" "$target"',
		'file -b "$target" 2>/dev/null | sed "s/^/[mem-image] file=/"',
		'sha256sum "$target" 2>/dev/null | awk \'{print "[mem-image] sha256="$1}\'',
		"python3 - \"$target\" <<'PY'",
		"import hashlib, pathlib, re, sys",
		"p = pathlib.Path(sys.argv[1])",
		"data = p.read_bytes()[:2_000_000] if p.is_file() else b''",
		"print('[mem-image] sample_sha256=%s sample_bytes=%d path=%s' % (hashlib.sha256(data).hexdigest() if data else 'none', len(data), p))",
		"text = data.decode('utf-8','ignore') + '\\n' + data.decode('latin1','ignore')",
		"# process/network string map (volatility surrogate)",
		"proc_rx = re.compile(r'(cmd\\.exe|powershell|/bin/(?:ba)?sh|python[0-9.]*|curl|wget|sshd|lsass|explorer\\.exe)', re.I)",
		"net_rx = re.compile(r'(https?://|\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b|socket|connect|TCP|UDP)', re.I)",
		"cred_rx = re.compile(r'(password|passwd|token|secret|Authorization:|Cookie:|AWS_ACCESS_KEY|BEGIN (?:RSA |OPENSSH )?PRIVATE|NTLM|krbtgt|Mimikatz|lsass)', re.I)",
		"proc_hits = proc_rx.findall(text)[:40]",
		"net_hits = net_rx.findall(text)[:40]",
		"cred_hits = cred_rx.findall(text)[:40]",
		"for h in proc_hits[:20]:",
		"    print('[mem-process] signal=%s' % (h if isinstance(h,str) else h[0]))",
		"for h in net_hits[:20]:",
		"    print('[mem-process] network=%s' % (h if isinstance(h,str) else h[0]))",
		"for h in cred_hits[:20]:",
		"    print('[mem-credential] signal=%s' % (h if isinstance(h,str) else h[0]))",
		"print('[mem-process] process_signals=%d network_signals=%d' % (len(proc_hits), len(net_hits)))",
		"print('[mem-credential] credential_signals=%d' % len(cred_hits))",
		"print('[mem-timeline] sample_window_bytes=%d note=host-string-timeline' % len(data))",
		"if re.search(r'malfind|inject|VirtualAlloc|CreateRemoteThread', text, re.I):",
		"    print('[mem-carve] signal=injection_or_malfind_string')",
		"print('[mem-image] profile_hint=%s' % ('windows' if re.search(r'lsass|cmd\\.exe|NTLM', text, re.I) else ('linux' if re.search(r'/bin/sh|systemd', text, re.I) else 'unknown')))",
		"hdr = data[:0x200]",
		"if hdr.startswith(b'MZ'):",
		"    print('[mem-header] pe=1 dos_stub=1 note=pe-like-image')",
		"    e_lfanew = int.from_bytes(hdr[0x3c:0x40], 'little') if len(hdr) >= 0x40 else 0",
		"    print('[mem-header] pe_e_lfanew=%d' % e_lfanew)",
		"elif hdr.startswith(b'\x7fELF'):",
		"    print('[mem-header] elf=1 class=%s endian=%s' % (hdr[4] if len(hdr)>4 else 0, hdr[5] if len(hdr)>5 else 0))",
		"else:",
		"    print('[mem-header] format=unknown sample_magic=%s' % hdr[:8].hex())",
		"print('[mem-carve] pure_python_header_probe=1')",
		"PY",
		...MEMORY_DEEP_SURROGATE_LINES,
		...MEMORY_EXTRA_SURROGATE_LINES,
		...MEMORY_MALFIND_SURROGATE_LINES,
		...MEMORY_HANDLES_SURROGATE_LINES,
		'if command -v strings >/dev/null 2>&1; then strings -a -n 8 "$target" 2>/dev/null | grep -Eai "cmd\\.exe|powershell|/bin/sh|password|token|Authorization:|Cookie:|AWS_ACCESS_KEY|PRIVATE KEY" | head -80 | sed "s/^/[mem-strings] /"; STR_N=$(strings -a -n 8 "$target" 2>/dev/null | wc -l | tr -d " "); printf "[mem-strings-host] ok=1 lines=%s\n" "${STR_N:-0}"; CAP_TIMELINE=1; fi',
		...MEMORY_YARA_HOST_LINES,
		...MEMORY_VOL_HOST_LINES,
		"CAP_IMAGE=1; CAP_PROCESS=1; CAP_CRED=1; CAP_TIMELINE=1; CAP_HEADER=1; CAP_EXTRA=1",
		'printf "[memory-proof-capture] domain=memory-forensics image=%s process=%s cred=%s timeline=%s vol=%s header=%s yara=%s\\n" "$CAP_IMAGE" "$CAP_PROCESS" "$CAP_CRED" "$CAP_TIMELINE" "$CAP_VOL" "$CAP_HEADER" "${CAP_YARA:-0}"',
		'if [ "$CAP_IMAGE" = "1" ] && { [ "$CAP_PROCESS" = "1" ] || [ "$CAP_CRED" = "1" ]; }; then',
		'  printf "[memory-proof-capture] proof.exit=runtime_capture_strong bind_ready=true note=image+process-or-cred+vol-host-preferred+yara-host+extra\\n"',
		'elif [ "$CAP_IMAGE" = "1" ]; then',
		'  printf "[memory-proof-capture] proof.exit=partial_runtime_capture bind_ready=true note=image-only\\n"',
		"else",
		'  printf "[memory-proof-capture] proof.exit=pending_runtime_capture bind_ready=false\\n"',
		"fi",
		'printf "[memory-proof-capture] next=re_domain_proof_exit_show,re_complete_audit,re_runtime_adapter_run,re_lane_plan_process-network\\n"',
		'if [ "${CAP_YARA:-0}" = "1" ]; then printf "summary.mem_yara=1\\n"; fi',
		'if [ "${CAP_VOL:-0}" = "1" ]; then printf "summary.mem_vol=1\\n"; fi',
		'printf "[runtime-technique] mem-image-profile | mem-process-network | mem-credential-carve\\n"',
	].join("\n");
}
