/** Extra pure-python memory CAP without volatility3: pslist-ish, net, yara-lite, timestamps. */
export const MEMORY_EXTRA_SURROGATE_LINES = [
	"python3 - \"$target\" <<'PY'",
	"import collections, pathlib, re, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()[:16_000_000] if p.is_file() else b''",
	"text = data.decode('latin1', 'ignore')",
	"print('[mem-extra] path=%s bytes=%d' % (p, len(data)))",
	"procs = collections.Counter()",
	"# Windows image paths → basename.exe/dll/sys only",
	"for m in re.finditer(r'(?:[A-Za-z]:\\\\[^\\x00\\n]{0,180}\\\\)?([A-Za-z0-9_\\-]+\\.(?:exe|dll|sys))\\b', text, re.I):",
	"  procs[m.group(1).lower()] += 1",
	"# Linux absolute bins",
	"for m in re.finditer(r'/(?:bin|sbin|usr/bin|usr/sbin)/([A-Za-z0-9_\\-]+)\\b', text):",
	"  procs[m.group(1)] += 1",
	"# Common process tokens even without full path (memory string dumps)",
	"for name in ('lsass.exe','cmd.exe','powershell.exe','explorer.exe','services.exe','svchost.exe','csrss.exe','winlogon.exe','bash','sshd','systemd','busybox','python3','node'):",
	"  if re.search(r'\\b' + re.escape(name) + r'\\b', text, re.I):",
	"    procs[name.lower()] += max(1, text.lower().count(name.lower()))",
	"for name, hits in procs.most_common(24):",
	"  print('[mem-pslist] name=%s hits=%d' % (name, hits))",
	"print('[mem-pslist] unique=%d' % len(procs))",
	"win_n = sum(1 for n in procs if str(n).endswith(('.exe','.dll','.sys')))",
	"lin_n = sum(1 for n in procs if not str(n).endswith(('.exe','.dll','.sys')))",
	"if win_n:",
	"  print('[mem-pslist-surrogate] windows_pslist=1 pure_python=1 count=%d' % win_n)",
	"  print('summary.mem_windows_pslist_surrogate=1')",
	"  # Alias for host-vol line readers that only look for windows_pslist=N (honest pure path)",
	"  print('[mem-vol] pure_python_pslist windows_pslist=%d linux_pslist=%d note=not_vol_dump' % (win_n, lin_n))",
	"if lin_n:",
	"  print('[mem-pslist-surrogate] linux_pslist=1 pure_python=1 count=%d' % lin_n)",
	"  print('summary.mem_linux_pslist_surrogate=1')",
	"  if not win_n:",
	"    print('[mem-vol] pure_python_pslist windows_pslist=0 linux_pslist=%d note=not_vol_dump' % lin_n)",
	"print('[mem-pslist-surrogate] note=pure_python_path_scan_not_vol_dump')",
	"ips = collections.Counter(re.findall(r'\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b', text))",
	"urls = [u.rstrip('\x00') for u in re.findall(r'https?://[w./:?#&=%+-]{4,120}', text, re.I)[:20]]",
	"for ip, hits in ips.most_common(12):",
	"  if ip.startswith('0.') or ip.startswith('255.'): continue",
	"  print('[mem-net] ip=%s hits=%d' % (ip, hits))",
	"for u in urls[:10]:",
	"  print('[mem-net] url=%s' % u[:160])",
	"print('[mem-net] ip_unique=%d url_hits=%d' % (len(ips), len(urls)))",
	"rules = {",
	"  'cred_dump': r'mimikatz|sekurlsa|lsass\\.exe|wdigest|kerberos|NtlmShared',",
	"  'inject': r'VirtualAllocEx|WriteProcessMemory|CreateRemoteThread|NtMapViewOfSection|QueueUserAPC',",
	"  'persist': r'CurrentVersion\\\\Run|schtasks|systemd|LaunchAgent|crontab',",
	"  'c2': r'User-Agent:|beacon|cobalt|meterpreter|https?://',",
	"  'crypto': r'CryptEncrypt|BCrypt|AES|RC4|RSA|CryptoAPI',",
	"}",
	"hit_rules=[]",
	"for name, pat in rules.items():",
	"  hits = re.findall(pat, text, re.I)[:8]",
	"  if hits:",
	"    hit_rules.append(name)",
	"    print('[mem-yara-lite] rule=%s hits=%d sample=%s' % (name, len(hits), str(hits[0])[:80]))",
	"print('[mem-yara-lite] matched=%d list=%s' % (len(hit_rules), ','.join(hit_rules) or 'none'))",
	"iso = re.findall(r'20\\d{2}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}', text)[:20]",
	"for ts in iso[:10]:",
	"  print('[mem-timeline] iso=%s' % ts)",
	"pe_sig = b'PE' + bytes([0,0])",
	"if data[:2]==b'MZ' and len(data)>0x40:",
	"  e_lfanew=struct.unpack_from('<I', data, 0x3c)[0]",
	"  pe=e_lfanew",
	"  if 0<pe<len(data)-0x18 and data[pe:pe+4]==pe_sig:",
	"    ts=struct.unpack_from('<I', data, pe+8)[0]",
	"    print('[mem-timeline] pe_timestamp=%u' % ts)",
	"print('[mem-timeline] iso_hits=%d' % len(iso))",
	"if len(iso) > 0: print('summary.mem_iso=1')",
	"print('[mem-extra] ok=1 pslist=%d yara=%d net=%d' % (len(procs), len(hit_rules), len(ips)+len(urls)))",
	"PY",
] as const;
