/** Deeper pure-python memory image probe without volatility3. */

export const MEMORY_DEEP_SURROGATE_LINES = [
	"python3 - \"$target\" <<'PY'",
	"import pathlib, re, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()[:12_000_000] if p.is_file() else b''",
	"print('[mem-deep] path=%s bytes=%d' % (p, len(data)))",
	"pe_hits = []",
	"elf_hits = []",
	"pe_sig = b'PE' + bytes([0,0])",
	"elf_sig = bytes([0x7f,0x45,0x4c,0x46])",
	"limit = max(0, min(len(data) - 0x40, 4_000_000))",
	"i = 0",
	"while i < limit:",
	"  if data[i:i+2] == b'MZ':",
	"    try:",
	"      e_lfanew = struct.unpack_from('<I', data, i+0x3c)[0]",
	"      pe = i + e_lfanew",
	"      if 0 < e_lfanew < 0x1000 and pe+4 <= len(data) and data[pe:pe+4] == pe_sig:",
	"        pe_hits.append(i)",
	"        if len(pe_hits) <= 12:",
	"          print('[mem-module] pe_offset=0x%x e_lfanew=%d' % (i, e_lfanew))",
	"    except Exception:",
	"      pass",
	"  elif data[i:i+4] == elf_sig:",
	"    elf_hits.append(i)",
	"    if len(elf_hits) <= 12:",
	"      print('[mem-module] elf_offset=0x%x class=%s' % (i, data[i+4] if i+4 < len(data) else 0))",
	"  i += 0x20",
	"print('[mem-module] pe_headers=%d elf_headers=%d' % (len(pe_hits), len(elf_hits)))",
	"text = data.decode('latin1', 'ignore')",
	"for tag in re.findall(r'(?:Proc|Thre|File|Mutant|Driver|CM10|Pool)[A-Za-z0-9_\\-]{0,12}', text)[:40]:",
	"  print('[mem-pool] tag=%s' % tag[:40])",
	"procs = re.findall(r'C:\\\\Windows\\\\[\\w.\\-\\\\]+', text, re.I)[:30]",
	"for pr in procs[:20]:",
	"  print('[mem-process] path=%s' % pr[:160])",
	"print('[mem-process] path_hits=%d' % len(procs))",
	"if len(procs) > 0: print('summary.mem_path=1')",
	"if re.search(r'lsass\\.exe|services\\.exe|winlogon\\.exe|csrss\\.exe', text, re.I):",
	"  print('[mem-process] windows_system_procs=1')",
	"if re.search(r'/sbin/init|systemd|kthreadd', text):",
	"  print('[mem-process] linux_system_procs=1')",
	"print('[mem-deep] pure_python_module_scan=1 ok=1')",
	"PY",
] as const;
