/** Pure-python memory injection / malfind-ish surface CAP (not vol malfind). */
// Landmark: mem-malfind MZ PE RWX inject summary.mem_malfind pure_python

export const MEMORY_MALFIND_SURROGATE_LINES = [
	"python3 - \"$target\" <<'PY'",
	"import pathlib, re, struct, sys",
	"p = pathlib.Path(sys.argv[1])",
	"data = p.read_bytes()[:16_000_000] if p.is_file() else b''",
	"text = data.decode('latin1','ignore')",
	"print('[mem-malfind] path=%s bytes=%d pure_python=1' % (p, len(data)))",
	"# PE-in-memory candidates (MZ ... PE\\0\\0 within 1k)",
	"mz = 0; pe_ok = 0",
	"i = 0",
	"while True:",
	"  j = data.find(b'MZ', i)",
	"  if j < 0 or j + 0x40 > len(data): break",
	"  mz += 1",
	"  try:",
	"    e_lfanew = struct.unpack_from('<I', data, j + 0x3C)[0]",
	"    if 0 < e_lfanew < 0x800 and j + e_lfanew + 4 <= len(data) and data[j+e_lfanew:j+e_lfanew+4] == b'PE\\x00\\x00':",
	"      pe_ok += 1",
	"      print('[mem-malfind] pe_image offset=0x%x e_lfanew=0x%x' % (j, e_lfanew))",
	"  except Exception:",
	"    pass",
	"  i = j + 2",
	"  if mz >= 12: break",
	"print('[mem-malfind] mz_hits=%d pe_images=%d' % (mz, pe_ok))",
	"# injection / RWX strings",
	"rx = re.findall(r'PAGE_EXECUTE(?:_READWRITE|_WRITECOPY|_READ)?|MEM_COMMIT|VirtualAlloc(?:Ex)?|NtProtectVirtualMemory|WriteProcessMemory|CreateRemoteThread|QueueUserAPC', text, re.I)",
	"for s in sorted(set(rx))[:16]:",
	"  print('[mem-malfind] inject_api=%s' % s[:80])",
	"rwx = len(re.findall(r'PAGE_EXECUTE_READWRITE|RWX|EXECUTE_READWRITE', text, re.I))",
	"print('[mem-malfind] inject_api_hits=%d rwx_string_hits=%d' % (len(rx), rwx))",
	"ok = 1 if (pe_ok > 0 or len(rx) > 0 or rwx > 0) else 0",
	"print('[mem-malfind] ok=%d pure_python=1 note=not_vol_malfind' % ok)",
	"if ok:",
	"  print('summary.mem_malfind=1')",
	"PY",
] as const;
