/** Runtime adapter command templates: mobile. */

export function mobileRuntimeFallbackCommandTemplate(): string {
	return [
		"adapter-frida-mobile-hook-runner-fallback: target=<target>;",
		'printf "[mobile-target] target=%s exists=%s\\n" "$target" "$([ -e "$target" ] && echo yes || echo no)";',
		'if [ -f "$target" ]; then',
		'  file "$target" 2>/dev/null || true;',
		"  if command -v python3 >/dev/null 2>&1; then",
		"    python3 - \"$target\" <<'PY'",
		"import hashlib, os, plistlib, re, sys, zipfile",
		"path = sys.argv[1]",
		"def sha(raw): return hashlib.sha256(raw or b'').hexdigest()[:24]",
		"def clean(value, max_len=700): return re.sub(r'\\s+', ' ', str(value)).strip()[:max_len]",
		"anchor_re = re.compile(r'(Crypto|Cipher|MessageDigest|NSURLSession|OkHttp|KeyStore|Keychain|TrustManager|CertificatePinner|SecTrust|pinning|X509|HostnameVerifier|SSLSocketFactory)', re.I)",
		"pin_re = re.compile(r'(TrustManager|CertificatePinner|SecTrust|pinning|X509|HostnameVerifier|SSLSocketFactory)', re.I)",
		"def printable_strings(raw):",
		"    return [item.decode('latin1', 'replace') for item in re.findall(rb'[\\x20-\\x7e]{4,}', raw[:2_000_000])]",
		"def mobile_archive_kind(name):",
		"    if re.search(r'classes.*\\.dex$', name, re.I): return 'android-dex'",
		"    if re.search(r'AndroidManifest\\.xml$', name, re.I): return 'android-manifest'",
		"    if re.search(r'Info\\.plist$', name, re.I): return 'ios-plist'",
		"    if re.match(r'Payload/[^/]+\\.app/[^/]+$', name, re.I): return 'ios-app-binary'",
		"    if re.search(r'Payload/[^/]+\\.app/(?:Frameworks/)?[^/]+\\.framework/[^/]+$', name, re.I): return 'ios-framework-binary'",
		"    if re.search(r'Payload/[^/]+\\.app/.+\\.dylib$', name, re.I): return 'ios-dylib'",
		"    if re.search(r'\\.(?:so|jar)$', name, re.I): return 'android-native-or-jar'",
		"    return ''",
		"def mobile_candidate_names(names):",
		"    selected = []",
		"    for name in names:",
		"        if name.endswith('/'): continue",
		"        kind = mobile_archive_kind(name)",
		"        if kind and name not in selected:",
		"            selected.append(name)",
		"    return selected[:18]",
		"def plist_identity(raw, text):",
		"    bundle = executable = '<unknown>'",
		"    try:",
		"        parsed = plistlib.loads(raw)",
		"        if isinstance(parsed, dict):",
		"            bundle = clean(parsed.get('CFBundleIdentifier') or bundle, 240)",
		"            executable = clean(parsed.get('CFBundleExecutable') or executable, 240)",
		"    except Exception:",
		"        pair_re = re.compile(r'<key>(CFBundleIdentifier|CFBundleExecutable)</key>\\s*<string>([^<]+)</string>', re.I)",
		"        for key, value in pair_re.findall(text):",
		"            if key == 'CFBundleIdentifier': bundle = clean(value, 240)",
		"            if key == 'CFBundleExecutable': executable = clean(value, 240)",
		"    return bundle, executable",
		"try:",
		"    total_anchors = []",
		"    if zipfile.is_zipfile(path):",
		"        with zipfile.ZipFile(path) as archive:",
		"            names = archive.namelist()",
		"            for info in archive.infolist()[:240]:",
		"                name = info.filename",
		"                if re.search(r'(AndroidManifest\\.xml|Info\\.plist|classes.*\\.dex|\\.so$|\\.jar$|\\.framework/|Payload/)', name, re.I):",
		"                    print('[mobile-archive-entry] name=%s size=%d sha256=%s' % (clean(name), info.file_size, sha(name.encode())))",
		"            manifest_name = next((name for name in names if name.endswith('AndroidManifest.xml') or name.endswith('Info.plist')), None)",
		"            if manifest_name:",
		"                manifest = archive.read(manifest_name)",
		"                text = manifest.decode('latin1', 'replace')",
		"                package = (re.search(r'package=[\\\"\\']([^\\\"\\']+)', text) or [None, '<binary-or-unknown>'])[1]",
		"                if manifest_name.endswith('Info.plist'):",
		"                    bundle, executable = plist_identity(manifest, text)",
		"                    package = bundle",
		"                    print('[mobile-ios-info] name=%s bundle=%s executable=%s bytes=%d sha256=%s' % (manifest_name, clean(bundle), clean(executable), len(manifest), sha(manifest)))",
		"                print('[mobile-manifest] name=%s package=%s bytes=%d sha256=%s' % (manifest_name, clean(package), len(manifest), sha(manifest)))",
		"            for name in mobile_candidate_names(names):",
		"                raw = archive.read(name)",
		"                kind = mobile_archive_kind(name)",
		"                anchors = []",
		"                for item in printable_strings(raw):",
		"                    if anchor_re.search(item):",
		"                        anchors.append(item)",
		"                total_anchors.extend(anchors)",
		"                if kind == 'android-dex':",
		"                    print('[mobile-dex] name=%s bytes=%d anchors=%d sha256=%s' % (clean(name), len(raw), len(anchors), sha(raw)))",
		"                elif kind.startswith('ios-'):",
		"                    print('[mobile-ios-binary] kind=%s name=%s bytes=%d anchors=%d sha256=%s' % (kind, clean(name), len(raw), len(anchors), sha(raw)))",
		"                else:",
		"                    print('[mobile-artifact] kind=%s name=%s bytes=%d anchors=%d sha256=%s' % (kind or 'archive-entry', clean(name), len(raw), len(anchors), sha(raw)))",
		"                for item in anchors[:120]:",
		"                    print('[mobile-dex-string] name=%s value=%s' % (clean(name, 180), clean(item)))",
		"                    print('[mobile-artifact-string] kind=%s name=%s value=%s' % (kind or 'archive-entry', clean(name, 180), clean(item)))",
		"                for item in [item for item in anchors if pin_re.search(item)][:80]:",
		"                    print('[mobile-cert-pinning] name=%s anchor=%s' % (clean(name, 180), clean(item)))",
		"    else:",
		"        raw = open(path, 'rb').read(2_000_000)",
		"        anchors = [item for item in printable_strings(raw) if anchor_re.search(item)]",
		"        total_anchors.extend(anchors)",
		"        print('[mobile-raw-artifact] bytes=%d anchors=%d sha256=%s' % (len(raw), len(anchors), sha(raw)))",
		"        for item in anchors[:160]: print('[mobile-dex-string] value=%s' % clean(item))",
		"        for item in [item for item in anchors if pin_re.search(item)][:80]: print('[mobile-cert-pinning] anchor=%s' % clean(item))",
		"    print('[mobile-hook-surface] anchors=%d hook_contract=frida-java-objc-swift' % len(total_anchors))",
		"except Exception as error:",
		"    print('[mobile-parse-error] %s' % clean(error))",
		"PY",
		"  fi;",
		'  if command -v jadx >/dev/null 2>&1; then work="' +
			"$" +
			'{REPI_RUNTIME_ADAPTER_WORKDIR:-$HOME/.repi/agent/recon/runtime/adapter-jadx}"; rm -rf "$work"; mkdir -p "$work"; jadx -q -d "$work" "$target" >/dev/null 2>&1 || true; grep -R -I -n -E \'Cipher|MessageDigest|OkHttp|TrustManager|CertificatePinner|KeyStore|Keychain|SecTrust|pinning\' "$work" 2>/dev/null | sed \'s/^/[mobile-jadx-match] /\' | head -180 || true; fi;',
		"else",
		"  if command -v adb >/dev/null 2>&1; then printf '[mobile-package-runtime] package=%s transport=adb\\n' \"$target\"; adb shell pm path \"$target\" 2>/dev/null | sed 's/^/[mobile-adb-path] /' | head -20; adb shell dumpsys package \"$target\" 2>/dev/null | grep -E -i 'versionName|userId|permission|activity|service|provider|receiver|signatures' | sed 's/^/[mobile-adb-package] /' | head -180 || true; else echo \"[mobile-runtime-blocked] reason=adb_missing_and_target_not_file target=$target\"; fi;",
		"fi",
		'printf "[mobile-proof-capture] domain=mobile capture_signals=1 proof_exit=partial_runtime_capture bind_ready=true note=host-tool-dependent\\n";',
		'printf "[mobile-proof-capture] next=re_domain_proof_exit_show,re_complete_audit,re_runtime_adapter_run\\n";',
	].join("\n");
}
