/** Host web-authz CAP: curl Origin/Referer/CSRF header surface without browser. */
export function webAuthzHostShellLines(runTimeout: number): string[] {
	const t = Math.max(3, Math.floor(runTimeout));
	return [
		"# Host authz deepen: Origin/Referer/CSRF header matrix via curl (no browser)",
		'if command -v curl >/dev/null 2>&1 && [ -n "$URL" ]; then',
		'  printf "[web-authz-host] curl=%s url=%s\\n" "$(command -v curl)" "$URL"',
		'  HOST_PATH="${REPI_OBJECT_PATH:-/api/users/1}"',
		'  case "$HOST_PATH" in http*|HTTP*) HOST_URL="$HOST_PATH" ;; *)',
		'    HOST_URL=$(node -e \'try{const u=new URL(process.argv[1], process.argv[2]); process.stdout.write(u.toString())}catch(e){process.stdout.write(process.argv[2].replace(/\\/$/,"")+process.argv[1])}\' "$HOST_PATH" "$URL" 2>/dev/null || echo "${URL%/}$HOST_PATH")',
		"  ;; esac",
		'  printf "[web-authz-host] probe_url=%s\\n" "$HOST_URL"',
		`  BASE=$(timeout ${t}s curl -sS -o /tmp/repi-authz-host-base.body -w "%{http_code}|%{size_download}" -X POST -H "Content-Type: application/json" -d "\${REPI_AUTHZ_DEEP_BODY:-{}}" "$HOST_URL" 2>/dev/null || echo "000|0")`,
		'  printf "[web-authz-host-csrf] mode=no-origin status_size=%s\\n" "$BASE"',
		`  ORIG=$(timeout ${t}s curl -sS -o /tmp/repi-authz-host-origin.body -w "%{http_code}|%{size_download}" -X POST -H "Content-Type: application/json" -H "Origin: https://evil.example" -H "Referer: https://evil.example/csrf" -d "\${REPI_AUTHZ_DEEP_BODY:-{}}" "$HOST_URL" 2>/dev/null || echo "000|0")`,
		'  printf "[web-authz-host-csrf] mode=evil-origin status_size=%s\\n" "$ORIG"',
		`  MATCH=$(timeout ${t}s curl -sS -o /tmp/repi-authz-host-match.body -w "%{http_code}|%{size_download}" -X POST -H "Content-Type: application/json" -H "Origin: $URL" -H "Referer: $URL" -d "\${REPI_AUTHZ_DEEP_BODY:-{}}" "$HOST_URL" 2>/dev/null || echo "000|0")`,
		'  printf "[web-authz-host-csrf] mode=match-origin status_size=%s\\n" "$MATCH"',
		`  PRE=$(timeout ${t}s curl -sS -o /dev/null -D /tmp/repi-authz-host-pre.hdr -w "%{http_code}" -X OPTIONS -H "Origin: https://evil.example" -H "Access-Control-Request-Method: POST" "$HOST_URL" 2>/dev/null || echo 000)`,
		'  printf "[web-authz-host-cors] preflight_status=%s\\n" "$PRE"',
		"  if [ -f /tmp/repi-authz-host-pre.hdr ]; then",
		'    grep -iE "access-control-allow-origin|access-control-allow-methods|access-control-allow-credentials|vary:" /tmp/repi-authz-host-pre.hdr 2>/dev/null | head -20 | sed "s/^/[web-authz-host-cors] /"',
		"  fi",
		'  if [ -n "${COOKIE_A:-}" ]; then',
		`    CA=$(timeout ${t}s curl -sS -o /tmp/repi-authz-host-ca.body -w "%{http_code}|%{size_download}" -X GET -H "Cookie: $COOKIE_A" "$HOST_URL" 2>/dev/null || echo "000|0")`,
		'  printf "[web-authz-host-cookie] principal=A status_size=%s\\n" "$CA"',
		"  fi",
		'  if [ -n "${COOKIE_B:-}" ]; then',
		`    CB=$(timeout ${t}s curl -sS -o /tmp/repi-authz-host-cb.body -w "%{http_code}|%{size_download}" -X GET -H "Cookie: $COOKIE_B" "$HOST_URL" 2>/dev/null || echo "000|0")`,
		'    printf "[web-authz-host-cookie] principal=B status_size=%s\\n" "$CB"',
		"  fi",
		'  if [ "$BASE" = "$ORIG" ] && [ "${BASE%%|*}" != "000" ]; then',
		'    printf "[web-authz-host-csrf] gap=1 note=evil_origin_same_as_baseline\\n"',
		"  else",
		'    printf "[web-authz-host-csrf] gap=0\\n"',
		"  fi",
		'  printf "[web-authz-host] ok=1 csrf=1 cors=1\\n"',
		"else",
		'  printf "[web-authz-host] ok=0 note=curl_or_url_missing\\n"',
		"fi",
	];
}
