/** Playwright security-header + form/cookie surface CAP fragment. */

export function liveBrowserPlaywrightSecFragment(): string {
	return [
		"  // security headers + form/cookie surface",
		"  try {",
		"    const sec = await page.evaluate(() => {",
		"      const meta = Array.from(document.querySelectorAll('meta[http-equiv],meta[name]')).map((el) => ({",
		"        httpEquiv: el.getAttribute('http-equiv') || '',",
		"        name: el.getAttribute('name') || '',",
		"        content: (el.getAttribute('content') || '').slice(0, 160),",
		"      })).filter((m) => /csp|content-security|x-frame|referrer|permissions-policy|xss/i.test(m.httpEquiv + m.name + m.content));",
		"      const forms = Array.from(document.forms).slice(0, 12).map((f) => ({",
		"        action: String(f.action || '').slice(0, 200),",
		"        method: String(f.method || 'get').toLowerCase(),",
		"        inputs: Array.from(f.querySelectorAll('input,select,textarea')).slice(0, 20).map((i) => ({",
		"          name: i.getAttribute('name') || i.getAttribute('id') || '',",
		"          type: i.getAttribute('type') || i.tagName.toLowerCase(),",
		"          autocomplete: i.getAttribute('autocomplete') || '',",
		"        })),",
		"      }));",
		"      const links = Array.from(document.querySelectorAll('a[href]')).map((a) => a.getAttribute('href') || '').filter((h) => /login|logout|admin|api|auth|oauth|jwt|token/i.test(h)).slice(0, 20);",
		"      const mixed = Array.from(document.querySelectorAll('script[src],img[src],iframe[src],link[href]')).map((el) => el.getAttribute('src') || el.getAttribute('href') || '').filter((u) => /^http:\\/\\//i.test(u)).slice(0, 12);",
		"      return { meta, forms, links, mixed, cookie: document.cookie || '', origin: location.origin, title: document.title || '', protocol: location.protocol };",
		"    });",
		"    console.log('[browser-sec] origin=' + String(sec.origin || '').slice(0, 200) + ' title=' + String(sec.title || '').slice(0, 120));",
		"    for (const m of (sec.meta || []).slice(0, 12)) {",
		"      console.log('[browser-sec-meta] name=' + (m.name || m.httpEquiv || '?') + ' content=' + String(m.content || '').slice(0, 160));",
		"    }",
		"    for (const f of (sec.forms || []).slice(0, 8)) {",
		"      console.log('[browser-sec-form] method=' + f.method + ' action=' + String(f.action || '').slice(0, 200) + ' inputs=' + (f.inputs || []).length);",
		"      for (const i of (f.inputs || []).slice(0, 8)) {",
		"        console.log('[browser-sec-input] name=' + String(i.name || '').slice(0, 80) + ' type=' + String(i.type || '') + ' autocomplete=' + String(i.autocomplete || ''));",
		"      }",
		"    }",
		"    for (const h of (sec.links || []).slice(0, 12)) console.log('[browser-sec-link] href=' + String(h).slice(0, 200));",
		"    for (const u of (sec.mixed || []).slice(0, 8)) console.log('[browser-sec-mixed] url=' + String(u).slice(0, 200));",
		"    if (sec.cookie) console.log('[browser-sec-cookie] present=1 sample=' + String(sec.cookie).slice(0, 120));",
		"    console.log('[browser-sec] ok=1 meta=' + ((sec.meta || []).length) + ' forms=' + ((sec.forms || []).length) + ' links=' + ((sec.links || []).length) + ' mixed=' + ((sec.mixed || []).length));",
		"  } catch (e) {",
		"    console.log('[browser-sec] failed=' + String(e && e.message || e).slice(0, 160));",
		"  }",
		"  // response security headers from last main document if available",
		"  try {",
		"    const headers = await page.evaluate(async () => {",
		"      try {",
		"        const res = await fetch(location.href, { credentials: 'include', cache: 'no-store' });",
		"        const interesting = ['content-security-policy','x-frame-options','x-content-type-options','strict-transport-security','referrer-policy','permissions-policy','access-control-allow-origin','cross-origin-opener-policy','cross-origin-resource-policy','set-cookie'];",
		"        const out = {};",
		"        for (const k of interesting) {",
		"          const v = res.headers.get(k);",
		"          if (v) out[k] = String(v).slice(0, 200);",
		"        }",
		"        return { status: res.status, headers: out, cookieDoc: document.cookie || '' };",
		"      } catch (e) { return { error: String(e && e.message || e) }; }",
		"    });",
		"    if (headers && headers.headers) {",
		"      const present = Object.keys(headers.headers);",
		"      for (const [k, v] of Object.entries(headers.headers)) {",
		"        console.log('[browser-sec-header] name=' + k + ' value=' + String(v).slice(0, 200));",
		"      }",
		"      const expected = ['content-security-policy','x-frame-options','x-content-type-options','referrer-policy'];",
		"      const missing = expected.filter((k) => !present.includes(k));",
		"      for (const k of missing) console.log('[browser-sec-header-missing] name=' + k);",
		"      if (missing.length === 0) console.log('[browser-sec-header-missing] name=none count=0');",
		"      console.log('[browser-sec-header] ok=1 status=' + (headers.status || 0) + ' count=' + present.length + ' missing=' + missing.length);",
		"      console.log('[browser-sec-score] headers_present=' + present.length + ' headers_missing=' + missing.length + ' score=' + Math.max(0, 100 - missing.length * 20));",
		"      if (headers.headers['set-cookie'] || headers.cookieDoc) capture.cookies = 1;",
		"      // cookie flag surface from Set-Cookie (response) + document.cookie names",
		"      try {",
		"        const rawSet = String(headers.headers['set-cookie'] || '');",
		"        const parts = rawSet ? rawSet.split(/,(?=s*[^;=]+=)/) : [];",
		"        let httponly=0, secure=0, samesite=0, lax=0, strict=0, none=0;",
		"        for (const p of parts) {",
		"          const low = p.toLowerCase();",
		"          if (low.includes('httponly')) httponly++;",
		"          if (/(?:^|;s*)secure(?:;|$)/i.test(p)) secure++;",
		"          if (low.includes('samesite')) {",
		"            samesite++;",
		"            if (low.includes('samesite=lax')) lax++;",
		"            if (low.includes('samesite=strict')) strict++;",
		"            if (low.includes('samesite=none')) none++;",
		"          }",
		"          const name = String(p.split('=')[0] || '').trim();",
		"          if (name) console.log('[browser-cookie-flags] name=' + name.slice(0,80) + ' httponly=' + Number(low.includes('httponly')) + ' secure=' + Number(/(?:^|;s*)secure(?:;|$)/i.test(p)) + ' samesite=' + ((low.match(/samesite=([^;s]+)/)||[])[1]||'absent'));",
		"        }",
		"        const docNames = String(headers.cookieDoc||'').split(';').map((x)=>x.trim().split('=')[0]).filter(Boolean);",
		"        console.log('[browser-cookie-flags] summary set_cookie_n=' + parts.length + ' httponly=' + httponly + ' secure=' + secure + ' samesite=' + samesite + ' doc_n=' + docNames.length);",
		"        if (parts.length || docNames.length) { console.log('summary.browser_cookie_flags=1'); }",
		"      } catch (ce) { console.log('[browser-cookie-flags] err=' + String(ce && ce.message || ce).slice(0,100)); }",
		"    } else {",
		"      console.log('[browser-sec-header] skipped=' + String(headers && headers.error || 'none'));",
		"    }",
		"  } catch (e) {",
		"    console.log('[browser-sec-header] failed=' + String(e && e.message || e).slice(0, 120));",
		"  }",
	].join("\n");
}
