/** Playwright deep CAP fragment: websocket probe + sourcemap follow + har-lite. */
// Landmark: browser-websocket-probe browser-sourcemap browser-har-lite browser-deep

export function liveBrowserPlaywrightDeepFragment(): string {
	return `${[
		"  // deep: open websocket if page advertises one, else probe same-origin /ws",
		"  try {",
		"    const wsProbe = await page.evaluate(async () => {",
		"      const found = [];",
		"      const html = document.documentElement.outerHTML;",
		"      const m = html.match(/wss?:\\/\\/[^\\\"'\\s]+/gi) || [];",
		"      for (const u of m.slice(0, 4)) found.push(u);",
		"      const inline = /new\\s+WebSocket\\s*\\(/i.test(html);",
		"      return { found, inline, origin: location.origin };",
		"    });",
		"    let wsUrl = (wsProbe.found && wsProbe.found[0]) || (wsProbe.origin ? wsProbe.origin.replace(/^http/, 'ws') + '/ws' : '');",
		"    if (wsUrl) {",
		"      console.log('[browser-websocket-probe] url=' + String(wsUrl).slice(0, 300) + ' inline=' + Number(!!wsProbe.inline));",
		"      try {",
		"        await page.evaluate(async (u) => {",
		"          await new Promise((resolve) => {",
		"            let done = false;",
		"            const finish = (msg) => { if (done) return; done = true; console.log('[browser-ws-page]', msg); resolve(null); };",
		"            try {",
		"              const ws = new WebSocket(u);",
		"              const t = setTimeout(() => finish('timeout'), 1500);",
		"              ws.onopen = () => { try { ws.send('repi-ws-ping'); } catch (_) {} console.log('[browser-ws-frame-out] bytes=12 head=repi-ws-ping'); finish('open'); clearTimeout(t); };",
		"              ws.onmessage = (ev) => { const d = String(ev.data || ''); console.log('[browser-ws-frame-in] bytes=' + d.length + ' head=' + d.slice(0, 180)); finish('message:' + d.slice(0, 80)); clearTimeout(t); };",
		"              ws.onerror = () => { finish('error'); clearTimeout(t); };",
		"              ws.onclose = () => { finish('close'); clearTimeout(t); };",
		"            } catch (e) { finish('throw:' + String(e && e.message || e)); }",
		"          });",
		"        }, wsUrl);",
		"        capture.websocket = 1;",
		"        console.log('[browser-websocket] url=' + String(wsUrl).slice(0, 300));",
		"        await page.waitForTimeout(800);",
		"        console.log('[browser-ws-settle] ms=800');",
		"      } catch (e) {",
		"        console.log('[browser-websocket-probe] failed=' + String(e && e.message || e).slice(0, 120));",
		"      }",
		"    } else {",
		"      console.log('[browser-websocket-probe] none');",
		"    }",
		"  } catch (e) {",
		"    console.log('[browser-websocket-probe] skipped=' + String(e && e.message || e).slice(0, 120));",
		"  }",
		"  // deep: follow sourceMappingURL from scripts",
		"  try {",
		"    const maps = await page.evaluate(() => {",
		"      const out = [];",
		"      for (const s of Array.from(document.scripts).slice(0, 20)) {",
		"        const t = s.src ? '' : (s.textContent || '');",
		"        const m = (t.match(/sourceMappingURL\\s*=\\s*(\\S+)/) || [])[1];",
		"        if (m) out.push({ kind: 'inline', map: m.replace(/\\*\\/$/, '') });",
		"        if (s.src) out.push({ kind: 'src', url: s.src });",
		"      }",
		"      return out.slice(0, 12);",
		"    });",
		"    for (const item of maps) {",
		"      if (item.kind === 'inline' && item.map) {",
		"        if (String(item.map).startsWith('data:')) { capture.sourcemap = 1; console.log('[browser-sourcemap] inline=1'); continue; }",
		"        try {",
		"          const abs = new URL(item.map, url).toString();",
		"          const res = await page.request.get(abs);",
		"          if (res.ok()) { capture.sourcemap = 1; console.log('[browser-sourcemap] url=' + abs.slice(0, 300)); }",
		"        } catch (_) {}",
		"      }",
		"      if (item.kind === 'src' && item.url) {",
		"        try {",
		"          const res = await page.request.get(item.url);",
		"          const body = await res.text();",
		"          const m = (body.match(/sourceMappingURL\\s*=\\s*(\\S+)/) || [])[1];",
		"          if (m) {",
		"            const abs = new URL(m.replace(/\\*\\/$/, ''), item.url).toString();",
		"            const r2 = await page.request.get(abs);",
		"            if (r2.ok()) { capture.sourcemap = 1; console.log('[browser-sourcemap] url=' + abs.slice(0, 300)); }",
		"          }",
		"        } catch (_) {}",
		"      }",
		"    }",
		"  } catch (e) {",
		"    console.log('[browser-sourcemap] deep_skipped=' + String(e && e.message || e).slice(0, 120));",
		"  }",
		"  // har-lite: resource summary from performance entries",
		"  try {",
		"    const har = await page.evaluate(() => {",
		"      const entries = (performance.getEntriesByType && performance.getEntriesByType('resource')) || [];",
		"      const rows = Array.from(entries).slice(0, 40).map((e) => ({ name: String(e.name||'').slice(0,180), type: e.initiatorType||'', dur: Math.round(e.duration||0), size: (e.transferSize||e.encodedBodySize||0) }));",
		"      return { count: entries.length, rows };",
		"    });",
		"    console.log('[browser-har-lite] resources=' + (har.count||0));",
		"    for (const r of (har.rows||[]).slice(0, 12)) {",
		"      console.log('[browser-har-lite] type=' + r.type + ' dur_ms=' + r.dur + ' size=' + r.size + ' url=' + r.name);",
		"    }",
		"    if ((har.count||0) > 0) { console.log('summary.browser_har_lite=1'); }",
		"  } catch (e) {",
		"    console.log('[browser-har-lite] skipped=' + String(e && e.message || e).slice(0, 120));",
		"  }",
		"  try {",
		"    console.log('[browser-deep] forms=' + (storage.forms ? storage.forms.length : 0) + ' links=' + (storage.links ? storage.links.length : 0) + ' scripts=' + (storage.scripts ? storage.scripts.length : 0));",
		"    console.log('[browser-deep] ok=1 websocket=' + capture.websocket + ' sourcemap=' + capture.sourcemap + ' storage=' + capture.storage);",
		"  } catch (_) {}",
	].join("\n")}\n`;
}
