/** Playwright launch/require boot fragment. */
export function liveBrowserPlaywrightBootFragment(): string {
	return `${[
		"async function playwrightCapture() {",
		"  let playwright;",
		"  try {",
		"    const { createRequire } = await import('node:module');",
		"    const { pathToFileURL } = await import('node:url');",
		"    const reqFrom = (base) => {",
		"      try { return createRequire(base); } catch { return null; }",
		"    };",
		"    const bases = [",
		"      import.meta.url,",
		"      process.cwd() + '/package.json',",
		"      '/usr/lib/node_modules/playwright-core/package.json',",
		"      '/usr/lib/node_modules/playwright/package.json',",
		"      '/usr/local/lib/node_modules/playwright-core/package.json',",
		"      '/usr/local/lib/node_modules/playwright/package.json',",
		"      (process.env.HOME || '') + '/.npm-global/lib/node_modules/playwright-core/package.json',",
		"      (process.env.HOME || '') + '/.npm-global/lib/node_modules/playwright/package.json',",
		"    ];",
		"    const names = ['playwright-core', 'playwright'];",
		"    let loaded = null;",
		"    let loadedFrom = '';",
		"    for (const base of bases) {",
		"      if (!base) continue;",
		"      const req = reqFrom(base);",
		"      if (!req) continue;",
		"      for (const name of names) {",
		"        try {",
		"          loaded = req(name);",
		"          loadedFrom = name + '@' + base;",
		"          break;",
		"        } catch {}",
		"      }",
		"      if (loaded) break;",
		"    }",
		"    if (!loaded) {",
		"      for (const name of names) {",
		"        try { loaded = await import(name); loadedFrom = 'import:' + name; break; } catch {}",
		"      }",
		"    }",
		"    playwright = loaded && (loaded.chromium ? loaded : loaded.default);",
		"    if (!playwright || !playwright.chromium) {",
		"      console.log('[browser-engine] playwright=no reason=chromium-export-missing');",
		"      return false;",
		"    }",
		"    console.log('[browser-engine] playwright=yes source=' + loadedFrom);",
		"  } catch (error) {",
		"    console.log('[browser-engine] playwright=no reason=' + String(error && error.message || error).slice(0, 180));",
		"    return false;",
		"  }",
		"  const execCandidates = [",
		"    process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,",
		"    process.env.CHROMIUM_PATH,",
		"    '/usr/bin/chromium-browser',",
		"    '/usr/bin/chromium',",
		"    '/usr/bin/google-chrome',",
		"    '/usr/bin/google-chrome-stable',",
		"  ].filter(Boolean);",
		"  let executablePath;",
		"  for (const c of execCandidates) {",
		"    try {",
		"      const { accessSync, constants } = await import('node:fs');",
		"      accessSync(c, constants.X_OK);",
		"      executablePath = c;",
		"      break;",
		"    } catch {}",
		"  }",
		"  const launchOpts = { headless: true };",
		"  if (executablePath) {",
		"    launchOpts.executablePath = executablePath;",
		"    console.log('[browser-engine] chromium_executable=' + executablePath);",
		"  }",
		"  let browser;",
		"  try {",
		"    browser = await playwright.chromium.launch(launchOpts);",
		"  } catch (error) {",
		"    console.log('[browser-engine] playwright-launch-failed ' + String(error && error.message || error).slice(0, 240));",
		"    return false;",
		"  }",
	].join("\n")}\n`;
}
