/** Live browser playwright capture function body (injected into node script). */
import { liveBrowserPlaywrightBootFragment } from "./browser-capture-playwright-boot.ts";
import { liveBrowserPlaywrightDeepFragment } from "./browser-capture-playwright-deep.ts";
import { liveBrowserPlaywrightSecFragment } from "./browser-capture-playwright-sec.ts";
// Landmark: createRequire / playwrightCapture / executablePath live in boot+deep fragments.
// createRequire playwrightCapture executablePath chromium-browser browser-sec browser-sec-header

export function liveBrowserPlaywrightFunctionSource(): string {
	const rest = [
		"  const context = await browser.newContext({ ignoreHTTPSErrors: true });",
		"  const page = await context.newPage();",
		"  page.on('request', (request) => {",
		"    const u = request.url();",
		"    log('[browser-request]', { method: request.method(), url: u, resource: request.resourceType() });",
		"    if (/\\/api\\/|graphql|\\.json(\\?|$)/i.test(u) || request.resourceType() === 'xhr' || request.resourceType() === 'fetch') {",
		"      capture.api = 1;",
		"      console.log('[browser-xhr] method=' + request.method() + ' url=' + u.slice(0, 300));",
		"    }",
		"    if (/\\.map(\\?|$)/i.test(u)) { capture.sourcemap = 1; console.log('[browser-sourcemap] url=' + u.slice(0, 300)); }",
		"    if (request.resourceType() === 'script') { capture.scripts = 1; console.log('[browser-script] url=' + u.slice(0, 300)); }",
		"  });",
		"  page.on('response', (response) => {",
		"    log('[browser-response]', { status: response.status(), url: response.url(), content_type: response.headers()['content-type'] || '' });",
		"    capture.status = 1;",
		"    const sc = response.headers()['set-cookie'];",
		"    if (sc) { capture.cookies = 1; console.log('[browser-cookie] head=' + String(sc).slice(0, 180)); }",
		"  });",
		"  page.on('websocket', (ws) => {",
		"    capture.websocket = 1;",
		"    log('[browser-websocket]', { url: ws.url() });",
		"    console.log('[browser-websocket] url=' + String(ws.url()).slice(0, 300));",
		"    ws.on('framereceived', (frame) => {",
		"      const payload = String(frame.payload || '');",
		"      log('[browser-ws-frame-in]', { bytes: payload.length, head: payload.slice(0, 180) });",
		"      console.log('[browser-ws-frame-in] bytes=' + payload.length + ' head=' + payload.slice(0, 180));",
		"    });",
		"    ws.on('framesent', (frame) => {",
		"      const payload = String(frame.payload || '');",
		"      log('[browser-ws-frame-out]', { bytes: payload.length, head: payload.slice(0, 180) });",
		"      console.log('[browser-ws-frame-out] bytes=' + payload.length + ' head=' + payload.slice(0, 180));",
		"    });",
		"  });",
		"  const mainResp = await page.goto(url, { waitUntil: 'domcontentloaded', timeout });",
		"  capture.url = 1;",
		"  try {",
		"    const headers = mainResp ? mainResp.headers() : {};",
		"    // Playwright lowercases header names; set-cookie may be multi via headersArray",
		"    let setCookies = [];",
		"    if (mainResp && typeof mainResp.headersArray === 'function') {",
		"      const arr = await Promise.resolve(mainResp.headersArray());",
		"      if (Array.isArray(arr)) {",
		"        setCookies = arr.filter((h) => String(h && h.name || '').toLowerCase() === 'set-cookie').map((h) => h.value);",
		"      }",
		"    }",
		"    if (!setCookies.length && headers['set-cookie']) {",
		"      setCookies = Array.isArray(headers['set-cookie']) ? headers['set-cookie'] : [headers['set-cookie']];",
		"    }",
		"    let httponly=0, secure=0, samesite=0;",
		"    for (const p of setCookies) {",
		"      const low = String(p).toLowerCase();",
		"      if (low.includes('httponly')) httponly++;",
		"      if (/(?:^|;s*)secure(?:;|$)/i.test(p)) secure++;",
		"      const sm = (low.match(/samesite=([^;s]+)/)||[])[1] || 'absent';",
		"      if (sm !== 'absent') samesite++;",
		"      const name = String(p.split('=')[0]||'').trim();",
		"      console.log('[browser-cookie-flags] name=' + name.slice(0,80) + ' httponly=' + Number(low.includes('httponly')) + ' secure=' + Number(/(?:^|;s*)secure(?:;|$)/i.test(p)) + ' samesite=' + sm);",
		"    }",
		"    const jar = await context.cookies();",
		"    for (const c of jar.slice(0, 12)) {",
		"      console.log('[browser-cookie-jar] name=' + String(c.name||'').slice(0,80) + ' httpOnly=' + Number(!!c.httpOnly) + ' secure=' + Number(!!c.secure) + ' sameSite=' + String(c.sameSite||'None'));",
		"      if (c.httpOnly) httponly++;",
		"      if (c.secure) secure++;",
		"      if (c.sameSite && String(c.sameSite).toLowerCase() !== 'none') samesite++;",
		"    }",
		"    console.log('[browser-cookie-flags] summary set_cookie_n=' + setCookies.length + ' jar_n=' + jar.length + ' httponly=' + httponly + ' secure=' + secure + ' samesite=' + samesite);",
		"    if (setCookies.length || jar.length) { capture.cookies = 1; console.log('summary.browser_cookie_flags=1'); }",
		"  } catch (ce) { console.log('[browser-cookie-flags] err=' + String(ce && ce.message || ce).slice(0,120)); }",
		"  try { await page.waitForTimeout(250); } catch (_) {}",
		"  let storage = await page.evaluate(() => ({",
		"    href: location.href,",
		"    title: document.title,",
		"    cookies: document.cookie,",
		"    localStorage: Object.keys(localStorage).map((key) => [key, String(localStorage.getItem(key) || '').slice(0, 120)]),",
		"    sessionStorage: Object.keys(sessionStorage).map((key) => [key, String(sessionStorage.getItem(key) || '').slice(0, 120)]),",
		"    forms: Array.from(document.forms).map((form) => ({ action: form.action, method: form.method, inputs: Array.from(form.elements).map((el) => el.getAttribute('name') || el.id || el.tagName).slice(0, 20) })).slice(0, 12),",
		"    links: Array.from(document.links).map((a) => a.href).filter((href) => /api|graphql|admin|user|account|id=|uuid|token|auth/i.test(href)).slice(0, 40),",
		"    scripts: Array.from(document.scripts).map((s) => s.src || '[inline]').slice(0, 30),",
		"  }));",
		"  if (!(storage.localStorage && storage.localStorage.length) && !(storage.sessionStorage && storage.sessionStorage.length)) {",
		"    try { await page.waitForTimeout(400); } catch (_) {}",
		"    storage = await page.evaluate(() => ({",
		"      href: location.href,",
		"      title: document.title,",
		"      cookies: document.cookie,",
		"      localStorage: Object.keys(localStorage).map((key) => [key, String(localStorage.getItem(key) || '').slice(0, 120)]),",
		"      sessionStorage: Object.keys(sessionStorage).map((key) => [key, String(sessionStorage.getItem(key) || '').slice(0, 120)]),",
		"      forms: Array.from(document.forms).map((form) => ({ action: form.action, method: form.method, inputs: Array.from(form.elements).map((el) => el.getAttribute('name') || el.id || el.tagName).slice(0, 20) })).slice(0, 12),",
		"      links: Array.from(document.links).map((a) => a.href).filter((href) => /api|graphql|admin|user|account|id=|uuid|token|auth/i.test(href)).slice(0, 40),",
		"      scripts: Array.from(document.scripts).map((s) => s.src || '[inline]').slice(0, 30),",
		"    }));",
		"    console.log('[browser-storage-retry] local=' + (storage.localStorage||[]).length + ' session=' + (storage.sessionStorage||[]).length);",
		"  }",
		"  if (storage.cookies || (storage.localStorage && storage.localStorage.length) || (storage.sessionStorage && storage.sessionStorage.length)) {",
		"    capture.cookies = 1;",
		"    capture.storage = 1;",
		"  }",
		"  if (storage.scripts && storage.scripts.length) capture.scripts = 1;",
		"  console.log('[browser-storage] ' + JSON.stringify(storage).slice(0, 4000));",
		"  __DEEP__",
		"  console.log('[browser-status] page');",
		"  emitProofCapture('playwright');",
		"  await browser.close();",
		"  return true;",
		"}",
	].join("\n");
	return (
		liveBrowserPlaywrightBootFragment() +
		rest.replace("__DEEP__", `${liveBrowserPlaywrightDeepFragment()}\n${liveBrowserPlaywrightSecFragment()}`)
	);
}
