/** JS signing deep follow-up: fetch linked scripts + rebuild selfcheck. */
export function jsSigningScriptDeepBody(): string[] {
	return [
		"// deep: follow script src + rebuild selfcheck + secret-like tokens",
		"async function fetchText(url) {",
		"  const res = await fetch(url, { redirect: 'follow', headers: { 'User-Agent': 'REPI-js-signing/1.0' } });",
		"  const text = await res.text();",
		"  return { status: res.status, text, contentType: res.headers.get('content-type') || '' };",
		"}",
		"function scanJsText(text, label) {",
		"  if (/sourceMappingURL|\\.map\\b/i.test(text)) { signals.sourcemap = 1; log('[js-signing-sourcemap]', { label, signal: true }); }",
		"  if (/fetch\\s*\\(|XMLHttpRequest|WebSocket|axios/i.test(text)) { signals.hooks = 1; log('[repi-js-hook]', { label, observed: 'network-api' }); }",
		"  const cryptoHits = Array.from(text.matchAll(/crypto\\.subtle(?:\\.(?:digest|sign|verify|encrypt|decrypt|importKey|deriveKey))?|subtle\\.(?:digest|sign|verify|encrypt|decrypt|importKey|deriveKey)|createHmac|createHash|\\bHMAC\\b|SHA-?256|btoa\\s*\\(|atob\\s*\\(/gi)).map((m) => m[0]);",
		"  if (cryptoHits.length) {",
		"    signals.crypto = 1;",
		"    for (const op of cryptoHits.slice(0, 8)) observed.cryptoOps.push(op);",
		"    log('[js-signing-crypto]', { label, ops: cryptoHits.slice(0, 8).join(',') });",
		"  }",
		"  const secrets = Array.from(text.matchAll(/(?:api[_-]?key|secret|token|password|authorization)[^A-Za-z0-9]{0,6}([A-Za-z0-9_\\-/.+=]{8,})/gi)).map((m) => m[1]).slice(0, 8);",
		"  for (const s of secrets) log('[js-signing-secret]', { label, sample: String(s).slice(0, 40) });",
		"  if (secrets.length) { signals.hooks = Math.max(signals.hooks, 1); log('[js-signing-candidate]', { label, signal: 'secret-like', count: secrets.length }); }",
		"  if (/sign(ature)?|nonce|timestamp|hmac|sha256|signRequest|getSign/i.test(text)) log('[js-signing-candidate]', { label, signal: 'sign-like' });",
		"}",
		"if (/^https?:\\/\\//i.test(target)) {",
		"  try {",
		"    const page = await fetchText(target);",
		"    // If target is already a JS/JSON URL (not HTML), scan its body directly.",
		"    const ct = String(page.contentType || '').toLowerCase();",
		"    const looksJs = /javascript|ecmascript|json|text\\/plain/.test(ct) || /\\.m?js(\\?|$)/i.test(target) || (!/<html[\\s>]/i.test(page.text) && /(?:function|const|let|var|=>|export|import)\\b/.test(page.text));",
		"    if (looksJs) {",
		"      signals.scripts = 1;",
		"      log('[js-signing-script]', { url: target.slice(0, 200), status: page.status, bytes: page.text.length, direct: 1 });",
		"      scanJsText(page.text, target);",
		"      observed.hooks.push({ kind: 'script-direct', url: target, status: page.status, bytes: page.text.length, sha16: digest(page.text) });",
		"    }",
		"    const scripts = Array.from(page.text.matchAll(/<script[^>]+src=[\\\"']([^\\\"']+)[\\\"']/gi)).map((m) => m[1]).slice(0, 12);",
		"    for (const src of scripts) {",
		"      let abs = src;",
		"      try { abs = new URL(src, target).toString(); } catch {}",
		"      try {",
		"        const body = await fetchText(abs);",
		"        signals.scripts = 1;",
		"        log('[js-signing-script]', { url: abs.slice(0, 200), status: body.status, bytes: body.text.length });",
		"        scanJsText(body.text, abs);",
		"        observed.hooks.push({ kind: 'script', url: abs, status: body.status, bytes: body.text.length, sha16: digest(body.text) });",
		"      } catch (err) {",
		"        log('[js-signing-script]', { url: String(abs).slice(0, 200), error: String(err && err.message || err).slice(0, 120) });",
		"      }",
		"    }",
		"    const inlines = Array.from(page.text.matchAll(/<script\\b[^>]*>([\\s\\S]*?)<\\/script>/gi)).map((m) => m[1]).filter((t) => t && t.trim().length > 20).slice(0, 8);",
		"    for (let i = 0; i < inlines.length; i++) {",
		"      scanJsText(inlines[i], 'inline:' + i);",
		"      signals.scripts = 1;",
		"    }",
		"    // Also scan HTML document text for embedded secrets/comments.",
		"    if (!looksJs) scanJsText(page.text, target);",
		"  } catch (error) {",
		"    console.log('[js-signing-deep] follow_failed=' + String(error && error.message || error).slice(0, 160));",
		"  }",
		"}",
		"if (Array.isArray(observed.files) && observed.files.length) {",
		"  for (const file of observed.files.slice(0, 24)) {",
		"    try { scanJsText(readFileSync(file, 'utf8'), file); } catch {}",
		"  }",
		"}",
		"try {",
		"  const body = 'repi-js-signing-selfcheck';",
		"  const secret = process.env.REPI_SECRET || 'repi-dev-secret';",
		"  const h = crypto.createHmac('sha256', secret).update(body).digest('hex');",
		"  const s = crypto.createHash('sha256').update(body).digest('hex');",
		"  log('[repi-signing-rebuild]', { selfcheck: 1, sha256: s.slice(0, 16), hmac: h.slice(0, 16) });",
		"  log('[js-signing-crypto]', { selfcheck: 1, ops: 'createHmac,createHash,SHA-256' });",
		"  signals.crypto = 1;",
		"  signals.hooks = Math.max(signals.hooks, 1);",
		"  observed.cryptoOps.push('createHmac', 'createHash', 'SHA-256');",
		"  observed.cryptoOps = Array.from(new Set(observed.cryptoOps)).slice(0, 16);",
		"} catch (e) {",
		"  console.log('[js-signing-deep] selfcheck_failed=' + String(e && e.message || e).slice(0, 120));",
		"}",
		"console.log('[js-signing-deep] ok=1 crypto=' + signals.crypto + ' hooks=' + signals.hooks + ' scripts=' + signals.scripts + ' sourcemap=' + signals.sourcemap);",
	];
}
