/** Pure-python / node WASM module header CAP for JS reverse. */
// Landmark: js-signing-wasm \0asm summary.js_signing_wasm

export const JS_SIGNING_WASM_LINES = [
	"if command -v python3 >/dev/null 2>&1; then",
	"  python3 - \"${TARGET:-.}\" <<'PY'",
	"import pathlib, struct, sys",
	"root = pathlib.Path(sys.argv[1] if len(sys.argv)>1 else '.')",
	"paths=[]",
	"if root.is_file():",
	"  paths=[root]",
	"  for extra in list(root.parent.glob('*.wasm'))[:8]:",
	"    if extra not in paths: paths.append(extra)",
	"else:",
	"  paths=list(root.rglob('*.wasm'))[:20] + list(root.rglob('*.js'))[:30]",
	"# always include smoke companion if present",
	"for extra in (pathlib.Path('/tmp/repi-js-sign-sample.wasm'), pathlib.Path('/tmp/repi-js-sign-sample.js')):",
	"  if extra.exists() and extra not in paths: paths.append(extra)",
	"hits=0",
	"for p in paths:",
	"  try: data=p.read_bytes()[:2_000_000]",
	"  except Exception: continue",
	"  # WASM binary magic",
	"  if data[:4]==b'\\x00asm':",
	"    ver=struct.unpack_from('<I', data, 4)[0] if len(data)>=8 else -1",
	"    print('[js-signing-wasm] file=%s magic=00asm version=%d pure_python=1' % (p, ver))",
	"    # section headers: id(1)+len(leb) — print first few section ids",
	"    i=8; secs=[]",
	"    while i < min(len(data), 8+4096) and len(secs)<12:",
	"      sid=data[i]; i+=1",
	"      # leb128 u32",
	"      n=0; sh=0",
	"      while i < len(data):",
	"        b=data[i]; i+=1; n |= (b & 0x7f) << sh; sh += 7",
	"        if not (b & 0x80): break",
	"      secs.append(sid)",
	"      i += n",
	"    print('[js-signing-wasm] sections=%s' % ','.join(str(x) for x in secs))",
	"    hits+=1",
	"  # JS embedding of wasm base64/array",
	"  text=data.decode('latin1','ignore') if p.suffix.lower() in ('.js','.mjs','.ts','.html') else ''",
	"  if 'WebAssembly' in text or 'application/wasm' in text or '\\\\x00asm' in text or '00asm' in text:",
	"    print('[js-signing-wasm] file=%s signal=js_webassembly pure_python=1' % p)",
	"    hits+=1",
	"print('[js-signing-wasm] count=%d' % hits)",
	"if hits:",
	"  print('[js-signing-wasm] ok=1')",
	"  print('summary.js_signing_wasm=1')",
	"else:",
	"  print('[js-signing-wasm] ok=0 note=no_wasm_surface')",
	"PY",
	"fi",
] as const;
