/** JS signing extra CAP: JWT/token surface, alg inventory, verify selfcheck. */
export function jsSigningScriptExtraBody(): string[] {
	return [
		"// extra: JWT-ish tokens, alg inventory, HMAC verify selfcheck, sourcemap follow",
		"function scanTokenSurface(text, label) {",
		"  const jwt = Array.from(text.matchAll(/\\beyJ[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\b/g)).map((m) => m[0]).slice(0, 6);",
		"  for (const tok of jwt) {",
		"    try {",
		"      const [h, p] = tok.split('.');",
		"      const hdr = JSON.parse(Buffer.from(h.replace(/-/g,'+').replace(/_/g,'/'), 'base64').toString('utf8'));",
		"      const payload = JSON.parse(Buffer.from(p.replace(/-/g,'+').replace(/_/g,'/'), 'base64').toString('utf8'));",
		"      log('[js-signing-jwt]', { label, alg: hdr.alg || '?', typ: hdr.typ || '?', keys: Object.keys(payload).slice(0, 8).join(',') });",
		"      signals.crypto = 1;",
		"    } catch {",
		"      log('[js-signing-jwt]', { label, parse: 'partial', sample: tok.slice(0, 24) });",
		"    }",
		"  }",
		"  const algs = Array.from(text.matchAll(/\\b(HS256|HS384|HS512|RS256|RS384|RS512|ES256|ES384|ES512|PS256|EdDSA|SHA-?256|SHA-?384|SHA-?512)\\b/g)).map((m) => m[1]);",
		"  if (algs.length) {",
		"    const uniq = Array.from(new Set(algs)).slice(0, 12);",
		"    log('[js-signing-alg]', { label, algs: uniq.join(',') });",
		"    signals.crypto = 1;",
		"  }",
		"  // base64url blobs that look like signed envelopes",
		"  const b64 = Array.from(text.matchAll(/\\b[A-Za-z0-9_-]{24,}={0,2}\\b/g)).map((m) => m[0]).slice(0, 20);",
		"  let decoded = 0;",
		"  for (const blob of b64) {",
		"    try {",
		"      const raw = Buffer.from(blob.replace(/-/g,'+').replace(/_/g,'/'), 'base64').toString('utf8');",
		"      if (/sign|hmac|nonce|timestamp|secret|token/i.test(raw)) {",
		"        log('[js-signing-b64]', { label, sample: raw.slice(0, 80).replace(/\\s+/g, ' ') });",
		"        decoded += 1;",
		"      }",
		"    } catch {}",
		"  }",
		"  if (decoded) log('[js-signing-b64]', { label, decoded });",
		"}",
		"async function followSourceMaps(text, base) {",
		"  const maps = Array.from(text.matchAll(/sourceMappingURL\\s*=\\s*(\\S+)/g)).map((m) => m[1].replace(/\\*\\/$/, '').trim()).slice(0, 4);",
		"  for (const m of maps) {",
		"    if (m.startsWith('data:')) { log('[js-signing-sourcemap]', { label: base, inline: 1 }); continue; }",
		"    let abs = m;",
		"    try { abs = new URL(m, base || target).toString(); } catch {}",
		"    if (!/^https?:\\/\\//i.test(abs)) continue;",
		"    try {",
		"      const body = await fetchText(abs);",
		"      signals.sourcemap = 1;",
		"      log('[js-signing-sourcemap]', { label: abs.slice(0, 180), status: body.status, bytes: body.text.length });",
		'      if (/"sourcesContent"|"mappings"/.test(body.text)) log(\'[js-signing-sourcemap]\', { label: abs.slice(0, 120), parsed: 1 });',
		"      scanTokenSurface(body.text, abs);",
		"    } catch (err) {",
		"      log('[js-signing-sourcemap]', { label: String(abs).slice(0, 160), error: String(err && err.message || err).slice(0, 100) });",
		"    }",
		"  }",
		"}",
		"// apply token/alg scan to already observed file/script corpus",
		"if (Array.isArray(observed.files)) {",
		"  for (const file of observed.files.slice(0, 24)) {",
		"    try {",
		"      const text = readFileSync(file, 'utf8');",
		"      scanTokenSurface(text, file);",
		"      await followSourceMaps(text, file);",
		"    } catch {}",
		"  }",
		"}",
		"if (/^https?:\\/\\//i.test(target)) {",
		"  try {",
		"    const page = await fetchText(target);",
		"    scanTokenSurface(page.text, target);",
		"    await followSourceMaps(page.text, target);",
		"  } catch {}",
		"}",
		"// HMAC verify selfcheck (sign then verify equality)",
		"try {",
		"  const body = 'repi-js-signing-verify';",
		"  const secret = process.env.REPI_SECRET || 'repi-dev-secret';",
		"  const sig = crypto.createHmac('sha256', secret).update(body).digest('hex');",
		"  const again = crypto.createHmac('sha256', secret).update(body).digest('hex');",
		"  const ok = sig === again;",
		"  log('[js-signing-verify]', { selfcheck: 1, pass: ok ? 1 : 0, alg: 'HMAC-SHA256', sig16: sig.slice(0, 16) });",
		"  if (ok) { signals.crypto = 1; signals.hooks = Math.max(signals.hooks, 1); }",
		"} catch (e) {",
		"  console.log('[js-signing-extra] verify_failed=' + String(e && e.message || e).slice(0, 120));",
		"}",
		"console.log('[js-signing-extra] ok=1');",
	];
}
