/** JS signing URL/file scan fragment of embedded node script. */
export function jsSigningScriptScanBody(): string[] {
	return [
		"if (!target) {",
		"  console.log('[js-signing-blocked] reason=missing_target');",
		"} else if (/^https?:\\/\\//i.test(target)) {",
		"  signals.url = 1;",
		"  log('[js-signing-url]', { url: target });",
		"  try {",
		"    const res = await fetch(target, { redirect: 'follow', headers: { 'User-Agent': 'REPI-js-signing/1.0' } });",
		"    const text = await res.text();",
		"    log('[js-signing-fetch]', { status: res.status, bytes: text.length, content_type: res.headers.get('content-type') || '' });",
		"    const scripts = Array.from(text.matchAll(/<script[^>]+src=[\"']([^\"']+)[\"']/gi)).map((m) => m[1]).slice(0, 40);",
		"    if (scripts.length) { signals.scripts = 1; log('[js-signing-script]', { count: scripts.length, head: scripts.slice(0, 8).join(',') }); }",
		"    if (/sourceMappingURL|\\.map\\b/i.test(text)) { signals.sourcemap = 1; log('[js-signing-sourcemap]', { signal: true }); }",
		"    if (/crypto\\.subtle|createHmac|createHash|XMLHttpRequest|WebSocket|fetch\\s*\\(/i.test(text)) {",
		"      signals.hooks = 1;",
		"      log('[repi-js-hook]', { observed: 'inline-or-bundle-pattern', engine: 'fetch-html' });",
		"    }",
		"    const cryptoHits = Array.from(text.matchAll(/crypto\\.subtle(?:\\.(?:digest|sign|verify|encrypt|decrypt|importKey|deriveKey))?|subtle\\.(?:digest|sign|verify|encrypt|decrypt|importKey|deriveKey)|createHmac|createHash|\\bHMAC\\b|SHA-?256/gi)).map((m) => m[0]);",
		"    if (cryptoHits.length) {",
		"      signals.crypto = 1;",
		"      observed.cryptoOps = Array.from(new Set(cryptoHits)).slice(0, 12);",
		"      log('[js-signing-crypto]', { ops: observed.cryptoOps.join(',') });",
		"    }",
		"    const secrets = Array.from(text.matchAll(/(?:api[_-]?key|secret|token|password|authorization)[^A-Za-z0-9]{0,6}([A-Za-z0-9_\\-/.+=]{8,})/gi)).map((m) => m[1]).slice(0, 8);",
		"    for (const s of secrets) log('[js-signing-secret]', { label: target, sample: String(s).slice(0, 40) });",
		"    if (secrets.length) log('[js-signing-candidate]', { label: target, signal: 'secret-like', count: secrets.length });",
		"    // direct JS URL: count as scripts surface",
		"    if (/javascript|ecmascript|json/.test(String(res.headers.get('content-type') || '').toLowerCase()) || /\\.m?js(\\?|$)/i.test(target)) { signals.scripts = 1; }",
		"    observed.hooks.push({ kind: 'document', status: res.status, bytes: text.length, sha16: digest(text) });",
		"  } catch (error) {",
		"    console.log('[js-signing-blocked] reason=fetch_failed error=' + String(error && error.message || error).slice(0, 200));",
		"  }",
		"} else {",
		"  const files = walkJs(target);",
		"  observed.files = files.slice(0, 40);",
		"  if (!files.length) {",
		"    console.log('[js-signing-blocked] reason=no_js_files target=' + target);",
		"  } else {",
		"    signals.scripts = 1;",
		"    log('[js-signing-files]', { count: files.length, head: files.slice(0, 8).join(',') });",
		"    for (const file of files.slice(0, 24)) {",
		"      let text = '';",
		"      try { text = readFileSync(file, 'utf8'); } catch { continue; }",
		"      if (/\\.map$/i.test(file) || /sourceMappingURL/i.test(text)) { signals.sourcemap = 1; log('[js-signing-sourcemap]', { file }); }",
		"      if (/fetch\\s*\\(|XMLHttpRequest|WebSocket|axios/i.test(text)) {",
		"        signals.hooks = 1;",
		"        log('[repi-js-hook]', { file, observed: 'network-api' });",
		"      }",
		"      const cryptoHits = Array.from(text.matchAll(/crypto\\.subtle(?:\\.(?:digest|sign|verify|encrypt|decrypt|importKey|deriveKey))?|subtle\\.(?:digest|sign|verify|encrypt|decrypt|importKey|deriveKey)|createHmac|createHash|\\bHMAC\\b|SHA-?256/gi)).map((m) => m[0]);",
		"      if (cryptoHits.length) {",
		"        signals.crypto = 1;",
		"        for (const op of cryptoHits.slice(0, 6)) observed.cryptoOps.push(op);",
		"        log('[js-signing-crypto]', { file, ops: cryptoHits.slice(0, 6).join(',') });",
		"      }",
		"      if (/sign(ature)?|nonce|timestamp|hmac|sha256/i.test(text)) {",
		"        log('[js-signing-candidate]', { file, signal: 'sign-like' });",
		"      }",
		"    }",
		"    observed.cryptoOps = Array.from(new Set(observed.cryptoOps)).slice(0, 16);",
		"  }",
		"}",
	];
}
