/** Extra JS-signing pure-node CAP: JWT header/alg matrix + weak-secret selfcheck (ESM, uses prelude crypto). */
import { JS_SIGNING_JWT_CLAIMS_LINES } from "./js-signing-script-jwt-claims.ts";

/** Extra JS-signing pure-node CAP: JWT header/alg matrix + weak-secret selfcheck (ESM, uses prelude crypto). */

const JS_SIGNING_JWT_ALG_LINES: string[] = [
	`// [js-signing-jwt-deep] pure node jwt/alg surface (ESM; crypto from prelude)`,
	`(function(){`,
	`  function b64url(buf){return Buffer.from(buf).toString('base64').replace(/=+$/,'').replace(/\\+/g,'-').replace(/\\//g,'_');}`,
	`  function b64urlJson(obj){return b64url(JSON.stringify(obj));}`,
	`  function signHs(alg, secret, header, payload){`,
	`    var h=b64urlJson(header), p=b64urlJson(payload), data=h+'.'+p;`,
	`    var dig=alg==='HS512'?'sha512':alg==='HS384'?'sha384':'sha256';`,
	`    var sig=crypto.createHmac(dig, secret).update(data).digest();`,
	`    return data+'.'+b64url(sig);`,
	`  }`,
	`  function decodeParts(tok){`,
	`    var parts=String(tok||'').split('.');`,
	`    if(parts.length<2) return null;`,
	`    function dec(s){ try{ return JSON.parse(Buffer.from(s.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')); }catch(e){ return null; } }`,
	`    return {header:dec(parts[0]), payload:dec(parts[1]), sig:parts[2]||''};`,
	`  }`,
	`  var secrets=['secret','password','repi','123456','changeme'];`,
	`  var algs=['HS256','HS384','HS512','none'];`,
	`  var hits=[];`,
	`  for(var i=0;i<algs.length;i++){`,
	`    var alg=algs[i];`,
	`    if(alg==='none'){`,
	`      var noneTok=b64urlJson({alg:'none',typ:'JWT'})+'.'+b64urlJson({sub:'repi',role:'admin'})+'.';`,
	`      var d=decodeParts(noneTok);`,
	`      console.log('[js-signing-jwt] alg=none token='+noneTok.slice(0,80)+' header_alg='+(d&&d.header&&d.header.alg));`,
	`      hits.push('none');`,
	`      continue;`,
	`    }`,
	`    var tok=signHs(alg,'repi-secret',{alg:alg,typ:'JWT'},{sub:'repi',iat:1,role:'user'});`,
	`    var parts=decodeParts(tok);`,
	`    console.log('[js-signing-jwt] alg='+alg+' token_len='+tok.length+' header_alg='+(parts&&parts.header&&parts.header.alg)+' sub='+(parts&&parts.payload&&parts.payload.sub));`,
	`    for(var s=0;s<secrets.length;s++){`,
	`      var cand=signHs(alg, secrets[s], {alg:alg,typ:'JWT'}, {sub:'repi',iat:1,role:'user'});`,
	`      if(cand===tok){ console.log('[js-signing-jwt-weak] alg='+alg+' secret='+secrets[s]+' match=1'); hits.push(alg+':'+secrets[s]); }`,
	`    }`,
	`    var good=signHs(alg,'repi-secret',{alg:alg,typ:'JWT'},{sub:'repi',iat:1,role:'user'});`,
	`    console.log('[js-signing-jwt-verify] alg='+alg+' self='+(good===tok?1:0));`,
	`    hits.push(alg);`,
	`  }`,
	`  try{`,
	`    var confused=signHs('HS256','repi-secret',{alg:'RS256',typ:'JWT'},{sub:'repi',role:'admin'});`,
	`    var cd=decodeParts(confused);`,
	`    console.log('[js-signing-jwt-confusion] header_alg='+(cd&&cd.header&&cd.header.alg)+' signed_with=HS256 token_len='+confused.length);`,
	`    hits.push('confusion');`,
	`  }catch(e){ console.log('[js-signing-jwt-confusion] err='+e); }`,
	`  if(typeof signals!=='undefined'){ signals.crypto=1; signals.hooks=Math.max(signals.hooks||0,1); }`,
	`  console.log('[js-signing-jwt-deep] ok=1 algs='+hits.length);`,
	`})();`,
];

export const JS_SIGNING_JWT_DEEP_LINES: string[] = [...JS_SIGNING_JWT_ALG_LINES, ...JS_SIGNING_JWT_CLAIMS_LINES];
