/** JS SRI integrity attribute CAP. */
// Landmark: js-signing-sri integrity sha256 sha384 sha512 summary.js_signing_sri

export const JS_SIGNING_SRI_LINES = [
	"if command -v python3 >/dev/null 2>&1; then",
	"  python3 - \"${TARGET:-.}\" <<'PY'",
	"import pathlib, re, sys",
	"arg = sys.argv[1] if len(sys.argv) > 1 else '.'",
	"root = pathlib.Path(arg)",
	"pat = re.compile(r'integrity\\s*=\\s*[\\'\"](sha(?:256|384|512)-[A-Za-z0-9+/=]+)[\\'\"]', re.I)",
	"hits = []",
	"paths = []",
	"# Always include product smoke companion HTML (static + dual-path URL runs).",
	"for extra in (",
	"  pathlib.Path('/tmp/repi-js-sign-sample.html'),",
	"  pathlib.Path('/tmp/repi-js-sign-sample.js'),",
	"  pathlib.Path('/tmp/repi-js-sign-work-static'),",
	"  pathlib.Path('/tmp/repi-js-sign-work-url'),",
	"):",
	"  if extra.is_file() and extra not in paths: paths.append(extra)",
	"  if extra.is_dir():",
	"    for p in list(extra.rglob('*.html'))[:20] + list(extra.rglob('*.js'))[:20]:",
	"      if p not in paths: paths.append(p)",
	"if root.is_file():",
	"  if root not in paths: paths.append(root)",
	"  sib = root.with_suffix('.html')",
	"  if sib.exists() and sib not in paths: paths.append(sib)",
	"  idx = root.parent / 'index.html'",
	"  if idx.exists() and idx not in paths: paths.append(idx)",
	"elif root.is_dir():",
	"  for p in list(root.rglob('*.html'))[:40] + list(root.rglob('*.js'))[:40] + list(root.rglob('*.htm'))[:20]:",
	"    if p not in paths: paths.append(p)",
	"for p in paths:",
	"  try: text = p.read_text(errors='ignore')",
	"  except Exception: continue",
	"  for m in pat.finditer(text):",
	"    hits.append((str(p), m.group(1)[:80]))",
	"    print('[js-signing-sri] file=%s integrity=%s pure_python=1' % (p, m.group(1)[:80]))",
	"print('[js-signing-sri] count=%d paths=%d' % (len(hits), len(paths)))",
	"if hits:",
	"  print('summary.js_signing_sri=1')",
	"  print('[js-signing-sri] ok=1')",
	"else:",
	"  print('[js-signing-sri] ok=0 note=no_integrity_attrs')",
	"PY",
	"fi",
] as const;
