/** Extra JS-signing CAP: JWT kid/jku/x5u + exp/nbf claim surface (ESM). */

export const JS_SIGNING_JWT_CLAIMS_LINES: string[] = [
	`// [js-signing-jwt-claims] kid/jku/x5u + temporal claim surface`,
	`(function(){`,
	`  function b64url(buf){return Buffer.from(buf).toString('base64').replace(/=+$/,'').replace(/\\+/g,'-').replace(/\\//g,'_');}`,
	`  function b64urlJson(obj){return b64url(JSON.stringify(obj));}`,
	`  function signHs(secret, header, payload){`,
	`    var h=b64urlJson(header), p=b64urlJson(payload), data=h+'.'+p;`,
	`    var sig=crypto.createHmac('sha256', secret).update(data).digest();`,
	`    return data+'.'+b64url(sig);`,
	`  }`,
	`  function decodeParts(tok){`,
	`    var parts=String(tok||'').split('.');`,
	`    if(parts.length<2) return null;`,
	`    function dec(s){ try{ return JSON.parse(Buffer.from(s.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')); }catch(e){ return null; } }`,
	`    return {header:dec(parts[0]), payload:dec(parts[1]), sig:parts[2]||''};`,
	`  }`,
	`  var now=Math.floor(Date.now()/1000);`,
	`  var cases=[`,
	`    {name:'kid-present', header:{alg:'HS256',typ:'JWT',kid:'repi-key-1'}, payload:{sub:'repi',iat:now,role:'user'}},`,
	`    {name:'jku-injection', header:{alg:'HS256',typ:'JWT',jku:'https://evil.example/jwks.json'}, payload:{sub:'repi',iat:now}},`,
	`    {name:'x5u-injection', header:{alg:'HS256',typ:'JWT',x5u:'https://evil.example/cert.pem'}, payload:{sub:'repi',iat:now}},`,
	`    {name:'expired', header:{alg:'HS256',typ:'JWT'}, payload:{sub:'repi',iat:now-7200,exp:now-3600}},`,
	`    {name:'nbf-future', header:{alg:'HS256',typ:'JWT'}, payload:{sub:'repi',iat:now,nbf:now+3600}},`,
	`    {name:'admin-role', header:{alg:'HS256',typ:'JWT',kid:'admin'}, payload:{sub:'repi',role:'admin',iat:now}},`,
	`  ];`,
	`  var hits=[];`,
	`  for(var i=0;i<cases.length;i++){`,
	`    var c=cases[i];`,
	`    var tok=signHs('repi-secret', c.header, c.payload);`,
	`    var d=decodeParts(tok);`,
	`    var hdr=d&&d.header||{};`,
	`    var pay=d&&d.payload||{};`,
	`    console.log('[js-signing-jwt-claim] case='+c.name+' token_len='+tok.length+' kid='+(hdr.kid||'')+' jku='+(hdr.jku?'1':'0')+' x5u='+(hdr.x5u?'1':'0')+' exp='+(pay.exp||'')+' nbf='+(pay.nbf||'')+' role='+(pay.role||''));`,
	`    hits.push(c.name);`,
	`  }`,
	`  // accept expired/nbf without validation = weak consumer signal (self-documenting)`,
	`  var expired=signHs('repi-secret',{alg:'HS256',typ:'JWT'},{sub:'repi',exp:now-10});`,
	`  var ed=decodeParts(expired);`,
	`  var expiredOk=ed&&ed.payload&&ed.payload.exp&&ed.payload.exp<now;`,
	`  console.log('[js-signing-jwt-claim] expired_token_parse='+(expiredOk?1:0)+' note=consumer_must_reject');`,
	`  if(typeof signals!=='undefined'){ signals.crypto=1; signals.hooks=Math.max(signals.hooks||0,1); }`,
	`  console.log('[js-signing-jwt-claims] ok=1 cases='+hits.length);`,
	`})();`,
];
