/** JS signing embedded script helper fragments. */
export function jsSigningScriptPrelude(): string[] {
	return [
		"import crypto from 'node:crypto';",
		"import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';",
		"import { join } from 'node:path';",
		"const target = process.argv[2] || process.env.REPI_URL || process.env.REPI_JS_TARGET || '';",
		"const work = process.env.REPI_WORKDIR || (process.env.HOME + '/.repi/agent/recon/runtime/js-signing');",
		"try { mkdirSync(work, { recursive: true }); } catch {}",
		"function log(tag, obj) {",
		"  if (typeof obj === 'string') { console.log(tag + ' ' + obj); return; }",
		"  const parts = Object.entries(obj || {}).map(([k, v]) => k + '=' + String(v).replace(/\\s+/g, ' ').slice(0, 240));",
		"  console.log(tag + ' ' + parts.join(' '));",
		"}",
		"function digest(buf) { return crypto.createHash('sha256').update(buf).digest('hex').slice(0, 16); }",
		"function walkJs(root, maxFiles = 80) {",
		"  const out = [];",
		"  function walk(dir, depth) {",
		"    if (out.length >= maxFiles || depth > 5) return;",
		"    let entries = [];",
		"    try { entries = readdirSync(dir); } catch { return; }",
		"    for (const name of entries) {",
		"      if (out.length >= maxFiles) break;",
		"      if (name === 'node_modules' || name === '.git') continue;",
		"      const p = join(dir, name);",
		"      let st;",
		"      try { st = statSync(p); } catch { continue; }",
		"      if (st.isDirectory()) walk(p, depth + 1);",
		"      else if (/\\.(js|mjs|cjs|map)$/i.test(name)) out.push(p);",
		"    }",
		"  }",
		"  if (existsSync(root)) {",
		"    const st = statSync(root);",
		"    if (st.isFile()) out.push(root); else walk(root, 0);",
		"  }",
		"  return out;",
		"}",
		"const signals = { url: 0, hooks: 0, crypto: 0, sourcemap: 0, scripts: 0, rebuild: 0, normalized: 0 };",
		"const observed = { target, hooks: [], cryptoOps: [], files: [] };",
	];
}

export function jsSigningScriptProofFooter(): string[] {
	return [
		"const rebuildPath = work + '/repi-signing-rebuild.mjs';",
		"const rebuildLines = [",
		"  \"import crypto from 'node:crypto';\",",
		"  \"const observed = JSON.parse(process.env.REPI_OBSERVED || '{}');\",",
		"  \"const body = String(observed.body || '');\",",
		"  \"const secret = process.env.REPI_SECRET || 'CHANGE_ME';\",",
		"  \"function sha256(message) { return crypto.createHash('sha256').update(message).digest('hex'); }\",",
		"  \"function hmacSha256(secret, message) { return crypto.createHmac('sha256', secret).update(message).digest('hex'); }\",",
		"  \"console.log('[repi-signing-rebuild] sha256(body)=' + sha256(body));\",",
		"  \"console.log('[repi-signing-rebuild] hmac_sha256=' + hmacSha256(secret, body));\",",
		"  \"console.log('[repi-signing-rebuild] patch first divergence with captured hook args');\",",
		"];",
		"writeFileSync(rebuildPath, rebuildLines.join('\\n'));",
		"signals.rebuild = 1;",
		"log('[repi-signing-rebuild]', { artifact: rebuildPath });",
		"const normalizedPath = work + '/repi-js-observed.json';",
		"writeFileSync(normalizedPath, JSON.stringify({ ...observed, signals, capturedAt: new Date().toISOString() }, null, 2));",
		"signals.normalized = 1;",
		"log('[js-signing-normalized]', { artifact: normalizedPath, events: (observed.hooks || []).length });",
		"const capturePath = signals.url ? 'url' : 'static';",
		"log('[js-signing-proof-capture]', {",
		"  path: capturePath,",
		"  url: signals.url,",
		"  status: signals.url ? 1 : 0,",
		"  hooks: signals.hooks,",
		"  crypto: signals.crypto,",
		"  sourcemap: signals.sourcemap,",
		"  scripts: signals.scripts,",
		"  rebuild: signals.rebuild,",
		"  normalized: signals.normalized,",
		"});",
		"console.log('[js-signing-path] mode=' + capturePath + ' url=' + signals.url);",
		"const strong = (signals.crypto && (signals.hooks || signals.sourcemap || signals.scripts || signals.rebuild)) || (signals.url && signals.crypto && signals.hooks) || (signals.hooks && signals.sourcemap && signals.scripts && signals.rebuild);",
		"const partial = signals.url || signals.scripts || signals.crypto || signals.hooks || signals.sourcemap || signals.rebuild;",
		"const proofExit = strong ? 'runtime_capture_strong' : (partial ? 'partial_runtime_capture' : 'pending_runtime_capture');",
		"console.log('[js-signing-proof-capture] proof.exit=' + proofExit + ' bind_ready=' + (proofExit === 'pending_runtime_capture' ? 'false' : 'true') + ' note=host-fetch-or-static-js');",
		"console.log('summary.proof_exit=' + proofExit);",
		"console.log('summary.capture.crypto=' + signals.crypto);",
		"console.log('summary.capture.hooks=' + signals.hooks);",
		"console.log('summary.capture.sourcemap=' + signals.sourcemap);",
		"console.log('summary.capture.scripts=' + signals.scripts);",
		"console.log('summary.capture.url=' + signals.url);",
	];
}
