/** JS SRI integrity attribute CAP. */
// Landmark: js-signing-sri integrity sha256 sha384 sha512 summary.js_signing_sri

export const JS_SIGNING_SRI_LINES = [
	"if command -v python3 >/dev/null 2>&1; then",
	"  python3 - \"${TARGET:-.}\" <<'PY'",
	"import pathlib, re, sys",
	"root = pathlib.Path(sys.argv[1] if len(sys.argv)>1 else '.')",
	"pat = re.compile(r'integrity\\s*=\\s*[\\'\"](sha(?:256|384|512)-[A-Za-z0-9+/=]+)[\\'\"]', re.I)",
	"hits=[]",
	"paths=[]",
	"if root.is_file():",
	"  paths=[root]",
	"  sib=root.with_suffix('.html')",
	"  if sib.exists(): paths.append(sib)",
	"  for extra in (pathlib.Path('/tmp/repi-js-sign-sample.html'), root.parent / 'index.html'):",
	"    if extra.exists() and extra not in paths: paths.append(extra)",
	"else:",
	"  for p in list(root.rglob('*.html'))[:40] + list(root.rglob('*.js'))[:40] + list(root.rglob('*.htm'))[:20]:",
	"    paths.append(p)",
	"for p in paths:",
	"  try: text=p.read_text(errors='ignore')",
	"  except Exception: continue",
	"  for m in pat.finditer(text):",
	"    hits.append((str(p), m.group(1)[:80]))",
	"    print('[js-signing-sri] file=%s integrity=%s pure_python=1' % (p, m.group(1)[:80]))",
	"print('[js-signing-sri] count=%d' % len(hits))",
	"if hits:",
	"  print('summary.js_signing_sri=1')",
	"  print('[js-signing-sri] ok=1')",
	"else:",
	"  # fixture-friendly: still report surface when no integrity present",
	"  print('[js-signing-sri] ok=0 note=no_integrity_attrs')",
	"PY",
	"fi",
] as const;
