/** Full mission checkpoint matrix. */
/** Mission checkpoint matrices by reverse/pentest domain. */
import type { MissionCheckpoint } from "./types.ts";

export const MISSION_CHECKPOINTS_FULL: MissionCheckpoint[] = [
	{ name: "route_selected", status: "done", note: "REPI route created" },
	{ name: "execution_kernel_ready", status: "pending" },
	{ name: "decision_core_ready", status: "pending" },
	{ name: "memory_checked", status: "pending" },
	{ name: "tool_index_checked", status: "pending" },
	{ name: "passive_map_done", status: "pending" },
	{ name: "live_browser_ready", status: "pending" },
	{ name: "web_authz_ready", status: "pending" },
	{ name: "exploit_lab_ready", status: "pending" },
	{ name: "mobile_runtime_ready", status: "pending" },
	{ name: "native_runtime_ready", status: "pending" },
	{ name: "minimal_path_proven", status: "pending" },
	{ name: "evidence_ledger_updated", status: "pending" },
	{ name: "repro_commands_ready", status: "pending" },
	{ name: "attack_graph_ready", status: "pending" },
	{ name: "exploit_chain_ready", status: "pending" },
	{ name: "campaign_plan_ready", status: "pending" },
	{ name: "operation_queue_ready", status: "pending" },
	{ name: "delegation_packets_ready", status: "pending" },
	{ name: "swarm_plan_ready", status: "pending" },
	{ name: "supervisor_review_ready", status: "pending" },
	{ name: "reflection_memory_ready", status: "pending" },
	{ name: "context_pack_ready", status: "pending" },
	{ name: "operator_queue_ready", status: "pending" },
	{ name: "verifier_matrix_ready", status: "pending" },
	{ name: "compiler_ready", status: "pending" },
	{ name: "replay_ready", status: "pending" },
	{ name: "autofix_ready", status: "pending" },
	{ name: "proof_loop_ready", status: "pending" },
	{ name: "reverse_proof_exit_ready", status: "pending" },
	{ name: "knowledge_graph_ready", status: "pending" },
	{ name: "report_or_writeup_ready", status: "pending" },
	{ name: "memory_or_evolution_written", status: "pending" },
];
