/** Mission checkpoints: web/frontend/mobile/agent. */
export const MISSION_CHECKPOINTS_WEB_MOBILE: Record<string, string[]> = {
	"Web / API pentest": [
		"live_browser_ready",
		"web_authz_ready",
		"attack_graph_ready",
		"operation_queue_ready",
		"verifier_matrix_ready",
		"compiler_ready",
		"replay_ready",
	],
	"Web pentest scanning": [
		"live_browser_ready",
		"web_authz_ready",
		"attack_graph_ready",
		"operation_queue_ready",
		"verifier_matrix_ready",
		"compiler_ready",
		"replay_ready",
	],
	"Frontend JS reverse": [
		"reverse_proof_exit_ready",
		"live_browser_ready",
		"web_authz_ready",
		"attack_graph_ready",
		"verifier_matrix_ready",
		"compiler_ready",
		"replay_ready",
	],
	"Mobile / Android": [
		"reverse_proof_exit_ready",
		"mobile_runtime_ready",
		"native_runtime_ready",
		"verifier_matrix_ready",
		"compiler_ready",
		"replay_ready",
	],
	"Mobile / iOS": [
		"reverse_proof_exit_ready",
		"mobile_runtime_ready",
		"native_runtime_ready",
		"verifier_matrix_ready",
		"compiler_ready",
		"replay_ready",
	],
	"Agent / LLM boundary": [
		"delegation_packets_ready",
		"swarm_plan_ready",
		"supervisor_review_ready",
		"context_pack_ready",
		"operator_queue_ready",
		"verifier_matrix_ready",
		"compiler_ready",
		"proof_loop_ready",
	],
};
