/** REPI storage layout directories for ensureRepiStorage. */
import { join } from "node:path";
import { reconArchiveDir, reconDir, reportDir } from "../paths/core.ts";
import {
	evidenceAutofixDir,
	evidenceBrowserDir,
	evidenceCampaignsDir,
	evidenceChainsDir,
	evidenceClaimReleaseDir,
	evidenceCompilersDir,
	evidenceContextsDir,
	evidenceDecisionsDir,
	evidenceDelegationsDir,
	evidenceExploitLabDir,
	evidenceFailuresDir,
	evidenceGraphsDir,
	evidenceJsSigningDir,
	evidenceKernelDir,
	evidenceKnowledgeDir,
	evidenceMapsDir,
	evidenceMobileRuntimeDir,
	evidenceNativeRuntimeDir,
	evidenceOperationsDir,
	evidenceOperatorsDir,
	evidenceProfileCheckDir,
	evidenceProofLoopsDir,
	evidenceReflectionsDir,
	evidenceRepairsDir,
	evidenceReplayersDir,
	evidenceRunsDir,
	evidenceSupervisorsDir,
	evidenceSwarmsDir,
	evidenceToolCallsDir,
	evidenceToolchainDir,
	evidenceVerifiersDir,
	evidenceWebAuthzDir,
} from "../paths/evidence.ts";
import { memoryPath, memoryPlaybooksArchiveDir, memoryPlaybooksDir, memoryTransactionsDir } from "../paths/memory.ts";

export function repiStorageLayoutDirs(): string[] {
	return [
		reconDir(),
		memoryPath(""),
		memoryTransactionsDir(),
		memoryPlaybooksDir(),
		memoryPlaybooksArchiveDir(),
		reconArchiveDir(),
		join(reconDir(), "mission"),
		join(reconDir(), "evidence"),
		evidenceRunsDir(),
		evidenceMapsDir(),
		evidenceBrowserDir(),
		evidenceWebAuthzDir(),
		evidenceJsSigningDir(),
		evidenceExploitLabDir(),
		evidenceMobileRuntimeDir(),
		evidenceNativeRuntimeDir(),
		evidenceKernelDir(),
		evidenceGraphsDir(),
		evidenceChainsDir(),
		evidenceDecisionsDir(),
		evidenceCampaignsDir(),
		evidenceOperationsDir(),
		evidenceDelegationsDir(),
		evidenceSwarmsDir(),
		evidenceSupervisorsDir(),
		evidenceReflectionsDir(),
		evidenceContextsDir(),
		evidenceOperatorsDir(),
		evidenceVerifiersDir(),
		evidenceCompilersDir(),
		evidenceReplayersDir(),
		evidenceAutofixDir(),
		evidenceFailuresDir(),
		evidenceRepairsDir(),
		evidenceClaimReleaseDir(),
		evidenceProofLoopsDir(),
		evidenceKnowledgeDir(),
		evidenceProfileCheckDir(),
		evidenceToolCallsDir(),
		evidenceToolchainDir(),
		reportDir(),
		join(reconDir(), "tools"),
		join(reconDir(), "builtin", "reverse-pentest-orchestrator"),
		join(reconDir(), "builtin", "prompts"),
	];
}
