import { type AgentMessage, uuidv7 } from "@repi/agent-core";
import type { ImageContent, Message, TextContent } from "@repi/ai";
import { randomBytes, randomUUID } from "crypto";
import {
	appendFileSync,
	chmodSync,
	closeSync,
	createReadStream,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readSync,
	renameSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from "fs";
import { readdir, stat } from "fs/promises";
import { basename, dirname, join, resolve } from "path";
import { createInterface } from "readline";
import { StringDecoder } from "string_decoder";
import { getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.ts";
import { normalizePath, resolvePath } from "../utils/paths.ts";
import {
	type BashExecutionMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.ts";
import { atomicWriteFileSync } from "./tools/atomic-write.ts";

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	allMessagesText: string;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
>;

function createSessionId(): string {
	return uuidv7();
}

export function assertValidSessionId(id: string): void {
	if (!/^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$/.test(id)) {
		throw new Error(
			"Session id must be non-empty, contain only alphanumeric characters, '-', '_', and '.', and start and end with an alphanumeric character",
		);
	}
}

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		// opt #225: record the generated id in the collision set so subsequent
		// generateId calls in this migration actually detect a collision. Pre-fix
		// `ids` was never added to, so the 100-retry collision check was dead —
		// two colliding 8-hex ids would silently share an id, shadowing one entry
		// in byId and corrupting the parent chain (silent context loss).
		ids.add(entry.id);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionContext {
	// Build uuid index if not available
	if (!byId) {
		byId = new Map<string, SessionEntry>();
		for (const entry of entries) {
			byId.set(entry.id, entry);
		}
	}

	// Find leaf
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		// Explicitly null - return no messages (navigated to before first entry)
		return { messages: [], thinkingLevel: "off", model: null };
	}
	if (leafId) {
		leaf = byId.get(leafId);
	}
	if (!leaf) {
		// Fallback to last entry (when leafId is undefined)
		leaf = entries[entries.length - 1];
	}

	if (!leaf) {
		return { messages: [], thinkingLevel: "off", model: null };
	}

	// Walk from leaf to root, collecting path
	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	const visited = new Set<string>();
	while (current) {
		if (visited.has(current.id)) {
			throw new Error(`Session cycle detected at entry ${current.id} (corrupt parentId chain)`);
		}
		visited.add(current.id);
		path.unshift(current);
		current = current.parentId ? byId.get(current.parentId) : undefined;
	}

	// opt #223: detect a dangling parentId — the walk stopped because an entry's
	// parentId was non-null but resolved to no entry (parent deleted/corrupt/not
	// in the loaded set, e.g. a partial-load or a re-parented branch). The path
	// is silently truncated at that point: every ancestor message before the
	// break is lost from the model's context with no signal. Surface a warning
	// so the loss is visible rather than silent. The truncation behavior itself
	// is preserved (emit what we have) so session load still succeeds.
	const pathRoot = path[0];
	if (pathRoot?.parentId && !byId.has(pathRoot.parentId)) {
		process.stderr.write(
			`Warning: session branch truncated at entry "${pathRoot.id}" — parentId "${pathRoot.parentId}" not found in session; ancestor messages dropped from context.\n`,
		);
	}

	// Extract settings and find compaction
	let thinkingLevel = "off";
	let model: { provider: string; modelId: string } | null = null;
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
		} else if (entry.type === "model_change") {
			model = { provider: entry.provider, modelId: entry.modelId };
		} else if (entry.type === "message" && entry.message.role === "assistant") {
			model = { provider: entry.message.provider, modelId: entry.message.model };
		} else if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	// Build messages and collect corresponding entries
	// When there's a compaction, we need to:
	// 1. Emit summary first (entry = compaction)
	// 2. Emit kept messages (from firstKeptEntryId up to compaction)
	// 3. Emit messages after compaction
	const messages: AgentMessage[] = [];

	const appendMessage = (entry: SessionEntry) => {
		if (entry.type === "message") {
			messages.push(entry.message);
		} else if (entry.type === "custom_message") {
			messages.push(
				createCustomMessage(entry.customType, entry.content, entry.display, entry.details, entry.timestamp),
			);
		} else if (entry.type === "branch_summary" && entry.summary) {
			messages.push(createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp));
		}
	};

	if (compaction) {
		// Emit summary first
		messages.push(createCompactionSummaryMessage(compaction.summary, compaction.tokensBefore, compaction.timestamp));

		// Find compaction index in path
		const compactionIdx = path.findIndex((e) => e.type === "compaction" && e.id === compaction.id);

		// Emit kept messages (before compaction, starting from firstKeptEntryId)
		let foundFirstKept = false;
		const firstKeptId = compaction.firstKeptEntryId;
		for (let i = 0; i < compactionIdx; i++) {
			const entry = path[i];
			if (firstKeptId && entry.id === firstKeptId) {
				foundFirstKept = true;
			}
			if (foundFirstKept) {
				appendMessage(entry);
			}
		}

		// opt #222: if firstKeptEntryId was missing (e.g. a v1 compaction whose
		// firstKeptEntryIndex pointed at the session header — migrateV1ToV2
		// leaves firstKeptEntryId undefined) or pointed at an entry not on this
		// path (orphaned by branching), the loop above emitted NOTHING — the
		// model would see a compaction summary with zero retained messages
		// (silent context loss). Fall back to emitting ALL pre-compaction messages
		// so the conversation is preserved (redundant with the summary, but
		// non-lossy). For the v1-header case this is exactly correct (kept window
		// was the whole pre-compaction history); for the orphaned-branch case it
		// is a safe over-inclusion. Surface a warning only when an id was present
		// but unresolvable (real corruption), not when it was never set (migration).
		if (!foundFirstKept) {
			if (firstKeptId) {
				process.stderr.write(
					`Warning: session compaction firstKeptEntryId "${firstKeptId}" not found on branch path; ` +
						`falling back to all pre-compaction messages to avoid context loss.\n`,
				);
			}
			for (let i = 0; i < compactionIdx; i++) {
				appendMessage(path[i]);
			}
		}

		// Emit messages after compaction
		for (let i = compactionIdx + 1; i < path.length; i++) {
			const entry = path[i];
			appendMessage(entry);
		}
	} else {
		// No compaction - emit all messages, handle branch summaries and custom messages
		for (const entry of path) {
			appendMessage(entry);
		}
	}

	return { messages, thinkingLevel, model };
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.repi/agent/sessions/.
 */
function getDefaultSessionDirPath(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const resolvedCwd = resolvePath(cwd);
	const resolvedAgentDir = resolvePath(agentDir);
	const safePath = `--${resolvedCwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
	return join(resolvedAgentDir, "sessions", safePath);
}

export function getDefaultSessionDir(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const sessionDir = getDefaultSessionDirPath(cwd, agentDir);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

const SESSION_READ_BUFFER_SIZE = 1024 * 1024;

function parseSessionEntryLine(line: string): FileEntry | null {
	if (!line.trim()) return null;
	try {
		const entry = JSON.parse(line) as FileEntry;
		// Foundational opt #270: validate the SHAPE of a parsed entry, not just
		// JSON syntax. A `type:"message"` line that is valid JSON but has a
		// missing/null `message` field (disk corruption, a partial write that
		// landed as valid JSON, a buggy extension/custom writer, or a
		// version-incompatible client) previously passed this check and entered
		// `fileEntries`. Then _buildIndex (line ~1147) did
		// `entry.message.role === "assistant"` and buildSessionContext (line ~403)
		// did `entry.message.provider` — `TypeError: Cannot read properties of
		// null/undefined (reading 'role')` — UNCAUGHT in setSessionFile (no
		// try/catch around _buildIndex), propagating out of the SessionManager
		// constructor and aborting every `--continue`/open/forkFrom on that
		// session. The headerless/empty recovery (backupCorruptSessionFile) only
		// fires when fileEntries.length===0, so a header-valid-but-entry-corrupt
		// session was permanently unopenable with no .corrupt.*.bak. Skip a
		// malformed message entry here (same as a malformed-JSON line) so the
		// session stays loadable; the rest of the entries are unaffected.
		if (entry.type === "message") {
			const message = (entry as { message?: unknown }).message;
			if (
				message === null ||
				typeof message !== "object" ||
				typeof (message as { role?: unknown }).role !== "string"
			) {
				return null;
			}
		}
		return entry;
	} catch {
		// Skip malformed lines
		return null;
	}
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string): FileEntry[] {
	const resolvedFilePath = normalizePath(filePath);
	if (!existsSync(resolvedFilePath)) return [];

	const entries: FileEntry[] = [];
	const fd = openSync(resolvedFilePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);
		let pending = "";

		while (true) {
			const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
			if (bytesRead === 0) break;

			pending += decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = pending.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				const entry = parseSessionEntryLine(pending.slice(lineStart, newlineIndex));
				if (entry) entries.push(entry);
				lineStart = newlineIndex + 1;
				newlineIndex = pending.indexOf("\n", lineStart);
			}
			pending = pending.slice(lineStart);
		}

		pending += decoder.end();
		const finalEntry = parseSessionEntryLine(pending);
		if (finalEntry) {
			entries.push(finalEntry);
		} else if (pending.trim()) {
			// Torn trailing line: a crash (SIGKILL/OOM/power loss) mid-appendFileSync
			// left a partial final line with no trailing "\n". The in-memory skip above
			// already made the session usable, but without re-truncating the file the
			// NEXT append would concatenate directly onto the partial line, fusing into
			// one unhealable interior corrupt line and silently losing BOTH the torn
			// entry AND the next appended entry on the following reopen. Heal by
			// atomically rewriting the parseable entries (mirrors the harness
			// loadJsonlStorage heal in jsonl-storage.ts; atomic temp+rename per #38 so
			// a crash during recovery cannot make things worse). Best-effort: a write
			// failure does not block open — the in-memory skip already succeeded.
			healTornTrailingLine(resolvedFilePath, entries);
		}
	} finally {
		closeSync(fd);
	}

	// Validate session header
	if (entries.length === 0) return entries;
	const header = entries[0];
	if (header.type !== "session" || typeof (header as { id?: unknown }).id !== "string") {
		return [];
	}

	return entries;
}

/**
 * Atomically re-truncate a session file to its parseable entries after a torn
 * trailing line was skipped by {@link loadEntriesFromFile}. Without this heal the
 * next `appendFileSync` fuses onto the partial line, losing both entries. Writes a
 * uniquely-named temp file in the same directory then renames into place (POSIX
 * atomic within the same filesystem), preserving the existing file's mode.
 * Best-effort: any failure is swallowed — the in-memory skip already made the
 * session usable, and a failed heal must not block open.
 */
function healTornTrailingLine(filePath: string, entries: FileEntry[]): void {
	// opt #221: never heal to an EMPTY file. If entries is empty (the only line
	// was a torn header / fully-corrupt blob), writing an empty temp and
	// renaming it over the original DESTROYS the corrupt content — which may be
	// partially recoverable by hand — before any caller-side backup runs. Leave
	// the file intact and let the caller (setSessionFile) decide. When entries
	// is empty the file has no valid header, so setSessionFile rewrites it with
	// a fresh header anyway; skipping the heal here only avoids clobbering the
	// original before that backup-aware path runs.
	if (entries.length === 0) return;
	const dir = dirname(filePath);
	const tempPath = join(dir, `.${basename(filePath)}.${process.pid}.${randomBytes(4).toString("hex")}.torn.tmp`);
	// Wrap the entire open→write→chmod→rename sequence in a single catch that
	// unlinks the temp on ANY failure. Previously only the renameSync step was
	// guarded: if writeFileSync threw mid-loop (disk full / EIO / EROFS), the
	// inner finally closed the fd and the error propagated to the outer catch —
	// which swallowed it but never unlinked tempPath, leaving a
	// `.<basename>.<pid>.<hex>.torn.tmp` file in the session dir permanently
	// (repeated heal attempts on a nearly-full disk accumulated them). This
	// mirrors atomicWriteFileSync's whole-sequence unlink-on-failure contract.
	// The heal itself stays best-effort: any failure is swallowed so a failed
	// heal never blocks open (the in-memory skip already made the session
	// usable).
	try {
		const fd = openSync(tempPath, "wx");
		try {
			for (const entry of entries) {
				writeFileSync(fd, `${JSON.stringify(entry)}\n`);
			}
		} finally {
			closeSync(fd);
		}
		try {
			const existing = statSync(filePath);
			try {
				chmodSync(tempPath, existing.mode & 0o777);
			} catch {
				/* best-effort: proceed with default mode */
			}
		} catch {
			/* target doesn't exist yet — keep default mode */
		}
		try {
			renameSync(tempPath, filePath);
		} catch {
			try {
				unlinkSync(tempPath);
			} catch {
				/* best-effort cleanup */
			}
		}
	} catch {
		// best-effort heal; the in-memory skip already made the session usable.
		// Clean up the temp on this write/open-failure path too (rename-failure
		// cleanup is handled above).
		try {
			unlinkSync(tempPath);
		} catch {
			/* best-effort: temp may not exist (open threw) or already removed */
		}
	}
}

/**
 * Best-effort backup of an unrecoverable session file before setSessionFile
 * overwrites it with a fresh header. Renames the original to
 * `<path>.corrupt.<ts>.bak` and surfaces a stderr warning so the user knows
 * their conversation was retained as a backup. opt #221.
 *
 * No-op when the file does not exist or is genuinely empty (size 0). A rename
 * failure is swallowed — setSessionFile proceeds to write a fresh session so
 * open still succeeds; the original is left in place (the fresh write then
 * overwrites it, but at least one backup attempt was made).
 */
function backupCorruptSessionFile(filePath: string): void {
	try {
		if (!existsSync(filePath)) return;
		const st = statSync(filePath);
		if (!st.isFile() || st.size === 0) return;
		const backup = `${filePath}.corrupt.${Date.now()}.bak`;
		try {
			renameSync(filePath, backup);
		} catch {
			// Rename failed (cross-device / permissions). Fall back to leaving the
			// original in place — the caller's fresh write will overwrite it, but we
			// avoid destroying it via a failed partial move. Return without warning
			// since no backup was created.
			return;
		}
		process.stderr.write(
			`Warning: session file "${filePath}" was corrupt or had no valid header and could not be recovered. ` +
				`A backup was saved to "${backup}" and a fresh session was started.\n`,
		);
	} catch {
		// best-effort: never block session open on a backup failure
	}
}

/** Exported for testing (opt #157: long-first-line regression pin). */
export function readSessionHeader(filePath: string): SessionHeader | null {
	let fd: number | undefined;
	try {
		fd = openSync(filePath, "r");
		// opt #157: read the first line in a loop until a newline, EOF, or a
		// sane 16 KB cap, instead of a fixed 512-byte readSync. A long header
		// line (deep cwd + full-path parentSession, which the writer stores at
		// persist/fork/resume sites) exceeds 512 bytes → the old read truncated
		// it mid-JSON → JSON.parse threw → the catch returned null → the session
		// was silently dropped from findMostRecentSession's --continue auto-pick.
		const CAP = 16 * 1024;
		const buffer = Buffer.alloc(CAP);
		let filled = 0;
		let firstLine: string | null = null;
		while (filled < CAP) {
			const n = readSync(fd, buffer, filled, CAP - filled, filled);
			if (n <= 0) {
				// EOF before a newline — the whole buffer is the first line.
				firstLine = buffer.toString("utf8", 0, filled);
				break;
			}
			const nl = buffer.toString("utf8", filled, filled + n).indexOf("\n");
			if (nl !== -1) {
				firstLine = buffer.toString("utf8", 0, filled + nl);
				break;
			}
			filled += n;
		}
		// firstLine === null → hit the 16 KB cap with no newline: a header this
		// long is pathological; treat as unparseable rather than read unbounded.
		if (!firstLine) return null;
		firstLine = firstLine.trim();
		if (!firstLine) return null;
		const header = JSON.parse(firstLine) as Record<string, unknown>;
		if (header.type !== "session" || typeof header.id !== "string") {
			return null;
		}
		return header as unknown as SessionHeader;
	} catch {
		return null;
	} finally {
		// Close in finally so a readSync/JSON.parse throw doesn't leak the fd.
		// (loadEntriesFromFile already does this; this path didn't.)
		if (fd !== undefined) {
			try {
				closeSync(fd);
			} catch {
				// Best-effort: fd may already be invalid.
			}
		}
	}
}

function getSessionHeaderCwd(header: SessionHeader): string | undefined {
	const cwd = (header as { cwd?: unknown }).cwd;
	return typeof cwd === "string" ? cwd : undefined;
}

function sessionCwdMatches(cwd: string | undefined, resolvedCwd: string): boolean {
	return cwd !== undefined && cwd !== "" && resolvePath(cwd) === resolvedCwd;
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string, cwd?: string): string | null {
	const resolvedSessionDir = normalizePath(sessionDir);
	const resolvedCwd = cwd ? resolvePath(cwd) : undefined;
	try {
		const files = readdirSync(resolvedSessionDir)
			.filter((f) => f.endsWith(".jsonl"))
			.map((f) => join(resolvedSessionDir, f))
			.map((path) => ({ path, header: readSessionHeader(path) }))
			.filter(
				(file): file is { path: string; header: SessionHeader } =>
					file.header !== null &&
					(!resolvedCwd || sessionCwdMatches(getSessionHeaderCwd(file.header), resolvedCwd)),
			)
			.flatMap(({ path }) => {
				try {
					return [{ path, mtime: statSync(path).mtime }];
				} catch {
					// opt #243: a single unreadable/deleted/broken-symlink .jsonl
					// mid-list used to throw out of the .map, abort the whole
					// .sort chain, and be caught by the outer try → return null
					// for the ENTIRE directory. `pi --continue` (continueRecent)
					// then silently started a fresh session instead of resuming
					// the real most-recent readable one. Skip just the bad file.
					return [];
				}
			})
			.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

		return files[0]?.path || null;
	} catch {
		return null;
	}
}

function isMessageWithContent(message: AgentMessage): message is Message {
	return typeof (message as Message).role === "string" && "content" in message;
}

function extractTextContent(message: Message): string {
	const content = message.content;
	if (typeof content === "string") {
		return content;
	}
	return content
		.filter((block): block is TextContent => block.type === "text")
		.map((block) => block.text)
		.join(" ");
}

function getMessageActivityTime(entry: SessionMessageEntry): number | undefined {
	const message = entry.message;
	if (!isMessageWithContent(message)) return undefined;
	if (message.role !== "user" && message.role !== "assistant") return undefined;

	const msgTimestamp = (message as { timestamp?: number }).timestamp;
	if (typeof msgTimestamp === "number") {
		return msgTimestamp;
	}

	const t = new Date(entry.timestamp).getTime();
	return Number.isNaN(t) ? undefined : t;
}

/**
 * Per-session cap on the accumulated transcript text held in memory for the
 * session-picker fuzzy search (`allMessagesText`). `0` disables the cap (full
 * transcript). Unset/garbage falls back to the default. Consistent with the
 * opt #27/#41 `envNonNegativeInteger` style: an explicit `0` is honored.
 */
const DEFAULT_SESSION_SEARCH_MAX_CHARS = 256 * 1024;

function getSessionSearchMaxChars(): number {
	const raw = process.env.REPI_SESSION_SEARCH_MAX_CHARS;
	if (raw === undefined || raw.trim() === "") return DEFAULT_SESSION_SEARCH_MAX_CHARS;
	const value = Number(raw);
	if (!Number.isFinite(value) || value < 0) return DEFAULT_SESSION_SEARCH_MAX_CHARS;
	return Math.floor(value);
}

/** Exported for testing (opt #167: bounded allMessagesText pin). */
export async function buildSessionInfo(filePath: string): Promise<SessionInfo | null> {
	try {
		const stats = await stat(filePath);
		let header: SessionHeader | null = null;
		let messageCount = 0;
		let firstMessage = "";
		// opt #167: cap the per-session transcript held in memory for the
		// session-picker fuzzy search. Previously every user/assistant
		// textContent was pushed into allMessages with no cap, then joined —
		// the full transcript of every session was accumulated in memory
		// (array + joined string), and buildSessionInfosWithConcurrency
		// (concurrency 10) ran this for ALL sessions at once on list/search →
		// OOM on several long sessions. Now: keep the first message (head) +
		// a bounded TAIL of recent messages (head+tail, faithful to "most
		// recent context" for fuzzy search). A session whose total text stays
		// under the cap — the normal case — is byte-identical to the uncapped
		// join (no truncation, no drops). cap=0 disables → original behavior.
		const cap = getSessionSearchMaxChars();
		const allMessages: string[] = []; // uncapped path (cap === 0)
		let head = ""; // first textContent, kept fully (capped to cap if one msg > cap)
		let haveHead = false;
		const tail: string[] = []; // recent messages after head, byte-bounded
		let tailBytes = 0;
		let name: string | undefined;
		let lastActivityTime: number | undefined;

		const rl = createInterface({
			input: createReadStream(filePath, { encoding: "utf8" }),
			crlfDelay: Infinity,
		});

		for await (const line of rl) {
			const entry = parseSessionEntryLine(line);
			if (!entry) continue;

			if (!header) {
				if (entry.type !== "session") return null;
				header = entry;
				continue;
			}

			// Extract session name (use latest, including explicit clears)
			if (entry.type === "session_info") {
				name = entry.name?.trim() || undefined;
			}

			if (entry.type !== "message") continue;
			messageCount++;

			const activityTime = getMessageActivityTime(entry);
			if (typeof activityTime === "number") {
				lastActivityTime = Math.max(lastActivityTime ?? 0, activityTime);
			}

			const message = entry.message;
			if (!isMessageWithContent(message)) continue;
			if (message.role !== "user" && message.role !== "assistant") continue;

			const textContent = extractTextContent(message);
			if (!textContent) continue;

			if (!firstMessage && message.role === "user") {
				firstMessage = textContent;
			}

			if (cap === 0) {
				// Uncapped path: preserve original behavior byte-for-byte.
				allMessages.push(textContent);
				continue;
			}
			// Capped head+tail path. Cap any single oversized message so one
			// huge message can't itself blow the bound.
			const piece = textContent.length > cap ? textContent.slice(0, cap) : textContent;
			if (!haveHead) {
				head = piece;
				haveHead = true;
				continue;
			}
			tail.push(piece);
			tailBytes += piece.length;
			// Drop oldest tail entries while over cap (keep head + recent tail).
			// Batch-drop half when the tail is large to keep amortized O(1)
			// even for pathological many-tiny-message sessions; each element is
			// physically removed at most once.
			while (tailBytes > cap && tail.length > 0) {
				const dropCount = tail.length > 1024 ? Math.floor(tail.length / 2) : 1;
				const removed = tail.splice(0, dropCount);
				for (const r of removed) tailBytes -= r.length;
			}
		}

		if (!header) return null;

		const cwd = typeof header.cwd === "string" ? header.cwd : "";
		const parentSessionPath = header.parentSession;
		const headerTime = typeof header.timestamp === "string" ? new Date(header.timestamp).getTime() : NaN;
		const modified =
			typeof lastActivityTime === "number" && lastActivityTime > 0
				? new Date(lastActivityTime)
				: !Number.isNaN(headerTime)
					? new Date(headerTime)
					: stats.mtime;

		// cap===0 → uncapped join (byte-identical to original behavior).
		// Otherwise head+tail join, then a final slice so the returned text is
		// <= cap chars regardless of join separators. The tail-drop loop above
		// bounds the in-memory working set; this slice bounds the output.
		const allMessagesText = cap === 0 ? allMessages.join(" ") : [head, ...tail].join(" ").slice(0, cap);

		return {
			path: filePath,
			id: header.id,
			cwd,
			name,
			parentSessionPath,
			created: new Date(header.timestamp),
			modified,
			messageCount,
			firstMessage: firstMessage || "(no messages)",
			allMessagesText,
		};
	} catch {
		return null;
	}
}

export type SessionListProgress = (loaded: number, total: number) => void;

const MAX_CONCURRENT_SESSION_INFO_LOADS = 10;

async function buildSessionInfosWithConcurrency(
	files: string[],
	onLoaded: () => void,
): Promise<(SessionInfo | null)[]> {
	const results: (SessionInfo | null)[] = new Array(files.length).fill(null);
	const inFlight = new Set<Promise<void>>();
	let nextIndex = 0;

	const startNext = (): void => {
		const index = nextIndex++;
		const file = files[index];
		if (!file) return;

		let task: Promise<void>;
		task = buildSessionInfo(file)
			.then((info) => {
				results[index] = info;
			})
			.catch(() => {
				results[index] = null;
			})
			.finally(() => {
				inFlight.delete(task);
				onLoaded();
			});
		inFlight.add(task);
	};

	while (nextIndex < files.length || inFlight.size > 0) {
		while (nextIndex < files.length && inFlight.size < MAX_CONCURRENT_SESSION_INFO_LOADS) {
			startNext();
		}
		if (inFlight.size > 0) {
			await Promise.race(inFlight);
		}
	}

	return results;
}

async function listSessionsFromDir(
	dir: string,
	onProgress?: SessionListProgress,
	progressOffset = 0,
	progressTotal?: number,
): Promise<SessionInfo[]> {
	const sessions: SessionInfo[] = [];
	if (!existsSync(dir)) {
		return sessions;
	}

	try {
		const dirEntries = await readdir(dir);
		const files = dirEntries.filter((f) => f.endsWith(".jsonl")).map((f) => join(dir, f));
		const total = progressTotal ?? files.length;

		let loaded = 0;
		const results = await buildSessionInfosWithConcurrency(files, () => {
			loaded++;
			onProgress?.(progressOffset + loaded, total);
		});
		for (const info of results) {
			if (info) {
				sessions.push(info);
			}
		}
	} catch {
		// Return empty list on error
	}

	return sessions;
}

/**
 * Manages conversation sessions as append-only trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	/** O(1) cache: true once an assistant message has been appended to fileEntries.
	 * Replaces the O(n) some() scan in _persist that ran on every append. */
	private _hasAssistant: boolean = false;
	/** O(1) cache of the latest CompactionEntry on the current branch (leaf→root path).
	 * Replaces the per-turn getLatestCompactionEntry(getBranch()) walk in the compaction hook.
	 * Updated in appendCompaction; recomputed in _buildIndex/branch/resetLeaf/branchWithSummary. */
	private _latestCompactionOnBranch: CompactionEntry | null = null;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	private labelsById: Map<string, string> = new Map();
	private labelTimestampsById: Map<string, string> = new Map();
	private leafId: string | null = null;

	private constructor(
		cwd: string,
		sessionDir: string,
		sessionFile: string | undefined,
		persist: boolean,
		newSessionOptions?: NewSessionOptions,
	) {
		this.cwd = resolvePath(cwd);
		this.sessionDir = normalizePath(sessionDir);
		this.persist = persist;
		if (persist && this.sessionDir && !existsSync(this.sessionDir)) {
			mkdirSync(this.sessionDir, { recursive: true });
		}

		if (sessionFile) {
			this.setSessionFile(sessionFile);
		} else {
			this.newSession(newSessionOptions);
		}
	}

	/** Switch to a different session file (used for resume and branching) */
	setSessionFile(sessionFile: string): void {
		this.sessionFile = resolvePath(sessionFile);
		if (existsSync(this.sessionFile)) {
			this.fileEntries = loadEntriesFromFile(this.sessionFile);

			// If file was empty or corrupted (no valid header), truncate and start fresh
			// to avoid appending messages without a session header (which breaks the session)
			if (this.fileEntries.length === 0) {
				// opt #221: before overwriting an unrecoverable session file with a
				// fresh header, back the original up to `<path>.corrupt.<ts>.bak` so
				// the user can attempt manual recovery. Pre-fix this branch silently
				// replaced the file (newSession + _rewriteFile) with a blank session,
				// permanently destroying the corrupt content — which may have been
				// partially recoverable (a torn header from a crash during the first
				// flush, or a single bad line). Best-effort: a rename failure is
				// swallowed so open still succeeds with a fresh session. Skip only when
				// the file is genuinely empty (size 0) — nothing to recover.
				backupCorruptSessionFile(this.sessionFile);
				const explicitPath = this.sessionFile;
				this.newSession();
				this.sessionFile = explicitPath;
				this._rewriteFile();
				this.flushed = true;
				return;
			}

			const header = this.fileEntries.find((e) => e.type === "session") as SessionHeader | undefined;
			this.sessionId = header?.id ?? createSessionId();

			if (migrateToCurrentVersion(this.fileEntries)) {
				this._rewriteFile();
			}

			this._buildIndex();
			this.flushed = true;
		} else {
			const explicitPath = this.sessionFile;
			this.newSession();
			this.sessionFile = explicitPath; // preserve explicit path from --session flag
		}
	}

	newSession(options?: NewSessionOptions): string | undefined {
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		this.sessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
		};
		this.fileEntries = [header];
		this.byId.clear();
		this.labelsById.clear();
		this.leafId = null;
		this.flushed = false;
		this._hasAssistant = false;
		this._latestCompactionOnBranch = null;

		if (this.persist) {
			const fileTimestamp = timestamp.replace(/[:.]/g, "-");
			this.sessionFile = join(this.getSessionDir(), `${fileTimestamp}_${this.sessionId}.jsonl`);
		}
		return this.sessionFile;
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		this._hasAssistant = false;
		for (const entry of this.fileEntries) {
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			this.leafId = entry.id;
			if (entry.type === "message" && entry.message.role === "assistant") {
				this._hasAssistant = true;
			}
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
					this.labelTimestampsById.set(entry.targetId, entry.timestamp);
				} else {
					this.labelsById.delete(entry.targetId);
					this.labelTimestampsById.delete(entry.targetId);
				}
			}
		}
		this._recomputeLatestCompactionOnBranch();
	}

	/** Recompute _latestCompactionOnBranch by walking leaf→root. O(depth). */
	private _recomputeLatestCompactionOnBranch(): void {
		this._latestCompactionOnBranch = null;
		let current = this.leafId ? this.byId.get(this.leafId) : undefined;
		const visited = new Set<string>();
		while (current) {
			if (visited.has(current.id)) {
				throw new Error(`Session cycle detected at entry ${current.id} (corrupt parentId chain)`);
			}
			visited.add(current.id);
			if (current.type === "compaction") {
				this._latestCompactionOnBranch = current as CompactionEntry;
				return;
			}
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
	}

	private _rewriteFile(): void {
		if (!this.persist || !this.sessionFile) return;
		// Atomic rewrite: write to a uniquely-named temp file in the SAME directory
		// as the session file, then rename it into place. A plain openSync("w")
		// truncates the live session file first, so a crash (SIGKILL/OOM/SIGTERM)
		// mid-write would leave a truncated/partial file and lose the whole
		// conversation. temp+rename means readers see either the previous complete
		// file or the new complete file, never a partial write. rename is atomic on
		// POSIX only within the same filesystem, which same-directory placement
		// guarantees. Mode is preserved from the existing file. fsync is omitted
		// (crash-consistency of content, not power-loss durability — matches the
		// async atomicWriteFile pattern in tools/atomic-write.ts).
		const target = this.sessionFile;
		const dir = dirname(target);
		const tempPath = join(
			dir,
			`.${basename(target)}.${process.pid}.${Date.now()}.${randomBytes(4).toString("hex")}.tmp`,
		);
		const fd = openSync(tempPath, "wx");
		try {
			try {
				for (const entry of this.fileEntries) {
					writeFileSync(fd, `${JSON.stringify(entry)}\n`);
				}
			} finally {
				closeSync(fd);
			}
			// Preserve the existing session file's mode (e.g. a restrictive 0o600)
			// across the replace; a temp+rename would otherwise reset it to the
			// default. ENOENT (target doesn't exist yet) is non-fatal.
			try {
				const existing = statSync(target);
				try {
					chmodSync(tempPath, existing.mode & 0o777);
				} catch {
					/* best-effort: proceed with default mode */
				}
			} catch {
				/* target doesn't exist yet — keep default mode */
			}
			try {
				renameSync(tempPath, target);
			} catch (error) {
				try {
					unlinkSync(tempPath);
				} catch {
					/* best-effort: temp may not exist or may have been renamed already */
				}
				throw error instanceof Error ? error : new Error(String(error));
			}
		} catch (error) {
			// opt #235: pre-fix only the renameSync step unlinked the temp. If
			// writeFileSync threw mid-loop (ENOSPC/EIO/EROFS), the finally closed
			// the fd and the error propagated — control never reached the rename
			// catch, so the partial `.<basename>.<pid>.<ts>.<hex>.tmp` file was
			// left permanently in the session dir on EVERY failed rewrite (leak;
			// same class opt #41 fixed for atomicWriteFileSync). Best-effort unlink
			// before re-throwing. The original target is untouched (rename never
			// reached), so no data loss — only the leaked temp is cleaned up.
			try {
				unlinkSync(tempPath);
			} catch {
				/* best-effort: temp may not exist (open threw) or already renamed */
			}
			throw error instanceof Error ? error : new Error(String(error));
		}
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	usesDefaultSessionDir(): boolean {
		return this.sessionDir === getDefaultSessionDirPath(this.cwd);
	}

	getSessionId(): string {
		return this.sessionId;
	}

	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	_persist(entry: SessionEntry): void {
		if (!this.persist || !this.sessionFile) return;

		const hasAssistant = this._hasAssistant;
		if (!hasAssistant) {
			if (this.flushed) {
				appendFileSync(this.sessionFile, `${JSON.stringify(entry)}\n`);
			} else {
				// Mark as not flushed so when assistant arrives, all entries get written
				this.flushed = false;
			}
			return;
		}

		if (!this.flushed) {
			const fd = openSync(this.sessionFile, "wx");
			try {
				for (const e of this.fileEntries) {
					writeFileSync(fd, `${JSON.stringify(e)}\n`);
				}
			} catch (error) {
				// A write failure (e.g. ENOSPC) mid-loop leaves a partial file on
				// disk while this.flushed stays false; the next _persist re-enters
				// this branch and openSync("wx") throws EEXIST on every subsequent
				// append, bricking persistence until process restart. Remove the
				// partial file so the next attempt recreates it cleanly via "wx".
				// Best-effort: never mask the original error. this.flushed remains
				// false so the retry takes the first-flush path again.
				try {
					unlinkSync(this.sessionFile);
				} catch {
					/* best-effort: file may not exist or may have been removed already */
				}
				throw error;
			} finally {
				closeSync(fd);
			}
			this.flushed = true;
		} else {
			appendFileSync(this.sessionFile, `${JSON.stringify(entry)}\n`);
		}
	}

	private _appendEntry(entry: SessionEntry): void {
		// opt #239: capture the pre-append in-memory state so a _persist failure
		// can be rolled back. _persist's flushed-append branches use a bare
		// `appendFileSync` with NO recovery (unlike the first-flush openSync("wx")
		// path which unlinks the partial file). A throw there left `entry` in
		// memory (fileEntries/byId/leafId/_hasAssistant) but NOT on disk. The NEXT
		// successful append then wrote an entry whose parentId pointed at this
		// failed (in-memory-only) id; on reload, buildSessionContext walks from
		// the leaf, hits a parentId absent from the on-disk record set, and
		// truncates the path — silently dropping all ancestor history from the
		// LLM context (DATA-LOSS). Roll back so memory matches disk (the prior
		// on-disk leaf is entry.parentId), then rethrow so the caller sees the
		// failure.
		//
		// opt #274: the rollback is PATH-AWARE. It is only correct for the
		// FLUSHED-APPEND path (priorFlushed=true): there a failed appendFileSync
		// leaves the entry in memory but not on disk, and the next successful
		// append would dangle a parentId at it. For the FIRST-FLUSH path
		// (priorFlushed=false — reached when the first assistant triggers the
		// initial openSync("wx") write of ALL buffered fileEntries), _persist's
		// OWN catch already recovers: it unlinks the partial file and leaves
		// flushed=false so the next assistant-triggered persist re-enters
		// first-flush and rewrites the WHOLE fileEntries set. Rolling back there
		// would POP the assistant and reset _hasAssistant=false → the next
		// (non-assistant) append takes the !hasAssistant no-flush branch → the
		// file is never created and the assistant message is silently LOST. Keep
		// the entry buffered for the first-flush retry instead.
		const priorLeafId = this.leafId;
		const priorHadAssistant = this._hasAssistant;
		const priorFlushed = this.flushed;
		this.fileEntries.push(entry);
		this.byId.set(entry.id, entry);
		this.leafId = entry.id;
		if (entry.type === "message" && entry.message.role === "assistant") {
			this._hasAssistant = true;
		}
		try {
			this._persist(entry);
		} catch (error) {
			if (priorFlushed) {
				this.fileEntries.pop();
				this.byId.delete(entry.id);
				this.leafId = priorLeafId;
				this._hasAssistant = priorHadAssistant;
			}
			throw error;
		}
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(provider: string, modelId: string): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
	): string {
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			summary,
			firstKeptEntryId,
			tokensBefore,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		// The new compaction entry is appended at the current leaf, so it is
		// the latest compaction on the branch — update the O(1) cache directly.
		this._latestCompactionOnBranch = entry as CompactionEntry;
		return entry.id;
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a session info entry (e.g., display name). Returns entry id. */
	appendSessionInfo(name: string): string {
		const entry: SessionInfoEntry = {
			type: "session_info",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			name: name.trim(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Get the current session name from the latest session_info entry, if any. */
	getSessionName(): string | undefined {
		// Walk entries in reverse to find the latest session_info entry.
		// Empty names explicitly clear the session title.
		const entries = this.getEntries();
		for (let i = entries.length - 1; i >= 0; i--) {
			const entry = entries[i];
			if (entry.type === "session_info") {
				return entry.name?.trim() || undefined;
			}
		}
		return undefined;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		return this.leafId ? this.byId.get(this.leafId) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		return this.byId.get(id);
	}

	/**
	 * Get all direct children of an entry.
	 */
	getChildren(parentId: string): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(entry);
			}
		}
		return children;
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
			this.labelTimestampsById.set(targetId, entry.timestamp);
		} else {
			this.labelsById.delete(targetId);
			this.labelTimestampsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		const visited = new Set<string>();
		while (current) {
			if (visited.has(current.id)) {
				throw new Error(`Session cycle detected at entry ${current.id} (corrupt parentId chain)`);
			}
			visited.add(current.id);
			path.unshift(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		return path;
	}

	/**
	 * O(1) accessor for the latest CompactionEntry on the current branch
	 * (leaf→root path). Backed by _latestCompactionOnBranch, kept in sync on
	 * appendCompaction / branch / resetLeaf / branchWithSummary / _buildIndex.
	 * Equivalent to getLatestCompactionEntry(this.getBranch()) but avoids the
	 * per-turn O(depth) walk + array allocation.
	 */
	getLatestCompactionOnBranch(): CompactionEntry | null {
		return this._latestCompactionOnBranch;
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 */
	buildSessionContext(): SessionContext {
		return buildSessionContext(this.getEntries(), this.leafId, this.byId);
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? (h as SessionHeader) : null;
	}

	/**
	 * Get all session entries (excludes header). Returns a shallow copy.
	 * The session is append-only: use appendXXX() to add entries, branch() to
	 * change the leaf pointer. Entries cannot be modified or deleted.
	 */
	getEntries(): SessionEntry[] {
		return this.fileEntries.filter((e): e is SessionEntry => e.type !== "session");
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			const labelTimestamp = this.labelTimestampsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label, labelTimestamp });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted.
	 */
	branch(branchFromId: string): void {
		if (!this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
		// Leaf moved to a different sub-branch; the latest compaction on the
		// path may differ — recompute the O(1) cache.
		this._recomputeLatestCompactionOnBranch();
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
		this._latestCompactionOnBranch = null;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), but also appends a branch_summary entry that captures
	 * context from the abandoned conversation path.
	 */
	branchWithSummary(branchFromId: string | null, summary: string, details?: unknown, fromHook?: boolean): string {
		if (branchFromId !== null && !this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		// Foundational opt #266: capture the PRE-CALL leaf so a _persist failure
		// restores it, NOT branchFromId. Below we set this.leafId = branchFromId
		// BEFORE _appendEntry; _appendEntry's own rollback (opt #239) captures
		// priorLeafId = this.leafId at that point = branchFromId, and restores
		// THAT on failure → the leaf silently jumps to branchFromId (the
		// navigation target) even though the branch_summary entry was never
		// persisted → the next appendMessage creates a child of branchFromId,
		// abandoning the original branch with no signal. Wrap _appendEntry so a
		// failure restores the original caller leaf and rethrows.
		const preCallLeafId = this.leafId;
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId: branchFromId ?? "root",
			summary,
			details,
			fromHook,
		};
		try {
			this._appendEntry(entry);
		} catch (error) {
			this.leafId = preCallLeafId;
			throw error;
		}
		this._recomputeLatestCompactionOnBranch();
		return entry.id;
	}

	/**
	 * Create a new session file containing only the path from root to the specified leaf.
	 * Useful for extracting a single conversation path from a branched session.
	 * Returns the new session file path, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		const previousSessionFile = this.sessionFile;
		const path = this.getBranch(leafId);
		if (path.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}

		// Filter out LabelEntry from path - we'll recreate them from the resolved map
		const pathWithoutLabels = path.filter((e) => e.type !== "label");

		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(this.getSessionDir(), `${fileTimestamp}_${newSessionId}.jsonl`);

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
		};

		// Collect labels for entries in the path
		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string; timestamp: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label, timestamp: this.labelTimestampsById.get(targetId)! });
			}
		}

		if (this.persist) {
			// Build label entries
			const lastEntryId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
			let parentId = lastEntryId;
			const labelEntries: LabelEntry[] = [];
			for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
				const labelEntry: LabelEntry = {
					type: "label",
					id: generateId(new Set(pathEntryIds)),
					parentId,
					timestamp: labelTimestamp,
					targetId,
					label,
				};
				pathEntryIds.add(labelEntry.id);
				labelEntries.push(labelEntry);
				parentId = labelEntry.id;
			}

			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
			this.sessionId = newSessionId;
			this.sessionFile = newSessionFile;
			this._buildIndex();

			// Only write the file now if it contains an assistant message.
			// Otherwise defer to _persist(), which creates the file on the
			// first assistant response, matching the newSession() contract
			// and avoiding the duplicate-header bug when _persist()'s
			// no-assistant guard later resets flushed to false.
			const hasAssistant = this._hasAssistant;
			if (hasAssistant) {
				this._rewriteFile();
				this.flushed = true;
			} else {
				this.flushed = false;
			}

			return newSessionFile;
		}

		// In-memory mode: replace current session with the path + labels
		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(new Set([...pathEntryIds, ...labelEntries.map((e) => e.id)])),
				parentId,
				timestamp: labelTimestamp,
				targetId,
				label,
			};
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}
		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
		this.sessionId = newSessionId;
		this._buildIndex();
		return undefined;
	}

	/**
	 * Create a new session.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.repi/agent/sessions/<encoded-cwd>/).
	 */
	static create(cwd: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		return new SessionManager(cwd, dir, undefined, true, options);
	}

	/**
	 * Open a specific session file.
	 * @param path Path to session file
	 * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
	 * @param cwdOverride Optional cwd override instead of the session header cwd.
	 */
	static open(path: string, sessionDir?: string, cwdOverride?: string): SessionManager {
		const resolvedPath = resolvePath(path);
		// Extract cwd from session header if possible, otherwise use process.cwd()
		const entries = loadEntriesFromFile(resolvedPath);
		const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
		const cwd = cwdOverride ?? header?.cwd ?? process.cwd();
		// If no sessionDir provided, derive from file's parent directory
		const dir = sessionDir ? normalizePath(sessionDir) : resolve(resolvedPath, "..");
		return new SessionManager(cwd, dir, resolvedPath, true);
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.repi/agent/sessions/<encoded-cwd>/).
	 */
	static continueRecent(cwd: string, sessionDir?: string): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const mostRecent = findMostRecentSession(dir, filterCwd ? cwd : undefined);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent, true);
		}
		return new SessionManager(cwd, dir, undefined, true);
	}

	/** Create an in-memory session (no file persistence) */
	static inMemory(cwd: string = process.cwd()): SessionManager {
		return new SessionManager(cwd, "", undefined, false);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new session in the target cwd with the full history from the source session.
	 * @param sourcePath Path to the source session file
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
	 */
	static forkFrom(
		sourcePath: string,
		targetCwd: string,
		sessionDir?: string,
		options?: NewSessionOptions,
	): SessionManager {
		const resolvedSourcePath = resolvePath(sourcePath);
		const resolvedTargetCwd = resolvePath(targetCwd);
		const sourceEntries = loadEntriesFromFile(resolvedSourcePath);
		if (sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session file is empty or invalid: ${resolvedSourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${resolvedSourcePath}`);
		}

		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(resolvedTargetCwd);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Create new session file with new ID but forked content
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		const newSessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: resolvedTargetCwd,
			parentSession: resolvedSourcePath,
		};
		// Atomic fork (opt #205): build the full file content (header + all
		// non-header source entries) in memory, then write via temp+rename so a
		// crash (SIGKILL/OOM) or an ENOSPC mid-write cannot leave a partial fork
		// on disk. The previous writeFileSync(flag:"wx") + appendFileSync loop
		// wrote the header first, then appended entries one at a time — a crash
		// or append throw mid-loop left a fresh (wx-created) file with the header
		// but only a SUBSET of source entries, silently losing conversation
		// history (a reader would load a truncated session with no signal).
		// Readers now see either no file or the complete fork. Mode 0o644 matches
		// the prior writeFileSync(flag:"wx") default (umask); the temp+rename
		// preserves it via atomicWriteFileSync's chmod-on-existing path.
		const forkLines: string[] = [`${JSON.stringify(newHeader)}\n`];
		for (const entry of sourceEntries) {
			if (entry.type !== "session") {
				forkLines.push(`${JSON.stringify(entry)}\n`);
			}
		}
		atomicWriteFileSync(newSessionFile, forkLines.join(""), 0o644);

		return new SessionManager(resolvedTargetCwd, dir, newSessionFile, true);
	}

	/**
	 * List all sessions for a directory.
	 * @param cwd Working directory (used to compute default session directory)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.repi/agent/sessions/<encoded-cwd>/).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(cwd: string, sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const resolvedCwd = resolvePath(cwd);
		const sessions = (await listSessionsFromDir(dir, onProgress)).filter(
			(session) => !filterCwd || sessionCwdMatches(session.cwd, resolvedCwd),
		);
		sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return sessions;
	}

	/**
	 * List all sessions across all project directories.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(
		sessionDirOrOnProgress?: string | SessionListProgress,
		onProgress?: SessionListProgress,
	): Promise<SessionInfo[]> {
		const customSessionDir =
			typeof sessionDirOrOnProgress === "string" ? normalizePath(sessionDirOrOnProgress) : undefined;
		const progress = typeof sessionDirOrOnProgress === "function" ? sessionDirOrOnProgress : onProgress;
		if (customSessionDir) {
			const sessions = await listSessionsFromDir(customSessionDir, progress);
			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		}

		const sessionsDir = getSessionsDir();

		try {
			if (!existsSync(sessionsDir)) {
				return [];
			}
			const entries = await readdir(sessionsDir, { withFileTypes: true });
			const dirs = entries.filter((e) => e.isDirectory()).map((e) => join(sessionsDir, e.name));

			// Count total files first for accurate progress
			let totalFiles = 0;
			const dirFiles: string[][] = [];
			for (const dir of dirs) {
				try {
					const files = (await readdir(dir)).filter((f) => f.endsWith(".jsonl"));
					dirFiles.push(files.map((f) => join(dir, f)));
					totalFiles += files.length;
				} catch {
					dirFiles.push([]);
				}
			}

			// Process all files with progress tracking
			let loaded = 0;
			const sessions: SessionInfo[] = [];
			const allFiles = dirFiles.flat();

			const results = await buildSessionInfosWithConcurrency(allFiles, () => {
				loaded++;
				progress?.(loaded, totalFiles);
			});

			for (const info of results) {
				if (info) {
					sessions.push(info);
				}
			}

			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		} catch {
			return [];
		}
	}
}
